import{load}from'cheerio';
import{zipSync,strToU8,type Zippable}from'fflate';
import{privateAssetBinding,type AssetManifest,type AssetManifestEntry}from'../domain/assets';
import{bytesDigest,type RenderAsset}from'../../renderer/protocol.mjs';
import{fail}from'./errors';
export type VerifiedAssetBytes={entry:AssetManifestEntry;bytes:Uint8Array};
function target(entry:AssetManifestEntry,manifest:AssetManifest,staticOnly:boolean){if(!staticOnly||entry.role!=='animation')return entry;if(!entry.fallback)fail(409,'ASSET_FALLBACK_REQUIRED','Choose an immutable static fallback.');const found=manifest.entries.find(e=>e.asset_id===entry.fallback!.asset_id&&e.variant_id===entry.fallback!.variant_id&&e.role==='fallback');if(!found)fail(409,'ASSET_FALLBACK_REQUIRED','The frozen static fallback is unavailable.');return found;}
function verified(entry:AssetManifestEntry,values:VerifiedAssetBytes[]){const found=values.find(v=>v.entry.asset_id===entry.asset_id&&v.entry.variant_id===entry.variant_id);if(!found||found.bytes.length!==entry.bytes||bytesDigest(found.bytes)!==entry.sha256)fail(503,'ASSET_INTEGRITY_FAILURE','Private image integrity failed.');return found.bytes;}
export function privatePreviewHtml(html:string,manifest:AssetManifest,values:VerifiedAssetBytes[]){if(values.reduce((n,v)=>n+v.bytes.length,0)>4*1024*1024)fail(413,'ASSET_PREVIEW_TOO_LARGE','Preview image bytes exceed 4 MiB. Select a smaller immutable variant; the image bundle retains the original derivatives.');return replaceImages(html,manifest,(e)=>{const selected=target(e,manifest,true);return `data:${selected.mime};base64,${Buffer.from(verified(selected,values)).toString('base64')}`;});}
function replaceImages(html:string,manifest:AssetManifest,replacement:(entry:AssetManifestEntry)=>string){const parsed=load(html);const bindings=new Map(manifest.entries.map(e=>[privateAssetBinding(e),e]));parsed('img[src]').each((_,img)=>{const src=parsed(img).attr('src')!;const entry=bindings.get(src);if(entry)parsed(img).attr('src',replacement(entry));else{let hostname:string;try{hostname=new URL(src).hostname;}catch{return;}if(hostname==='mailcraft-assets.invalid')fail(409,'ASSET_BINDING_UNREGISTERED','An image binding is absent from the frozen manifest.');}});return parsed.html();}
export function renderAssetBundle(manifest:AssetManifest,values:VerifiedAssetBytes[]):RenderAsset[]{const assets:RenderAsset[]=[];let total=0;for(const entry of manifest.entries){const selected=target(entry,manifest,true),bytes=verified(selected,values);total+=bytes.length;if(total>1024*1024)fail(413,'ASSET_RENDER_TOO_LARGE','Static image bytes exceed the 1 MiB isolated-render transport budget. Select a smaller variant or download the image bundle.');assets.push({url:privateAssetBinding(entry),mime:selected.mime as 'image/png'|'image/jpeg',sha256:selected.sha256,base64:Buffer.from(bytes).toString('base64')});}return assets;}
export function privateImageBundle(revision:{html:string;plaintext:string;artifact_hash:string},manifest:AssetManifest,values:VerifiedAssetBytes[]){if(manifest.entries.length>200||values.reduce((n,v)=>n+v.bytes.length,0)>40*1024*1024)fail(413,'ASSET_BUNDLE_TOO_LARGE','Private image bundle exceeds its bounded budget.');const files:Zippable={},mtime=new Date(1980,0,1);const filename=(entry:AssetManifestEntry)=>`assets/${entry.asset_id}-${entry.variant_id}-${entry.sha256}.${entry.mime==='image/png'?'png':entry.mime==='image/jpeg'?'jpg':'gif'}`;for(const entry of manifest.entries)files[filename(entry)]=[verified(entry,values),{level:0,mtime}];const staticHtml=replaceImages(revision.html,manifest,e=>filename(target(e,manifest,true))),animatedHtml=replaceImages(revision.html,manifest,filename);files['email.html']=[strToU8(staticHtml),{level:0,mtime}];files['email-animated.html']=[strToU8(animatedHtml),{level:0,mtime}];files['email.txt']=[strToU8(revision.plaintext),{level:0,mtime}];files['manifest.json']=[strToU8(JSON.stringify({version:'private-image-bundle-1',artifact_hash:revision.artifact_hash,assets:manifest,default:'email.html',animation:'email-animated.html',notice:'Private local bundle. Static fallback is the default. Public hosting, ESP delivery and real-client compatibility are unverified.'},null,2)),{level:0,mtime}];const ordered:Zippable={};for(const name of Object.keys(files).sort())ordered[name]=files[name];const bytes=zipSync(ordered,{level:0,mtime});if(bytes.length>48*1024*1024)fail(413,'ASSET_BUNDLE_TOO_LARGE','Private bundle exceeds 48 MiB.');return Buffer.from(bytes);}
