import {z} from 'zod';
import {parse} from 'csv-parse/sync';
import {withPrincipal} from './auth';
import {keyed} from './commands';
import {audit,digest} from './audit';
import {fail} from './errors';
import {normalizeEmail,eligibility} from '../domain/audience';
export async function audienceRoute(req:Request,path:string[],body:Record<string,unknown>,key:string|null){
 const [root,id,cmd]=path;
 return withPrincipal(req,root==='campaigns'?(cmd==='approve'?'approve':['send','schedule','pause','resume','cancel'].includes(cmd)?'send':req.method==='GET'?'read':'edit'):'audience',async(tx,p)=>{
  if(root==='contacts'){
   if(req.method==='GET')return {data:(await tx.query('SELECT c.*,EXISTS(SELECT 1 FROM suppressions s WHERE s.contact_id=c.id) AS suppressed FROM contacts c ORDER BY created_at DESC LIMIT 100')).rows};
   if(cmd==='suppress'){return keyed(tx,p,'contact.suppress:'+id,key,body,async()=>{const c=(await tx.query('SELECT id FROM contacts WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!c)fail(404,'RESOURCE_NOT_FOUND','Contact not found.');await tx.query("INSERT INTO suppressions(workspace_id,contact_id,reason) VALUES($1,$2,'manual') ON CONFLICT DO NOTHING",[p.workspace,id]);await tx.query('UPDATE contacts SET consent_version=consent_version+1 WHERE id=$1',[id]);await tx.query("INSERT INTO consent_events(workspace_id,contact_id,action,evidence) VALUES($1,$2,'manual_block',$3)",[p.workspace,id,JSON.stringify({actor:p.user})]);await audit(tx,p.workspace,p.user,'contact.suppressed',id);return {suppressed:true};});}
  }
  if(root==='contact-imports'){
   if(!id){const csv=z.string().max(2*1024*1024).parse(body.csv);let parsed:Record<string,string>[];try{parsed=parse(csv,{columns:true,skip_empty_lines:true,bom:true,relax_column_count:false});}catch{fail(422,'CSV_INVALID','The CSV could not be parsed. Use a header row and consistent columns.');}if(parsed.length>10000)fail(413,'IMPORT_LIMIT','At most 10,000 rows per local import.');const rows=parsed.map((r,i)=>{try{const email=normalizeEmail(r.email??'');const allowed=/@(example\.(com|org|net)|[^@]+\.(test|invalid|example))$/i.test(email.original);return {...email,row:i+2,first_name:r.first_name??'',error:allowed?null:'Only reserved fixture addresses are admitted until legal/consent launch gates pass.',consent:'pending_confirmation'};}catch{return {row:i+2,error:'Invalid email',original:'',lookup:'',first_name:'',consent:'pending_confirmation'};}});const seen=new Set<string>();for(const r of rows){if(r.lookup){if(seen.has(r.lookup))r.error='Duplicate/case-collision address in this import.';seen.add(r.lookup);}}return keyed(tx,p,'contacts.import.dryrun',key,body,async()=>{const op=(await tx.query("INSERT INTO operations(workspace_id,type,state,input,result,created_by) VALUES($1,'contacts.import','succeeded',$2,$3,$4) RETURNING id",[p.workspace,JSON.stringify({digest:digest(csv)}),JSON.stringify({rows,total:rows.length,valid:rows.filter(r=>!r.error).length,confirmed:false}),p.user])).rows[0];return {operation_id:op.id,preview:{rows:rows.slice(0,100),total:rows.length,valid:rows.filter(r=>!r.error).length,held:rows.filter(r=>!r.error).length,eligible:0}};});}
   if(cmd==='confirm')return keyed(tx,p,'contacts.import.confirm:'+id,key,body,async()=>{const op=(await tx.query("SELECT * FROM operations WHERE id=$1 AND type='contacts.import' FOR UPDATE",[id])).rows[0];if(!op)fail(404,'RESOURCE_NOT_FOUND','Import not found.');if(op.result.confirmed)return {imported:op.result.imported,held:op.result.imported,eligible:0};const rows=op.result.rows.filter((r:{error:unknown})=>!r.error);for(const r of rows){const c=(await tx.query("INSERT INTO contacts(workspace_id,email_original,email_lookup,attrs) VALUES($1,$2,$3,$4) ON CONFLICT(workspace_id,email_lookup) DO NOTHING RETURNING id",[p.workspace,r.original,r.lookup,JSON.stringify({first_name:r.first_name})])).rows[0];if(c)await tx.query("INSERT INTO consent_events(workspace_id,contact_id,action,evidence) VALUES($1,$2,'import_held',$3)",[p.workspace,c.id,JSON.stringify({source_operation:id,reason:'No verified opt-in proof'})]);}await tx.query('UPDATE operations SET result=$1 WHERE id=$2',[JSON.stringify({...op.result,confirmed:true,imported:rows.length}),id]);await audit(tx,p.workspace,p.user,'contacts.imported',id);return {imported:rows.length,held:rows.length,eligible:0};});
  }
  if(root==='campaigns'){
   if(req.method==='GET')return {data:(await tx.query('SELECT * FROM campaigns ORDER BY created_at DESC LIMIT 100')).rows};
   if(!id)return keyed(tx,p,'campaign.create',key,body,async()=>{const name=z.string().min(1).max(160).parse(body.name),revision=z.string().uuid().parse(body.revision_id);const r=(await tx.query('SELECT artifact_hash FROM revisions WHERE id=$1',[revision])).rows[0];if(!r)fail(404,'RESOURCE_NOT_FOUND','Revision not found.');const contacts=(await tx.query('SELECT c.id,c.subscription,c.deleted,EXISTS(SELECT 1 FROM suppressions s WHERE s.contact_id=c.id) AS suppressed FROM contacts c ORDER BY c.id')).rows;const intent={revision_id:revision,artifact_hash:r.artifact_hash,audience:contacts.map(c=>({id:c.id,...eligibility(c)})),provider:null,sender:null,topic:'marketing',schedule:null,tracking:false};const c=(await tx.query('INSERT INTO campaigns(workspace_id,name,revision_id,intent,digest,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[p.workspace,name,revision,JSON.stringify(intent),digest(intent),p.user])).rows[0];await audit(tx,p.workspace,p.user,'campaign.created',c.id);return {campaign:c};});
   return keyed(tx,p,'campaign.'+cmd+':'+id,key,body,async()=>{const c=(await tx.query('SELECT * FROM campaigns WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!c)fail(404,'RESOURCE_NOT_FOUND','Campaign not found.');
    if(cmd==='submit-review'){await tx.query("UPDATE campaigns SET state='review_pending' WHERE id=$1 AND state='draft'",[id]);return {campaign:{...c,state:'review_pending'},notice:'Review requested. Sender, real-client preflight and delivery gates remain incomplete.'};}
    if(cmd==='approve'){const preflight=(await tx.query("SELECT state,artifact_hash FROM preflights WHERE revision_id=$1 ORDER BY created_at DESC LIMIT 1",[c.revision_id])).rows[0];if(!preflight||preflight.state!=='passed'||preflight.artifact_hash!==c.intent.artifact_hash)fail(422,'PREFLIGHT_BLOCKED','Critical and real-client checks must pass for this exact artifact before send approval.');if(!c.intent.provider||!c.intent.sender)fail(409,'PROVIDER_NOT_READY','Select and verify a provider-bound sender first.');fail(409,'RELEASE_GATES_INCOMPLETE','Production delivery gates have not been verified. No approval was issued.');}
    if(cmd==='send'||cmd==='schedule'||cmd==='resume')fail(409,'PROVIDER_NOT_READY','Sending is disabled until identity, consent, preview, spend and delivery gates are verified. No mail was submitted.');
    if(cmd==='cancel'||cmd==='pause'){const state=cmd==='cancel'?'cancelled':'paused';await tx.query('UPDATE campaigns SET state=$1 WHERE id=$2',[state,id]);await audit(tx,p.workspace,p.user,'campaign.'+state,id);return {campaign:{...c,state},accepted:0,uncertain:0,notice:'No provider submissions exist for this campaign.'};}fail(404,'RESOURCE_NOT_FOUND','Campaign command not found.');});
  }
  fail(404,'RESOURCE_NOT_FOUND','Audience command not found.');
 });
}
