import{createHash}from'node:crypto';import type{Tx}from'./db';import{BrandSourceInput,BrandSource,BrandMemoryChunk,BrandMemoryContext,chunkMemoryText,selectMemoryChunks}from'../domain/brand-memory';import{fail}from'./errors';
export const sourceFields='id,workspace_id,brand_kit_version_id,title,source_ref,content_digest,content_bytes,chunk_count,allowed_usage,embedding_model,embedding_version,created_at,deleted_at';
function hash(text:string){return createHash('sha256').update(text,'utf8').digest('hex');}
export function sourceRecord(row:Record<string,unknown>){return BrandSource.parse(Object.fromEntries(Object.entries(row).map(([k,v])=>[k,v instanceof Date?v.toISOString():v])));}
export async function addBrandSource(tx:Tx,workspace:string,body:unknown){const input=BrandSourceInput.parse(body);if(!(await tx.query('SELECT id FROM brands WHERE id=$1',[input.brand_kit_version_id])).rowCount)fail(404,'RESOURCE_NOT_FOUND','Confirmed brand version not found.');const chunks=chunkMemoryText(input.text);let row:Record<string,unknown>;try{row=(await tx.query('INSERT INTO brand_sources(workspace_id,brand_kit_version_id,title,source_ref,content_digest,content_bytes,chunk_count)VALUES($1,$2,$3,$4,$5,$6,$7)RETURNING '+sourceFields,[workspace,input.brand_kit_version_id,input.title,input.source_ref,hash(input.text),Buffer.byteLength(input.text),chunks.length])).rows[0];}catch(error){if(error instanceof Error&&error.message==='BRAND_MEMORY_CAPACITY')fail(409,'BRAND_MEMORY_CAPACITY','Brand source capacity is full. Remove unused sources before adding more.');throw error;}
 for(const[ordinal,content]of chunks.entries())await tx.query('INSERT INTO brand_memory_chunks(workspace_id,source_id,ordinal,content,content_digest)VALUES($1,$2,$3,$4,$5)',[workspace,row.id,ordinal,content,hash(content)]);return sourceRecord(row);}
export async function getBrandSource(tx:Tx,id:string){const row=(await tx.query('SELECT '+sourceFields+' FROM brand_sources WHERE id=$1',[id])).rows[0];if(!row)fail(404,'RESOURCE_NOT_FOUND','Brand source not found.');return sourceRecord(row);}
export async function removeBrandSource(tx:Tx,id:string){await tx.query('SELECT id FROM brand_sources WHERE id=$1 FOR UPDATE',[id]);const source=await getBrandSource(tx,id);if(source.deleted_at)return source;return sourceRecord((await tx.query('UPDATE brand_sources SET deleted_at=clock_timestamp()WHERE id=$1 RETURNING '+sourceFields,[id])).rows[0]);}
export async function readSourceChunks(tx:Tx,id:string){return(await tx.query('SELECT c.id,c.source_id,s.title AS source_title,s.source_ref,c.content,c.content_digest,c.ordinal FROM brand_memory_chunks c JOIN brand_sources s ON s.workspace_id=c.workspace_id AND s.id=c.source_id WHERE c.source_id=$1 AND s.deleted_at IS NULL ORDER BY c.ordinal',[id])).rows.map((row)=>BrandMemoryChunk.parse(row));}
export async function retrieveBrandMemory(tx:Tx,brand:string,query:string){if(!(await tx.query('SELECT id FROM brands WHERE id=$1',[brand])).rowCount)fail(404,'RESOURCE_NOT_FOUND','Selected brand version not found.');const rows=(await tx.query('SELECT c.id,c.source_id,s.title AS source_title,s.source_ref,c.content,c.content_digest,c.ordinal FROM brand_memory_chunks c JOIN brand_sources s ON s.workspace_id=c.workspace_id AND s.id=c.source_id WHERE s.brand_kit_version_id=$1 AND s.deleted_at IS NULL ORDER BY c.id',[brand])).rows.map((row)=>BrandMemoryChunk.parse(row));return BrandMemoryContext.parse({brand_kit_version_id:brand,retrieval_version:'lexical-1',retrieved_at:new Date().toISOString(),chunks:selectMemoryChunks(rows,query)});}
