import{Queue,Worker}from'bullmq';import{Redis}from'ioredis';import type pg from'pg';
import{CreationWake,creationJobId,CREATION_POLICY,type CreationWakeData}from'../domain/creation-queue';
import{dueCreation,recoverCreation,claimCreation,prepareCreationAttempt,beginCreationAttempt,renewCreation,settleCreation}from'./creation-queue-store';import{runCreation,type CreationAdapters}from'./creation-engine';
export async function startCreationService({workerPool,schedulerPool,redisUrl,adapters,signal,prefix='lettercape-creation'}:{workerPool:pg.Pool;schedulerPool:pg.Pool;redisUrl:string;adapters:CreationAdapters;signal:AbortSignal;prefix?:string}){
 if(!/^[a-z0-9-]{1,80}$/.test(prefix))throw new Error('Invalid queue prefix.');const url=new URL(redisUrl);if(!['redis:','rediss:'].includes(url.protocol))throw new Error('Invalid Redis protocol.');
 const connection=new Redis(redisUrl,{maxRetriesPerRequest:null,enableOfflineQueue:false,lazyConnect:true,connectTimeout:2000});connection.on('error',()=>console.error('creation_wakeup_unavailable'));try{await connection.connect();await connection.ping();}catch(error){connection.disconnect();throw error;}
 const stop=new AbortController(),combined=AbortSignal.any([signal,stop.signal]),types=['email.generate','brand.extract']as const;
 const store={prepare:(claim:Parameters<typeof prepareCreationAttempt>[1])=>prepareCreationAttempt(workerPool,claim),begin:(claim:Parameters<typeof beginCreationAttempt>[1])=>beginCreationAttempt(workerPool,claim),renew:(claim:Parameters<typeof renewCreation>[1])=>renewCreation(workerPool,claim),settle:(claim:Parameters<typeof settleCreation>[1],outcome:Parameters<typeof settleCreation>[2])=>settleCreation(workerPool,claim,outcome)};
 const queues=types.map(type=>new Queue(type==='email.generate'?'generation':'extraction',{prefix,connection,defaultJobOptions:{attempts:1,removeOnComplete:true,removeOnFail:10}}));
 const workers=types.map((type,index)=>new Worker(index===0?'generation':'extraction',async job=>{const wake=CreationWake.parse(job.data);const route=(await schedulerPool.query('SELECT mailcraft_creation_route($1,$2)AS type',[wake.workspace_id,wake.operation_id])).rows[0].type;if(route!==type)return;const claim=await claimCreation(workerPool,wake);if(claim)await runCreation(claim,{store,adapters,signal:combined});},{prefix,connection,concurrency:CREATION_POLICY.global_concurrency}));
 for(const queue of queues)queue.on('error',()=>console.error('creation_wakeup_unavailable'));for(const worker of workers)worker.on('error',()=>console.error('creation_wakeup_unavailable')); 
 async function enqueueCreation(input:CreationWakeData,type:'email.generate'|'brand.extract'){const wake=CreationWake.parse(input);await queues[type==='email.generate'?0:1].add('wake',wake,{jobId:creationJobId(wake)});}
 let reconciling:Promise<void>|null=null;
 function reconcileCreation():Promise<void>{if(reconciling)return reconciling;reconciling=(async()=>{for(const wake of await dueCreation(schedulerPool)){if(combined.aborted)return;await recoverCreation(schedulerPool,wake);const type=(await schedulerPool.query('SELECT mailcraft_creation_route($1,$2)AS type',[wake.workspace_id,wake.operation_id])).rows[0].type;if(type==='email.generate'||type==='brand.extract')await enqueueCreation(wake,type);}})().finally(()=>{reconciling=null;});return reconciling;}
 const timer=setInterval(()=>{if(!combined.aborted)void reconcileCreation().catch(()=>console.error('creation_reconciliation_unavailable'));},1500);timer.unref();
 try{await reconcileCreation();}catch{console.error('creation_reconciliation_unavailable');}
 return{enqueueCreation,reconcileCreation,queues,async close(){clearInterval(timer);stop.abort();await reconciling?.catch(()=>undefined);await Promise.all(workers.map(worker=>worker.close()));await Promise.all(queues.map(queue=>queue.close()));await connection.quit();}};
}
