import env from'@next/env';import pg from'pg';import{readFileSync,existsSync}from'node:fs';import{startCreationService}from'./creation-queues';import{productionCreationAdapters}from'./creation-adapters';
env.loadEnvConfig(process.cwd());
if(process.env.CREATION_WORKER_ENABLED!=='true')throw new Error('Creation worker disabled. Production requires private identities and complete release evidence.');
if(process.env.LOCAL_DEVELOPMENT==='true'||process.env.DATABASE_URL||process.env.MIGRATION_DATABASE_URL||process.env.LOCAL_BOOTSTRAP_SECRET||!process.env.CREATION_WORKER_DATABASE_URL||!process.env.CREATION_SCHEDULER_DATABASE_URL||!process.env.REDIS_URL)throw new Error('Dedicated creation worker/scheduler credentials required; web/local/migration credentials must not reach this service.');
const gates=JSON.parse(readFileSync('release-gates.json','utf8'));
if(!process.env.RELEASE_BUILD?.trim()||gates.baseline!=='A-full-GA'||gates.environment!=='production'||!Array.from({length:13},(_,i)=>'GATE-'+String(i+1).padStart(2,'0')).every(id=>gates.gates[id]==='passed'&&gates.evidence[id]?.build===process.env.RELEASE_BUILD&&gates.evidence[id]?.environment==='production'&&gates.evidence[id]?.owner&&gates.evidence[id]?.time&&gates.evidence[id]?.path&&existsSync(gates.evidence[id].path)))throw new Error('Creation worker production activation refused: full-GA evidence incomplete.');
const workerPool=new pg.Pool({connectionString:process.env.CREATION_WORKER_DATABASE_URL,max:3,connectionTimeoutMillis:2000,options:'-c statement_timeout=5000 -c lock_timeout=2000'}),schedulerPool=new pg.Pool({connectionString:process.env.CREATION_SCHEDULER_DATABASE_URL,max:2,connectionTimeoutMillis:2000,options:'-c statement_timeout=5000 -c lock_timeout=2000'}),stop=new AbortController();
try{
 for(const[pool,expected,other]of[[workerPool,'mailcraft_creation_worker','mailcraft_creation_scheduler'],[schedulerPool,'mailcraft_creation_scheduler','mailcraft_creation_worker']]as const){const role=(await pool.query("SELECT r.rolsuper,r.rolbypassrls,r.rolcreatedb,r.rolcreaterole,pg_has_role(current_user,$1,'USAGE')AS expected,pg_has_role(current_user,$2,'MEMBER')AS other,pg_has_role(current_user,'mailcraft_runtime','MEMBER')AS runtime,pg_has_role(current_user,'mailcraft_creation_admin','MEMBER')AS admin FROM pg_roles r WHERE rolname=current_user",[expected,other])).rows[0];if(!role?.expected||role.other||role.runtime||role.admin||role.rolsuper||role.rolbypassrls||role.rolcreatedb||role.rolcreaterole)throw new Error('Creation service identity is invalid.');}
 for(const signal of['SIGTERM','SIGINT']as const)process.on(signal,()=>stop.abort());
 const service=await startCreationService({workerPool,schedulerPool,redisUrl:process.env.REDIS_URL,adapters:productionCreationAdapters,signal:stop.signal});console.log('Lettercape durable creation worker active.');await new Promise<void>(resolve=>{if(stop.signal.aborted)resolve();else stop.signal.addEventListener('abort',()=>resolve(),{once:true});});await service.close();
}finally{await Promise.all([workerPool.end(),schedulerPool.end()]);}
