import type{Tx}from'./db';import type{Principal}from'./auth';import{CreationSummary,CreationMetadata,CreationAttempt,CreationType}from'../domain/creation-history';import{resourcePage}from'./pagination';import{requireKeyScope}from'./api-keys';import{operationScope}from'../domain/api-keys';import{fail}from'./errors';
const fields='id,type,state,created_at,started_at,completed_at,error';
function dates(row:Record<string,unknown>){return Object.fromEntries(Object.entries(row).map(([key,value])=>[key,value instanceof Date?value.toISOString():value]));}
export async function creationMetadata(tx:Tx,id:string){
 const job=(await tx.query('SELECT policy_version,phase,failure_attempts,deadline_at,next_at FROM creation_jobs WHERE operation_id=$1',[id])).rows[0];if(!job)return null;
 const ledger=(await tx.query('SELECT kind FROM usage_ledger WHERE operation_id=$1',[id])).rows.map(row=>row.kind);
 const accounting=ledger.includes('consume')?'consumed':ledger.includes('release')?'released':ledger.includes('reserve')?(job.phase==='unknown'?'retained':'reserved'):'none';return CreationMetadata.parse({...dates(job),attempt_limit:3,accounting});
}
export async function creationView(tx:Tx,row:Record<string,unknown>){const summary=CreationSummary.parse({...dates(Object.fromEntries(fields.split(',').map(key=>[key,row[key]]))),creation:await creationMetadata(tx,String(row.id))});return{...summary,result:row.result??null};}
export async function creationPage(req:Request,tx:Tx,p:Principal){const type=CreationType.parse(new URL(req.url).searchParams.get('type'));requireKeyScope(p,operationScope(type));const page=await resourcePage(req,tx,p,{resource:'creation-operations',from:'operations',fields,where:'type=$1',values:[type],filters:{type}});const data=[];for(const row of page.data)data.push(CreationSummary.parse({...dates(row),creation:await creationMetadata(tx,row.id)}));return{...page,data};}
export async function creationAttempts(req:Request,tx:Tx,p:Principal,id:string,type:string){if(!CreationType.safeParse(type).success)fail(404,'RESOURCE_NOT_FOUND','Creation history not found.');const page=await resourcePage(req,tx,p,{resource:'creation-attempts',from:'creation_attempts',fields:'id,operation_id,lease_epoch,phase,outcome_code,recorded_at',created:'recorded_at',where:'operation_id=$1',values:[id],filters:{operation_id:id}});return{...page,data:page.data.map(row=>CreationAttempt.parse(dates(row)))};}
