import{z}from'zod';
export const memoryLimits={sourceBytes:65536,chunkCodepoints:1500,sourceChunks:64,workspaceSources:100,workspaceBytes:1048576,returnedChunks:8,returnedCodepoints:12000}as const;
export function normalizeMemoryText(text:string){return text.replace(/\r\n?/g,'\n').trim();}
export const BrandSourceInput=z.object({brand_kit_version_id:z.uuid(),title:z.string().trim().min(1).max(160),source_ref:z.string().trim().min(1).max(2048),text:z.string().transform(normalizeMemoryText).refine((v)=>v.length>0&&new TextEncoder().encode(v).length<=memoryLimits.sourceBytes,'Use nonempty text up to64KiB.'),acknowledge_rights_and_no_private_data:z.literal(true)}).strict();
export const BrandSource=z.object({id:z.uuid(),workspace_id:z.uuid(),brand_kit_version_id:z.uuid(),title:z.string(),source_ref:z.string(),content_digest:z.string().regex(/^[a-f0-9]{64}$/),content_bytes:z.number().int().positive(),chunk_count:z.number().int().positive(),allowed_usage:z.literal('approved_context'),embedding_model:z.null(),embedding_version:z.null(),created_at:z.iso.datetime(),deleted_at:z.iso.datetime().nullable()}).strict();
export const BrandMemoryChunk=z.object({id:z.uuid(),source_id:z.uuid(),source_title:z.string().min(1).max(160),source_ref:z.string().min(1).max(2048),content:z.string().min(1).max(3000).refine((text)=>Array.from(text).length<=1500),content_digest:z.string().regex(/^[a-f0-9]{64}$/),ordinal:z.number().int().nonnegative()}).strict();
export const BrandMemoryContext=z.object({brand_kit_version_id:z.uuid(),retrieval_version:z.literal('lexical-1'),retrieved_at:z.iso.datetime(),chunks:z.array(BrandMemoryChunk).max(8)}).strict();
export const MemoryPreviewInput=z.object({query:z.string().max(8000)}).strict();
export type MemoryContext=z.infer<typeof BrandMemoryContext>;export type MemoryChunk=z.infer<typeof BrandMemoryChunk>;export type SourceRecord=z.infer<typeof BrandSource>;
export function chunkMemoryText(text:string){const chars=Array.from(normalizeMemoryText(text)),chunks:string[]=[];for(let i=0;i<chars.length;i+=memoryLimits.chunkCodepoints)chunks.push(chars.slice(i,i+memoryLimits.chunkCodepoints).join(''));if(chunks.length>memoryLimits.sourceChunks||new TextEncoder().encode(text).length>memoryLimits.sourceBytes)throw new Error('Brand memory source exceeds its bound');return chunks;}
export function selectMemoryChunks(rows:MemoryChunk[],query:string):MemoryChunk[]{const tokens=[...new Set(query.toLocaleLowerCase('en-US').match(/[\p{L}\p{N}]{2,}/gu)??[])].slice(0,64);return rows.map((row)=>({row,score:tokens.reduce((n,t)=>n+(row.content.toLocaleLowerCase('en-US').includes(t)?1:0),0)})).sort((a,b)=>b.score-a.score||(a.row.id<b.row.id?-1:a.row.id>b.row.id?1:0)).slice(0,memoryLimits.returnedChunks).map(({row})=>row);}
