import{z}from'zod';import{parse,type DefaultTreeAdapterMap}from'parse5';import{BrandSchema,type Brand}from'./brand';import{toneFindings}from'./voice-guard';import type{EmailSpec,Block}from'./email-schema';import type{Finding}from'./email';
export const LIVE_VOICE_RULES_VERSION='draft-voice-1';export const MAX_VOICE_HTML_BYTES=65536;
type Field={location:string;label:string;text:string;forbiddenText?:string};
export type LiveVoiceFinding=Finding&{key:string;field_label:string;excerpt:string};
export type LiveVoiceReport={rules_version:typeof LIVE_VOICE_RULES_VERSION;findings:LiveVoiceFinding[];coverage:{key:string;message:string}[];checked_fields:number;configured_rules:number};
export type VoiceBrand={id:string;version:number;data:Brand};export type VoiceBrandPage={data:VoiceBrand[];has_more:boolean;next_cursor:string|null;total_count:number};
export function checkedVoiceBrandPage(input:unknown,workspace:string):VoiceBrandPage{
 const page=z.object({data:z.array(z.object({id:z.uuid(),workspace_id:z.uuid().optional(),version:z.number().int().positive(),data:BrandSchema})).max(100),has_more:z.boolean(),next_cursor:z.string().min(1).max(4096).nullable(),total_count:z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER)}).parse(input);
 if(page.has_more!==!!page.next_cursor||new Set(page.data.map(b=>b.id.toLowerCase())).size!==page.data.length||page.data.some(b=>b.workspace_id&&b.workspace_id.toLowerCase()!==workspace.toLowerCase()))throw Error('Brand page could not be verified.');
 return{...page,data:page.data.map(({id,version,data})=>({id,version,data}))};
}
export function liveVoiceReport(spec:EmailSpec,provided:Brand):LiveVoiceReport{
 const brand=BrandSchema.parse(provided),fields:Field[]=[{location:'subject',label:'Subject',text:spec.subject},{location:'preheader',label:'Preheader',text:spec.preheader}],coverage:LiveVoiceReport['coverage']=[];
 const html=(source:string,parts:(string|number)[],label:string)=>{
  const location=JSON.stringify(parts);if(source.length>MAX_VOICE_HTML_BYTES||new TextEncoder().encode(source).length>MAX_VOICE_HTML_BYTES){coverage.push({key:location,message:label+': HTML copy was not checked because this field exceeds 65,536 UTF-8 bytes. Use the separate frozen preflight and client review.'});return;}
  coverage.push({key:location,message:label+': inert HTML text extraction only. CSS visibility, conditional markup, sanitization projection and real-client appearance are not verified.'});
  const plain:string[]=[],tone:string[]=[],stack:{node:DefaultTreeAdapterMap['node'];end?:boolean}[]=[{node:parse(source)}];let image=0;
  const skipped=new Set(['head','title','meta','script','style','textarea','option','template']),breaks=new Set(['p','div','h1','h2','h3','h4','h5','h6','pre','address','caption','tfoot','li','ul','ol','table','thead','tbody','tr','td','th','blockquote']);
  while(stack.length){const{node,end}=stack.pop()!,name=node.nodeName;if(end){tone.push('\n');continue;}if(skipped.has(name))continue;if(name==='#text'&&'value'in node){plain.push(node.value);tone.push(node.value);continue;}if(name==='br'||name==='hr')tone.push('\n');if(name==='img'&&'attrs'in node){const alt=node.attrs.find(a=>a.name==='alt')?.value??'';image++;fields.push({location:JSON.stringify([...parts,'image',image,'alt']),label:label+' / Image '+image+' alt',text:alt});}if('childNodes'in node){if(breaks.has(name)){tone.push('\n');stack.push({node,end:true});}for(let n=node.childNodes.length-1;n>=0;n--)stack.push({node:node.childNodes[n]});}}
  fields.push({location,label,text:tone.join(''),forbiddenText:plain.join('')});
 };
 const visit=(block:Block,label:string)=>{
  const field=(name:string,text:string,human:string)=>fields.push({location:JSON.stringify(['block',block.id,name]),label:label+' · '+human,text});
  switch(block.type){case'hero':field('heading',block.heading,'Heading');field('text',block.text,'Supporting text');break;case'text':field('text',block.text,'Body text');break;case'image':if(!block.decorative)field('alt',block.alt,'Alternative text');break;case'button':field('label',block.label,'Button label');break;case'legal_footer':field('identity',block.identity,'Sender identity');field('address',block.address,'Postal address');break;case'product_card':field('title',block.title,'Product title');field('description',block.description,'Description');field('price',block.price,'Price');break;case'social':block.links.forEach((link,i)=>field('label:'+i,link.label,'Social label '+(i+1)));break;case'custom_html':html(block.html,['block',block.id,'html'],label+' · Custom HTML');break;case'columns':block.columns.forEach((column,c)=>column.forEach((child,i)=>visit(child,label+' / Column '+(c+1)+' / Item '+(i+1))));break;}
 };
 if(spec.editing_mode==='structured'){spec.sections.forEach((b,i)=>visit(b,'Block '+(i+1)+' ['+b.id+']'));if(spec.raw_html!==undefined)coverage.push({key:'inactive_raw',message:'Inactive retained raw HTML is not checked in structured mode.'});}else{html(spec.raw_html??'',['raw_html'],'Raw HTML');if(spec.sections.length)coverage.push({key:'inactive_blocks',message:'Inactive retained blocks are not checked in raw HTML mode.'});}
 const findings:LiveVoiceFinding[]=[];for(const field of fields){const found=toneFindings(field.text,field.location,brand.tone_rules??{}),literal=(field.forbiddenText??field.text).toLowerCase();for(const phrase of brand.forbidden_phrases.filter(p=>p.trim()))if(literal.includes(phrase.toLowerCase()))found.push({code:'VOICE_FORBIDDEN',severity:'blocking',location:field.location,message:'Remove or revise the prohibited phrase “'+phrase+'” in this field. This is literal matching, not semantic evaluation.'});for(const[f,index]of found.map((f,index)=>[f,index]as const))findings.push({...f,key:JSON.stringify([field.location,f.code,index]),field_label:field.label,excerpt:Array.from(field.text.slice(0,400)).slice(0,200).join('')});}
 return{rules_version:LIVE_VOICE_RULES_VERSION,findings,coverage,checked_fields:fields.length,configured_rules:brand.forbidden_phrases.filter(p=>p.trim()).length+Object.values(brand.tone_rules??{}).filter(v=>v!==undefined).length};
}
