import{test}from'node:test';import assert from'node:assert/strict';
import{blankSpec,compileEmail,EmailSpecSchema,sanitizeRaw,lintEmail}from'../src/domain/email';
import{privateAssetBinding,type AssetManifest,type AssetManifestEntry}from'../src/domain/assets';
const asset='11111111-1111-4111-8111-111111111111',variant='22222222-2222-4222-8222-222222222222';
const entry:AssetManifestEntry={asset_id:asset,variant_id:variant,source_sha256:'a'.repeat(64),sha256:'b'.repeat(64),mime:'image/png',bytes:100,width:2,height:2,role:'static',frames:1,processing_profile:'raster-v1',storage_profile:'local-private-v1',visibility:'private',rights_evidence_id:'33333333-3333-4333-8333-333333333333',scan_evidence_ids:['44444444-4444-4444-8444-444444444444','55555555-5555-4555-8555-555555555555']};
const managed=()=>({...blankSpec('brand','Brand'),schema_version:'1.1' as const,sections:[{id:'image',type:'image' as const,asset_ref:{asset_id:asset,variant_id:variant},alt:'Verified artwork'}]});
const manifest:AssetManifest={version:'asset-manifest-1',entries:[entry]};
test('legacy schema rejects private refs and explicit managed schema preserves exact source choice',()=>{assert.equal(EmailSpecSchema.safeParse({...managed(),schema_version:'1.0'}).success,false);assert.equal(EmailSpecSchema.safeParse(managed()).success,true);assert.equal(EmailSpecSchema.safeParse({...managed(),sections:[{...managed().sections[0],src:'https://example.com/image.png'}]}).success,false);assert.equal(EmailSpecSchema.safeParse({...managed(),sections:[{id:'image',type:'image',alt:'Missing'}]}).success,false);});
test('managed compiler requires server-resolved immutable evidence and binds all three identities',async()=>{await assert.rejects(compileEmail(managed()),/ASSET_MANIFEST_REQUIRED/);const first=await compileEmail(managed(),{assets:manifest});assert.ok(first.html.includes(privateAssetBinding(entry)));assert.deepEqual(first.manifest.assets,manifest);assert.equal(first.hash,(await compileEmail(managed(),{assets:manifest})).hash);await assert.rejects(compileEmail(managed(),{assets:{...manifest,entries:[{...entry,asset_id:'66666666-6666-4666-8666-666666666666'}]}}),/ASSET_REFERENCE_UNRESOLVED/);});
test('raw managed registry only permits exact registered bindings and legacy compilation stays unchanged',async()=>{const legacy=blankSpec('brand','Brand');const before=await compileEmail(legacy);assert.equal(before.manifest.schema,'1.0');assert.equal('assets'in before.manifest,false);const spec={...managed(),editing_mode:'raw_html' as const,raw_html:sanitizeRaw(`<img src="${privateAssetBinding(entry)}" alt="Artwork">`).html,asset_registry:[{asset_id:asset,variant_id:variant}]};assert.ok((await compileEmail(spec,{assets:manifest})).html.includes(privateAssetBinding(entry)));const changed={...spec,raw_html:spec.raw_html.replace(entry.sha256,'c'.repeat(64))};const blocked=await compileEmail(changed,{assets:manifest});assert.equal(blocked.manifest.spec.raw_html,changed.raw_html);assert.ok('raw_projection'in blocked.manifest&&blocked.manifest.raw_projection?.delivery_status==='blocked');assert.ok(!blocked.html.includes('c'.repeat(64)));assert.ok(!blocked.html.includes('src='));});
test('explicit raw-fragment conversion retains registered managed identity',async()=>{const{conversionProposal}=await import('../src/domain/email-conversion');const spec={...managed(),editing_mode:'raw_html' as const,raw_html:sanitizeRaw(`<img src="${privateAssetBinding(entry)}" alt="Artwork">`).html,asset_registry:[{asset_id:asset,variant_id:variant}]};const proposal=await conversionProposal(spec,1,manifest);assert.equal(proposal.status,'available');const image=proposal.spec!.sections[0];assert.equal(image.type,'image');if(image.type==='image'){assert.deepEqual(image.asset_ref,{asset_id:asset,variant_id:variant});assert.equal(image.src,undefined);}});

test('frozen private image preflight reports measured bytes and delivery limit without claiming unknown image weight',async()=>{const spec=managed(),compiled=await compileEmail(spec,{assets:manifest}),findings=lintEmail(spec,[],{html:compiled.html,assets:manifest});assert.ok(findings.some(f=>f.code==='ASSET_PRIVATE_DELIVERY_UNAVAILABLE'));assert.equal(findings.some(f=>f.code==='IMAGE_WEIGHT_UNAVAILABLE'||f.code==='ASSET_EVIDENCE_MISSING'),false);const unknown=lintEmail(spec,[],{html:compiled.html});assert.ok(unknown.some(f=>f.code==='ASSET_EVIDENCE_MISSING'));});
