import test from'node:test';import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import pg from'pg';import env from'@next/env';import{tenant,closeDb}from'../src/server/db';import{addBrandSource,retrieveBrandMemory,removeBrandSource,readSourceChunks}from'../src/server/brand-memory';env.loadEnvConfig(process.cwd());
test('brand memory binds exact kit/tenant, excludes tombstones from fresh context and keeps immutable provenance',async()=>{
 const db=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL}),workspace=randomUUID(),other=randomUUID(),user='memory-'+randomUUID(),brand=randomUUID(),next=randomUUID(),foreign=randomUUID();
 try{await db.query("INSERT INTO workspaces(id,name)VALUES($1,'Memory fixture'),($2,'Memory foreign')",[workspace,other]);await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$3,'Owner'),($2,$3,'Owner')",[workspace,other,user]);for(const[w,id,v]of[[workspace,brand,1],[workspace,next,2],[other,foreign,1]])await db.query('INSERT INTO brands(workspace_id,id,version,data)VALUES($1,$2,$3,$4)',[w,id,v,'{}']);
 const input={brand_kit_version_id:brand,title:'Shoe facts',source_ref:'Owned product brief',text:'Sneakers made with verified cotton.',acknowledge_rights_and_no_private_data:true};const source=await tenant(workspace,user,(tx)=>addBrandSource(tx,workspace,input));const context=await tenant(workspace,user,(tx)=>retrieveBrandMemory(tx,brand,'cotton'));assert.equal(context.chunks.length,1);assert.equal(context.chunks[0].source_id,source.id);assert.equal(context.chunks[0].content,input.text);assert.equal(context.brand_kit_version_id,brand);
 assert.equal((await tenant(workspace,user,(tx)=>retrieveBrandMemory(tx,next,'cotton'))).chunks.length,0);await assert.rejects(()=>tenant(other,user,(tx)=>retrieveBrandMemory(tx,brand,'')),/Selected brand version not found/);await assert.rejects(()=>tenant(workspace,user,(tx)=>addBrandSource(tx,workspace,{...input,brand_kit_version_id:foreign})),/Confirmed brand version not found/);assert.equal((await tenant(other,user,(tx)=>readSourceChunks(tx,source.id))).length,0);assert.equal((await tenant('',user,(tx)=>tx.query('SELECT id FROM brand_sources'))).rowCount,0);
 await assert.rejects(()=>tenant(workspace,user,(tx)=>tx.query('UPDATE brand_memory_chunks SET content=$1 WHERE source_id=$2',['Changed',source.id])),/permission denied/);await assert.rejects(()=>tenant(workspace,user,(tx)=>tx.query('UPDATE brand_sources SET content_digest=$1 WHERE id=$2',['b'.repeat(64),source.id])),/permission denied/);
 const removed=await tenant(workspace,user,(tx)=>removeBrandSource(tx,source.id)),again=await tenant(workspace,user,(tx)=>removeBrandSource(tx,source.id));assert.equal(removed.deleted_at,again.deleted_at);assert.equal(removed.content_digest,source.content_digest);assert.equal((await tenant(workspace,user,(tx)=>retrieveBrandMemory(tx,brand,'cotton'))).chunks.length,0);assert.equal((await tenant(workspace,user,(tx)=>readSourceChunks(tx,source.id))).length,0);await assert.rejects(()=>tenant(workspace,user,(tx)=>tx.query('UPDATE brand_sources SET deleted_at=NULL WHERE id=$1',[source.id])),/BRAND_SOURCE_IMMUTABLE/);assert.equal(context.chunks[0].source_id,removed.id);
 }finally{for(const table of['brand_memory_chunks','brand_sources','brands','memberships'])await db.query(`DELETE FROM ${table} WHERE workspace_id=ANY($1::uuid[])`,[[workspace,other]]);await db.query('DELETE FROM workspaces WHERE id=ANY($1::uuid[])',[[workspace,other]]);await db.end();await closeDb();}
});
