import test from'node:test';import assert from'node:assert/strict';
const contract=await import('../src/domain/campaign-configuration').catch(()=>null);
function module(){assert.ok(contract,'Campaign configuration contract must exist');return contract;}
const id='11111111-1111-4111-8111-111111111111',input={expected_version:1,name:'Owned campaign',revision_id:id,planned_timing:null};
test('campaign configuration accepts explicit unscheduled settings and rejects unapproved fields or invalid versions',()=>{const m=module();assert.deepEqual(m.CampaignConfigurationInput.parse(input),input);for(const extra of[{provider:'ses'},{sender:'invented'},{approval:{approved:true}},{audience:[]},{state:'scheduled'}])assert.equal(m.CampaignConfigurationInput.safeParse({...input,...extra}).success,false);for(const expected_version of[0,1.5,2147483647,'1'])assert.equal(m.CampaignConfigurationInput.safeParse({...input,expected_version}).success,false);assert.equal(m.CampaignConfigurationInput.safeParse({...input,name:'   '}).success,false);});
test('planned timing requires an explicit local minute timezone and offset and rejects extra authority',()=>{const m=module();const timing={local_time:'2026-10-02T10:15',time_zone:'UTC',utc_offset:'+00:00'};assert.deepEqual(m.RequestedCampaignTiming.parse(timing),timing);assert.equal(m.RequestedCampaignTiming.safeParse({...timing,utc_offset:undefined}).success,false);assert.equal(m.RequestedCampaignTiming.safeParse({...timing,accepted:true}).success,false);assert.equal(m.RequestedCampaignTiming.safeParse({...timing,local_time:'2026-10-02T10:15:30'}).success,false);assert.equal(m.CampaignConfigurationInput.safeParse({...input,planned_timing:undefined}).success,false);});
test('UTC planned timing retains original intent and deterministically resolves its UTC candidate',()=>{const m=module(),timing={local_time:'2026-10-02T10:15',time_zone:'UTC',utc_offset:'+00:00'};assert.deepEqual(m.resolveCampaignTiming(timing),{...timing,utc:'2026-10-02T10:15:00.000Z'});assert.deepEqual(m.resolveCampaignTiming(timing),m.resolveCampaignTiming(timing));});
test('Gregorian calendar validation rejects normalization and accepts a real leap minute',()=>{const m=module();for(const local_time of['2026-02-30T10:15','2025-02-29T10:15','2026-13-02T10:15','2026-10-02T24:15'])assert.throws(()=>m.resolveCampaignTiming({local_time,time_zone:'UTC',utc_offset:'+00:00'}));assert.equal(m.resolveCampaignTiming({local_time:'2024-02-29T10:15',time_zone:'UTC',utc_offset:'+00:00'}).utc,'2024-02-29T10:15:00.000Z');});
test('DST nonexistent minutes reject both adjacent offsets instead of silently moving the local time',()=>{const m=module();for(const utc_offset of['-05:00','-04:00'])assert.throws(()=>m.resolveCampaignTiming({local_time:'2026-03-08T02:30',time_zone:'America/New_York',utc_offset}));});
test('DST repeated minute resolves each explicitly chosen offset to its distinct occurrence',()=>{const m=module(),timing={local_time:'2026-11-01T01:30',time_zone:'America/New_York'};assert.equal(m.resolveCampaignTiming({...timing,utc_offset:'-04:00'}).utc,'2026-11-01T05:30:00.000Z');assert.equal(m.resolveCampaignTiming({...timing,utc_offset:'-05:00'}).utc,'2026-11-01T06:30:00.000Z');});
test('non-hour timezone offsets retain the selected timezone and minute precision',()=>{const m=module(),timing={local_time:'2026-10-02T10:15',time_zone:'Asia/Kathmandu',utc_offset:'+05:45'};assert.deepEqual(m.resolveCampaignTiming(timing),{...timing,utc:'2026-10-02T04:30:00.000Z'});assert.equal(m.resolveCampaignTiming({local_time:'2026-10-02T10:15',time_zone:'Australia/Adelaide',utc_offset:'+09:30'}).utc,'2026-10-02T00:45:00.000Z');});
test('unknown zones mismatched and malformed offsets cannot become stored resolved timing',()=>{const m=module();for(const [time_zone,utc_offset]of[['Mars/Phobos','+00:00'],['file:///tmp/private','+00:00'],['UTC','+01:00'],['UTC','+24:00'],['UTC','00:00']])assert.throws(()=>m.resolveCampaignTiming({local_time:'2026-10-02T10:15',time_zone,utc_offset}));});
test('configuration canonical JSON ignores object insertion order but retains audience array order and distinct chosen timing',()=>{const m=module(),a={z:1,a:{y:'safe',b:2},audience:['one','two']},b={audience:['one','two'],a:{b:2,y:'safe'},z:1};assert.equal(m.campaignCanonicalJSON(a),m.campaignCanonicalJSON(b));assert.notEqual(m.campaignCanonicalJSON(a),m.campaignCanonicalJSON({...b,audience:['two','one']}));const timing={local_time:'2026-11-01T01:30',time_zone:'America/New_York'};assert.notEqual(m.campaignCanonicalJSON(m.resolveCampaignTiming({...timing,utc_offset:'-04:00'})),m.campaignCanonicalJSON(m.resolveCampaignTiming({...timing,utc_offset:'-05:00'})));});
