import test from'node:test';import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{spawn,type ChildProcess}from'node:child_process';import{once}from'node:events';import{createServer}from'node:http';import pg from'pg';import{Redis}from'ioredis';import env from'@next/env';import{withCreationDatabase}from'./fixtures/creation-database';import{CreationWake,creationJobId}from'../src/domain/creation-queue';import{Queue}from'bullmq';env.loadEnvConfig(process.cwd());
test('actual durable worker process crash and lost Redis wakes preserve SQL fences and finite admission',async()=>withCreationDatabase(async connection=>{
 const db=new pg.Pool({connectionString:connection}),prefix='creation-fixture-'+randomUUID().replaceAll('-',''),children:ChildProcess[]=[],workspaces:string[]=[randomUUID(),randomUUID()],user='owned-creation-fixture';let hold=true;const held:import('node:http').ServerResponse[]=[];
 await db.query('CREATE TABLE fixture_effects(id uuid DEFAULT gen_random_uuid(),workspace_id uuid,operation_id uuid)');
 const server=createServer(async(req,res)=>{try{let body='';for await(const part of req){body+=part.toString();if(body.length>512)throw new Error('oversized');}const wake=CreationWake.parse(JSON.parse(body));assert.ok(workspaces.includes(wake.workspace_id));await db.query('INSERT INTO fixture_effects(workspace_id,operation_id)VALUES($1,$2)',[wake.workspace_id,wake.operation_id]);if(hold)held.push(res);else{res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({proposals:['Owned HTTP fixture']}));}}catch{res.writeHead(400);res.end();}});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();assert.ok(address&&typeof address!=='string');const receiver='http://127.0.0.1:'+address.port;
 async function until(check:()=>Promise<boolean>,name:string){const end=Date.now()+12000;while(Date.now()<end){if(await check())return;await new Promise(resolve=>setTimeout(resolve,20));}throw new Error('Owned fixture timeout: '+name);}
 async function kill(child:ChildProcess){if(child.exitCode!==null||child.signalCode!==null)return;const exited=once(child,'exit');child.kill('SIGKILL');await exited;}
 async function start(mode:'normal'|'prestart'='normal'){const child=spawn(process.execPath,['--import','tsx','tests/fixtures/creation-worker-process.ts'],{env:{LOCAL_DEVELOPMENT:'true',NODE_ENV:'test'},stdio:['pipe','pipe','pipe']});children.push(child);let output='',errors='';const messages:{event:string;pid:number}[]=[];child.stdout!.on('data',part=>{output+=part.toString();for(;;){const split=output.indexOf('\n');if(split<0)break;messages.push(JSON.parse(output.slice(0,split)));output=output.slice(split+1);}});child.stderr!.on('data',part=>{errors+=part.toString();});child.stdin!.end(JSON.stringify({connection,redis:process.env.REDIS_URL,prefix,receiver,mode}));await until(async()=>{if(child.exitCode!==null||child.signalCode!==null)throw new Error('Owned worker stopped: '+errors);return messages.some(m=>m.event==='ready');},'worker ready');return{child,pid:messages.find(m=>m.event==='ready')!.pid,messages};}
 const brands:Record<string,string>={};async function job(index=0){const workspace=workspaces[index],id=randomUUID();await db.query("INSERT INTO operations(workspace_id,id,type,input,created_by)VALUES($1,$2,'email.generate',$3,$4)",[workspace,id,JSON.stringify({brand_kit_version_id:brands[workspace],prompt:'Owned brief',locale:'en-US',mode:'single'}),user]);await db.query("INSERT INTO usage_ledger(workspace_id,operation_id,metric,kind,units)VALUES($1,$2,'generation','reserve',1)",[workspace,id]);return id;}
 try{
  for(const workspace of workspaces){brands[workspace]=randomUUID();await db.query("INSERT INTO workspaces(id,name)VALUES($1,'Owned restart fixture')",[workspace]);await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,'Owner')",[workspace,user]);await db.query('INSERT INTO brands(workspace_id,id,version,data)VALUES($1,$2,1,$3)',[workspace,brands[workspace],JSON.stringify({name:'Fixture',website:'https://example.org',description:'Fixture',voice:'Plain',accent:'#0B625D',background:'#F7F6F2',font_stack:'Arial, sans-serif',address:'Fixture address',approved_claims:[],forbidden_phrases:[],provenance:[]})]);}
  const unknown=await job(),first=await start();await until(async()=>(await db.query('SELECT FROM fixture_effects WHERE operation_id=$1',[unknown])).rowCount===1,'committed external effect');await kill(first.child);await db.query("UPDATE creation_jobs SET lease_until=clock_timestamp()-interval '1 second'WHERE operation_id=$1",[unknown]);
  hold=false;const second=await start();assert.notEqual(first.pid,second.pid);await until(async()=>(await db.query('SELECT error FROM operations WHERE id=$1',[unknown])).rows[0].error?.code==='AI_RECONCILIATION_REQUIRED','unknown recovery');assert.equal((await db.query('SELECT count(*)::int AS n FROM fixture_effects WHERE operation_id=$1',[unknown])).rows[0].n,1);assert.equal((await db.query("SELECT count(*)::int AS n FROM usage_ledger WHERE operation_id=$1 AND kind<>'reserve'",[unknown])).rows[0].n,0);await kill(second.child);
  const safe=await job(),before=await start('prestart');await until(async()=>before.messages.some(m=>m.event==='prepared'),'prepared without external start');assert.equal((await db.query('SELECT phase FROM creation_jobs WHERE operation_id=$1',[safe])).rows[0].phase,'leased');await kill(before.child);await db.query("UPDATE creation_jobs SET lease_until=clock_timestamp()-interval '1 second'WHERE operation_id=$1",[safe]);
  const redis=new Redis(process.env.REDIS_URL!);try{const keys=await redis.keys(prefix+':*');assert.ok(keys.length>0);const data=await redis.hgetall(prefix+':generation:'+workspaces[0]+'-'+safe);if(data.data)CreationWake.parse(JSON.parse(data.data));await redis.del(...keys);}finally{await redis.quit();}
  const rebuilt=await start();assert.notEqual(rebuilt.pid,before.pid);await until(async()=>(await db.query('SELECT state FROM operations WHERE id=$1',[safe])).rows[0].state==='succeeded','Redis loss rebuild');assert.equal((await db.query('SELECT count(*)::int AS n FROM fixture_effects WHERE operation_id=$1',[safe])).rows[0].n,1);assert.equal((await db.query("SELECT count(*)::int AS n FROM usage_ledger WHERE operation_id=$1 AND kind='consume'",[safe])).rows[0].n,1);await kill(rebuilt.child);
  hold=true;const ids=[await job(),await job(),await job(1)],bounded=await start();await until(async()=>(await db.query('SELECT count(*)::int AS n FROM fixture_effects WHERE operation_id=ANY($1::uuid[])',[ids])).rows[0].n===2,'two admitted workspaces');assert.deepEqual((await db.query('SELECT count(*)::int AS n FROM fixture_effects WHERE operation_id=ANY($1::uuid[])GROUP BY workspace_id',[ids])).rows.map(r=>r.n),[1,1]);assert.equal((await db.query("SELECT count(*)::int AS n FROM creation_jobs WHERE phase='started'")).rows[0].n,2);
  hold=false;for(const res of held){res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({proposals:['Owned HTTP fixture']}));}await until(async()=>(await db.query("SELECT count(*)::int AS n FROM operations WHERE id=ANY($1::uuid[])AND state='succeeded'",[ids])).rows[0].n===3,'bounded remainder');
  const duplicateConnection=new Redis(process.env.REDIS_URL!,{maxRetriesPerRequest:null}),duplicateQueue=new Queue('generation',{connection:duplicateConnection,prefix});try{await duplicateQueue.pause();const wake={workspace_id:workspaces[0],operation_id:safe},jobId=creationJobId(wake);await duplicateQueue.add('wake',wake,{jobId,attempts:1,removeOnComplete:true});await duplicateQueue.add('wake',wake,{jobId,attempts:1,removeOnComplete:true});const waiting=await duplicateQueue.getJob(jobId);assert.ok(waiting);CreationWake.parse(waiting.data);await duplicateQueue.resume();await until(async()=>!(await duplicateQueue.getJob(jobId)),'duplicate wake acknowledgment');assert.equal((await db.query('SELECT count(*)::int AS n FROM fixture_effects WHERE operation_id=$1',[safe])).rows[0].n,1);}finally{await duplicateQueue.close();await duplicateConnection.quit();}
  await kill(bounded.child);
 }finally{for(const child of children)await kill(child);server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));const redis=new Redis(process.env.REDIS_URL!);try{const keys=await redis.keys(prefix+':*');if(keys.length)await redis.del(...keys);}finally{await redis.quit();}await db.end();}
}));
