import test from 'node:test';import assert from 'node:assert/strict';import{randomUUID}from'node:crypto';
import type{CreationClaim,CreationContext,CreationSettlement}from'../src/server/creation-queue-store';
const engine=await import('../src/server/creation-engine').catch(()=>null);
function fixture(){const claim:CreationClaim={workspace_id:randomUUID(),operation_id:randomUUID(),token:randomUUID(),lease_until:new Date(Date.now()+30000).toISOString(),deadline_at:new Date(Date.now()+120000).toISOString()};const context:CreationContext={operation:{workspace_id:claim.workspace_id,id:claim.operation_id,type:'email.generate',input:{},created_by:'fixture',created_api_key_id:null},brand:null,memory:null,grant_until:new Date(Date.now()+5000).toISOString()};const calls:string[]=[],settlements:CreationSettlement[]=[];return{claim,context,calls,settlements,store:{prepare:async()=>{calls.push('prepare');return context;},begin:async()=>{calls.push('begin');return context;},renew:async()=>true,settle:async(_claim:CreationClaim,outcome:CreationSettlement)=>{settlements.push(outcome);return true;}}};}
test('unconfigured adapters end before recording an external start',async()=>{assert.ok(engine?.runCreation);const f=fixture();await engine.runCreation(f.claim,{store:f.store,signal:new AbortController().signal,adapters:{preflight:()=>{throw new Error('Provider unavailable');},generate:async()=>{throw new Error('Must not run');},extract:async()=>({})}});assert.deepEqual(f.calls,['prepare']);assert.equal(f.settlements[0].outcome,'terminal');});
test('ordinary generation transport errors remain ambiguous and never invent a safe retry',async()=>{assert.ok(engine?.runCreation);const f=fixture();await engine.runCreation(f.claim,{store:f.store,signal:new AbortController().signal,adapters:{preflight:()=>{},generate:async()=>{throw new Error('Connection lost after request');},extract:async()=>({})}});assert.deepEqual(f.calls,['prepare','begin']);assert.deepEqual(f.settlements,[{outcome:'ambiguous'}]);});
test('known success settles its validated result once',async()=>{assert.ok(engine?.runCreation);const f=fixture();await engine.runCreation(f.claim,{store:f.store,signal:new AbortController().signal,adapters:{preflight:()=>{},generate:async()=>({proposals:['owned fixture']}),extract:async()=>({})}});assert.deepEqual(f.settlements,[{outcome:'success',result:{proposals:['owned fixture']}}]);});
test('current grant denial prevents any external adapter invocation',async()=>{assert.ok(engine?.runCreation);const f=fixture();let external=0;await engine.runCreation(f.claim,{store:{...f.store,begin:async()=>null},signal:new AbortController().signal,adapters:{preflight:()=>{},generate:async()=>{external++;return{};},extract:async()=>({})}});assert.equal(external,0);assert.deepEqual(f.settlements,[]);});
test('shutdown after external start retains uncertainty instead of refunding',async()=>{assert.ok(engine?.runCreation);const f=fixture(),stop=new AbortController();await engine.runCreation(f.claim,{store:f.store,signal:stop.signal,adapters:{preflight:()=>{},generate:async(_context,signal)=>{stop.abort();signal.throwIfAborted();return{};},extract:async()=>({})}});assert.equal(f.settlements[0].outcome,'ambiguous');});
test('expired five-second grant prevents the external request',async()=>{assert.ok(engine?.runCreation);const f=fixture();f.context.grant_until=new Date(Date.now()-1).toISOString();let requests=0;await engine.runCreation(f.claim,{store:f.store,signal:new AbortController().signal,adapters:{preflight:()=>{},generate:async()=>{requests++;return{};},extract:async()=>({})}});assert.equal(requests,0);assert.equal(f.settlements[0].outcome,'ambiguous');});
