import type{EventEmitter as Emitter}from'node:events';
import test from'node:test';import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import pg from'pg';import{Redis}from'ioredis';import env from'@next/env';import{withCreationDatabase}from'./fixtures/creation-database';import{startCreationService}from'../src/server/creation-queues';import{creationJobId}from'../src/domain/creation-queue';import{claimCreation,beginCreationAttempt,settleCreation}from'../src/server/creation-queue-store';env.loadEnvConfig(process.cwd());
const kit={name:'Review fixture',website:'https://example.org',description:'Owned fixture',voice:'Plain',accent:'#0B625D',background:'#F7F6F2',font_stack:'Arial, sans-serif',address:'Reserved fixture address',approved_claims:[],forbidden_phrases:[],provenance:[]};
async function seed(db:pg.Pool,generation=false){const workspace=randomUUID(),operation=randomUUID(),brand=randomUUID(),key=randomUUID(),user='creation-review-'+randomUUID();await db.query("INSERT INTO workspaces(id,name)VALUES($1,'Owned review fixture')",[workspace]);await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,'Owner')",[workspace,user]);await db.query('INSERT INTO brands(workspace_id,id,version,data)VALUES($1,$2,1,$3)',[workspace,brand,JSON.stringify(kit)]);await db.query("INSERT INTO api_keys(workspace_id,id,key_hash,name,scopes,created_by,expires_at)VALUES($1,$2,$3,'Owned fixture',$4,$5,clock_timestamp()+interval '1 hour')",[workspace,key,randomUUID(),JSON.stringify([generation?'emails:write':'brands:write']),user]);await db.query('INSERT INTO operations(workspace_id,id,type,input,created_by,created_api_key_id)VALUES($1,$2,$3,$4,$5,$6)',[workspace,operation,generation?'email.generate':'brand.extract',JSON.stringify(generation?{brand_kit_version_id:brand,prompt:'Owned fixture',locale:'en-US',mode:'single'}:{url:'https://example.org'}),user,key]);if(generation)await db.query("INSERT INTO usage_ledger(workspace_id,operation_id,metric,kind,units)VALUES($1,$2,'generation','reserve',1)",[workspace,operation]);return{workspace_id:workspace,operation_id:operation,key,user};}
async function until(check:()=>Promise<boolean>,label:string,ms=8000){const end=Date.now()+ms;while(Date.now()<end){if(await check())return;await new Promise(r=>setTimeout(r,20));}throw new Error('Owned fixture timeout: '+label);}
test('a failed deterministic Redis wake is rebuilt after a transient SQL claim failure',async()=>withCreationDatabase(async connection=>{
 const db=new pg.Pool({connectionString:connection}),worker=new pg.Pool({connectionString:connection,options:'-c role=mailcraft_creation_worker -c lock_timeout=100'}),scheduler=new pg.Pool({connectionString:connection,options:'-c role=mailcraft_creation_scheduler'}),prefix='creation-fixture-'+randomUUID().replaceAll('-',''),stop=new AbortController(),redis=new Redis(process.env.REDIS_URL!);let service:Awaited<ReturnType<typeof startCreationService>>|undefined,calls=0;const lock=await db.connect();
 try{service=await startCreationService({workerPool:worker,schedulerPool:scheduler,redisUrl:process.env.REDIS_URL!,prefix,signal:stop.signal,adapters:{preflight(){},generate:async()=>{throw new Error('No AI adapter');},extract:async()=>{calls++;return{proposal:'Owned fixture'};}}});const f=await seed(db),wake={workspace_id:f.workspace_id,operation_id:f.operation_id};await lock.query('BEGIN');await lock.query('SELECT id FROM workspaces WHERE id=$1 FOR UPDATE',[f.workspace_id]);await service.enqueueCreation(wake,'brand.extract');const queue=service.queues[1],id=creationJobId(wake);await until(async()=>{const job=await queue.getJob(id);return!!job&&(await job.getState())==='failed';},'retained failed wake');assert.equal(calls,0);await lock.query('COMMIT');for(let i=0;i<3;i++)await service.reconcileCreation();await until(async()=>(await db.query('SELECT state FROM operations WHERE id=$1',[f.operation_id])).rows[0].state==='succeeded','recovered failed wake');assert.equal(calls,1);
 }finally{await lock.query('ROLLBACK');lock.release();stop.abort();await service?.close();const keys=await redis.keys(prefix+':*');if(keys.length)await redis.del(...keys);await redis.quit();await Promise.all([db.end(),worker.end(),scheduler.end()]);}
}));
test('known generation success after key revocation or permission loss consumes once without publishing',async()=>withCreationDatabase(async connection=>{
 const db=new pg.Pool({connectionString:connection}),worker=new pg.Pool({connectionString:connection,options:'-c role=mailcraft_creation_worker'});try{for(const mode of['revoked','expired','scope','member','workspace']){const f=await seed(db,true),claim=await claimCreation(worker,{workspace_id:f.workspace_id,operation_id:f.operation_id});assert.ok(claim);assert.ok(await beginCreationAttempt(worker,claim));if(mode==='revoked')await db.query('UPDATE api_keys SET revoked_at=clock_timestamp()WHERE id=$1',[f.key]);if(mode==='expired')await db.query("UPDATE api_keys SET expires_at=clock_timestamp()-interval '1 second'WHERE id=$1",[f.key]);if(mode==='scope')await db.query("UPDATE api_keys SET scopes='[\"brands:write\"]'WHERE id=$1",[f.key]);if(mode==='member')await db.query("UPDATE memberships SET role='Viewer'WHERE workspace_id=$1 AND user_id=$2",[f.workspace_id,f.user]);if(mode==='workspace')await db.query("UPDATE workspaces SET status='locked'WHERE id=$1",[f.workspace_id]);assert.equal(await settleCreation(worker,claim,{outcome:'success',result:{proposals:['Known charge fixture']}}),true);assert.equal(await settleCreation(worker,claim,{outcome:'success',result:{proposals:['Duplicate']}}),false);const row=(await db.query('SELECT state,result,error FROM operations WHERE id=$1',[f.operation_id])).rows[0];assert.equal(row.state,'cancelled',mode);assert.equal(row.result,null);assert.equal(row.error.code,'PERMISSION_REVOKED');assert.deepEqual((await db.query("SELECT kind FROM usage_ledger WHERE operation_id=$1 AND kind<>'reserve'",[f.operation_id])).rows.map(r=>r.kind),['consume']);}}
 finally{await Promise.all([db.end(),worker.end()]);}
}));
test('post-start key expiry during settlement lock wait suppresses the proposal and keeps known charge',async()=>withCreationDatabase(async connection=>{
 const db=new pg.Pool({connectionString:connection}),worker=new pg.Pool({connectionString:connection,options:'-c role=mailcraft_creation_worker'}),lock=await db.connect();let pending:Promise<boolean>|undefined;try{const f=await seed(db,true),claim=await claimCreation(worker,{workspace_id:f.workspace_id,operation_id:f.operation_id});assert.ok(claim);assert.ok(await beginCreationAttempt(worker,claim));await db.query("UPDATE api_keys SET expires_at=clock_timestamp()+interval '1 second'WHERE id=$1",[f.key]);await lock.query('BEGIN');const pid=(await lock.query('SELECT pg_backend_pid()AS pid')).rows[0].pid;await lock.query('SELECT operation_id FROM creation_jobs WHERE operation_id=$1 FOR UPDATE',[f.operation_id]);pending=settleCreation(worker,claim,{outcome:'success',result:{proposals:['Owned fixture']}});await until(async()=>!!(await db.query('SELECT FROM pg_stat_activity WHERE $1::int=ANY(pg_blocking_pids(pid))',[pid])).rowCount,'settlement lock');await until(async()=>(await db.query('SELECT expires_at<=clock_timestamp()AS expired FROM api_keys WHERE id=$1',[f.key])).rows[0].expired,'key expiry');await lock.query('COMMIT');assert.equal(await pending,true);assert.equal((await db.query('SELECT state FROM operations WHERE id=$1',[f.operation_id])).rows[0].state,'cancelled');assert.equal((await db.query("SELECT count(*)::int AS n FROM usage_ledger WHERE operation_id=$1 AND kind='consume'",[f.operation_id])).rows[0].n,1);}finally{await lock.query('ROLLBACK');lock.release();await pending?.catch(()=>undefined);await Promise.all([db.end(),worker.end()]);}
}));
test('committed PostgreSQL cancellation between redirect hops prevents another extraction request',async t=>withCreationDatabase(async connection=>{
 const http=(await import('node:http')).default,https=(await import('node:https')).default,dns=(await import('node:dns/promises')).default,{EventEmitter}=await import('node:events'),{syncBuiltinESMExports}=await import('node:module'),{safeFetchHtml}=await import('../src/server/safe-fetch'),{runCreation}=await import('../src/server/creation-engine'),{prepareCreationAttempt,renewCreation}=await import('../src/server/creation-queue-store');const db=new pg.Pool({connectionString:connection}),worker=new pg.Pool({connectionString:connection,options:'-c role=mailcraft_creation_worker'});let calls=0;
 try{const f=await seed(db);await db.query("UPDATE operations SET input=jsonb_build_object('url','http://example.org')WHERE id=$1",[f.operation_id]);const claim=await claimCreation(worker,{workspace_id:f.workspace_id,operation_id:f.operation_id});assert.ok(claim);t.mock.method(https,'get',()=>{throw new Error('Owned fixture refuses HTTPS traffic.');});t.mock.method(dns,'lookup',async()=>[{address:'93.184.215.14',family:4}]);syncBuiltinESMExports();t.mock.method(http,'get',(_url:unknown,_options:unknown,callback:(response:unknown)=>void)=>{calls++;const first=calls===1,request=new EventEmitter()as Emitter&{setTimeout:()=>void;destroy:()=>void};request.setTimeout=()=>{};request.destroy=()=>{request.emit('close');};queueMicrotask(()=>{void(async()=>{if(first)await db.query("UPDATE operations SET state='cancel_requested'WHERE id=$1",[f.operation_id]);const response=new EventEmitter()as Emitter&{statusCode:number;headers:Record<string,string>;destroy:()=>void};response.statusCode=first?301:200;response.headers=first?{location:'/redirected'}:{'content-type':'text/html'};response.destroy=()=>{request.emit('close');};callback(response);if(!first){response.emit('data',Buffer.from('<p>Owned fixture</p>'));response.emit('end');request.emit('close');}})().catch(error=>request.emit('error',error));});return request;});syncBuiltinESMExports();
 await runCreation(claim,{store:{prepare:c=>prepareCreationAttempt(worker,c),begin:c=>beginCreationAttempt(worker,c),renew:c=>renewCreation(worker,c),settle:(c,o)=>settleCreation(worker,c,o)},signal:new AbortController().signal,adapters:{preflight(){},generate:async()=>{throw new Error('No AI fixture');},extract:async(c,s,beforeRead)=>{await(safeFetchHtml as(input:string,signal?:AbortSignal,guard?:()=>Promise<void>)=>Promise<unknown>)(String(c.operation.input.url),s,beforeRead);return{proposal:'Owned fixture'};}}});assert.equal(calls,1);const row=(await db.query('SELECT state,result FROM operations WHERE id=$1',[f.operation_id])).rows[0];assert.equal(row.state,'cancelled');assert.equal(row.result,null);
 }finally{t.mock.restoreAll();syncBuiltinESMExports();await Promise.all([db.end(),worker.end()]);}
}));
