import test from'node:test';import assert from'node:assert/strict';import{spawnSync}from'node:child_process';
test('creation production entry refuses disabled activation and incomplete same-build evidence before queues/providers',()=>{
 const base={...process.env,LOCAL_DEVELOPMENT:'false',DATABASE_URL:'',MIGRATION_DATABASE_URL:'',LOCAL_BOOTSTRAP_SECRET:'',CREATION_WORKER_DATABASE_URL:'postgresql://private-worker@127.0.0.1:1/fixture',CREATION_SCHEDULER_DATABASE_URL:'postgresql://private-scheduler@127.0.0.1:1/fixture',REDIS_URL:'redis://127.0.0.1:1',RELEASE_BUILD:'owned-gate-fixture'};
 for(const enabled of['false','true']){const child=spawnSync(process.execPath,['--import','tsx','src/server/creation-worker.ts'],{env:{...base,CREATION_WORKER_ENABLED:enabled},encoding:'utf8',timeout:5000});assert.equal(child.status,1);assert.match(child.stderr,enabled==='true'?/full-GA evidence incomplete/:/Creation worker disabled/);assert.doesNotMatch(child.stderr,/ECONNREFUSED|creation_wakeup_unavailable/);}
});
test('complete owned activation evidence still refuses missing model or finite allowance before database or Redis access',async()=>{
 const{mkdtemp,writeFile,rm}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join}=await import('node:path'),directory=await mkdtemp(join(tmpdir(),'lettercape-creation-gate-')),script=new URL('../src/server/creation-worker.ts',import.meta.url).pathname,build='owned-provider-preflight',path=join(directory,'owned-evidence.txt');
 try{await writeFile(path,'Owned test only. No production approval.');const gates:Record<string,string>={},evidence:Record<string,unknown>={};for(let i=1;i<=13;i++){const id='GATE-'+String(i).padStart(2,'0');gates[id]='passed';evidence[id]={build,environment:'production',owner:'Owned fixture',time:new Date().toISOString(),path};}await writeFile(join(directory,'release-gates.json'),JSON.stringify({baseline:'A-full-GA',environment:'production',gates,evidence}));
 for(const config of[{OPENAI_API_KEY:'',OPENAI_MODEL:'',AI_GENERATION_ALLOWANCE:'0'},{OPENAI_API_KEY:'owned-never-used',OPENAI_MODEL:'',AI_GENERATION_ALLOWANCE:'1'},{OPENAI_API_KEY:'owned-never-used',OPENAI_MODEL:'owned-never-used',AI_GENERATION_ALLOWANCE:'Infinity'}]){const child=spawnSync(process.execPath,['--import',import.meta.resolve('tsx'),script],{cwd:directory,env:{PATH:process.env.PATH,NODE_ENV:'test',LOCAL_DEVELOPMENT:'false',CREATION_WORKER_ENABLED:'true',CREATION_WORKER_DATABASE_URL:'postgresql://private-worker@127.0.0.1:1/fixture',CREATION_SCHEDULER_DATABASE_URL:'postgresql://private-scheduler@127.0.0.1:1/fixture',REDIS_URL:'redis://127.0.0.1:1',RELEASE_BUILD:build,...config},encoding:'utf8',timeout:5000});assert.equal(child.status,1);assert.match(child.stderr,/PROVIDER_NOT_READY|AI provider.*configured|finite approved generation allowance/i);assert.doesNotMatch(child.stderr,/ECONNREFUSED|creation_wakeup_unavailable/);}
 }finally{await rm(directory,{recursive:true,force:true});}
});
