import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID}from'node:crypto';
import pg from'pg';
import {withCreationDatabase}from'./fixtures/creation-database';
import {blankSpec}from'../src/domain/email';
import {createEmail,saveDraft} from '../src/server/emails';
import {prepareEmailConversion,acceptEmailConversion}from'../src/server/email-conversion';
import type{Principal}from'../src/server/auth';
async function fixture(run:(db:pg.Pool,app:pg.Pool,p:Principal,id:string)=>Promise<void>){
 await withCreationDatabase(async url=>{const db=new pg.Pool({connectionString:url}),app=new pg.Pool({connectionString:url,options:'-c role=mailcraft_runtime'}),workspace=randomUUID(),user='conversion-db-'+randomUUID(),brand=randomUUID();
 try{await db.query("INSERT INTO workspaces(id,name)VALUES($1,'Owned conversion')",[workspace]);await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,'Owner')",[workspace,user]);await db.query("INSERT INTO brands(workspace_id,id,version,data)VALUES($1,$2,1,'{}')",[workspace,brand]);const spec={...blankSpec(brand,'Owned'),editing_mode:'raw_html' as const,raw_html:'<h1>Owned title</h1><p>Exact source</p><table><tbody><tr><td>Preserved layout</td></tr></tbody></table>'};const principal:Principal={workspace,user,role:'Owner'},created=await tx(app,principal,c=>createEmail(c,principal,'Owned conversion',spec));await run(db,app,principal,created.id);}finally{await Promise.all([app.end(),db.end()]);}});
}
async function tx<T>(app:pg.Pool,p:Principal,run:(c:pg.PoolClient)=>Promise<T>){const c=await app.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('app.workspace_id',$1,true),set_config('app.user_id',$2,true)",[p.workspace,p.user]);const result=await run(c);await c.query('COMMIT');return result;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
const error=(status:number,code:string)=>(e:unknown)=>(e as {status?:number;code?:string}).status===status&&(e as {code?:string}).code===code;
test('conversion proposals are read-only; acceptance pins source, checkpoints original and replays original fact without duplicate head',async()=>fixture(async(db,app,p,id)=>{
 const before=(await db.query('SELECT spec,doc_version FROM emails WHERE id=$1',[id])).rows[0];const proposal=await tx(app,p,c=>prepareEmailConversion(c,p,id,{expected_version:1}));assert.equal(proposal.status,'available');assert.equal((await db.query('SELECT count(*)::int AS n FROM revisions')).rows[0].n,0);assert.deepEqual((await db.query('SELECT spec,doc_version FROM emails WHERE id=$1',[id])).rows[0],before);
 const input={expected_version:1,source_hash:proposal.source_hash,proposal_hash:proposal.proposal_hash,acknowledge_layout_change:true as const},key=randomUUID();const saved=await tx(app,p,c=>acceptEmailConversion(c,p,id,input,key));assert.equal(saved.email.doc_version,2);assert.equal(saved.email.spec.editing_mode,'structured');assert.ok(saved.email.spec.sections.some(x=>x.type==='custom_html'&&x.html.includes('Preserved layout')));
 const history=(await db.query('SELECT spec,source_doc_version FROM revisions WHERE email_id=$1 ORDER BY revision_no',[id])).rows;assert.equal(history.length,2);assert.deepEqual(history[0].spec,before.spec);assert.equal(history[0].source_doc_version,1);assert.deepEqual(history[1].spec,saved.email.spec);assert.equal(history[1].source_doc_version,2);
 await db.query("UPDATE emails SET doc_version=3,spec=jsonb_set(spec,'{subject}','\"Later current subject\"')WHERE id=$1",[id]);const replay=await tx(app,p,c=>acceptEmailConversion(c,p,id,input,key));assert.deepEqual(replay,saved);assert.equal((await db.query('SELECT doc_version FROM emails WHERE id=$1',[id])).rows[0].doc_version,3);assert.equal((await db.query('SELECT count(*)::int AS n FROM revisions')).rows[0].n,2);
 await assert.rejects(tx(app,p,c=>acceptEmailConversion(c,p,id,{...input,proposal_hash:'0'.repeat(64)},key)),error(409,'IDEMPOTENCY_MISMATCH'));
}));
test('stale or tampered conversion never creates a checkpoint or changes raw source, and unavailable conversion stays raw',async()=>fixture(async(db,app,p,id)=>{
 const proposal=await tx(app,p,c=>prepareEmailConversion(c,p,id,{expected_version:1}));const input={expected_version:1,source_hash:proposal.source_hash,proposal_hash:proposal.proposal_hash,acknowledge_layout_change:true as const};
 await assert.rejects(tx(app,p,c=>acceptEmailConversion(c,p,id,{...input,source_hash:'0'.repeat(64)},randomUUID())),error(409,'CONVERSION_SOURCE_CHANGED'));
 await assert.rejects(tx(app,p,c=>acceptEmailConversion(c,p,id,{...input,proposal_hash:'0'.repeat(64)},randomUUID())),error(409,'CONVERSION_SOURCE_CHANGED'));
 await tx(app,p,async c=>{const current=(await c.query('SELECT spec FROM emails WHERE id=$1',[id])).rows[0];return saveDraft(c,p,id,1,{...current.spec,raw_html:'<p>New source</p>'});});await assert.rejects(tx(app,p,c=>acceptEmailConversion(c,p,id,input,randomUUID())),error(412,'VERSION_MISMATCH'));
 await tx(app,p,async c=>{const current=(await c.query('SELECT spec FROM emails WHERE id=$1',[id])).rows[0];return saveDraft(c,p,id,2,{...current.spec,raw_html:'<html><body><p>Wrapper</p></body></html>'});});const unavailable=await tx(app,p,c=>prepareEmailConversion(c,p,id,{expected_version:3}));assert.equal(unavailable.status,'unsupported');await assert.rejects(tx(app,p,c=>acceptEmailConversion(c,p,id,{...input,expected_version:3,source_hash:unavailable.source_hash,proposal_hash:unavailable.proposal_hash},randomUUID())),error(409,'CONVERSION_UNSUPPORTED'));
 assert.equal((await db.query('SELECT count(*)::int AS n FROM revisions')).rows[0].n,0);assert.equal((await db.query("SELECT spec->>'editing_mode' AS mode FROM emails WHERE id=$1",[id])).rows[0].mode,'raw_html');
}));
test('conversion admission denies foreign source and current Viewer before reads or receipt replay',async()=>fixture(async(db,app,p,id)=>{
 await assert.rejects(tx(app,p,c=>prepareEmailConversion(c,p,randomUUID(),{expected_version:1})),error(404,'RESOURCE_NOT_FOUND'));
 const proposal=await tx(app,p,c=>prepareEmailConversion(c,p,id,{expected_version:1}));const input={expected_version:1,source_hash:proposal.source_hash,proposal_hash:proposal.proposal_hash,acknowledge_layout_change:true as const},key=randomUUID();await tx(app,p,c=>acceptEmailConversion(c,p,id,input,key));await db.query("UPDATE memberships SET role='Viewer'WHERE workspace_id=$1 AND user_id=$2",[p.workspace,p.user]);await assert.rejects(tx(app,p,c=>prepareEmailConversion(c,p,id,{expected_version:2})),error(403,'INSUFFICIENT_SCOPE'));await assert.rejects(tx(app,p,c=>acceptEmailConversion(c,p,id,input,key)),error(403,'INSUFFICIENT_SCOPE'));
}));
test('passive session expiry while waiting on raw source lock denies conversion before checkpoint or mutation',async()=>fixture(async(db,app,p,id)=>{
 const token=randomUUID().replaceAll('-','');await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,clock_timestamp()+interval '2 seconds')",[token,p.user]);const session={...p,local_session:{token_hash:token}},proposal=await tx(app,session,c=>prepareEmailConversion(c,session,id,{expected_version:1}));const input={expected_version:1,source_hash:proposal.source_hash,proposal_hash:proposal.proposal_hash,acknowledge_layout_change:true as const},blocker=await db.connect();let waiting:Promise<unknown>|undefined;
 try{await blocker.query('BEGIN');await blocker.query('SELECT id FROM emails WHERE id=$1 FOR UPDATE',[id]);waiting=tx(app,session,c=>acceptEmailConversion(c,session,id,input,randomUUID()));let blocked=false;
  for(let n=0;n<100;n++){blocked=(await db.query("SELECT EXISTS(SELECT1 FROM pg_stat_activity WHERE datname=current_database() AND query LIKE 'SELECT id FROM emails WHERE id=%' AND cardinality(pg_blocking_pids(pid))>0)AS blocked".replace('SELECT1','SELECT 1'))).rows[0].blocked;if(blocked)break;await new Promise(resolve=>setTimeout(resolve,20));}assert.equal(blocked,true,'The actual conversion must wait on the owned source row.');
  for(;;){if((await db.query('SELECT expires_at<=clock_timestamp()AS expired FROM auth_sessions WHERE token_hash=$1',[token])).rows[0].expired)break;await new Promise(resolve=>setTimeout(resolve,25));}
  await blocker.query('COMMIT');await assert.rejects(waiting,error(401,'AUTH_REQUIRED'));assert.equal((await db.query('SELECT count(*)::int AS n FROM revisions')).rows[0].n,0);assert.equal((await db.query('SELECT doc_version FROM emails WHERE id=$1',[id])).rows[0].doc_version,1);
 }finally{await blocker.query('ROLLBACK');blocker.release();await waiting?.catch(()=>{});}
}));
