import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {sourceDatabase} from '../scripts/smoke-source-truth';import {blankSpec} from '../src/domain/email';import {createEmail,checkpoint,saveDraft} from '../src/server/emails';import {deriveEmail} from '../src/server/derivation';import {localeSourceComparison} from '../src/server/locale-source-comparison';
test('actual read-only comparison pins original lineage and current parent/child while preserving every version',async()=>sourceDatabase(async({db,p,brand,tx})=>{
 const parent=await tx(c=>createEmail(c,p,'Parent',blankSpec(brand,'Parent'))),frozen=await tx(c=>checkpoint(c,p,parent.id,1)),child=await tx(c=>deriveEmail(c,p,frozen.id,{kind:'locale',title:'French',locale:'fr-FR'}));
 const target=await tx(c=>saveDraft(c,p,child.email.id,1,{...child.email.spec,subject:'Manuel'}));await tx(c=>saveDraft(c,p,parent.id,1,{...parent.spec,subject:'New parent'}));
 const before=(await db.query('SELECT id,doc_version,spec FROM emails ORDER BY id')).rows;const counts=(await db.query('SELECT (SELECT count(*) FROM revisions) revisions,(SELECT count(*)FROM audit_events) audits,(SELECT count(*)FROM idempotency) commands')).rows;
 const comparison=await tx(c=>localeSourceComparison(c,p,child.email.id));assert.equal(comparison.baseline.spec.subject,parent.spec.subject);assert.equal(comparison.parent.spec.subject,'New parent');assert.equal(comparison.target.spec.subject,'Manuel');assert.equal(comparison.target.doc_version,target.doc_version);assert.equal(comparison.source_status,'outdated');assert.equal(comparison.baseline.revision_id,frozen.id);assert.equal(comparison.parent.id,parent.id);
 assert.deepEqual((await db.query('SELECT id,doc_version,spec FROM emails ORDER BY id')).rows,before);assert.deepEqual((await db.query('SELECT (SELECT count(*) FROM revisions) revisions,(SELECT count(*)FROM audit_events) audits,(SELECT count(*)FROM idempotency) commands')).rows,counts);
 await tx(c=>saveDraft(c,p,parent.id,2,{...parent.spec,subject:'Newer parent'}));assert.equal((await tx(c=>localeSourceComparison(c,p,child.email.id))).parent.doc_version,3);
 await assert.rejects(tx(c=>localeSourceComparison(c,p,parent.id)),{code:'LOCALE_DRAFT_REQUIRED'});await assert.rejects(tx(c=>localeSourceComparison(c,p,randomUUID())),{code:'RESOURCE_NOT_FOUND'});
 const viewer='viewer-'+randomUUID();await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,'Viewer')",[p.workspace,viewer]);assert.equal((await tx(c=>localeSourceComparison(c,{...p,user:viewer,role:'Viewer'},child.email.id),viewer)).actor_id,viewer);
 await assert.rejects(tx(c=>localeSourceComparison(c,{...p,workspace:randomUUID()},child.email.id)));
 const foreignWorkspace=randomUUID(),foreignId=randomUUID();await db.query("INSERT INTO workspaces(id,name)VALUES($1,'foreign comparison fixture')",[foreignWorkspace]);await db.query('INSERT INTO emails(workspace_id,id,title,spec,created_by)VALUES($1,$2,$3,$4,$5)',[foreignWorkspace,foreignId,'Foreign',JSON.stringify(blankSpec(brand,'Foreign')),p.user]);await assert.rejects(tx(c=>localeSourceComparison(c,p,foreignId)),{code:'RESOURCE_NOT_FOUND'});
}));
test('actual oversized escaped three-document comparison refuses without modifying accepted raw source',async()=>sourceDatabase(async({db,p,brand,tx})=>{
 const source='"'.repeat(1500000),parent=await tx(c=>createEmail(c,p,'Large source',{...blankSpec(brand,'Owned'),editing_mode:'raw_html',raw_html:source})),frozen=await tx(c=>checkpoint(c,p,parent.id,1)),child=await tx(c=>deriveEmail(c,p,frozen.id,{kind:'locale',title:'Large French',locale:'fr-FR'}));
 const before=(await db.query("SELECT id,doc_version,octet_length(spec->>'raw_html') bytes,encode(sha256(convert_to(spec->>'raw_html','UTF8')),'hex') hash FROM emails ORDER BY id")).rows;
 await assert.rejects(tx(c=>localeSourceComparison(c,p,child.email.id)),{code:'LOCALE_COMPARISON_TOO_LARGE',status:413});assert.deepEqual((await db.query("SELECT id,doc_version,octet_length(spec->>'raw_html') bytes,encode(sha256(convert_to(spec->>'raw_html','UTF8')),'hex') hash FROM emails ORDER BY id")).rows,before);
}));
