import test from 'node:test';import assert from 'node:assert/strict';
import {blankSpec} from '../src/domain/email';import {localeComparisonRows,applyLocaleSourceSelection} from '../src/domain/locale-source-comparison';
test('selected untranslated source text preserves manual translations and nontext facts',()=>{
 const original={...blankSpec('owned','Original'),subject:'Old',sections:[{id:'copy',type:'hero' as const,heading:'Old heading',text:'Old text'},{id:'cta',type:'button' as const,label:'Old label',href:'https://old.example.com'}]};
 const source={...original,subject:'New',sections:[{...original.sections[0],heading:'New heading',text:'New text'},{...original.sections[1],label:'New label',href:'https://new.example.com'}]};
 const target={...original,locale:'ar-SA' as const,direction:'rtl' as const,subject:'عنوان',preheader:'Manual preheader',sections:[{id:'copy',type:'hero' as const,heading:'عنوان يدوي',text:'Manual body'},{id:'cta',type:'button' as const,label:'Manual CTA',href:'https://manual.example.com'}]};
 const before=structuredClone(target);const result=applyLocaleSourceSelection(original,source,target,['subject',JSON.stringify(['copy','heading']),JSON.stringify(['cta','label'])]);
 assert.equal(result.subject,'New');assert.equal(result.sections[0].type==='hero'&&result.sections[0].heading,'New heading');assert.equal(result.sections[0].type==='hero'&&result.sections[0].text,'Manual body');assert.equal(result.sections[1].type==='button'&&result.sections[1].href,'https://manual.example.com');assert.equal(result.preheader,'Manual preheader');assert.equal(result.locale,'ar-SA');assert.equal(result.direction,'rtl');assert.deepEqual(target,before);assert.deepEqual(result.theme,target.theme);
});
test('raw, structural, image, custom and legal changes are visible and cannot be selectively copied',()=>{
 const original={...blankSpec('owned','Original'),sections:[{id:'opaque',type:'custom_html' as const,html:'<p>Old</p>'},{id:'old',type:'text' as const,text:'Old'}]};const source={...original,sections:[{id:'opaque',type:'custom_html' as const,html:'<script>globalThis.__localeRan=true</script>\r\n'},{id:'old',type:'button' as const,label:'Type changed',href:'https://example.com'},{id:'new',type:'text' as const,text:'Added'}]};
 const rows=localeComparisonRows(original,source,original);assert.ok(rows.some(r=>r.source.includes('<script>')));assert.equal(rows.filter(r=>r.selectable).length,0);assert.throws(()=>applyLocaleSourceSelection(original,source,original,[JSON.stringify(['opaque'])]));assert.throws(()=>applyLocaleSourceSelection(original,source,original,[]));
 const raw={...original,editing_mode:'raw_html' as const,raw_html:'\ufeff<!--exact-->\r\n<script>raw()</script>'};const changed={...raw,raw_html:raw.raw_html+'\r',subject:'New'};const rawRows=localeComparisonRows(raw,changed,raw);assert.equal(rawRows.at(-1)?.source,changed.raw_html);assert.ok(rawRows.every(r=>!r.selectable));assert.throws(()=>applyLocaleSourceSelection(raw,changed,raw,['subject']));
});
test('selected text validation refuses changed or duplicate selectors and preserves offer price/URL',()=>{
 const original={...blankSpec('owned','Original'),sections:[{id:'product',type:'product_card' as const,title:'Old',description:'Old description',price:'EUR 10',href:'https://example.com/old'}]};const source={...original,sections:[{...original.sections[0],title:'New',description:'New description',price:'USD 12',href:'https://example.com/new'}]};const target={...original,sections:[{...original.sections[0],title:'Manual',price:'JPY 1000',href:'https://example.com/manual'}]};const key=JSON.stringify(['product','title']);
 const result=applyLocaleSourceSelection(original,source,target,[key]);assert.equal(result.sections[0].type==='product_card'&&result.sections[0].price,'JPY 1000');assert.equal(result.sections[0].type==='product_card'&&result.sections[0].href,'https://example.com/manual');assert.throws(()=>applyLocaleSourceSelection(original,source,target,[key,key]));assert.throws(()=>applyLocaleSourceSelection(original,source,target,[JSON.stringify(['product','price'])]));
});
