import test from'node:test';import assert from'node:assert/strict';import{randomUUID}from'node:crypto';
import{comparisonSelectionKey,readComparisonSelection,writeComparisonSelection}from'../src/ui/revision-comparison-selection';import{scopeForResource}from'../src/domain/api-keys';
test('checkpoint selection stores metadata only and isolates workspace/account/email without adopting malformed recovery',()=>{
 const scope={workspace:randomUUID(),actor:'fixture',email:randomUUID()},data=new Map<string,string>(),storage={getItem:(key:string)=>data.get(key)??null,setItem:(key:string,value:string)=>{data.set(key,value);}},pair={before:randomUUID(),after:randomUUID(),open:true};writeComparisonSelection(scope,pair,storage);assert.deepEqual(readComparisonSelection(scope,storage),pair);assert.deepEqual(Object.keys(JSON.parse(data.get(comparisonSelectionKey(scope))!)),['before','after','open']);for(const field of ['workspace','actor','email'])assert.equal(readComparisonSelection({...scope,[field]:randomUUID()},storage),null);data.set(comparisonSelectionKey(scope),JSON.stringify({...pair,spec:'private'}));assert.throws(()=>readComparisonSelection(scope,storage));assert.throws(()=>writeComparisonSelection(scope,pair,{setItem:()=>{throw new DOMException('quota','QuotaExceededError');}}));
});
test('new read-only comparison family uses existing email read scope and never grants write scope',()=>{assert.equal(scopeForResource('revision-comparisons','GET',undefined),'emails:read');assert.equal(scopeForResource('revision-comparisons','POST',undefined),'unsupported');});
test('uppercase recovered checkpoint selections normalize while scoped storage and actor identity stay exact',()=>{
 const first='abcdefab-cdef-4abc-8def-abcdefabcdef',second='fedcbafe-dcba-4fed-8cba-fedcbafedcba',scope={workspace:randomUUID(),actor:'CaseSensitiveActor',email:second},other={...scope,actor:'casesensitiveactor'},values=new Map<string,string>(),storage={getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value);}};values.set(comparisonSelectionKey(scope),JSON.stringify({before:first.toUpperCase(),after:second.toUpperCase(),open:true}));assert.deepEqual(readComparisonSelection(scope,storage),{before:first,after:second,open:true});assert.equal(readComparisonSelection(other,storage),null);writeComparisonSelection(scope,{before:first.toUpperCase(),after:second.toUpperCase(),open:true},storage);assert.deepEqual(JSON.parse(values.get(comparisonSelectionKey(scope))!),{before:first,after:second,open:true});assert.notEqual(comparisonSelectionKey(scope),comparisonSelectionKey({...scope,email:scope.email.toUpperCase()}));
});
