import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {blankSpec} from '../src/domain/email';import {revisionComparisonRows,RevisionComparisonSchema,RevisionComparisonQuery} from '../src/domain/revision-comparison';
import {EmailSourceSpecSchema} from '../src/domain/email-schema';
const brand=randomUUID();
test('structured comparisons identify field edits and nested stable-ID moves/add/remove without changing either checkpoint',()=>{
 const a={...blankSpec(brand,'Before'),sections:[{id:'cols',type:'columns' as const,columns:[[{id:'copy',type:'text' as const,text:'Original'},{id:'gone',type:'button' as const,label:'Old',href:'https://example.test'}],[]]}]};const b=structuredClone(a);b.subject='After';b.sections[0].columns=[[{id:'added',type:'text',text:'Added'}],[{id:'copy',type:'text',text:'Changed'}]];
 const pristine=JSON.stringify([a,b]),rows=revisionComparisonRows(a,b);assert.ok(rows.some(r=>r.label==='Subject'&&r.before===a.subject&&r.after==='After'));assert.ok(rows.some(r=>r.kind==='structure'&&r.label.includes('copy')&&r.changed));assert.ok(rows.some(r=>r.key===JSON.stringify(['block', 'copy', 'field', 'text'])&&r.before==='Original'&&r.after==='Changed'));assert.ok(rows.some(r=>r.key===JSON.stringify(['block', 'gone', 'presence'])&&r.after==='(Absent)'));assert.ok(rows.some(r=>r.key===JSON.stringify(['block', 'added', 'presence'])&&r.before==='(Absent)'));assert.equal(JSON.stringify([a,b]),pristine);
});
test('raw source changes remain byte-exact even when only CRLF/BOM changes; mode switches distinguish inactive stored blocks',()=>{
 const a={...blankSpec(brand,'Raw'),editing_mode:'raw_html' as const,raw_html:'\ufeff<p>é 😀</p>\r\n'},b={...a,raw_html:'<p>é 😀</p>\n'};const row=revisionComparisonRows(a,b).find(r=>r.key==='raw_html');assert.equal(row?.before,a.raw_html);assert.equal(row?.after,b.raw_html);assert.equal(row?.kind,'source');assert.equal(row?.changed,true);assert.ok(revisionComparisonRows(blankSpec(brand,'Structured'),a).some(r=>r.key==='editing_mode'&&r.after==='raw_html'));assert.ok(revisionComparisonRows(a,b).some(r=>r.key==='stored_sections'&&r.label.includes('inactive')));
});
test('custom HTML is literal source; same checkpoint and duplicate-ID legacy structures are described without dropped data',()=>{
 const a={...blankSpec(brand,'Custom'),sections:[{id:'html',type:'custom_html' as const,html:'<script>inert()</script>\r\n'}]},b={...a,sections:[{...a.sections[0],html:a.sections[0].html+'<!--changed-->'}]};assert.equal(revisionComparisonRows(a,b).find(r=>r.key===JSON.stringify(['block', 'html', 'field', 'html']))?.kind,'source');assert.equal(revisionComparisonRows(a,a).filter(r=>r.changed).length,0);const duplicate={...a,sections:[...a.sections,...a.sections]};assert.ok(revisionComparisonRows(duplicate,b).some(r=>r.key==='ambiguous_sections'&&r.before.includes('<script>')));
});
test('comparison queries/receipts are strict and preserve same-checkpoint comparison while refusing cross-email documents',()=>{
 const id=randomUUID(),before=randomUUID(),after=randomUUID();assert.ok(RevisionComparisonQuery.safeParse({email_id:id,before,after}).success);assert.equal(RevisionComparisonQuery.safeParse({email_id:id,before,after,extra:true}).success,false);const row={id:before,email_id:id,revision_no:1,source_doc_version:null,artifact_hash:'a'.repeat(64),created_at:'2026-10-03T00:00:00Z',raw_source_profile:null,spec:blankSpec(brand,'Test')};assert.ok(RevisionComparisonSchema.safeParse({workspace_id:randomUUID(),actor_id:'fixture',email_id:id,before:row,after:row}).success);assert.equal(RevisionComparisonSchema.safeParse({workspace_id:randomUUID(),actor_id:'fixture',email_id:id,before:row,after:{...row,email_id:randomUUID()}}).success,false);
});
test('structured checkpoints retain inactive raw source differences without omitting block edits',()=>{
 const a={...blankSpec(brand,'Retained'),raw_html:'<p>before</p>\r\n'},b={...a,raw_html:'<p>after</p>\n',subject:'Changed'};assert.ok(EmailSourceSpecSchema.safeParse(a).success);assert.ok(EmailSourceSpecSchema.safeParse(b).success);const rows=revisionComparisonRows(a,b),row=rows.find(r=>r.key==='raw_html');assert.equal(row?.kind,'source');assert.equal(row?.before,a.raw_html);assert.equal(row?.after,b.raw_html);assert.equal(row?.changed,true);assert.ok(row?.label.includes('inactive'));assert.ok(rows.some(r=>r.key==='subject'&&r.changed));
});
test('absent values and a valid literal absence marker are different stored authoring values',()=>{
 const a={...blankSpec(brand,'Presence'),sections:[{id:'presence',type:'divider' as const}]},b={...a,sections:[{id:'presence',type:'custom_html' as const,html:'(Absent)'}]};const row=revisionComparisonRows(a,b).find(r=>r.key===JSON.stringify(['block', 'presence', 'field', 'html']));assert.equal(row?.changed,true);assert.equal(row?.before_present,false);assert.equal(row?.after_present,true);assert.equal(row?.after,'(Absent)');assert.ok(EmailSourceSpecSchema.safeParse(a).success);assert.ok(EmailSourceSpecSchema.safeParse(b).success);const reversed=revisionComparisonRows(b,a).find(r=>r.key===JSON.stringify(['block', 'presence', 'field', 'html']));assert.equal(reversed?.changed,true);assert.equal(reversed?.before_present,true);assert.equal(reversed?.after_present,false);assert.equal(revisionComparisonRows(b,b).filter(r=>r.changed).length,0);const rawA=blankSpec(brand,'Retained'),rawB={...rawA,raw_html:'(Absent)'};assert.equal(revisionComparisonRows(rawA,rawB).find(r=>r.key==='raw_html')?.changed,true);assert.equal(revisionComparisonRows(rawB,rawA).find(r=>r.key==='raw_html')?.changed,true);
});
test('legal colon percent quote Unicode block IDs have unique stable comparison identities across presence and fields',()=>{
 const a={...blankSpec(brand,'Identity fixture'),sections:[{id:'a',type:'text' as const,text:'old'},{id:'a:text',type:'text' as const,text:'removed'},{id:'a%3Atext',type:'text' as const,text:'percent'},{id:'a:"字段',type:'text' as const,text:'unicode'},{id:'col',type:'columns' as const,columns:[[],[]]},{id:'col:column_count',type:'text' as const,text:'removed column ID'}]},b={...a,sections:[{id:'a',type:'text' as const,text:'new'},{id:'a%3Atext',type:'text' as const,text:'changed percent'},{id:'a:"字段',type:'text' as const,text:'changed unicode'},{id:'col',type:'columns' as const,columns:[[]]}]};assert.ok(EmailSourceSpecSchema.safeParse(a).success);assert.ok(EmailSourceSpecSchema.safeParse(b).success);const first=revisionComparisonRows(a,b),second=revisionComparisonRows(structuredClone(a),structuredClone(b));assert.equal(new Set(first.map(r=>r.key)).size,first.length);assert.deepEqual(second.map(r=>r.key),first.map(r=>r.key));assert.ok(first.find(r=>r.label==='Block a · text')?.changed);assert.ok(first.find(r=>r.label==='Block a:text removed')?.changed);assert.equal(first.find(r=>r.label==='Block a:"字段 · text')?.after,'changed unicode');
});
