import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {blankSpec} from '../src/domain/email';import {revisionComparisonRows,RevisionComparisonSchema,RevisionComparisonQuery} from '../src/domain/revision-comparison';
const brand=randomUUID();
test('structured comparisons identify field edits and nested stable-ID moves/add/remove without changing either checkpoint',()=>{
 const a={...blankSpec(brand,'Before'),sections:[{id:'cols',type:'columns' as const,columns:[[{id:'copy',type:'text' as const,text:'Original'},{id:'gone',type:'button' as const,label:'Old',href:'https://example.test'}],[]]}]};const b=structuredClone(a);b.subject='After';b.sections[0].columns=[[{id:'added',type:'text',text:'Added'}],[{id:'copy',type:'text',text:'Changed'}]];
 const pristine=JSON.stringify([a,b]),rows=revisionComparisonRows(a,b);assert.ok(rows.some(r=>r.label==='Subject'&&r.before===a.subject&&r.after==='After'));assert.ok(rows.some(r=>r.kind==='structure'&&r.label.includes('copy')&&r.changed));assert.ok(rows.some(r=>r.key==='node:copy:text'&&r.before==='Original'&&r.after==='Changed'));assert.ok(rows.some(r=>r.key==='node:gone'&&r.after==='(Absent)'));assert.ok(rows.some(r=>r.key==='node:added'&&r.before==='(Absent)'));assert.equal(JSON.stringify([a,b]),pristine);
});
test('raw source changes remain byte-exact even when only CRLF/BOM changes; mode switches distinguish inactive stored blocks',()=>{
 const a={...blankSpec(brand,'Raw'),editing_mode:'raw_html' as const,raw_html:'\ufeff<p>é 😀</p>\r\n'},b={...a,raw_html:'<p>é 😀</p>\n'};const row=revisionComparisonRows(a,b).find(r=>r.key==='raw_html');assert.equal(row?.before,a.raw_html);assert.equal(row?.after,b.raw_html);assert.equal(row?.kind,'source');assert.equal(row?.changed,true);assert.ok(revisionComparisonRows(blankSpec(brand,'Structured'),a).some(r=>r.key==='editing_mode'&&r.after==='raw_html'));assert.ok(revisionComparisonRows(a,b).some(r=>r.key==='stored_sections'&&r.label.includes('inactive')));
});
test('custom HTML is literal source; same checkpoint and duplicate-ID legacy structures are described without dropped data',()=>{
 const a={...blankSpec(brand,'Custom'),sections:[{id:'html',type:'custom_html' as const,html:'<script>inert()</script>\r\n'}]},b={...a,sections:[{...a.sections[0],html:a.sections[0].html+'<!--changed-->'}]};assert.equal(revisionComparisonRows(a,b).find(r=>r.key==='node:html:html')?.kind,'source');assert.equal(revisionComparisonRows(a,a).filter(r=>r.changed).length,0);const duplicate={...a,sections:[...a.sections,...a.sections]};assert.ok(revisionComparisonRows(duplicate,b).some(r=>r.key==='ambiguous_sections'&&r.before.includes('<script>')));
});
test('comparison queries/receipts are strict and preserve same-checkpoint comparison while refusing cross-email documents',()=>{
 const id=randomUUID(),before=randomUUID(),after=randomUUID();assert.ok(RevisionComparisonQuery.safeParse({email_id:id,before,after}).success);assert.equal(RevisionComparisonQuery.safeParse({email_id:id,before,after,extra:true}).success,false);const row={id:before,email_id:id,revision_no:1,source_doc_version:null,artifact_hash:'a'.repeat(64),created_at:'2026-10-03T00:00:00Z',raw_source_profile:null,spec:blankSpec(brand,'Test')};assert.ok(RevisionComparisonSchema.safeParse({workspace_id:randomUUID(),actor_id:'fixture',email_id:id,before:row,after:row}).success);assert.equal(RevisionComparisonSchema.safeParse({workspace_id:randomUUID(),actor_id:'fixture',email_id:id,before:row,after:{...row,email_id:randomUUID()}}).success,false);
});
