import test from'node:test';import assert from'node:assert/strict';import{randomUUID}from'node:crypto';
import{sourceDatabase}from'../scripts/smoke-source-truth';import{blankSpec}from'../src/domain/email';import{createEmail,checkpoint,saveDraft}from'../src/server/emails';import{compareRevisions}from'../src/server/revision-comparison';
test('actual runtime compares exactly two same-email checkpoints with current read permission and no content/audit/history writes',async()=>sourceDatabase(async({db,p,brand,tx})=>{
 const email=await tx(c=>createEmail(c,p,'History fixture',blankSpec(brand,'Before'))),a=await tx(c=>checkpoint(c,p,email.id,1));await tx(c=>saveDraft(c,p,email.id,1,{...email.spec,subject:'Changed'}));const b=await tx(c=>checkpoint(c,p,email.id,2)),other=await tx(c=>createEmail(c,p,'Other',email.spec)),otherRevision=await tx(c=>checkpoint(c,p,other.id,1));
 const witness=async()=>{const out=[];for(const table of['emails','revisions','audit_events','idempotency','email_source_provenance'])out.push((await db.query(`SELECT md5(coalesce(string_agg(md5(to_jsonb(t)::text),'' ORDER BY md5(to_jsonb(t)::text)),'')) AS hash FROM ${table} t`)).rows[0]);return out;};const before=await witness();const input={email_id:email.id,before:a.id,after:b.id},value=await tx(c=>compareRevisions(c,p,input));assert.equal(value.email_id,email.id);assert.equal(value.before.id,a.id);assert.equal(value.after.id,b.id);assert.equal(value.before.spec.subject,email.spec.subject);assert.equal(value.after.spec.subject,'Changed');assert.deepEqual(await witness(),before);
 const viewer='comparison-viewer-'+randomUUID();await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,'Viewer')",[p.workspace,viewer]);assert.equal((await tx(c=>compareRevisions(c,{...p,user:viewer,role:'Viewer'},input),viewer)).actor_id,viewer);await db.query("UPDATE memberships SET role='Billing'WHERE workspace_id=$1 AND user_id=$2",[p.workspace,viewer]);await assert.rejects(tx(c=>compareRevisions(c,{...p,user:viewer,role:'Viewer'},input),viewer),{code:'INSUFFICIENT_SCOPE'});
 await assert.rejects(tx(c=>compareRevisions(c,p,{...input,after:otherRevision.id})),{code:'RESOURCE_NOT_FOUND'});await assert.rejects(tx(c=>compareRevisions(c,p,{...input,before:randomUUID()})),{code:'RESOURCE_NOT_FOUND'});assert.equal((await tx(c=>compareRevisions(c,p,{...input,after:a.id}))).after.id,a.id);
 await assert.rejects(tx(c=>compareRevisions(c,{...p,workspace:randomUUID()},input)));
}));

test('actual escaped pair budget refuses without changing durable maximum-size exact source or frozen history',async()=>sourceDatabase(async({db,p,brand,tx})=>{const raw='"'.repeat(2*1024*1024),email=await tx(c=>createEmail(c,p,'Maximum exact source',{...blankSpec(brand,'Large'),editing_mode:'raw_html',raw_html:raw})),a=await tx(c=>checkpoint(c,p,email.id,1));const before=(await db.query("SELECT id,doc_version,octet_length(spec->>'raw_html') bytes,encode(sha256(convert_to(spec->>'raw_html','UTF8')),'hex') hash FROM emails")).rows;await assert.rejects(tx(c=>compareRevisions(c,p,{email_id:email.id,before:a.id,after:a.id})),{code:'REVISION_COMPARISON_TOO_LARGE',status:413});assert.deepEqual((await db.query("SELECT id,doc_version,octet_length(spec->>'raw_html') bytes,encode(sha256(convert_to(spec->>'raw_html','UTF8')),'hex') hash FROM emails")).rows,before);}));
test('actual comparison uppercase and mixed UUID spellings retrieve canonical records without authoring writes',async()=>sourceDatabase(async({db,p,brand,tx})=>{const email=await tx(c=>createEmail(c,p,'UUID spellings',blankSpec(brand,'First'))),a=await tx(c=>checkpoint(c,p,email.id,1));await tx(c=>saveDraft(c,p,email.id,1,{...email.spec,subject:'Second'}));const b=await tx(c=>checkpoint(c,p,email.id,2));const input={email_id:email.id,before:a.id,after:b.id};const witness=async()=>{const out=[];for(const table of['emails','revisions','audit_events','idempotency','email_source_provenance'])out.push((await db.query(`SELECT md5(coalesce(string_agg(md5(to_jsonb(t)::text),'' ORDER BY md5(to_jsonb(t)::text)),'')) AS hash FROM ${table} t`)).rows[0]);return out;};const before=await witness();for(const candidate of[{...input,before:a.id.toUpperCase()},{...input,after:b.id.toUpperCase()},{...input,email_id:email.id.toUpperCase()},{email_id:email.id.toUpperCase(),before:a.id.toUpperCase(),after:b.id.slice(0,18).toUpperCase()+b.id.slice(18)},{email_id:email.id.toUpperCase(),before:b.id.toUpperCase(),after:a.id.toUpperCase()},{email_id:email.id.toUpperCase(),before:a.id.toUpperCase(),after:a.id.toUpperCase()}]){const receipt=await tx(c=>compareRevisions(c,p,candidate));assert.equal(receipt.email_id,email.id);assert.equal(receipt.before.id,candidate.before.toLowerCase());assert.equal(receipt.after.id,candidate.after.toLowerCase());assert.equal(receipt.actor_id,p.user);}assert.deepEqual(await witness(),before);}));
