import test from'node:test';import assert from'node:assert/strict';import pg from'pg';import env from'@next/env';import{randomUUID,randomBytes}from'node:crypto';import{tenant,closeDb}from'../src/server/db';import{persistWebhookEndpoint}from'../src/server/webhook-endpoints';import{parseWebhookVault}from'../src/server/webhook-secrets';import{recordEvent}from'../src/server/events';import{settleWebhookDelivery}from'../src/server/webhook-deliveries';env.loadEnvConfig(process.cwd());
test('permissioned replay retains logical identity/history/budget and rejects stale, acknowledged, expired or revoked requests',async()=>{
 const db=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL}),workspace=randomUUID(),other=randomUUID(),user='webhook-replay-'+randomUUID(),vault=parseWebhookVault(JSON.stringify({fixture:randomBytes(32).toString('hex')}),'fixture');
 const fixtureLock=await db.connect();await fixtureLock.query("SELECT pg_advisory_lock(hashtextextended('lettercape.fixture.webhook-queue',0))");
 try{await db.query("INSERT INTO workspaces(id,name)VALUES($1,'Replay fixture'),($2,'Replay foreign')",[workspace,other]);await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$3,'Owner'),($2,$3,'Owner')",[workspace,other,user]);
 const created=await tenant(workspace,user,(tx)=>persistWebhookEndpoint(tx,{workspace,user,role:'Owner'},{name:'Replay fixture',url:'https://example.org/hook',subscriptions:['contact.unsubscribed']},vault,new Date().toISOString()));await db.query("UPDATE webhook_endpoints SET status='enabled',version=version+1 WHERE workspace_id=$1",[workspace]);
 const contact=randomUUID();await db.query("INSERT INTO contacts(workspace_id,id,email_original,email_lookup,subscription,consent_version)VALUES($1,$2,'replay@example.org','replay@example.org','unsubscribed',2)",[workspace,contact]);await db.query("INSERT INTO suppressions(workspace_id,contact_id,reason)VALUES($1,$2,'unsubscribe')",[workspace,contact]);const event=await tenant(workspace,user,(tx)=>recordEvent(tx,workspace,{type:'contact.unsubscribed',aggregate:{type:'contact',id:contact,version:2},data:{contact_id:contact,scope:'marketing',reason:'recipient_opt_out'}}));
 const row=(await db.query("INSERT INTO webhook_deliveries(workspace_id,endpoint_id,event_id,state,attempt_number)VALUES($1,$2,$3,'terminal',1)RETURNING *",[workspace,created.endpoint.id,event.id])).rows[0];await db.query("INSERT INTO webhook_attempts(workspace_id,delivery_id,attempt_number,phase,status_code,error_class)VALUES($1,$2,1,'settled',400,'http_terminal')",[workspace,row.id]);assert.equal((await db.query("SELECT deadline-created_at=interval '24 hours'AS exact FROM webhook_deliveries WHERE workspace_id=$1 AND id=$2",[workspace,row.id])).rows[0].exact,true);
 const replay=(expected=1,ack=true,w=workspace)=>tenant(w,user,(tx)=>tx.query('SELECT * FROM mailcraft_replay_webhook($1,$2,$3,$4)',[w,row.id,expected,ack]));
 await assert.rejects(()=>replay(1,false),/REPLAY_ACK_REQUIRED/);await assert.rejects(()=>replay(2),/REPLAY_VERSION_CONFLICT/);await assert.rejects(()=>replay(1,true,other),/RESOURCE_NOT_FOUND/);
 const result=(await replay()).rows[0];assert.equal(result.id,row.id);assert.equal(result.event_id,event.id);assert.equal(result.state,'pending');assert.equal(result.deadline.toISOString(),row.deadline.toISOString());assert.equal(result.failure_attempts,0);assert.equal((await db.query('SELECT count(*)::int AS n FROM webhook_attempts WHERE workspace_id=$1',[workspace])).rows[0].n,1);
 await assert.rejects(()=>replay(),/REPLAY_STATE_CONFLICT/);await db.query("UPDATE webhook_deliveries SET state='acknowledged'WHERE workspace_id=$1",[workspace]);await assert.rejects(()=>replay(),/REPLAY_STATE_CONFLICT/);
 const leaseToken=randomUUID();await db.query("UPDATE webhook_deliveries SET state='leased',attempt_number=2,lease_token=$3,lease_until=clock_timestamp()+interval '30 seconds',authorized_until=clock_timestamp()+interval '10 seconds',authorized_key_version=1 WHERE workspace_id=$1 AND id=$2",[workspace,row.id,leaseToken]);
 const worker=await db.connect();try{await worker.query('BEGIN');await worker.query('SET LOCAL ROLE mailcraft_webhook_worker');assert.equal(await settleWebhookDelivery(worker,{id:row.id,workspace_id:workspace,endpoint_id:created.endpoint.id,event_id:event.id,attempt_number:2,lease_token:leaseToken},{status:429,retry_after:'86400',error_class:null},0.5),true);await worker.query('COMMIT');}catch(error){await worker.query('ROLLBACK');throw error;}finally{worker.release();}
 const rateLimited=(await db.query('SELECT state,failure_attempts,deadline>clock_timestamp()AS budget_open FROM webhook_deliveries WHERE workspace_id=$1 AND id=$2',[workspace,row.id])).rows[0];assert.deepEqual(rateLimited,{state:'dead_letter',failure_attempts:0,budget_open:true});await assert.rejects(()=>replay(2),/REPLAY_RATE_DEFERRED/);assert.equal((await db.query('SELECT state FROM webhook_deliveries WHERE workspace_id=$1 AND id=$2',[workspace,row.id])).rows[0].state,'dead_letter');
 await db.query("UPDATE webhook_deliveries SET state='terminal'WHERE workspace_id=$1",[workspace]);await db.query("UPDATE memberships SET role='Viewer'WHERE workspace_id=$1",[workspace]);await assert.rejects(()=>replay(2),/REPLAY_FORBIDDEN/);
 await assert.rejects(()=>tenant(workspace,user,(tx)=>tx.query("UPDATE webhook_deliveries SET state='pending'WHERE id=$1",[row.id])),/permission denied/);
 await db.query("UPDATE memberships SET role='Owner'WHERE workspace_id=$1",[workspace]);const expiredEndpoint=await tenant(workspace,user,(tx)=>persistWebhookEndpoint(tx,{workspace,user,role:'Owner'},{name:'Expired fixture',url:'https://example.org/expired',subscriptions:['contact.unsubscribed']},vault,new Date().toISOString()));await db.query("UPDATE webhook_endpoints SET status='enabled',version=version+1 WHERE workspace_id=$1 AND id=$2",[workspace,expiredEndpoint.endpoint.id]);
 const expired=(await db.query("INSERT INTO webhook_deliveries(workspace_id,endpoint_id,event_id,state,attempt_number,created_at,deadline)VALUES($1,$2,$3,'dead_letter',1,statement_timestamp()-interval '25 hours',statement_timestamp()-interval '1 hour')RETURNING id",[workspace,expiredEndpoint.endpoint.id,event.id])).rows[0].id;
 await assert.rejects(()=>tenant(workspace,user,(tx)=>tx.query('SELECT * FROM mailcraft_replay_webhook($1,$2,1,true)',[workspace,expired])),/REPLAY_BUDGET_EXPIRED/);

 }finally{for(const table of['webhook_attempts','webhook_deliveries','webhook_queue_state','webhook_signing_keys','webhook_endpoints','outbox','suppressions','contacts','audit_events','memberships'])await db.query(`DELETE FROM ${table} WHERE workspace_id=ANY($1::uuid[])`,[[workspace,other]]);await db.query('DELETE FROM workspaces WHERE id=ANY($1::uuid[])',[[workspace,other]]);await fixtureLock.query("SELECT pg_advisory_unlock(hashtextextended('lettercape.fixture.webhook-queue',0))");fixtureLock.release();await db.end();await closeDb();}
});
