import test from'node:test';import assert from'node:assert/strict';import{randomUUID,randomBytes}from'node:crypto';import{spawn,type ChildProcess}from'node:child_process';import{readFile}from'node:fs/promises';import{once}from'node:events';import pg from'pg';import env from'@next/env';import{signWebhook}from'../src/server/webhook-protocol';env.loadEnvConfig(process.cwd());
test('real receiver process restart after a committed lost acknowledgment preserves dedupe and aggregate ordering',async()=>{
 const db=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL}),schema='hook_restart_'+randomUUID().replaceAll('-',''),workspace=randomUUID(),consumer=randomUUID(),contact=randomUUID(),secret=randomBytes(32).toString('hex'),children:ChildProcess[]=[];
 async function start(hold_ack=false){const child=spawn(process.execPath,['--import','tsx','tests/fixtures/webhook-consumer-process.ts'],{cwd:process.cwd(),env:{LOCAL_DEVELOPMENT:'true',NODE_ENV:'test'},stdio:['pipe','pipe','pipe']});children.push(child);let output='',stderr='';const messages:{event:string;port?:number;pid?:number}[]=[];child.stdout!.on('data',(bytes)=>{output+=bytes.toString();for(;;){const split=output.indexOf('\n');if(split<0)break;messages.push(JSON.parse(output.slice(0,split)));output=output.slice(split+1);}});child.stderr!.on('data',(bytes)=>{stderr+=bytes.toString();});child.stdin!.end(JSON.stringify({connection_string:process.env.MIGRATION_DATABASE_URL,schema,workspace,consumer,secret,hold_ack})+'\n');
  async function wait(event:string){const deadline=Date.now()+10000;while(Date.now()<deadline){const message=messages.find((m)=>m.event===event);if(message)return message;if(child.exitCode!==null||child.signalCode!==null)throw new Error('Owned receiver stopped before '+event+': '+stderr);await new Promise((r)=>setTimeout(r,20));}throw new Error('Owned receiver readiness deadline');}
  const ready=await wait('ready');assert.ok(ready.port&&ready.pid);return{child,origin:'http://127.0.0.1:'+ready.port,pid:ready.pid,wait};
 }
 async function kill(child:ChildProcess){if(child.exitCode!==null||child.signalCode!==null)return;const exited=once(child,'exit');child.kill('SIGKILL');let timer:ReturnType<typeof setTimeout>|undefined;try{await Promise.race([exited,new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error('Owned receiver exit deadline')),5000);})]);}finally{if(timer)clearTimeout(timer);}}
 const event=(version:number)=>Buffer.from(JSON.stringify({id:randomUUID(),workspace_id:workspace,schema_version:1,type:'contact.unsubscribed',occurred_at:new Date().toISOString(),recorded_at:new Date().toISOString(),trace_id:randomUUID(),aggregate:{type:'contact',id:contact,version},data:{contact_id:contact,scope:'marketing',reason:'recipient_opt_out'}}));
 let signatureTime=Math.floor(Date.now()/1000);const signatures:string[]=[];async function submit(origin:string,body:Buffer){const signing=signWebhook(body,secret,signatureTime++);signatures.push(signing['X-Lettercape-Signature']);return fetch(origin,{method:'POST',body:Uint8Array.from(body),headers:{...signing,'X-Lettercape-Key-Version':'1'},signal:AbortSignal.timeout(10000)});}
 try{await db.query('CREATE SCHEMA '+schema);const tx=await db.connect();try{await tx.query('SET search_path TO '+schema+',pg_catalog');await tx.query(await readFile('examples/webhook-consumer/schema.sql','utf8'));}finally{await tx.query('RESET search_path');tx.release();}
  const body=event(3),first=await start(true),uncertain=submit(first.origin,body).then(()=>false,()=>true);await first.wait('committed');assert.equal((await db.query('SELECT count(*)::int AS n FROM '+schema+'.webhook_consumer_receipts')).rows[0].n,1);await kill(first.child);assert.equal(await uncertain,true);
  const second=await start();assert.notEqual(second.pid,first.pid);const repeated=await submit(second.origin,body);assert.equal(repeated.status,204);assert.notEqual(signatures[0],signatures[1]);assert.equal(repeated.headers.get('x-fixture-duplicate'),'true');assert.equal((await db.query('SELECT count(*)::int AS n FROM '+schema+'.webhook_consumer_receipts')).rows[0].n,1);assert.equal((await db.query('SELECT count(*)::int AS n FROM '+schema+'.webhook_resource_observations')).rows[0].n,1);
  assert.equal((await submit(second.origin,event(2))).status,204);assert.equal((await db.query('SELECT resource_version FROM '+schema+'.webhook_resource_observations')).rows[0].resource_version,3);
  const changed=JSON.parse(body.toString());changed.trace_id=randomUUID();assert.equal((await submit(second.origin,Buffer.from(JSON.stringify(changed)))).status,400);assert.equal((await db.query('SELECT count(*)::int AS n FROM '+schema+'.webhook_consumer_receipts')).rows[0].n,2);
 }finally{for(const child of children)await kill(child);await db.query('DROP SCHEMA IF EXISTS '+schema+' CASCADE');await db.end();}
});
