'use client';
import{useCallback,useEffect,useRef,useState}from'react';import type{SourceRecord,MemoryContext,MemoryChunk}from'@/domain/brand-memory';import{api}from'./api';import{memoryCommand,finishMemoryCommand}from'./brand-memory-command';
type Page={data:SourceRecord[];has_more:boolean;next_cursor:string|null;total_count:number};
export function BrandMemoryPanel({workspace,brand,version}:{workspace:string;brand:string;version:number}){return<ScopedMemory key={workspace+':'+brand}workspace={workspace}brand={brand}version={version}/>;}
function ScopedMemory({workspace,brand,version}:{workspace:string;brand:string;version:number}){
 const[page,setPage]=useState<Page|null>(null),[title,setTitle]=useState(''),[reference,setReference]=useState(''),[text,setText]=useState(''),[ack,setAck]=useState(false),[query,setQuery]=useState(''),[context,setContext]=useState<MemoryContext|null>(null),[chunks,setChunks]=useState<MemoryChunk[]|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const epoch=useRef(0),alive=useRef(true),running=useRef(false),snapshot=useRef<Page|null>(null),edit=useRef(0);
 const list=useCallback(async(older=false)=>{if(running.current||!alive.current)return;const before=snapshot.current;if(older&&!before?.next_cursor)return;running.current=true;setBusy(true);setError('');const stamp=++epoch.current;try{const result=await api<Page>(workspace,'brand-sources?brand_kit_version_id='+brand+(older?'&after='+encodeURIComponent(before!.next_cursor!):''));if(epoch.current!==stamp)return;const next=older?{...result,data:[...before!.data,...result.data]}:result;snapshot.current=next;setPage(next);}catch(cause){if(epoch.current===stamp)setError(cause instanceof Error?cause.message:'Sources unavailable.');}finally{if(epoch.current===stamp){running.current=false;setBusy(false);}}},[workspace,brand]);
 useEffect(()=>{alive.current=true;void Promise.resolve().then(()=>list());const life=alive,fence=epoch;return()=>{life.current=false;fence.current++;};},[list]);
 async function command(path:string,input:unknown,adding=false){if(running.current||!alive.current)return;running.current=true;setBusy(true);setError('');setNotice('');const stamp=++epoch.current,edited=edit.current;try{const receipt=await memoryCommand(workspace,path,input),result=await api<{source:SourceRecord}>(workspace,path,'POST',input,undefined,receipt.key);finishMemoryCommand(receipt);if(epoch.current!==stamp)return;setNotice(result.source.deleted_at?'Source removed from new retrieval. Historical references remain.':'Source saved for brand v'+version+'.');setContext(null);setChunks(null);if(adding&&edit.current===edited){setText('');setTitle('');setReference('');setAck(false);}const before=snapshot.current;if(before){const exists=before.data.some((s)=>s.id===result.source.id),next={...before,data:exists?before.data.map((s)=>s.id===result.source.id?result.source:s):[result.source,...before.data],total_count:before.total_count+(exists?0:1)};snapshot.current=next;setPage(next);}}catch(cause){if(epoch.current===stamp)setError(cause instanceof Error?cause.message:'Source command outcome is unknown. Retry unchanged input to recover.');}finally{if(epoch.current===stamp){running.current=false;setBusy(false);}}}
 async function inspect(path:string,preview=false){if(running.current||!alive.current)return;running.current=true;setBusy(true);setError('');const stamp=++epoch.current;try{if(preview){const result=await api<{context:MemoryContext}>(workspace,path,'POST',{query});if(epoch.current===stamp){setContext(result.context);setChunks(null);}}else{const result=await api<{chunks:MemoryChunk[]}>(workspace,path);if(epoch.current===stamp){setChunks(result.chunks);setContext(null);}}}catch(cause){if(epoch.current===stamp)setError(cause instanceof Error?cause.message:'Source inspection failed.');}finally{if(epoch.current===stamp){running.current=false;setBusy(false);}}}
 const changed=()=>{edit.current++;};return<section className="panel brand-memory-panel"><h2>Brand Memory</h2><p className="muted">Sources for confirmed brand v{version}. New generation retrieves active chunks from this version. Existing emails keep their pinned kit.</p><p className="small muted">Text ranking · no embeddings configured. Source removal excludes new retrieval; historical context and privacy erasure have separate lifecycles.</p>{error&&<p role="alert"className="alert danger">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <form onSubmit={(event)=>{event.preventDefault();void command('brand-sources',{brand_kit_version_id:brand,title,source_ref:reference,text,acknowledge_rights_and_no_private_data:ack},true);}}><label>Source title<input value={title}maxLength={160}required onChange={(e)=>{changed();setTitle(e.target.value);}}/></label><label>Source reference<input value={reference}maxLength={2048}required placeholder="Owned product brief or public page reference"onChange={(e)=>{changed();setReference(e.target.value);}}/></label><label htmlFor={brand+'-source-text'}>Approved source text</label><textarea id={brand+'-source-text'} value={text}required rows={5}onChange={(e)=>{changed();setText(e.target.value);}}/><label className="checkbox-label"><input type="checkbox"checked={ack}onChange={(e)=>{changed();setAck(e.target.checked);}}/>I have rights to use this source as AI context. It contains no contacts, secrets or private personal data.</label><button disabled={busy||!ack}>Add approved source</button></form>
 <div className="toolbar"><span>{page?.total_count??0} sources</span><button disabled={busy}onClick={()=>void list()}>Reload brand sources</button></div>{page?.total_count===0&&<p>No source added to this brand version.</p>}{page?.data.map((source)=><article className="event-receipt"key={source.id}style={{overflowWrap:'anywhere'}}><h3>{source.title}</h3><p>{source.deleted_at?'Removed from new retrieval':'Active approved context'} · {source.chunk_count} chunks</p><p className="small muted">{source.source_ref}<br/>Source {source.id}<br/>Digest {source.content_digest}</p><button disabled={busy}onClick={()=>void inspect('brand-sources/'+source.id)}>Inspect source {source.title}</button><button disabled={busy}onClick={()=>void command('brand-sources/'+source.id+'/remove',{})}>{source.deleted_at?'Confirm removal of ':'Remove source '}{source.title}</button></article>)}{page?.has_more&&<button disabled={busy}onClick={()=>void list(true)}>Load older brand sources</button>}
 <form onSubmit={(event)=>{event.preventDefault();void inspect('brands/'+brand+'/memory-preview',true);}}><label htmlFor={brand+'-retrieval-brief'}>Retrieval brief</label><textarea id={brand+'-retrieval-brief'} value={query}maxLength={8000}rows={2}onChange={(e)=>setQuery(e.target.value)}/><button disabled={busy}>Inspect retrieval context</button></form>{context&&<div role="status"><p>{context.chunks.length} selected chunks · {context.retrieval_version} · {context.retrieved_at}</p>{context.chunks.map((chunk)=><article key={chunk.id}><strong>{chunk.source_title}</strong><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{chunk.content}</p><p className="small muted">Source {chunk.source_id} · chunk {chunk.id}</p></article>)}</div>}{chunks&&<div>{chunks.length===0?<p>No active chunks: source was removed.</p>:chunks.map((chunk)=><p key={chunk.id}style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{chunk.content}</p>)}</div>}
 </section>;
}
