'use client';
import{useEffect,useRef,useState}from'react';import{api}from'./api';import{useResourcePage}from'./paged';import type{CreationSummaryData}from'../domain/creation-history';import type{z}from'zod';import type{CreationAttempt}from'../domain/creation-history';
export function CreationHistory({workspace,type,refreshToken='',onProposal,proposalDisabled=false}:{workspace:string;type:'brand.extract'|'email.generate';refreshToken?:string;proposalDisabled?:boolean;onProposal:(result:unknown)=>void}){
 const page=useResourcePage<CreationSummaryData>(workspace,'operations?type='+type,refreshToken),[detail,setDetail]=useState<(CreationSummaryData&{result:unknown})|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),guard=useRef(false),epoch=useRef(0);
 const history=useResourcePage<z.infer<typeof CreationAttempt>>(detail?workspace:'',detail?'operations/'+detail.id+'/attempts':'operations');
 useEffect(()=>{const fence=epoch;return()=>{fence.current++;};},[workspace]);
 async function inspect(id:string){if(guard.current)return;guard.current=true;setBusy(true);setError('');const current=epoch.current;try{const r=await api<{operation:CreationSummaryData&{result:unknown}}>(workspace,'operations/'+id);if(current===epoch.current)setDetail(r.operation);}catch(e){if(current===epoch.current)setError((e as Error).message);}finally{if(current===epoch.current){guard.current=false;setBusy(false);}}}
 return <section className="panel creation-history" aria-label="Recent creation operations"><div className="section-heading"><h2>Recent {type==='email.generate'?'generations':'extractions'}</h2><button disabled={page.busy} onClick={()=>void page.reload()}>Reload creation history</button></div><p className="small muted">Refreshing or inspecting keeps the original operation. It does not start another request. Queued work waits for an available worker.</p>{(page.error||error||history.error)&&<p className="alert danger" role="alert">{page.error||error||history.error}</p>}{page.loaded&&!page.data.length&&<p>No creation operations yet.</p>}{page.data.map(item=><article key={item.id}><p className="small break-word">{item.id}</p><p>{item.state.replaceAll('_',' ')} · {item.creation?.accounting??'none'}</p>{item.error&&<p className="alert warning">{item.error.message}</p>}<button disabled={busy} onClick={()=>void inspect(item.id)}>Inspect operation {item.id}</button></article>)}{page.hasMore&&<button disabled={page.busy} onClick={()=>void page.loadMore()}>Load older creation operations</button>}{detail&&<div className="creation-detail" role="status"><h3>Operation receipt</h3><p className="small break-word">{detail.id}</p><p>State: {detail.state.replaceAll('_',' ')}</p><p>Accounting: {detail.creation?.accounting??'none'}</p>{detail.creation&&<p className="small">Retry failures {detail.creation.failure_attempts} of {detail.creation.attempt_limit} · policy {detail.creation.policy_version}</p>}{detail.error?.code==='AI_RECONCILIATION_REQUIRED'&&<p className="alert warning">Provider accounting is unresolved. The reservation remains held. No automatic retry was issued. Your brief is preserved.</p>}{detail.error&&<p>{detail.error.message}</p>}{detail.state==='succeeded'&&Boolean(detail.result)&&<button disabled={proposalDisabled} onClick={()=>{if(proposalDisabled)return;try{onProposal(detail.result);setError('');}catch(e){setError((e as Error).message);}}}>Review completed proposal</button>}<h4>Recorded attempts</h4>{history.loaded&&!history.data.length&&<p>No external start is recorded.</p>}{history.data.map(attempt=><p className="small"key={attempt.id}>Attempt {attempt.lease_epoch} · {attempt.phase} · {attempt.outcome_code??'recorded'} · {new Date(attempt.recorded_at).toLocaleString()}</p>)}{history.hasMore&&<button disabled={history.busy}onClick={()=>void history.loadMore()}>Load older creation attempts</button>}</div>}</section>;
}
