'use client';
import{useLayoutEffect,useMemo,useRef,useState}from'react';import{api,ApiError}from'./api';import{checkedVoiceBrandPage,liveVoiceReport,type VoiceBrand}from'@/domain/live-voice-guard';import{canonicalSpecString}from'@/domain/email-source-values';import type{EmailSpec}from'@/domain/email-schema';
type Scope={workspace:string;actor:string;email:string};type State={binding:string;kit:VoiceBrand|null;cursor:string|null;scanned:number;exhausted:boolean};
export function LiveVoiceGuard({scope,spec}:{scope:Scope;spec:EmailSpec}){
 const binding=JSON.stringify([scope.workspace,scope.actor,scope.email,spec.brand_kit_version_id.toLowerCase()]),[open,setOpen]=useState(false),[state,setState]=useState<State|null>(null),[pending,setPending]=useState(''),[error,setError]=useState<{binding:string;message:string}|null>(null),[page,setPage]=useState({identity:'',index:0});
 const mounted=useRef(false),opened=useRef(false),epoch=useRef(0),current=useRef(binding),running=useRef<AbortController|null>(null),cursors=useRef(new Set<string>());
 useLayoutEffect(()=>{const fence=epoch;mounted.current=true;return()=>{mounted.current=false;opened.current=false;fence.current++;running.current?.abort();};},[]);
 useLayoutEffect(()=>{current.current=binding;const generation=++epoch.current;running.current?.abort();running.current=null;cursors.current.clear();queueMicrotask(()=>{if(mounted.current&&generation===epoch.current&&!running.current)setPending('');});},[binding]);
 const active=state?.binding===binding?state:null,kit=active?.kit??null,busy=pending===binding;
 const evaluation=useMemo(()=>{if(!open||!kit)return{report:null,error:''};try{return{report:liveVoiceReport(spec,kit.data),error:''};}catch{return{report:null,error:'This draft could not be checked. Your source and recovery are preserved; use the separate frozen preflight.'};}},[open,kit,spec]);
 const identity=useMemo(()=>canonicalSpecString([binding,spec,kit?[kit.id,kit.version,kit.data]:[]]),[binding,spec,kit]),report=evaluation.report,pages=Math.max(1,Math.ceil((report?.findings.length??0)/20)),position=Math.min(page.identity===identity?page.index:0,pages-1),shown=report?.findings.slice(position*20,(position+1)*20)??[];
 const load=async(reset:boolean)=>{
  if(running.current||!mounted.current||!opened.current)return;const controller=new AbortController(),generation=++epoch.current,anchor=binding,after=reset?null:active?.cursor;if(!reset&&!after)return;
  running.current=controller;setPending(anchor);setError(null);if(reset){cursors.current.clear();setState(null);}const matches=()=>mounted.current&&opened.current&&!controller.signal.aborted&&generation===epoch.current&&current.current===anchor;
  try{const received=await api(scope.workspace,'brands?limit=100'+(after?'&after='+encodeURIComponent(after):''),'GET',undefined,undefined,undefined,controller.signal,scope.actor);if(!matches())return;const next=checkedVoiceBrandPage(received,scope.workspace);if(next.next_cursor&&(next.next_cursor===after||cursors.current.has(next.next_cursor)))throw Error('Repeated brand cursor.');if(next.next_cursor)cursors.current.add(next.next_cursor);const exact=next.data.find(b=>b.id.toLowerCase()===spec.brand_kit_version_id.toLowerCase())??null;setState({binding:anchor,kit:exact,cursor:next.next_cursor,scanned:(reset?0:active?.scanned??0)+next.data.length,exhausted:!next.has_more});}
  catch(caught){if(matches())setError({binding:anchor,message:caught instanceof ApiError?caught.message:'Pinned rules could not be verified. Your draft and recovery are preserved. Refresh or retry the older page.'});}
  finally{if(matches()){running.current=null;setPending('');}}
 };
 const close=()=>{opened.current=false;epoch.current++;running.current?.abort();running.current=null;setPending('');setOpen(false);setState(null);setError(null);};
 return <><button type="button" onClick={()=>{opened.current=true;setOpen(true);void load(true);}} hidden={open}>Show live Voice Guard</button>{open&&<section className="revision-comparison" aria-label="Live mechanical Voice Guard">
  <div className="field-row"><button type="button" onClick={close}>Hide live Voice Guard</button><button type="button" disabled={busy} onClick={()=>void load(true)}>Refresh pinned rules</button>{!kit&&active?.cursor&&<button type="button" disabled={busy} onClick={()=>void load(false)}>Search older brand versions</button>}</div>
  <h2>Live mechanical Voice Guard</h2><p>Feedback on your current unsaved copy. Nothing is saved, rewritten or approved. No AI evaluation or send approval. Review and check remains the separate frozen preflight.</p>
  <p>Pinned kit ID <code className="break-word">{spec.brand_kit_version_id}</code></p>{busy&&<p role="status">Reading pinned brand rules… Feedback is unavailable until this read is verified.</p>}{error?.binding===binding&&<p role="alert" className="alert danger">{error.message}</p>}{evaluation.error&&<p role="alert">{evaluation.error}</p>}
  {!busy&&!kit&&<p role="status">{active?.exhausted?'Pinned kit unavailable in this workspace. No feedback evaluated.':active?'Pinned kit not found in '+active.scanned+' versions. Search older brand versions to continue.':'Pinned rules are not loaded. Refresh to check the current draft.'}</p>}
  {kit&&report&&<><strong>Pinned kit · v{kit.version}</strong><p>{kit.data.name} · Rules {report.rules_version}. {report.checked_fields} supported fields checked against this kit.</p>{!report.configured_rules&&<p>No brand phrase or numeric limits are configured.</p>}
   <p role="status">{report.findings.length?report.findings.length+' located mechanical findings. Edit the named field and feedback updates automatically.':'No supported mechanical issues found.'}</p><p className="small">Literal phrase matching and configured per-field word/exclamation limits only. Language-sensitive tone, factual claims, links, accessibility, delivery and real-client appearance need their separate checks.</p>
   {!!report.coverage.length&&<details open><summary>HTML and source coverage</summary><ul>{report.coverage.map(note=><li className="break-word" key={note.key}>{note.message}</li>)}</ul></details>}
   {pages>1&&<div className="field-row"><button type="button" disabled={!position} onClick={()=>setPage({identity,index:position-1})}>Previous voice findings</button><span>Page {position+1} of {pages}</span><button type="button" disabled={position===pages-1} onClick={()=>setPage({identity,index:position+1})}>Next voice findings</button></div>}
   {!!shown.length&&<ol className="revision-change-list" start={position*20+1}>{shown.map(f=><li className="break-word" key={f.key} data-live-voice-location={f.location} data-live-voice-code={f.code}><h3>{f.field_label}</h3><span className="badge neutral">{f.code==='VOICE_FORBIDDEN'?'Exact phrase':'Style warning'}</span><p>{f.message}</p><pre lang={spec.locale} dir={spec.direction}>{f.excerpt}</pre><p className="small">Excerpt: first 200 Unicode characters of this field. Edit the named authoring field; feedback does not rewrite it.</p></li>)}</ol>}
  </>}
 </section>}</>;
}
