'use client';
import{useMemo,useState}from'react';import{liveHygieneReport}from'@/domain/live-authoring-hygiene';import type{EmailSpec}from'@/domain/email-schema';
type Scope={workspace:string;actor:string;email:string};
export function LiveAuthoringHygiene({scope,spec}:{scope:Scope;spec:EmailSpec}){
 const[open,setOpen]=useState(false),[page,setPage]=useState({identity:'',index:0});
 const evaluation=useMemo(()=>{if(!open)return{report:null,identity:'',error:''};try{const report=liveHygieneReport(spec);return{report,identity:JSON.stringify([scope.workspace,scope.actor,scope.email,spec.brand_kit_version_id,spec.locale,spec.direction,report]),error:''};}catch{return{report:null,identity:'',error:'Basic copy feedback is unavailable. Your editable draft is retained; use the authoring fields and the separate Review and check.'};}},[open,spec,scope.workspace,scope.actor,scope.email]);
 const{report,identity}=evaluation,pages=Math.max(1,Math.ceil((report?.findings.length??0)/20)),position=Math.min(page.identity===identity?page.index:0,pages-1),shown=report?.findings.slice(position*20,(position+1)*20)??[];
 return <><button type="button" hidden={open} onClick={()=>setOpen(true)}>Show live authoring checks</button>{open&&<section className="revision-comparison" aria-label="Live authoring hygiene">
  <button type="button" onClick={()=>{setOpen(false);setPage({identity:'',index:0});}}>Hide live authoring checks</button><h2>Live authoring hygiene</h2><p>Basic feedback on current unsaved subject, preheader and supported image alt. Nothing is saved, rewritten or approved. No AI evaluation, accessibility certification or send approval. Review and check remains the separate frozen preflight.</p>
  {evaluation.error&&<p role="alert">{evaluation.error}</p>}{report&&<><p>{report.checked_fields} supported fields checked · Rules {report.rules_version}.</p><p role="status">{report.findings.length?report.findings.length+' located basic copy findings. Edit the named field and feedback updates automatically.':'No supported basic copy issues found.'}</p><p className="small">Subject 70 and preheader 150 are proposed warning thresholds, not measured client truncation. Length follows existing preflight; some Unicode characters count twice. Alt checks only find empty text; they do not judge its meaning or whether an image is decorative.</p>
   {!!report.coverage.length&&<details open><summary>HTML and source coverage</summary><ul>{report.coverage.map(c=><li className="break-word" key={c.key}>{c.message}</li>)}</ul></details>}
   {pages>1&&<div className="field-row"><button type="button" disabled={!position} onClick={()=>setPage({identity,index:position-1})}>Previous hygiene findings</button><span>Page {position+1} of {pages}</span><button type="button" disabled={position===pages-1} onClick={()=>setPage({identity,index:position+1})}>Next hygiene findings</button></div>}
   {!!shown.length&&<ol className="revision-change-list" start={position*20+1}>{shown.map(f=><li className="break-word" key={f.key} data-hygiene-code={f.code} data-hygiene-location={f.location}><h3>{f.field_label}</h3><span className="badge neutral">{f.limit!==undefined?'Length advisory':f.severity==='blocking'?'Required copy':'Suggested copy'}</span><p>{f.message}</p>{f.excerpt.trim()?<pre lang={spec.locale} dir={spec.direction}>{f.excerpt}</pre>:<p className="small">Empty or whitespace-only text.</p>}<p className="small">Excerpt: first 200 Unicode characters. Edit the named authoring field; this feedback does not replace it.</p></li>)}</ol>}
  </>}
 </section>}</>;
}
