'use client';
import{useCallback,useEffect,useRef,useState}from'react';import type{WebhookDeliveryRecord as Delivery,WebhookAttemptRecord as Attempt}from'@/domain/webhook-history';import{api}from'./api';import{beginWebhookCommand,finishWebhookCommand,reconcileWebhookReplayRejection,pendingWebhookReplay,type WebhookCommandReceipt}from'./webhook-command';
type Page<T>={data:T[];has_more:boolean;next_cursor:string|null;total_count:number;configuration:{key_configured:boolean;delivery_enabled:false}};
export function WebhookDeliveryHistory(props:{workspace:string;role:string}){return<ScopedHistory key={props.workspace+':'+props.role}{...props}/>;}
function ScopedHistory({workspace,role}:{workspace:string;role:string}){
 const manager=['Owner','Admin'].includes(role),epoch=useRef(0),running=useRef(false),alive=useRef(true),snapshot=useRef<Page<Delivery>|null>(null);
 const[page,setPage]=useState<Page<Delivery>|null>(null),[attempts,setAttempts]=useState<Page<Attempt>|null>(null),[selected,setSelected]=useState(''),[pending,setPending]=useState<Record<string,WebhookCommandReceipt>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[ack,setAck]=useState(false),[readTime,setReadTime]=useState(0);
 const load=useCallback(async(older=false)=>{
  if(running.current||!manager||!alive.current)return;const before=snapshot.current;if(older&&!before?.next_cursor)return;running.current=true;setBusy(true);setError('');setMessage('');const generation=++epoch.current;
  try{const result=await api<Page<Delivery>>(workspace,'webhook-deliveries'+(older?'?after='+encodeURIComponent(before!.next_cursor!):''));const data=older?[...before!.data,...result.data.filter((row)=>!before!.data.some((old)=>old.id===row.id))]:result.data;const receipts:Record<string,WebhookCommandReceipt>={};for(const row of data){const receipt=await pendingWebhookReplay(workspace,row.id);if(receipt)receipts[row.id]=receipt;}if(epoch.current!==generation)return;const next={...result,data};snapshot.current=next;setPage(next);setReadTime(Date.now());setPending(receipts);setAttempts(null);setSelected('');}
  catch(cause){if(epoch.current===generation)setError(cause instanceof Error?cause.message:'Delivery history could not be loaded.');}finally{if(epoch.current===generation){running.current=false;setBusy(false);}}
 },[workspace,manager]);
 useEffect(()=>{alive.current=true;void Promise.resolve().then(()=>load());const life=alive,fence=epoch;return()=>{life.current=false;fence.current++;};},[load]);
 async function readAttempts(row:Delivery,older=false){if(running.current)return;const previous=attempts;if(older&&!previous?.next_cursor)return;running.current=true;setBusy(true);setError('');setMessage('');const generation=++epoch.current;
  try{const result=await api<Page<Attempt>>(workspace,'webhook-deliveries/'+row.id+'/attempts'+(older?'?after='+encodeURIComponent(previous!.next_cursor!):''));if(epoch.current!==generation)return;setSelected(row.id);setAttempts(older?{...result,data:[...previous!.data,...result.data]}:result);}catch(cause){if(epoch.current===generation)setError(cause instanceof Error?cause.message:'Attempt history could not be loaded.');}finally{if(epoch.current===generation){running.current=false;setBusy(false);}}
 }
 async function replay(row:Delivery){if(running.current||!ack)return;running.current=true;setBusy(true);setError('');setMessage('');const generation=++epoch.current;let receipt:WebhookCommandReceipt|undefined;
  try{const path='webhook-deliveries/'+row.id+'/replay';receipt=await beginWebhookCommand(workspace,path,{expected_attempt:row.attempt_number,acknowledge_duplicate_effect:true});const result=await api<{delivery:Delivery}>(workspace,path,'POST',receipt.input,undefined,receipt.key);finishWebhookCommand(receipt);if(epoch.current!==generation)return;setPending((old)=>{const next={...old};delete next[row.id];return next;});setMessage('Replay command acknowledged. Current receipt: '+result.delivery.state+'. Receiver acknowledgment requires an actual HTTP response.');setAck(false);const before=snapshot.current;if(before){const next={...before,data:before.data.map((item)=>item.id===row.id?result.delivery:item)};snapshot.current=next;setPage(next);}setAttempts(null);setSelected('');}
  catch(cause){
   try{if(receipt&&reconcileWebhookReplayRejection(receipt,cause)){if(epoch.current===generation){setPending((old)=>{const next={...old};delete next[row.id];return next;});setError('This replay had no effect because its attempt changed. Reload delivery history and review the current attempt before starting a new command.');}}else if(epoch.current===generation)setError(cause instanceof Error?cause.message:'Replay could not be acknowledged. Recover the same command after checking its state.');}
   catch(recoveryError){if(epoch.current===generation)setError(recoveryError instanceof Error?recoveryError.message:'Replay recovery requires reconciliation.');}
  }finally{if(epoch.current===generation){running.current=false;setBusy(false);}}
 }
 const time=(value:string)=>new Date(value).toLocaleString(undefined,{timeZone:'UTC'})+' UTC';
 return<section className="panel webhook-history-panel"><h2>Webhook delivery history</h2><p className="muted">Processing reservations and receiver responses, with immutable event IDs. A receiver acknowledgment does not establish email delivery.</p><p className="alert warning">Outbound worker is disabled. Replay retains the same event and original retry budget; expired or unresolved receipts require reconciliation.</p>
 {!manager?<p>Owner or Admin access is required.</p>:<>
 {error&&<p role="alert"className="alert danger">{error}</p>}{message&&<p role="status">{message}</p>}{!page&&!error&&<p role="status">Loading webhook delivery history…</p>}
 <div className="toolbar"><span>{page?.total_count??0} deliveries</span><button disabled={busy}onClick={()=>void load()}>Reload webhook delivery history</button></div>{page&&!page.total_count&&<p>No webhook delivery receipt yet.</p>}
 <label className="checkbox-label"><input type="checkbox"checked={ack}disabled={busy}onChange={(event)=>setAck(event.target.checked)}/>I reviewed the failure and receiver deduplication. A retry may repeat an external effect.</label>
 {page?.data.map((row)=><article className="event-receipt"key={row.id}style={{overflowWrap:'anywhere'}}><h3>{row.state==='acknowledged'?'Receiver acknowledged':row.state.replaceAll('_',' ')}</h3><p className="small muted">Delivery {row.id} · Event {row.event_id}<br/>Endpoint {row.endpoint_id}</p><p>Processing attempt {row.attempt_number} · failed attempts {row.failure_attempts} · policy {row.policy_version}</p><p className="small muted">Recorded {time(row.created_at)}<br/>Retry budget ends {time(row.deadline)}{row.state==='pending'&&<><br/>Next attempt {time(row.next_at)}</>}</p>{row.error_class&&<p>Error class: {row.error_class.replaceAll('_',' ')}</p>}
 <button disabled={busy}onClick={()=>void readAttempts(row)}>Read attempts for {row.id}</button>
 <button disabled={busy||!ack||!page.configuration.key_configured||(!pending[row.id]&&(!['terminal','dead_letter'].includes(row.state)||row.attempt_number<1||row.failure_attempts>=10||Date.parse(row.deadline)<=readTime))}onClick={()=>void replay(row)}>{pending[row.id]?'Recover pending replay for ':'Replay failed delivery '}{row.id}</button>
 {selected===row.id&&attempts&&<div>{!attempts.total_count&&<p>No processing attempt recorded.</p>}{attempts.data.map((item)=><p className="small"key={item.id}>Attempt {item.attempt_number}: {item.phase==='started'?'processing reservation':item.phase==='authorized'?'request authorized':item.phase==='recovered'?'expired lease recovered':item.status_code===null?'no HTTP response recorded':'HTTP '+item.status_code}{item.secret_version!==null?' · signing version '+item.secret_version:''}{item.error_class?' · '+item.error_class:''}<br/>{time(item.recorded_at)}</p>)}{attempts.has_more&&<button disabled={busy}onClick={()=>void readAttempts(row,true)}>Load older webhook attempts</button>}</div>}
 </article>)}{page?.has_more&&<button disabled={busy}onClick={()=>void load(true)}>Load older webhook deliveries</button>}
 </>}</section>;
}
