import assert from 'node:assert/strict';
import { randomBytes, randomUUID, createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import pg from 'pg';
import env from '@next/env';
import { chromium, type Page, type Route } from 'playwright';
import { digest } from '../src/server/audit';
import { blankSpec } from '../src/domain/email';
import { FileAssetStore } from '../src/server/asset-store';
env.loadEnvConfig(process.cwd());
const origin = process.env.APP_ORIGIN ?? 'http://127.0.0.1:3003', parsed = new URL(origin);
assert.equal(process.env.LOCAL_DEVELOPMENT, 'true', 'Owned local development fixture required.');
assert.ok(['127.0.0.1', 'localhost'].includes(parsed.hostname) && parsed.protocol === 'http:' && (['3002', '3003'].includes(parsed.port) || (process.env.CI === 'true' && parsed.port === '3000')), 'Only owned port 3002/3003 or CI 3000 is allowed.');
for (const name of ['DATABASE_URL', 'MIGRATION_DATABASE_URL']) { const url = new URL(process.env[name]!); assert.equal(url.hostname, '127.0.0.1'); assert.equal(url.port, '55439'); }
const redis = new URL(process.env.REDIS_URL!); assert.equal(redis.hostname, '127.0.0.1'); assert.equal(redis.port, '56379');
const workspace = randomUUID(), other = randomUUID(), user = 'assets-browser-' + randomUUID(), otherUser = 'assets-other-' + randomUUID(), cookie = randomBytes(32).toString('hex'), otherCookie = randomBytes(32).toString('hex'), brand = randomUUID(), otherBrand = randomUUID(), email = randomUUID(), otherEmail = randomUUID();
const db = new pg.Pool({ connectionString: process.env.MIGRATION_DATABASE_URL }), workspaces = [workspace, other], users = [user, otherUser], tokens = [digest(cookie), digest(otherCookie)];
let browser: Awaited<ReturnType<typeof chromium.launch>> | undefined, activePage: Page | undefined, externalRequests = 0;
const evidence: string[] = [];
function note(line: string) { evidence.push(line); console.log(line); }
async function abortLostResponse(route:Route){try{await route.abort('failed');}catch(error){if(!/Route is already handled/.test(String(error)))throw error;note('Accepted response-loss request was already aborted; preserving original command recovery.');}}
async function call(path: string, method = 'GET', body?: unknown, w = workspace, c = cookie) { const r = await fetch(origin + '/v1/' + path, { method, headers: { Origin: origin, 'Content-Type': 'application/json', 'X-Workspace-Id': w, Cookie: 'mailcraft_local_session=' + c, 'Idempotency-Key': randomUUID() }, body: body === undefined ? undefined : JSON.stringify(body) }); const j = await r.json(); return { r, j }; }
async function truth() { return (await db.query('SELECT doc_version,spec FROM emails WHERE workspace_id=$1 AND id=$2', [workspace, email])).rows[0]; }
async function openPicker(page: Page, id = email) { await page.goto(origin + '/app/emails/' + id); await page.getByRole('textbox', { name: 'Subject', exact: true }).waitFor(); await page.locator('.outline-select').filter({ hasText: 'image' }).first().click(); const open = page.getByRole('button', { name: 'Choose uploaded image', exact: true }); await open.waitFor({ timeout: 10000 }); await open.click(); const panel = page.getByRole('region', { name: 'Uploaded media', exact: true }); await panel.waitFor(); return panel; }
try {
  const journal='/tmp/lettercape-media-ui-fixture-'+workspace+'.json';await writeFile(journal,JSON.stringify({origin,workspaces,users,tokens,store_root:process.env.ASSET_STORE_ROOT},null,2),{mode:0o600});note('Exact fixture cleanup journal '+journal);
  await db.query("INSERT INTO workspaces(id,name)VALUES($1,'Owned media browser'),($2,'Owned media other')", workspaces);
  await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$3,'Owner'),($2,$3,'Owner'),($1,$4,'Owner'),($2,$4,'Owner')", [workspace, other, user, otherUser]);
  await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$3,clock_timestamp()+interval '1 hour'),($2,$4,clock_timestamp()+interval '1 hour')", [...tokens, ...users]);
  for (const [w, b, e] of [[workspace, brand, email], [other, otherBrand, otherEmail]]) { await db.query("INSERT INTO brands(workspace_id,id,version,data)VALUES($1,$2,1,'{}')", [w, b]); const spec = { ...blankSpec(b, 'Owned uploaded media'), sections: [{ id: 'media-one', type: 'image', src: 'https://example.invalid/prior.png', alt: 'Prior image' }, { id: 'media-two', type: 'image', src: 'https://example.invalid/second.png', alt: 'Second image' }] }; await db.query('INSERT INTO emails(workspace_id,id,title,spec,created_by)VALUES($1,$2,$3,$4,$5)', [w, e, 'Owned uploaded media', JSON.stringify(spec), user]); }
  browser = await chromium.launch({ headless: true }); const context = await browser.newContext({ viewport: { width: 390, height: 844 }, reducedMotion: 'reduce' }); await context.addCookies([{ name: 'mailcraft_local_session', value: cookie, url: origin, sameSite: 'Strict' }]); await context.addInitScript(w => localStorage.setItem('mailcraft.workspace', w), workspace); await context.route(url => url.origin !== origin && url.protocol !== 'blob:' && url.protocol !== 'data:', route => { externalRequests++; return route.abort('blockedbyclient'); }); const page = await context.newPage(); page.on('dialog', dialog => dialog.accept());
  activePage = page; const panel = await openPicker(page); await panel.getByRole('status').filter({ hasText: 'No uploaded media' }).waitFor(); assert.equal(await panel.locator('img').count(), 0); assert.equal(await panel.getByRole('button', { name: 'Upload to quarantine', exact: true }).isDisabled(), true); assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  if (process.argv.includes('--controls-red')) { note('Owned controls present: actual empty media library at 390px.'); }
  else {
    const fixturePath = resolve(process.env.MEDIA_BROWSER_FIXTURE ?? 'tests/fixtures/media/disposal-1.gif'), bytes = await readFile(fixturePath), sha = createHash('sha256').update(bytes).digest('hex'), name = fixturePath.split('/').at(-1)!;
    note('Actual source fixture ' + name + ' ' + bytes.length + ' bytes SHA256 ' + sha);
    const file = panel.getByLabel('PNG, JPEG or GIF file (20 MiB maximum)', { exact: true }), upload = panel.getByRole('button', { name: 'Upload to quarantine', exact: true }); await file.setInputFiles({ name, mimeType: 'image/gif', buffer: bytes }); await panel.getByLabel('Upload image description', { exact: true }).fill('Owned red and blue animation'); assert.equal(await upload.isDisabled(), true); await panel.getByRole('checkbox', { name: /I confirm I have the rights/ }).check();
    const commands: { body: string; key: string }[] = [];let uploadRouteError:unknown,completeUploadRoute!:()=>void;const uploadRouteDone=new Promise<void>(resolve=>{completeUploadRoute=resolve;});
    await page.route('**/v1/assets/uploads', async route => {try{if (route.request().method() !== 'POST') { await route.continue(); return; } commands.push({ body: route.request().postData()!, key: route.request().headers()['idempotency-key'] }); const accepted = await route.fetch(); assert.equal(accepted.status(), 202); await abortLostResponse(route);}catch(error){uploadRouteError=error;await abortLostResponse(route).catch(()=>{});}finally{completeUploadRoute();}});
    await upload.evaluate((button: HTMLButtonElement) => { button.click(); button.click(); }); await panel.getByRole('alert').waitFor();await uploadRouteDone;if(uploadRouteError)throw uploadRouteError;assert.equal(commands.length, 1, 'Repeated synchronous click must admit one intent.'); assert.equal((await db.query('SELECT count(*)::int AS n FROM asset_uploads WHERE workspace_id=$1', [workspace])).rows[0].n, 1); assert.equal((await truth()).spec.sections[0].src, 'https://example.invalid/prior.png');
    await page.unroute('**/v1/assets/uploads'); await context.addCookies([{ name: 'mailcraft_local_session', value: otherCookie, url: origin, sameSite: 'Strict' }]); await openPicker(page); assert.equal(await panel.getByRole('button', { name: 'Resume original upload', exact: true }).count(), 0); assert.equal(commands.length, 1, 'Changing actor must not replay a retained intent.'); await context.addCookies([{ name: 'mailcraft_local_session', value: cookie, url: origin, sameSite: 'Strict' }]); await openPicker(page); await panel.getByRole('button', { name: 'Resume original upload', exact: true }).waitFor(); assert.equal(await panel.getByRole('button', { name: 'Resume original upload', exact: true }).isDisabled(), true);
    await file.setInputFiles({ name: 'different.gif', mimeType: 'image/gif', buffer: Buffer.from([1, 2, 3]) }); await panel.getByRole('button', { name: 'Resume original upload', exact: true }).click(); await panel.getByRole('alert').filter({ hasText: 'same file content' }).waitFor(); assert.equal((await db.query('SELECT count(*)::int AS n FROM assets WHERE workspace_id=$1', [workspace])).rows[0].n, 0);
    await page.route('**/v1/assets/uploads', async route => { if (route.request().method() === 'POST') commands.push({ body: route.request().postData()!, key: route.request().headers()['idempotency-key'] }); await route.continue(); }); await file.setInputFiles({ name, mimeType: 'image/gif', buffer: bytes }); await panel.getByRole('button', { name: 'Resume original upload', exact: true }).focus(); await page.keyboard.press('Enter'); await panel.getByText('Recovered upload:', { exact: false }).filter({ hasText: 'processing' }).waitFor(); assert.deepEqual(commands[1], commands[0]); await page.unroute('**/v1/assets/uploads');
    const assetRow = (await db.query('SELECT * FROM assets WHERE workspace_id=$1', [workspace])).rows[0]; assert.equal(assetRow.source_sha256, sha); assert.equal(assetRow.source_bytes, bytes.length); assert.equal((await db.query('SELECT count(*)::int AS n FROM asset_uploads WHERE workspace_id=$1', [workspace])).rows[0].n, 1); assert.equal((await truth()).spec.sections[0].src, 'https://example.invalid/prior.png');
    note('Actual lost acknowledgment/reload/samehash/repeated-click upload recovery PASS; original body/key and one durable intent/asset, previous image preserved.');
    const library = panel.getByLabel('Private media library', { exact: true }); await library.selectOption(assetRow.id);
    if (process.argv.includes('--quarantine')) {
      assert.ok(['quarantined', 'processing'].includes((await call('assets/' + assetRow.id)).j.asset.state)); assert.equal(await panel.locator('img').count(), 0); assert.equal(await panel.getByRole('button', { name: 'Apply ready private variant', exact: true }).count(), 0); await page.screenshot({ path: '/tmp/lettercape-media-quarantine-mobile.png' }); note('Actual quarantine no-preview/no-apply refusal PASS. Scanner readiness is not claimed.');
      await panel.getByRole('button', { name: 'Cancel upload operation', exact: true }).click(); await panel.getByRole('status').filter({ hasText: 'Upload cancellation acknowledged.' }).waitFor(); const operation = (await db.query('SELECT state FROM operations WHERE workspace_id=$1 AND id=(SELECT operation_id FROM asset_uploads WHERE workspace_id=$1 LIMIT 1)', [workspace])).rows[0]; assert.ok(['cancelled', 'cancel_requested'].includes(operation.state)); assert.equal((await truth()).spec.sections[0].src, 'https://example.invalid/prior.png'); note('Actual upload cancellation preserves previous node image PASS.');
    } else {
      // No database readiness seeding or canned clean response: the real worker must settle this source.
      await page.waitForFunction(() => { const select = Array.from(document.querySelectorAll('select')).find(e => e.parentElement?.textContent?.startsWith('Private media library')); return Array.from(select?.options ?? []).some(o => o.textContent?.includes('ready_private')); }, {}, { timeout: 240000 }); await library.selectOption(''); await library.focus();
      // Native typeahead works for macOS Chromium's collapsed select; End/arrows do not commit its popup selection in headless mode.
      await page.keyboard.press('o'); await page.keyboard.press('Enter'); assert.equal(await library.inputValue(), assetRow.id); await panel.locator('img').waitFor(); await panel.getByText('Reduced motion: static fallback preview.', { exact: true }).waitFor(); assert.equal(await panel.getByRole('button', { name: 'Play private animation', exact: true }).isDisabled(), true);
      const measured = (await call('assets/' + assetRow.id)).j.asset; assert.equal(measured.state, 'ready_private'); assert.ok(measured.variants.every((v: { scan_evidence_ids: string[] }) => v.scan_evidence_ids.length >= 2));
      const actualImage = panel.locator('img'); await actualImage.evaluate((img: HTMLImageElement) => img.decode()); const pixel = await actualImage.evaluate((img: HTMLImageElement) => { const canvas = document.createElement('canvas'); canvas.width = img.naturalWidth; canvas.height = img.naturalHeight; const ctx = canvas.getContext('2d')!; ctx.drawImage(img, 0, 0); return Array.from(ctx.getImageData(0, 0, 1, 1).data); }); assert.deepEqual(pixel, [255, 0, 0, 255], 'Qualified first frame must display expected red pixel.'); await page.screenshot({ path: '/tmp/lettercape-media-ready-mobile.png' });
      await page.emulateMedia({ reducedMotion: 'no-preference' }); const play = panel.getByRole('button', { name: 'Play private animation', exact: true }); await play.waitFor(); await play.click(); await panel.getByRole('button', { name: 'Pause private animation', exact: true }).click(); await page.emulateMedia({ reducedMotion: 'reduce' });
      const fallbackFrame = panel.getByLabel('Static fallback frame', { exact: true }), createFallback = panel.getByRole('button', { name: 'Create immutable fallback', exact: true }); for (const invalid of ['-1', '1.5', '199']) { await fallbackFrame.fill(invalid); assert.equal(await createFallback.isDisabled(), true); } await fallbackFrame.fill('1');
      const fallbackCommands: { body: string; key: string; version: string }[] = [];let fallbackRouteError:unknown,completeFallbackRoute!:()=>void;const fallbackRouteDone=new Promise<void>(resolve=>{completeFallbackRoute=resolve;});
      await page.route('**/v1/assets/' + assetRow.id + '/fallback', async route => {try{fallbackCommands.push({ body: route.request().postData()!, key: route.request().headers()['idempotency-key'], version: route.request().headers()['if-match'] }); assert.equal((await route.fetch()).status(), 202); await abortLostResponse(route);}catch(error){fallbackRouteError=error;await abortLostResponse(route).catch(()=>{});}finally{completeFallbackRoute();}}); await createFallback.evaluate((button: HTMLButtonElement) => { button.click(); button.click(); }); await panel.getByRole('button', { name: 'Retry original fallback', exact: true }).waitFor();await fallbackRouteDone;if(fallbackRouteError)throw fallbackRouteError;assert.equal(fallbackCommands.length, 1); assert.equal((await truth()).spec.sections[0].src, 'https://example.invalid/prior.png');
      await page.unroute('**/v1/assets/' + assetRow.id + '/fallback'); await openPicker(page); await panel.getByRole('button', { name: 'Retry original fallback', exact: true }).waitFor(); await page.route('**/v1/assets/' + assetRow.id + '/fallback', async route => { fallbackCommands.push({ body: route.request().postData()!, key: route.request().headers()['idempotency-key'], version: route.request().headers()['if-match'] }); await route.continue(); }); await panel.getByRole('button', { name: 'Retry original fallback', exact: true }).click(); await panel.locator('p').filter({hasText:/^Fallback operation /}).waitFor(); assert.deepEqual(fallbackCommands[1], fallbackCommands[0]); assert.equal((await db.query("SELECT count(*)::int AS n FROM operations WHERE workspace_id=$1 AND type='asset.fallback'", [workspace])).rows[0].n, 1); await page.unroute('**/v1/assets/' + assetRow.id + '/fallback');
      await panel.getByRole('button', { name: 'Acknowledge fallback status', exact: true }).waitFor({ timeout: 240000 }); await library.selectOption(assetRow.id); const fallbackAsset = (await call('assets/' + assetRow.id)).j.asset, selectedFallback = fallbackAsset.variants.find((v: { role: string; selected_frame: number }) => v.role === 'fallback' && v.selected_frame === 1); assert.ok(selectedFallback, 'Actual worker must create frame1 immutable fallback.'); await panel.getByLabel('Immutable variant', { exact: true }).selectOption(selectedFallback.variant_id); await actualImage.waitFor(); await assertEventually(async () => { const selectedPixel = await actualImage.evaluate((img: HTMLImageElement) => { const canvas = document.createElement('canvas'); canvas.width = img.naturalWidth; canvas.height = img.naturalHeight; const ctx = canvas.getContext('2d')!; ctx.drawImage(img, 0, 0); return Array.from(ctx.getImageData(1, 0, 1, 1).data); }); assert.deepEqual(selectedPixel, [0, 0, 255, 255], 'Selected frame1 must retain independently expected blue topmiddle pixel.'); }); await page.screenshot({ path: '/tmp/lettercape-media-selected-fallback-mobile.png' }); assert.equal((await truth()).spec.sections[0].src, 'https://example.invalid/prior.png'); note('Actual fallback integer validation/repeated click/lost acknowledgment/reload same CAS+key+body/selected-frame pixel and no autoapply PASS.');
      const apply = panel.getByRole('button', { name: 'Apply ready private variant', exact: true }); await apply.focus(); await page.keyboard.press('Enter'); await page.waitForFunction(() => !document.querySelector('[aria-label="Uploaded media"]')?.textContent?.includes('Working…')); await assertEventually(async () => { const saved = await truth(); assert.equal(saved.spec.schema_version, '1.1'); assert.equal(saved.spec.sections[0].asset_ref.asset_id, assetRow.id); assert.equal(saved.spec.sections[1].src, 'https://example.invalid/second.png'); });
      note('Actual clean scan/decode/private verified fallback pixels/keyboard manual apply PASS; saved correct image schema1.1 and preserved other node.');
      const beforeViewer=await truth();
      await db.query("UPDATE memberships SET role='Viewer' WHERE workspace_id=$1 AND user_id=$2",[workspace,user]);
      try {
        await openPicker(page);await panel.getByLabel('Private media library',{exact:true}).selectOption(assetRow.id);await panel.locator('img').waitFor();await panel.locator('img').evaluate((img:HTMLImageElement)=>img.decode());
        assert.ok((await panel.locator('img').getAttribute('src'))?.startsWith('blob:'),'Viewer must receive verified private bytes, not an authenticated URL.');
        assert.equal(await panel.getByLabel('Immutable variant',{exact:true}).isEnabled(),true);await panel.getByLabel('Immutable variant',{exact:true}).selectOption(selectedFallback.variant_id);await panel.locator('img').waitFor();
        assert.equal(await panel.getByRole('button',{name:'Apply ready private variant',exact:true}).isDisabled(),true);assert.equal(await panel.getByRole('button',{name:'Upload to quarantine',exact:true}).isDisabled(),true);
        const animation=fallbackAsset.variants.find((v:{role:string})=>v.role==='animation');await panel.getByLabel('Immutable variant',{exact:true}).selectOption(animation.variant_id);await page.emulateMedia({reducedMotion:'no-preference'});await panel.getByRole('button',{name:'Play private animation',exact:true}).click();await panel.getByRole('button',{name:'Pause private animation',exact:true}).click();assert.equal(await panel.getByRole('button',{name:'Create immutable fallback',exact:true}).isDisabled(),true);
        assert.equal((await call('assets/uploads','POST',JSON.parse(commands[0].body))).r.status,403);assert.deepEqual(await truth(),beforeViewer);await page.screenshot({path:'/tmp/lettercape-media-viewer-mobile.png'});note('Actual Viewer metadata/verified derivative/variant/PlayPause read access and UI+server write refusal PASS; saved document unchanged.');
      } finally {await db.query("UPDATE memberships SET role='Owner' WHERE workspace_id=$1 AND user_id=$2",[workspace,user]);await page.emulateMedia({reducedMotion:'reduce'});}
    }
    const crossed = await call('assets/' + assetRow.id, 'GET', undefined, other, otherCookie); assert.equal(crossed.r.status, 404); assert.equal((await call('assets', 'GET', undefined, other, otherCookie)).j.data.length, 0);
    await openPicker(page); let releaseRead!: () => void, observedRead!: () => void, completeRead!: () => void; const held = new Promise<void>(resolve => { releaseRead = resolve; }), started = new Promise<void>(resolve => { observedRead = resolve; }), completed = new Promise<void>(resolve => { completeRead = resolve; }); await page.route('**/v1/assets', async route => { const actual = await route.fetch(); observedRead(); await held; try { await route.fulfill({ response: actual }); } catch (error) { assert.match(String(error), /already handled|Target.*closed|cancel/i); } finally { completeRead(); } }); await panel.getByRole('button', { name: 'Refresh media status', exact: true }).click(); await started; await page.locator('.outline-select').filter({ hasText: 'image' }).nth(1).click(); await page.getByLabel('Alternative text', { exact: true }).waitFor(); assert.equal(await page.getByLabel('Alternative text', { exact: true }).inputValue(), 'Second image'); releaseRead(); await completed; await page.unroute('**/v1/assets'); assert.equal(await page.getByLabel('Alternative text', { exact: true }).inputValue(), 'Second image'); assert.equal(await panel.getByRole('button', { name: 'Resume original upload', exact: true }).count(), 0); assert.equal((await truth()).spec.sections[1].src, 'https://example.invalid/second.png'); note('Actual delayed library response after node selection cannot replace the new node PASS.');
    await openPicker(page); await page.route('**/v1/assets', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { code: 'OWNED_LIBRARY_UNAVAILABLE', message: 'Owned library temporarily unavailable.' } }) })); await page.reload(); await page.locator('.outline-select').filter({ hasText: 'image' }).first().click(); await page.getByRole('button', { name: 'Choose uploaded image', exact: true }).click(); await panel.getByRole('alert').filter({ hasText: 'Owned library temporarily unavailable.' }).waitFor(); assert.equal(await panel.locator('img').count(), 0); await page.unroute('**/v1/assets');
    note('Actual cross-workspace asset denial and library availability error PASS.');
  }
  assert.equal(externalRequests, 0, 'Picker and editor must not request an external source.');
} catch (error) { note('ACTUAL_MEDIA_BROWSER_FAILURE ' + (error instanceof Error ? error.stack : String(error))); if (activePage && !activePage.isClosed()) await activePage.screenshot({ path: '/tmp/lettercape-media-browser-failure-' + Date.now() + '.png', fullPage: true }).catch(() => { }); throw error; } finally {
  await browser?.close(); const cleanup = await db.connect(); try {
    await cleanup.query('BEGIN'); await cleanup.query('SELECT id FROM emails WHERE workspace_id=ANY($1::uuid[]) FOR UPDATE', [workspaces]);
    const hasAssets=(await cleanup.query("SELECT to_regclass('assets') AS found")).rows[0].found,hasStaging=(await cleanup.query("SELECT to_regclass('asset_object_staging') AS found")).rows[0].found;
    const objects=hasAssets?(await cleanup.query('SELECT source_key AS key FROM assets WHERE workspace_id=ANY($1::uuid[]) UNION SELECT object_key AS key FROM asset_variants WHERE workspace_id=ANY($1::uuid[])'+(hasStaging?' UNION SELECT object_key AS key FROM asset_object_staging WHERE workspace_id=ANY($1::uuid[])':''),[workspaces])).rows:[];
    if(objects.length){const store=new FileAssetStore(process.env.ASSET_STORE_ROOT!);for(const o of objects){if(o.key)await store.removeAuthorized(o.key).catch(error=>{if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;});}}
    for (const table of ['asset_revision_references', 'asset_draft_references', 'asset_variants', 'asset_scans', 'media_jobs', 'asset_object_staging', 'asset_rights', 'asset_uploads', 'assets', 'asset_quotas', 'render_downloads', 'preflights', 'idempotency', 'audit_events', 'operations', 'revisions', 'emails', 'brands', 'memberships']) if ((await cleanup.query('SELECT to_regclass($1) AS found', [table])).rows[0].found) await cleanup.query('DELETE FROM ' + table + ' WHERE workspace_id=ANY($1::uuid[])', [workspaces]); await cleanup.query('DELETE FROM workspaces WHERE id=ANY($1::uuid[])', [workspaces]); await cleanup.query('DELETE FROM auth_sessions WHERE token_hash=ANY($1::text[]) AND user_id=ANY($2::text[])', [tokens, users]); await cleanup.query('COMMIT'); assert.equal((await db.query('SELECT count(*)::int AS n FROM workspaces WHERE id=ANY($1::uuid[])', [workspaces])).rows[0].n, 0); assert.equal((await db.query('SELECT count(*)::int AS n FROM auth_sessions WHERE token_hash=ANY($1::text[])', [tokens])).rows[0].n, 0); note('Exact owned two-workspace/session/object cleanup PASS.');
} catch (error) { await cleanup.query('ROLLBACK'); note('ACTUAL_MEDIA_BROWSER_CLEANUP_FAILURE ' + String(error)); throw error; } finally { cleanup.release(); await db.end(); await writeFile('/tmp/lettercape-media-ui-browser-evidence.log', evidence.join('\n') + '\n'); }
}
async function assertEventually(check: () => Promise<void>) { const until = Date.now() + 20000; let last: unknown; while (Date.now() < until) { try { await check(); return; } catch (e) { last = e; } await new Promise(resolve => setTimeout(resolve, 250)); } throw last; }
