import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import type pg from 'pg';
type Fixture={origin:string;workspace:string;other:string;cookie:string;revision:string;user:string;db:pg.Pool;call:(path:string,method?:string,body?:unknown,key?:string,w?:string)=>Promise<{r:Response;j:Record<string,any>}>}; // eslint-disable-line @typescript-eslint/no-explicit-any
export async function verifyCalendarBrowser({origin,workspace,other,cookie,revision,call,db,user}:Fixture){
 const browser=await chromium.launch({headless:true});try{
  const context=await browser.newContext({viewport:{width:390,height:844}});await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);await context.addInitScript(w=>{if(!localStorage.getItem('mailcraft.workspace'))localStorage.setItem('mailcraft.workspace',w);},workspace);const page=await context.newPage(),box=page.locator('[data-workspace-calendar]'),zone=box.getByLabel('Display IANA time zone',{exact:true}),month=box.getByLabel('Calendar month',{exact:true}),save=box.getByRole('button',{name:'Save display timezone',exact:true}),retry=box.getByRole('button',{name:'Retry original timezone',exact:true}),reload=box.getByRole('button',{name:'Reload saved timezone',exact:true}),summary=box.locator('[data-calendar-summary]'),more=box.getByRole('button',{name:'Load more planned campaigns',exact:true}),refresh=box.getByRole('button',{name:'Refresh calendar',exact:true});
  let release!:()=>void,entered!:()=>void;let gate=new Promise<void>(r=>release=r),ready=new Promise<void>(r=>entered=r);
  await page.route('**/v1/workspace-preferences',async route=>{const response=await route.fetch();entered();await gate;await route.fulfill({response});});
  try{await page.goto(origin+'/app/campaigns');await ready;await box.getByRole('heading',{name:'Planned campaign calendar',exact:true}).waitFor();assert.equal(await zone.isDisabled(),true);}finally{release();await page.unrouteAll({behavior:'wait'});}
  await page.waitForFunction(()=>document.querySelector<HTMLInputElement>('[data-workspace-calendar] input')?.value==='America/New_York');await month.fill('2026-11');await summary.filter({hasText:'Showing 2 of 2'}).waitFor();assert.match(await box.innerText(),/01:30 America\/New_York \(-05:00\)/);assert.match(await box.innerText(),/01:30 America\/New_York \(-04:00\)/);assert.equal(await box.locator('[data-calendar-date="2026-11-01"] .calendar-dot').count(),1);
  await box.getByRole('button',{name:'Previous month',exact:true}).click();await summary.filter({hasText:'2026-10'}).waitFor();assert.match(await box.innerText(),/Original plan: 2026-11-01T00:15 Asia\/Kathmandu/);await box.getByRole('button',{name:'Next month',exact:true}).click();await summary.filter({hasText:'2026-11'}).waitFor();await month.fill('2026-12');await box.locator('[data-calendar-empty]').waitFor();await month.fill('2026-11');await summary.filter({hasText:'Showing 2 of 2'}).waitFor();
  for(let n=0;n<6;n++){const made=await call('campaigns','POST',{name:'Page plan '+n,revision_id:revision});const result=await call('campaigns/'+made.j.campaign.id+'/configuration','POST',{expected_version:1,name:'Page plan '+n,revision_id:revision,planned_timing:{local_time:'2026-11-'+String(n+3).padStart(2,'0')+'T10:00',time_zone:'UTC',utc_offset:'+00:00'}});assert.equal(result.r.status,200);}
  await refresh.click();await summary.filter({hasText:'Showing 5 of 8'}).waitFor();let calendarGets=0;page.on('request',req=>{if(req.url().includes('/v1/campaigns/calendar'))calendarGets++;});let failedMore=true;await page.route('**/v1/campaigns/calendar?*',async route=>{if(route.request().url().includes('after=')&&failedMore){failedMore=false;await route.fulfill({status:503,json:{error:{code:'DEPENDENCY_UNAVAILABLE',message:'Owned calendar page unavailable'}}});}else await route.continue();});await more.click();await box.getByRole('alert').filter({hasText:'Owned calendar page unavailable'}).waitFor();assert.equal(await box.locator('[data-calendar-entry]').count(),5);await page.unrouteAll({behavior:'wait'});const before=calendarGets;await more.evaluate((button:HTMLButtonElement)=>{button.click();button.click();});await summary.filter({hasText:'Showing 8 of 8'}).waitFor();assert.equal(calendarGets,before+1);assert.equal(await box.locator('[data-calendar-entry]').count(),8);
  await page.route('**/v1/campaigns/calendar?*',route=>route.fulfill({status:503,json:{error:{code:'DEPENDENCY_UNAVAILABLE',message:'Owned initial calendar unavailable'}}}));await refresh.click();await box.getByRole('alert').filter({hasText:'Owned initial calendar unavailable'}).waitFor();assert.equal(await box.locator('[data-calendar-entry]').count(),0);await page.unrouteAll({behavior:'wait'});await refresh.click();await summary.filter({hasText:'Showing 5 of 8'}).waitFor();
  await zone.fill('Europe/London');assert.equal((await call('workspace-preferences/timezone','POST',{expected_version:3,time_zone:'UTC'})).r.status,200);await more.click();await box.getByRole('alert').filter({hasText:'This cursor is invalid'}).waitFor();assert.match(await summary.innerText(),/America\/New_York/);assert.equal(await zone.inputValue(),'Europe/London');await refresh.click();await summary.filter({hasText:'UTC'}).waitFor();assert.equal(await zone.inputValue(),'Europe/London');assert.equal(await save.isDisabled(),true);await reload.click();await page.waitForFunction(()=>document.querySelector<HTMLInputElement>('[data-workspace-calendar] input')?.value==='UTC');
  // Calendar selection must work independently of the first25 campaign cards.
  const olderId=(await call('campaigns/calendar?month=2026-11')).j.data.find((row:{name:string})=>row.name==='First fold').id;for(let n=0;n<26;n++)assert.equal((await call('campaigns','POST',{name:'Newer unplanned '+n,revision_id:revision})).r.status,200);await page.reload();await page.waitForFunction(()=>document.querySelector<HTMLInputElement>('[data-workspace-calendar] input')?.value==='UTC');await month.fill('2026-11');await summary.filter({hasText:'Showing 5 of 8'}).waitFor();await more.click();await summary.filter({hasText:'Showing 8 of 8'}).waitFor();assert.equal(await page.locator('#campaign-'+olderId).count(),0);await box.getByRole('button',{name:'Open plan for First fold',exact:true}).click({timeout:4000});const selected=box.getByRole('region',{name:'Selected planned campaign',exact:true});await selected.getByRole('heading',{name:'First fold',exact:true}).waitFor();await page.waitForFunction(id=>document.querySelector<HTMLInputElement>('[data-workspace-calendar] [data-campaign-configuration="'+id+'"] input')?.value==='First fold',olderId);assert.equal(await selected.getByLabel('Configuration frozen revision',{exact:true}).inputValue(),revision);await selected.getByRole('button',{name:'Close selected plan',exact:true}).click();assert.equal(await selected.count(),0);
  let posts=0;const keys:string[]=[];page.on('request',req=>{if(new URL(req.url()).pathname==='/v1/workspace-preferences/timezone'&&req.method()==='POST'){posts++;keys.push(req.headers()['idempotency-key']);}});
  await zone.fill('Asia/Kathmandu');await context.setOffline(true);await save.click();await box.getByRole('alert').filter({hasText:/Failed to fetch|fetch failed/i}).waitFor();assert.equal(await zone.inputValue(),'Asia/Kathmandu');assert.equal(await zone.isDisabled(),true);await context.setOffline(false);await retry.click();await box.getByRole('status').filter({hasText:'Display timezone saved.'}).waitFor();assert.equal((await call('workspace-preferences')).j.preferences.version,5);await summary.filter({hasText:'Asia/Kathmandu'}).waitFor();
  async function loseAcknowledgment(target:string,expected:number){await zone.fill(target);await page.route('**/v1/workspace-preferences/timezone',async route=>{const response=await route.fetch();assert.equal(response.status(),200);await route.abort('failed');});const before=posts;await save.evaluate((button:HTMLButtonElement)=>{button.click();button.click();});await box.getByRole('alert').waitFor();assert.equal(posts,before+1);assert.equal(await zone.isDisabled(),true);assert.equal((await call('workspace-preferences')).j.preferences.version,expected);await page.unrouteAll({behavior:'wait'});await retry.click();await box.getByRole('status').filter({hasText:'Display timezone saved.'}).waitFor();assert.equal(keys.at(-1),keys.at(-2));assert.equal((await call('workspace-preferences')).j.preferences.version,expected);}
  await loseAcknowledgment('America/New_York',6);
  await zone.fill('UTC');await page.route('**/v1/workspace-preferences',route=>route.fulfill({status:503,json:{error:{code:'DEPENDENCY_UNAVAILABLE',message:'Owned current timezone unavailable'}}}));await save.click();await box.getByRole('alert').filter({hasText:'Owned current timezone unavailable'}).waitFor();assert.equal(await zone.isDisabled(),true);assert.equal((await call('workspace-preferences')).j.preferences.version,7);await page.unrouteAll({behavior:'wait'});await retry.click();await box.getByRole('status').filter({hasText:'Display timezone saved.'}).waitFor();assert.equal(keys.at(-1),keys.at(-2));
  await page.evaluate("Object.defineProperty(Storage.prototype,'getItem',{configurable:true,value:function(key){if(this===sessionStorage)throw new Error('Owned storage unavailable');return key==='mailcraft.workspace'?localStorage['mailcraft.workspace']:null;}});Object.defineProperty(Storage.prototype,'setItem',{configurable:true,value:function(){throw new Error('Owned storage unavailable');}});");await loseAcknowledgment('Europe/London',8);
  const second=await context.newPage();await second.goto(origin+'/app/campaigns');const secondBox=second.locator('[data-workspace-calendar]'),secondZone=secondBox.getByLabel('Display IANA time zone',{exact:true});await second.waitForFunction(()=>document.querySelector<HTMLInputElement>('[data-workspace-calendar] input')?.value==='Europe/London');await secondZone.fill('America/New_York');assert.equal((await call('workspace-preferences/timezone','POST',{expected_version:8,time_zone:'UTC'})).r.status,200);await secondBox.getByRole('button',{name:'Save display timezone',exact:true}).click();await secondBox.getByRole('alert').filter({hasText:'The saved timezone changed.'}).waitFor();assert.equal(await secondZone.inputValue(),'America/New_York');await secondBox.getByRole('button',{name:'Reload saved timezone',exact:true}).click();await second.waitForFunction(()=>document.querySelector<HTMLInputElement>('[data-workspace-calendar] input')?.value==='UTC');await second.close();
  const errorPage=await context.newPage();await errorPage.route('**/v1/workspace-preferences',route=>route.fulfill({status:503,json:{error:{code:'DEPENDENCY_UNAVAILABLE',message:'Owned saved timezone unavailable'}}}));await errorPage.goto(origin+'/app/campaigns');const errorBox=errorPage.locator('[data-workspace-calendar]');await errorBox.getByRole('alert').filter({hasText:'Owned saved timezone unavailable'}).waitFor();assert.equal(await errorBox.getByLabel('Display IANA time zone',{exact:true}).isDisabled(),true);await errorPage.unrouteAll({behavior:'wait'});await errorBox.getByRole('button',{name:'Reload saved timezone',exact:true}).click();await errorPage.waitForFunction(()=>document.querySelector<HTMLInputElement>('[data-workspace-calendar] input')?.value==='UTC');await errorPage.close();
  await db.query("UPDATE memberships SET role='Viewer'WHERE workspace_id=$1 AND user_id=$2",[workspace,user]);await page.reload();await box.getByRole('heading',{name:'Planned campaign calendar',exact:true}).waitFor();await page.waitForFunction(()=>document.querySelector<HTMLInputElement>('[data-workspace-calendar] input')?.value==='UTC');assert.equal(await zone.isDisabled(),true);assert.equal(await save.isDisabled(),true);await month.fill('2026-11');await summary.filter({hasText:'UTC'}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'/tmp/lettercape-calendar-mobile.png',fullPage:false});await db.query("UPDATE memberships SET role='Owner'WHERE workspace_id=$1 AND user_id=$2",[workspace,user]);
  gate=new Promise<void>(r=>release=r);ready=new Promise<void>(r=>entered=r);await page.route('**/v1/campaigns/calendar?*',async route=>{const response=await route.fetch();entered();await gate;try{await route.fulfill({response});}catch{}});await refresh.click();await ready;await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.locator('#workspace').selectOption(other);await page.getByRole('heading',{name:'Make something worth opening.',exact:true}).waitFor();release();await page.unrouteAll({behavior:'wait'});await page.goto(origin+'/app/campaigns');await page.waitForFunction(()=>document.querySelector<HTMLInputElement>('[data-workspace-calendar] input')?.value==='UTC');await month.fill('2026-11');await box.locator('[data-calendar-empty]').waitFor();assert.equal(await box.locator('[data-calendar-entry]').count(),0);await context.close();
  console.log('Calendar actual Chromium PASS: initial/error fences, NY folds, month/empty/navigation, repeated/error pages, changed-zone cursor isolation and explicit stale form reload, offline/lost acknowledgment/failed current read/storage-unavailable original-key recovery, independent CAS, Viewer,390px and interrupted workspace response.');
 }finally{await browser.close();}
}
