// Explicit local fixture runner. Production private storage/identities/operations are unconfigured.
import pg from'pg';import env from'@next/env';import{setTimeout as pause}from'node:timers/promises';
import{configuredAssetStore}from'../src/server/asset-store';import{runNextMediaJob}from'../src/server/media-worker';import{mediaSupervisorConfig}from'../src/server/media-supervisor';
env.loadEnvConfig(process.cwd());
if(process.env.MEDIA_LOCAL_FIXTURES_ONLY!=='true'||process.env.LOCAL_DEVELOPMENT!=='true'||process.env.NODE_ENV==='production')throw Error('MEDIA_PRODUCTION_NOT_CONFIGURED: Dedicated production identities, private storage and release evidence are required.');
const url=new URL(process.env.MIGRATION_DATABASE_URL??'');if(!['127.0.0.1','localhost'].includes(url.hostname)||url.port!=='55439'||(url.pathname!=='/mailcraft'&&!(process.env.SOURCE_TRUTH_FIXTURE==='true'&&/^\/creation_fixture_[a-f0-9]{32}$/.test(url.pathname))))throw Error('Only the owned local media fixture database is allowed.');
const worker=new pg.Pool({connectionString:url.toString(),max:2,options:'-c role=mailcraft_media_worker -c statement_timeout=5000 -c lock_timeout=2000'}),scheduler=new pg.Pool({connectionString:url.toString(),max:1,options:'-c role=mailcraft_media_scheduler -c statement_timeout=5000 -c lock_timeout=2000'}),stop=new AbortController();
for(const signal of['SIGINT','SIGTERM']as const)process.on(signal,()=>stop.abort());
try{for(const[pool,expected]of[[worker,'mailcraft_media_worker'],[scheduler,'mailcraft_media_scheduler']]as const){const role=(await pool.query('SELECT current_user AS name,rolsuper,rolbypassrls,rolcreatedb,rolcreaterole FROM pg_roles WHERE rolname=current_user')).rows[0];if(role?.name!==expected||role.rolsuper||role.rolbypassrls||role.rolcreatedb||role.rolcreaterole)throw Error('MEDIA_FIXTURE_ROLE_INVALID');}const store=configuredAssetStore(),config=mediaSupervisorConfig();console.log('Owned local media fixture worker active; public production delivery is unavailable.');while(!stop.signal.aborted){try{const ran=await runNextMediaJob(scheduler,worker,store,stop.signal,config);if(!ran)await pause(1000,undefined,{signal:stop.signal});else console.log('Media fixture job settled; inspect its authenticated operation receipt for outcome.');}catch(error){if(stop.signal.aborted)break;console.error('Media fixture worker refused: '+((error as{code?:string}).code??(error as Error).message));await pause(1000,undefined,{signal:stop.signal}).catch(()=>{});}}}finally{await Promise.all([worker.end(),scheduler.end()]);}
