import { chromium } from 'playwright';
import assert from'node:assert/strict';import{randomUUID,randomBytes}from'node:crypto';import pg from'pg';import env from'@next/env';import{digest}from'../src/server/audit';env.loadEnvConfig(process.cwd());
const origin=process.env.APP_ORIGIN??'http://127.0.0.1:3000';if(process.env.LOCAL_DEVELOPMENT!=='true'||!['127.0.0.1','localhost'].includes(new URL(origin).hostname))throw new Error('Owned loopback membership fixtures only.');
const db=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL}),workspace=randomUUID(),other=randomUUID(),users=Array.from({length:5},()=> 'team-http-'+randomUUID()),tokens=users.map(()=>randomBytes(32).toString('hex')),roles=['Owner','Admin','Editor','Viewer','Billing'],bearer='lc_'+randomBytes(32).toString('hex');
async function call(path:string,method='GET',body?:unknown,actor=0,extra:Record<string,string>={}){const res=await fetch(origin+'/v1/'+path,{method,signal:AbortSignal.timeout(15000),headers:{Origin:origin,Cookie:'mailcraft_local_session='+tokens[actor],'X-Workspace-Id':workspace,'Content-Type':'application/json','Idempotency-Key':randomUUID(),...extra},body:body===undefined?undefined:JSON.stringify(body)});return{status:res.status,body:await res.json()};}
async function denied(path:string,method:string,body:unknown,code:string,actor=0,extra:Record<string,string>={}){const result=await call(path,method,body,actor,extra);assert.equal(result.body.error?.code,code,JSON.stringify(result.body));assert.ok(result.status>=400);}
async function journalCount(){return(await db.query('SELECT count(*)::int AS count FROM membership_changes WHERE workspace_id=$1',[workspace])).rows[0].count;}
let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
try{
 await db.query("INSERT INTO workspaces(id,name)VALUES($1,'Team browser'),($2,'Team fallback')",[workspace,other]);
 for(let i=0;i<users.length;i++){await db.query('INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,$3)',[workspace,users[i],roles[i]]);await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,now()+interval '1 hour')",[digest(tokens[i]),users[i]]);}
 await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,'Owner')",[other,users[0]]);
 await db.query("INSERT INTO api_keys(workspace_id,id,key_hash,name,scopes,created_by,expires_at)VALUES($1,$2,$3,'Team authority fixture',$4,$5,now()+interval '1 hour')",[workspace,randomUUID(),digest(bearer),JSON.stringify(['emails:read']),users[0]]);
 const list=await call('memberships');assert.equal(list.status,200,JSON.stringify(list.body.error));assert.equal(list.body.total_count,5);
 const memberIds=users.map(user=>list.body.data.find((member:{user_id:string})=>member.user_id===user).id);
 const path=(actor:number,command='role')=>`memberships/${memberIds[actor]}/${command}`;
 const summary=await call('memberships/summary');assert.equal(summary.body.summary.editing_seats,3);assert.equal(summary.body.summary.active_owners,1);assert.equal(summary.body.summary.mfa_mode,'local-development');
 assert.equal((await call('membership-changes')).body.total_count,0);
 for(const actor of[2,3,4])await denied('memberships','GET',undefined,'INSUFFICIENT_SCOPE',actor);
 await denied('memberships','GET',undefined,'SESSION_REQUIRED',0,{Authorization:'Bearer '+bearer});
 await denied('m%65mberships','GET',undefined,'SESSION_REQUIRED',0,{Authorization:'Bearer '+bearer});
 await denied(path(0),'POST',{role:'Viewer',expected_version:1},'LAST_OWNER_REQUIRED');
 await denied(path(0,'remove'),'POST',{expected_version:1,acknowledge:true},'LAST_OWNER_REQUIRED');
 await denied(path(0),'POST',{role:'Admin',expected_version:1},'ROLE_PROTECTED',1);
 await denied(path(4),'POST',{role:'Viewer',expected_version:1},'ROLE_PROTECTED',1);
 await denied(path(2),'POST',{role:'Billing',expected_version:1},'ROLE_PROTECTED',1);
 await denied(path(3),'POST',{role:'Editor',expected_version:1},'SEAT_POLICY_REQUIRED');
 await denied(path(2),'POST',{role:'Owner',expected_version:1},'VALIDATION_FAILED');
 await denied(path(2,'remove'),'POST',{expected_version:1,acknowledge:false},'VALIDATION_FAILED');
 await denied(path(2),'POST',{role:'Viewer',expected_version:1},'ORIGIN_DENIED',0,{Origin:''});
 await denied(path(2),'POST',{role:'Viewer',expected_version:1},'ORIGIN_DENIED',0,{Origin:'https://unowned.invalid'});
 await denied(path(2),'POST',{role:'Viewer',expected_version:1},'IDEMPOTENCY_KEY_REQUIRED',0,{'Idempotency-Key':''});
 const foreign=(await db.query('SELECT id FROM memberships WHERE workspace_id=$1',[other])).rows[0].id;
 await denied(`memberships/${foreign}/remove`,'POST',{expected_version:1,acknowledge:true},'RESOURCE_NOT_FOUND');
 const key=randomUUID(),input={role:'Admin',expected_version:1},changed=await call(path(2),'POST',input,0,{'Idempotency-Key':key});assert.equal(changed.status,200,JSON.stringify(changed.body));assert.equal(changed.body.member.version,2);assert.equal(changed.body.changes[0].editing_seats_after,3);assert.equal(await journalCount(),1);
 const replay=await call(path(2),'POST',input,0,{'Idempotency-Key':key});assert.equal(replay.status,200);assert.deepEqual(replay.body.member,changed.body.member);assert.equal(await journalCount(),1);
 await denied(path(2),'POST',{role:'Viewer',expected_version:1},'IDEMPOTENCY_MISMATCH',0,{'Idempotency-Key':key});
 await denied(path(2),'POST',{role:'Viewer',expected_version:1},'MEMBERSHIP_VERSION_CONFLICT');
 assert.equal((await call(path(2),'POST',{role:'Editor',expected_version:2})).status,200);
 const removed=await call(path(3,'remove'),'POST',{expected_version:1,acknowledge:true});assert.equal(removed.status,200);await denied(path(3),'POST',{role:'Billing',expected_version:2},'MEMBERSHIP_INACTIVE');await denied('memberships','GET',undefined,'RESOURCE_NOT_FOUND',3);
 const fillers=Array.from({length:22},()=> 'team-page-'+randomUUID());for(const user of fillers)await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,'Viewer')",[workspace,user]);
 const first=await call('memberships');assert.equal(first.body.total_count,27);assert.equal(first.body.data.length,25);assert.equal(first.body.has_more,true);
 const next=await call('memberships?after='+encodeURIComponent(first.body.next_cursor));assert.equal(next.status,200);assert.equal(next.body.data.length,2);assert.equal(new Set([...first.body.data,...next.body.data].map(member=>member.id)).size,27);
 await denied('memberships?after='+encodeURIComponent(first.body.next_cursor),'GET',undefined,'INVALID_CURSOR',1);
 await denied('membership-changes?after='+encodeURIComponent(first.body.next_cursor),'GET',undefined,'INVALID_CURSOR');
 await denied('memberships?created_after=2000-01-01T00%3A00%3A00Z&after='+encodeURIComponent(first.body.next_cursor),'GET',undefined,'INVALID_CURSOR');
 await denied('memberships?after='+encodeURIComponent(first.body.next_cursor+'x'),'GET',undefined,'INVALID_CURSOR');
 await db.query('DELETE FROM memberships WHERE workspace_id=$1 AND user_id=ANY($2::text[])',[workspace,fillers]);
 browser=await chromium.launch({headless:true});const context=await browser.newContext();await context.addCookies([{name:'mailcraft_local_session',value:tokens[0],url:origin}]);await context.addInitScript(w=>localStorage.setItem('mailcraft.workspace',w),workspace);const page=await context.newPage();await page.goto(origin+'/app/settings');await page.getByRole('heading',{name:/Clear limits/}).waitFor();assert.equal(await page.getByRole('heading',{name:'Team members',exact:true}).count(),1,'Team controls must exist in the real Settings screen.');
 const row=(actor:number)=>page.locator(`[data-member-id="${memberIds[actor]}"]`);
 await row(2).getByRole('combobox').waitFor();await page.getByText('No membership changes yet.',{exact:true}).waitFor({state:'hidden'});
 assert.equal(await row(0).getByRole('button',{name:'Remove member',exact:true}).isDisabled(),true);
 let posts=0;const before=await journalCount();
 await page.route('**/v1/'+path(2),async route=>{if(route.request().method()!=='POST'){await route.continue();return;}posts++;await route.fetch();await route.abort('failed');});
 await row(2).getByRole('combobox').selectOption('Viewer');await row(2).getByRole('button',{name:'Change role',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Confirm membership change'});await dialog.getByRole('button',{name:'Confirm change',exact:true}).evaluate((button:HTMLButtonElement)=>{button.click();button.click();});
 await page.getByRole('alert').filter({hasText:/Failed to fetch|fetch failed/i}).waitFor();assert.equal(posts,1);assert.equal(await journalCount(),before+1);
 await page.unroute('**/v1/'+path(2));await page.reload();
 for(const status of[401,403]){await row(2).getByRole('button',{name:'Retry same role change',exact:true}).click();await page.route('**/v1/'+path(2),route=>route.fulfill({status,contentType:'application/json',body:JSON.stringify({error:{code:'FIXTURE_AUTHORITY_DENIED',message:'Controlled authority rejection'}})}));await dialog.getByRole('button',{name:'Retry original command',exact:true}).click();await page.getByRole('alert').filter({hasText:'Controlled authority rejection'}).waitFor();assert.equal(await journalCount(),before+1);await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await page.unroute('**/v1/'+path(2));await page.reload();}
 await row(2).getByRole('button',{name:'Retry same role change',exact:true}).click();await dialog.getByRole('button',{name:'Retry original command',exact:true}).click();await row(2).getByText('Viewer · active · version 4',{exact:true}).waitFor();assert.equal(await journalCount(),before+1);await row(2).getByRole('button',{name:'Retry same role change',exact:true}).waitFor({state:'hidden'});
 await row(2).getByRole('combobox').selectOption('Billing');await row(2).getByRole('button',{name:'Change role',exact:true}).click();assert.equal((await call(path(2),'POST',{role:'Billing',expected_version:4})).status,200);await dialog.getByRole('button',{name:'Confirm change',exact:true}).click();await page.getByRole('alert').filter({hasText:'Membership changed.'}).waitFor();await row(2).getByText('Billing · active · version 5',{exact:true}).waitFor();assert.equal(await row(2).getByRole('button',{name:'Retry same role change',exact:true}).count(),0);
 await context.setOffline(true);await page.getByRole('button',{name:'Refresh team',exact:true}).click();await page.getByRole('alert').filter({hasText:/Failed to fetch|fetch failed/i}).waitFor();await context.setOffline(false);await page.getByRole('button',{name:'Refresh team',exact:true}).click();await page.getByRole('alert').filter({hasText:/Failed to fetch|fetch failed/i}).waitFor({state:'hidden'});
 // A lost transfer acknowledgment must remain recoverable after the caller
 // becomes Admin and the target Owner becomes protected from new commands.
 const transferBefore=await journalCount();await page.route('**/v1/'+path(1,'transfer-owner'),async route=>{await route.fetch();await route.abort('failed');});await row(1).getByRole('button',{name:'Transfer ownership',exact:true}).click();assert.equal(await dialog.getByRole('button',{name:'Confirm change',exact:true}).isDisabled(),true);await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Confirm change',exact:true}).click();await page.getByRole('alert').filter({hasText:/Failed to fetch|fetch failed/i}).waitFor();assert.equal(await journalCount(),transferBefore+2);
 await page.unroute('**/v1/'+path(1,'transfer-owner'));await page.reload();await row(1).getByRole('button',{name:'Retry same transfer-owner change',exact:true}).click();await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Retry original command',exact:true}).click();await row(1).getByRole('button',{name:'Retry same transfer-owner change',exact:true}).waitFor({state:'hidden'});assert.equal(await journalCount(),transferBefore+2);assert.equal((await call('memberships/summary')).body.summary.active_owners,1);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/lettercape-memberships-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false,'Team controls must fit the mobile viewport.');await page.getByRole('heading',{name:'Team members',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/lettercape-memberships-mobile-detail.png'});
 await page.setViewportSize({width:1280,height:900});
 let releaseHistory!:()=>void,heldHistory!:()=>void;const historyHeld=new Promise<void>(resolve=>{heldHistory=resolve;}),historyRelease=new Promise<void>(resolve=>{releaseHistory=resolve;});
 await page.route('**/v1/membership-changes',async route=>{if(route.request().headers()['x-workspace-id']!==workspace){await route.continue();return;}const response=await route.fetch();heldHistory();await historyRelease;await route.fulfill({response});});await page.getByRole('button',{name:'Refresh team',exact:true}).click();await historyHeld;await page.locator('#workspace').selectOption(other);await page.waitForURL('**/app');await page.getByRole('link',{name:'Settings',exact:true}).click();await page.getByRole('heading',{name:'Team members',exact:true}).waitFor();await page.waitForFunction(id=>!document.querySelector(`[data-member-id="${id}"]`),memberIds[1]);await page.getByText('No membership changes yet.',{exact:true}).waitFor();const returnedHistory=page.waitForResponse(response=>response.url().endsWith('/v1/membership-changes')&&response.request().headers()['x-workspace-id']===workspace);releaseHistory();await returnedHistory;await page.unroute('**/v1/membership-changes');assert.equal(await page.locator('[data-member-id]').count(),1);await page.locator('#workspace').selectOption(workspace);await page.waitForURL('**/app');await page.getByRole('link',{name:'Settings',exact:true}).click();await row(0).getByRole('combobox').waitFor();
 await row(0).getByRole('combobox').selectOption('Viewer');await row(0).getByRole('button',{name:'Change role',exact:true}).click();await dialog.getByRole('button',{name:'Confirm change',exact:true}).click();await page.getByText(/Your management access changed/).waitFor();assert.equal(await page.locator('[data-member-id]').count(),0);await denied('memberships','GET',undefined,'INSUFFICIENT_SCOPE');await denied('emails','GET',undefined,'AUTH_REQUIRED',0,{Authorization:'Bearer '+bearer});
 await page.getByRole('button',{name:'Reload workspace',exact:true}).click();await page.getByRole('link',{name:'Brand',exact:true}).click();await page.getByRole('heading',{name:/brand/i}).first().waitFor();
 console.log('Membership HTTP: five roles, last Owner, protected roles, seat increase denial, strict inputs, CSRF, bearer/encoded roots, foreign IDs, immutable keyed replay/CAS, removal/no resurrection, signed paging negatives PASS. Chromium: real Settings, lost acknowledgment/401/403/reload/original retry, repeated clicks, stale CAS, offline/refresh, transfer recovery as Admin, delayed history across workspace navigation, self-demotion/key revocation and mobile PASS. Production Clerk MFA and billing remain unconfigured.');
}finally{
 await browser?.close();
 for(const table of['membership_changes','idempotency','api_rate_events','audit_events','api_keys','memberships'])await db.query(`DELETE FROM ${table} WHERE workspace_id=ANY($1::uuid[])`,[[workspace,other]]);
 await db.query('DELETE FROM auth_sessions WHERE user_id=ANY($1::text[])',[users]);await db.query('DELETE FROM workspaces WHERE id=ANY($1::uuid[])',[[workspace,other]]);await db.end();
}
