import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {spawn,type ChildProcess} from 'node:child_process';
import {open} from 'node:fs/promises';
import {chromium} from 'playwright';
import {sourceDatabase} from './smoke-source-truth';
import {createEmail,checkpoint} from '../src/server/emails';
import {blankSpec} from '../src/domain/email';
import {digest} from '../src/server/audit';
import {assessmentRecoverySlot} from '../src/ui/recipient-assessment-recovery';
import {RecipientAssessmentView,RecipientObservationView} from '../src/domain/recipient-assessments';
const origin='http://127.0.0.1:3004';
await sourceDatabase(async({db,p,brand,tx})=>{
 const email=await tx(c=>createEmail(c,p,'Owned assessment content',blankSpec(brand,'Owned'))),revision=await tx(c=>checkpoint(c,p,email.id,1));
 const contacts=[randomUUID(),randomUUID(),randomUUID()].sort(),segment=randomUUID(),snapshot=randomUUID(),evaluated_at=new Date().toISOString();
 for(const [n,id]of contacts.entries())await db.query("INSERT INTO contacts(workspace_id,id,email_original,email_lookup,subscription)VALUES($1,$2,$3,$3,'subscribed')",[p.workspace,id,'owned-assessment-'+n+'@example.test']);
 await db.query("INSERT INTO segments(workspace_id,id,name)VALUES($1,$2,'Owned assessment rule')",[p.workspace,segment]);await db.query('INSERT INTO segment_versions(workspace_id,segment_id,version,schema_version,rule,created_by)VALUES($1,$2,1,1,$3,$4)',[p.workspace,segment,JSON.stringify({kind:'attribute',field:'first_name',op:'exists'}),p.user]);
 const members=contacts.map(id=>({id,locale:'en-US',consent_version:1,eligible:true,reason:'ELIGIBLE'})),source={schema_version:1,segment_id:segment,segment_version:1,evaluated_at,members,matched_count:3,eligible_count:3,excluded_count:0};
 await db.query('INSERT INTO audience_snapshots(workspace_id,id,segment_id,segment_version,evaluated_at,members,matched_count,eligible_count,digest,created_by)VALUES($1,$2,$3,1,$4,$5,3,3,$6,$7)',[p.workspace,snapshot,segment,evaluated_at,JSON.stringify(members),digest(source),p.user]);
 await db.query("UPDATE contacts SET subscription='pending_confirmation',consent_version=consent_version+1 WHERE id=$1",[contacts[1]]);await db.query("INSERT INTO suppressions(workspace_id,contact_id,reason)VALUES($1,$2,'manual')",[p.workspace,contacts[2]]);
 const cookie=randomBytes(32).toString('hex'),viewer='assessment-viewer-'+randomUUID(),viewerCookie=randomBytes(32).toString('hex');await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,'Viewer')",[p.workspace,viewer]);for(const [user,value]of[[p.user,cookie],[viewer,viewerCookie]])await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,clock_timestamp()+interval '1 hour')",[digest(value),user]);
 const runtime=new URL(process.env.DATABASE_URL!);runtime.pathname=new URL(db.options.connectionString!).pathname;assert.match(runtime.pathname,/^\/creation_fixture_[a-f0-9]{32}$/);
 const appLog=await open('/tmp/lettercape-recipient-app.log','w'),workerLog=await open('/tmp/lettercape-recipient-worker.log','w');let app:ChildProcess|undefined,worker:ChildProcess|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
 const localEnv:NodeJS.ProcessEnv={PATH:process.env.PATH,NODE_ENV:'development',LOCAL_DEVELOPMENT:'true',APP_ORIGIN:origin,DATABASE_URL:runtime.toString(),MIGRATION_DATABASE_URL:db.options.connectionString!,NEXT_TELEMETRY_DISABLED:'1',PREFERENCE_SIGNING_SECRET:randomBytes(32).toString('hex')};
 try{
  app=spawn(process.execPath,['node_modules/next/dist/bin/next','dev','--hostname','127.0.0.1','--port','3004'],{env:localEnv,stdio:['ignore',appLog.fd,appLog.fd]});
  for(let n=0;n<120;n++){if(app.exitCode!==null)throw Error('Owned assessment app exited');try{if((await fetch(origin+'/v1/health')).ok)break;}catch{}if(n===119)throw Error('Owned assessment app unavailable');await new Promise(r=>setTimeout(r,250));}
  browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);await context.addInitScript(w=>{if(top===window)localStorage.setItem('mailcraft.workspace',w);},p.workspace);
  const headers={'X-Workspace-Id':p.workspace,'X-Actor-Id':p.user,Origin:origin,'Idempotency-Key':randomUUID()};
  const created=await context.request.post(origin+'/v1/campaigns',{headers,data:{name:'Owned recipient assessment campaign',revision_id:revision.id}});assert.equal(created.status(),200);let campaign=(await created.json()).campaign;
  const configured=await context.request.post(origin+'/v1/campaigns/'+campaign.id+'/configuration',{headers:{...headers,'Idempotency-Key':randomUUID()},data:{expected_version:campaign.version,name:campaign.name,revision_id:revision.id,planned_timing:null,audience_snapshot_id:snapshot}});assert.equal(configured.status(),200);campaign=(await configured.json()).campaign;
  const before=(await db.query('SELECT (SELECT count(*)FROM frequency_reservations) frequency,(SELECT count(*)FROM usage_ledger) usage,(SELECT count(*)FROM operations) operations')).rows;const original=(await db.query('SELECT state,version,digest,approval FROM campaigns WHERE id=$1',[campaign.id])).rows;
  const page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());let external=0;await context.route(url=>url.origin!==origin&&url.protocol!=='blob:'&&url.protocol!=='data:',r=>{external++;return r.abort();});
  await page.goto(origin+'/app/campaigns');const panel=page.locator('[data-recipient-assessments="'+campaign.id+'"]');await panel.waitFor();await panel.getByText('No recipient assessments',{exact:false}).waitFor();
  const endpoint=origin+'/v1/campaigns/'+campaign.id+'/recipient-assessments';let requests=0,assessmentId='';
  let committed!:()=>void,commitFailed!:(e:unknown)=>void;const commitObserved=new Promise<void>((resolve,reject)=>{committed=resolve;commitFailed=reject;});
  await page.route(endpoint,async route=>{if(route.request().method()!=='POST')return route.continue();requests++;try{const response=await route.fetch();assert.equal(response.status(),202);assessmentId=RecipientAssessmentView.parse((await response.json()).assessment).id;await route.abort('failed');committed();}catch(e){commitFailed(e);try{await route.abort();}catch{}}});
  await panel.getByRole('button',{name:'Create recipient assessment',exact:true}).evaluate((b:HTMLButtonElement)=>{b.click();b.click();});await commitObserved;await panel.getByRole('button',{name:'Retry original assessment command',exact:true}).waitFor();assert.equal(requests,1);assert.ok(assessmentId);assert.equal((await db.query('SELECT count(*)::int n FROM recipient_assessments')).rows[0].n,1);await page.unroute(endpoint);
  await db.query("INSERT INTO contacts(workspace_id,email_original,email_lookup,subscription)VALUES($1,'new-after-freeze@example.test','new-after-freeze@example.test','subscribed')",[p.workspace]);
  const doomed=spawn(process.execPath,['--import','tsx','tests/fixtures/recipient-assessment-crash.ts',p.workspace,p.user],{env:localEnv,stdio:['ignore',workerLog.fd,workerLog.fd,'ipc']});
  await new Promise<void>((resolve,reject)=>{const timeout=setTimeout(()=>{doomed.kill('SIGKILL');reject(Error('Owned staged child unavailable'));},15000);doomed.once('message',(message:{staged?:boolean;processed_count?:number})=>{clearTimeout(timeout);assert.equal(message.staged,true);assert.equal(message.processed_count,3);resolve();});doomed.once('exit',()=>{clearTimeout(timeout);reject(Error('Owned staged child exited before observation'));});});
  const died=new Promise<void>(resolve=>doomed.once('exit',()=>resolve()));doomed.kill('SIGKILL');await died;
  assert.equal((await db.query('SELECT count(*)::int n FROM recipient_observations')).rows[0].n,0);assert.equal((await db.query('SELECT processed_count FROM recipient_assessment_jobs WHERE id=$1',[assessmentId])).rows[0].processed_count,0);
  console.log('Actual worker SIGKILL after staged observations/progress before commit rolls back every row; restart uses original durable job PASS.');
  worker=spawn(process.execPath,['--import','tsx','scripts/recipient-assessment-worker.ts','--workspace',p.workspace,'--actor',p.user],{env:localEnv,stdio:['ignore',workerLog.fd,workerLog.fd]});
  for(let n=0;n<100;n++){if(worker.exitCode!==null)throw Error('Owned assessment worker exited');const row=(await db.query('SELECT status FROM recipient_assessment_jobs WHERE id=$1',[assessmentId])).rows[0];if(row?.status==='completed')break;if(n===99)throw Error('Owned assessment worker did not complete');await new Promise(r=>setTimeout(r,100));}
  await page.reload();await panel.getByRole('button',{name:'Retry original assessment command',exact:true}).click();const detail=panel.locator('[data-recipient-assessment-detail="'+assessmentId+'"]');await detail.waitFor();await detail.getByText('completed',{exact:false}).first().waitFor();assert.equal((await db.query('SELECT count(*)::int n FROM recipient_assessments')).rows[0].n,1);
  const result=await context.request.get(origin+'/v1/recipient-assessments/'+assessmentId,{headers});assert.equal(result.status(),200);const view=RecipientAssessmentView.parse((await result.json()).assessment);assert.equal(view.processed_count,3);assert.equal(view.excluded_count,3);assert.equal(view.authorization_issued,false);
  const observations=await context.request.get(origin+'/v1/recipient-assessments/'+assessmentId+'/observations?limit=2',{headers});assert.equal(observations.status(),200);const first=await observations.json();assert.equal(first.data.length,2);assert.equal(first.total_count,3);assert.equal(first.has_more,true);for(const item of first.data)RecipientObservationView.parse(item);const second=await context.request.get(origin+'/v1/recipient-assessments/'+assessmentId+'/observations?limit=2&after='+encodeURIComponent(first.next_cursor),{headers});assert.equal(second.status(),200);assert.equal((await second.json()).data.length,1);assert.equal((await context.request.get(origin+'/v1/recipient-assessments/'+assessmentId+'/observations?after='+encodeURIComponent(first.next_cursor)+'&created_after=2020-01-01T00:00:00Z',{headers})).status(),400);
  const reasons=(await db.query('SELECT contact_id,current_reason,reasons FROM recipient_observations ORDER BY contact_id')).rows;assert.deepEqual(reasons.map(r=>r.contact_id),contacts);assert.equal(reasons[1].current_reason,'CONSENT_NOT_CONFIRMED');assert.equal(reasons[2].current_reason,'SUPPRESSED');assert.ok(reasons.every(r=>r.reasons.includes('TOPIC_NOT_SELECTED')));
  assert.deepEqual((await db.query('SELECT (SELECT count(*)FROM frequency_reservations) frequency,(SELECT count(*)FROM usage_ledger) usage,(SELECT count(*)FROM operations) operations')).rows,before);assert.deepEqual((await db.query('SELECT state,version,digest,approval FROM campaigns WHERE id=$1',[campaign.id])).rows,original);console.log('Actual HTTP/Chromium lost committed acknowledgment, repeated-click/reload original replay, durable worker, frozen membership and current reasons with zero send/frequency/quota/campaign mutation PASS.');
  // Two actual clients queue admission behind the same origin Web Lock.
  worker.kill('SIGTERM');await new Promise<void>(resolve=>worker!.once('exit',()=>resolve()));worker=undefined;
  const otherPage=await context.newPage();await otherPage.goto(origin+'/app/campaigns');const otherPanel=otherPage.locator('[data-recipient-assessments="'+campaign.id+'"]');await otherPanel.getByRole('button',{name:'Create recipient assessment',exact:true}).waitFor();
  const slot=assessmentRecoverySlot({workspace:p.workspace,campaign:campaign.id,actor:p.user});
  await page.evaluate(async name=>{await new Promise<void>(resolve=>{void navigator.locks.request(name,{mode:'exclusive'},()=>{resolve();return new Promise<void>(release=>{Reflect.set(window,'__releaseRecipientAdmission',release);});});});},slot);
  let admissions=0,secondId='',secondCommitted!:()=>void;const secondObserved=new Promise<void>(r=>secondCommitted=r);
  await context.route(endpoint,async route=>{if(route.request().method()!=='POST')return route.continue();admissions++;const response=await route.fetch();assert.equal(response.status(),202);secondId=RecipientAssessmentView.parse((await response.json()).assessment).id;await route.abort('failed');secondCommitted();});
  await Promise.all([panel.getByRole('button',{name:'Create recipient assessment',exact:true}).click(),otherPanel.getByRole('button',{name:'Create recipient assessment',exact:true}).click()]);
  await page.waitForFunction(async()=>((await navigator.locks.query()).pending??[]).length>=2);
  await page.evaluate(()=>{(Reflect.get(window,'__releaseRecipientAdmission') as ()=>void)();});await secondObserved;
  await panel.getByRole('button',{name:'Retry original assessment command',exact:true}).waitFor();await otherPanel.getByRole('button',{name:'Retry original assessment command',exact:true}).waitFor();assert.equal(admissions,1);assert.equal((await db.query('SELECT count(*)::int n FROM recipient_assessments')).rows[0].n,2);
  assert.equal(await page.evaluate(name=>localStorage.getItem(name),slot),await otherPage.evaluate(name=>localStorage.getItem(name),slot));await context.unroute(endpoint);
  await panel.getByRole('button',{name:'Retry original assessment command',exact:true}).click();await panel.locator('[data-recipient-assessment-detail="'+secondId+'"]').waitFor();await otherPage.close();
  await page.reload();await panel.getByRole('button',{name:'View assessment '+secondId,exact:true}).click();await panel.getByRole('button',{name:'Cancel recipient assessment',exact:true}).click();await panel.locator('[data-recipient-assessment-detail="'+secondId+'"]').getByText('cancelled',{exact:true}).waitFor();
  assert.equal((await db.query('SELECT status FROM recipient_assessment_jobs WHERE id=$1',[secondId])).rows[0].status,'cancelled');assert.equal((await db.query('SELECT count(*)::int n FROM recipient_observations WHERE assessment_id=$1',[secondId])).rows[0].n,0);
  const unsupported=await browser.newContext();await unsupported.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);await unsupported.addInitScript(w=>{localStorage.setItem('mailcraft.workspace',w);Object.defineProperty(navigator,'locks',{value:undefined,configurable:true});},p.workspace);const unsupportedPage=await unsupported.newPage();await unsupportedPage.goto(origin+'/app/campaigns');const unsupportedPanel=unsupportedPage.locator('[data-recipient-assessments="'+campaign.id+'"]');await unsupportedPanel.getByText('Durable browser recovery is unavailable.',{exact:false}).waitFor();assert.equal(await unsupportedPanel.getByRole('button',{name:'Create recipient assessment',exact:true}).isEnabled(),false);await unsupportedPanel.getByRole('button',{name:'View assessment '+assessmentId,exact:true}).click();await unsupportedPanel.locator('[data-recipient-assessment-detail="'+assessmentId+'"]').waitFor();await unsupported.close();
  await panel.getByRole('button',{name:'View assessment '+assessmentId,exact:true}).click();await detail.waitFor();
  console.log('Actual two-tab origin-lock admission preserves one original command/one durable job; replay and explicit cancel retain history; unsupported locks allow reads and refuse mutations PASS.');
  await page.route(origin+'/v1/recipient-assessments/'+assessmentId,route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'OWNED_UNAVAILABLE',message:'Owned assessment status unavailable'}})}));await detail.getByRole('button',{name:'Refresh assessment status',exact:true}).click();await panel.getByRole('alert').filter({hasText:'Owned assessment status unavailable'}).waitFor();await page.unroute(origin+'/v1/recipient-assessments/'+assessmentId);await panel.getByRole('button',{name:'View assessment '+assessmentId,exact:true}).click();await detail.getByText('completed',{exact:false}).first().waitFor();
  await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await panel.screenshot({path:'/tmp/lettercape-recipient-mobile.png'});
  let release!:()=>void,arrived!:()=>void;const held=new Promise<void>(r=>release=r),fetched=new Promise<void>(r=>arrived=r);await page.route(origin+'/v1/recipient-assessments/'+assessmentId,async route=>{const response=await route.fetch();arrived();await held;try{await route.fulfill({response});}catch{}});await detail.getByRole('button',{name:'Refresh assessment status',exact:true}).click();await fetched;await page.goto(origin+'/app/emails');release();await page.unroute(origin+'/v1/recipient-assessments/'+assessmentId);assert.equal(await page.locator('[data-recipient-assessment-detail]').count(),0);
  await context.addCookies([{name:'mailcraft_local_session',value:viewerCookie,url:origin,sameSite:'Strict'}]);assert.equal((await context.request.get(origin+'/v1/recipient-assessments/'+assessmentId,{headers:{...headers,'X-Actor-Id':viewer}})).status(),403);assert.equal((await context.request.get(endpoint,{headers:{...headers,'X-Actor-Id':viewer}})).status(),403);await page.goto(origin+'/app/campaigns');assert.equal(await page.locator('[data-recipient-assessment-detail]').count(),0);assert.equal(await page.getByRole('button',{name:'Create recipient assessment',exact:true}).count(),0);assert.equal(external,0);assert.deepEqual(errors,[]);console.log('Actual signed paging/filter fence, transient error retry, mobile, delayed status after navigation and Viewer denial PASS; no external calls/page errors.');
 }finally{
  await browser?.close();for(const child of[worker,app])if(child&&child.exitCode===null){child.kill('SIGTERM');await new Promise<void>(resolve=>{const timer=setTimeout(()=>{if(child.exitCode===null)child.kill('SIGKILL');resolve();},5000);child.once('exit',()=>{clearTimeout(timer);resolve();});});}await appLog.close();await workerLog.close();
 }
});
