import assert from 'node:assert/strict';
import {randomUUID,randomBytes} from 'node:crypto';
import pg from 'pg';
import env from '@next/env';
import {chromium} from 'playwright';
import {digest} from '../src/server/audit';
import {blankSpec} from '../src/domain/email';
env.loadEnvConfig(process.cwd());
const origin=process.env.APP_ORIGIN??'http://127.0.0.1:3003';
if(process.env.LOCAL_DEVELOPMENT!=='true'||!['127.0.0.1','localhost'].includes(new URL(origin).hostname))throw Error('Owned loopback editor fixture required.');
const db=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL}),workspace=randomUUID(),user='editor-core-'+randomUUID(),cookie=randomBytes(32).toString('hex'),brand=randomUUID(),email=randomUUID();
let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
try{
 await db.query("INSERT INTO workspaces(id,name)VALUES($1,'Owned editor core')",[workspace]);await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,'Owner')",[workspace,user]);await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,clock_timestamp()+interval '1 hour')",[digest(cookie),user]);
 await db.query("INSERT INTO brands(workspace_id,id,version,data)VALUES($1,$2,1,'{}')",[workspace,brand]);await db.query('INSERT INTO emails(workspace_id,id,title,spec,created_by)VALUES($1,$2,$3,$4,$5)',[workspace,email,'Owned editor core',JSON.stringify(blankSpec(brand,'Owned editor')),user]);
 browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);await context.addInitScript(w=>localStorage.setItem('mailcraft.workspace',w),workspace);const page=await context.newPage();page.on('dialog',dialog=>dialog.accept());
 await page.goto(origin+'/app/emails/'+email);const subject=page.getByRole('textbox',{name:'Subject',exact:true}),heading=page.getByRole('textbox',{name:'Heading',exact:true});await subject.waitFor();await heading.waitFor();
 const original=await subject.inputValue();await subject.fill('Undo this temporary subject');await page.getByRole('button',{name:'Undo',exact:true}).click();assert.equal(await subject.inputValue(),original);
 await subject.fill('Owned saved checkpoint');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('status').filter({hasText:/Saved/}).waitFor();await page.reload();await subject.waitFor();assert.equal(await subject.inputValue(),'Owned saved checkpoint');
 await page.getByRole('button',{name:'Review and check',exact:true}).click();await page.getByRole('heading',{name:'Review evidence',exact:true}).waitFor();await subject.fill('A later saved head');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('status').filter({hasText:/Saved/}).waitFor();
 await page.getByRole('button',{name:'History',exact:true}).click();const history=page.locator('.history-row').filter({hasText:'Owned saved checkpoint'}).first();await history.getByRole('button',{name:'Restore as new head',exact:true}).click();await page.waitForFunction(()=>Array.from(document.querySelectorAll('input')).some(input=>input.value==='Owned saved checkpoint'));assert.equal(await subject.inputValue(),'Owned saved checkpoint');await page.getByRole('button',{name:'Close history',exact:true}).click();
 // Hold draft writes so a real reload exercises retained local work before acknowledgment.
 const draftPattern='**/v1/emails/*/draft';await page.route(draftPattern,route=>route.abort());await subject.fill('Local recovery before acknowledgment');await page.waitForFunction(()=>Object.keys(localStorage).some(key=>key.startsWith('mailcraft.draft.')&&localStorage.getItem(key)?.includes('Local recovery before acknowledgment')));await page.reload();await subject.waitFor();assert.equal(await subject.inputValue(),'Local recovery before acknowledgment');await page.unroute(draftPattern);await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('status').filter({hasText:/Saved/}).waitFor();
 // Existing legacy regression assertions now run in an owned, repeatable Chromium fixture.
 await page.getByRole('button',{name:'HTML',exact:true}).first().click();const importPattern='**/v1/emails/*/import-html';await page.route(importPattern,async route=>{await new Promise(resolve=>setTimeout(resolve,500));await route.continue();});await heading.fill('The exact newly acknowledged heading');const rawRequest=page.waitForRequest(request=>request.url().includes('/import-html'));await page.getByRole('button',{name:'Edit raw HTML',exact:true}).click();await rawRequest;assert.equal(await subject.evaluate(element=>(element as HTMLInputElement).readOnly),true);const raw=page.getByRole('textbox',{name:'Raw HTML source',exact:true});await page.locator('.html-code-editor').filter({has:page.getByText('Raw HTML source',{exact:true})}).getByRole('button',{name:'Use basic editor',exact:true}).click();await raw.waitFor();assert.ok((await raw.inputValue()).includes('The exact newly acknowledged heading'));await page.unroute(importPattern);
 const freezePattern='**/v1/emails/*/revisions';await page.route(freezePattern,async route=>{const response=await route.fetch();await new Promise(resolve=>setTimeout(resolve,600));await route.fulfill({response});});const freezeRequest=page.waitForRequest(request=>request.url().endsWith('/revisions')&&request.method()==='POST');await page.getByRole('button',{name:'Review and check',exact:true}).click();await freezeRequest;await subject.fill('A newer subject after checkpoint request');await page.getByRole('alert').filter({hasText:'draft changed during freezing'}).waitFor();assert.equal(await page.getByRole('heading',{name:'Review evidence',exact:true}).count(),0);await page.unroute(freezePattern);await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('status').filter({hasText:/Saved/}).waitFor();
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/lettercape-editor-core-mobile.png'});
 console.log('Owned editor Chromium PASS: Undo, explicit save/reload, frozen history restore, unacknowledged local recovery, raw conversion flush/read-only transition, delayed checkpoint stale-report fence and390px.');
}catch(error){console.error('EDITOR_FIXTURE_FAILURE',error);throw error;}finally{
 await browser?.close();const cleanup=await db.connect();
 try{await cleanup.query('BEGIN');await cleanup.query('SELECT id FROM emails WHERE workspace_id=$1 FOR UPDATE',[workspace]);for(const table of ['render_downloads','preflights','idempotency','audit_events','revisions','emails','brands','memberships'])await cleanup.query('DELETE FROM '+table+' WHERE workspace_id=$1',[workspace]);await cleanup.query('DELETE FROM workspaces WHERE id=$1',[workspace]);await cleanup.query('DELETE FROM auth_sessions WHERE user_id=$1',[user]);await cleanup.query('COMMIT');}catch(error){await cleanup.query('ROLLBACK');throw error;}finally{cleanup.release();await db.end();}
}
