import assert from'node:assert/strict';import{randomUUID,randomBytes}from'node:crypto';import pg from'pg';import env from'@next/env';import{digest}from'../src/server/audit';import{blankSpec}from'../src/domain/email';import{apiSpec,absoluteSchema,validateSchema}from'./api-validation';env.loadEnvConfig(process.cwd());
const origin=process.env.APP_ORIGIN??'http://127.0.0.1:3003';if(process.env.LOCAL_DEVELOPMENT!=='true'||!['127.0.0.1','localhost'].includes(new URL(origin).hostname))throw new Error('Owned local Voice Guard fixture required.');const db=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL}),workspace=randomUUID(),other=randomUUID(),user='voice-http-'+randomUUID(),cookie=randomBytes(32).toString('hex');let browser:Awaited<ReturnType<(typeof import('playwright'))['chromium']['launch']>>|undefined;
async function call(path:string,method='GET',body?:unknown,key=randomUUID(),w=workspace,version?:number,bearer?:string){const r=await fetch(origin+'/v1/'+path,{method,headers:{Origin:origin,'Content-Type':'application/json','Idempotency-Key':key,...(bearer?{Authorization:'Bearer '+bearer}:{Cookie:'mailcraft_local_session='+cookie,'X-Workspace-Id':w}),...(version?{'If-Match':'"draft-'+version+'"'}:{})},body:body===undefined?undefined:JSON.stringify(body)});return{r,j:await r.json()};}
const kit={name:'Voice fixture',website:'',description:'Owned fixture',voice:'Plain',accent:'#0B625D',background:'#F7F6F2',font_stack:'Arial, sans-serif',address:'Reserved fixture address',approved_claims:[],forbidden_phrases:[],provenance:[]};
try{
 await db.query("INSERT INTO workspaces(id,name)VALUES($1,'Voice HTTP fixture'),($2,'Voice HTTP foreign')",[workspace,other]);for(const w of[workspace,other])await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,'Owner')",[w,user]);await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,clock_timestamp()+interval '1 hour')",[digest(cookie),user]);const first=(await call('brands','POST',kit)).j.brand.id,spec=blankSpec(first,kit.name);spec.subject='Plain';spec.preheader='Plain';spec.sections=[{id:'copy',type:'text',text:'One two three!'}];const email=(await call('emails','POST',{title:'Old kit pinned',spec})).j.email,revision=(await call('emails/'+email.id+'/revisions','POST',{},randomUUID(),workspace,email.doc_version)).j.revision;assert.ok(revision?.id);
 // Synthetic passing row is owned fixture data, never a vendor or GA acceptance claim.
 await db.query("INSERT INTO preflights(workspace_id,revision_id,artifact_hash,state,findings,rule_set_version)VALUES($1,$2,$3,'passed','[]','static-2')",[workspace,revision.id,revision.artifact_hash]);const campaign=(await call('campaigns','POST',{name:'Owned stale-rule fixture',revision_id:revision.id})).j.campaign;assert.ok(campaign?.id);const blocked=await call('campaigns/'+campaign.id+'/approve','POST',{});assert.equal(blocked.r.status,422);assert.equal(blocked.j.error.code,'PREFLIGHT_BLOCKED');
 const rules={max_sentence_words:2,max_exclamations:0},key=randomUUID(),next=await call('brands','POST',{...kit,tone_rules:rules},key);assert.equal(next.r.status,201);validateSchema(absoluteSchema(apiSpec.components.schemas.BrandResponse),next.j);assert.deepEqual(next.j.brand.data.tone_rules,rules);assert.equal((await call('brands','POST',{...kit,tone_rules:rules},key)).j.brand.id,next.j.brand.id);assert.equal((await call('brands','POST',{...kit,tone_rules:{regex:'.*'}})).r.status,422);
 const oldReport=(await call('email-revisions/'+revision.id+'/preflight','POST',{})).j.report;assert.equal(oldReport.rule_set_version,'static-3');assert.equal(oldReport.findings.some((f:{code:string})=>f.code==='VOICE_SENTENCE_LENGTH'||f.code==='VOICE_EXCLAMATIONS'),false);assert.equal((await db.query('SELECT data FROM brands WHERE id=$1',[first])).rows[0].data.tone_rules,undefined);
 const nextSpec={...spec,brand_kit_version_id:next.j.brand.id},newEmail=(await call('emails','POST',{title:'New kit pinned',spec:nextSpec})).j.email,newRevision=(await call('emails/'+newEmail.id+'/revisions','POST',{},randomUUID(),workspace,newEmail.doc_version)).j.revision,report=(await call('email-revisions/'+newRevision.id+'/preflight','POST',{})).j.report;assert.equal(report.rule_set_version,'static-3');assert.deepEqual(report.findings.filter((f:{code:string})=>['VOICE_SENTENCE_LENGTH','VOICE_EXCLAMATIONS'].includes(f.code)).map((f:{code:string;location:string})=>[f.code,f.location]),[['VOICE_SENTENCE_LENGTH','copy'],['VOICE_EXCLAMATIONS','copy']]);assert.notEqual(report.state,'passed');assert.equal((await call('brands','POST',{...kit,name:'Foreign own kit'},randomUUID(),other)).r.status,201);assert.equal((await call('emails','POST',{title:'Foreign pinned kit',spec:nextSpec},randomUUID(),other)).r.status,404);
 for(const role of['Viewer','Billing']){await db.query('UPDATE memberships SET role=$1 WHERE workspace_id=$2 AND user_id=$3',[role,workspace,user]);assert.equal((await call('brands','POST',{...kit,tone_rules:rules})).r.status,403);}await db.query("UPDATE memberships SET role='Owner'WHERE workspace_id=$1 AND user_id=$2",[workspace,user]);const reader=(await call('api-keys','POST',{name:'Owned tone reader',scopes:['brands:read'],expires_in_days:1})).j.secret;assert.equal((await call('brands','POST',{...kit,tone_rules:rules},randomUUID(),workspace,undefined,reader)).r.status,403);
 if(!process.argv.includes('--api')){
  const{chromium}=await import('playwright');browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844}});
  await context.addInitScript(w=>{if(!localStorage.getItem('mailcraft.workspace'))localStorage.setItem('mailcraft.workspace',w);},workspace);await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);const page=await context.newPage();
  const words=page.getByLabel('Maximum words per sentence',{exact:true}),exclamations=page.getByLabel('Maximum exclamation marks per field',{exact:true}),save=page.getByRole('button',{name:'Confirm brand version',exact:true});
  let entered!:()=>void,release!:()=>void;const ready=new Promise<void>(r=>entered=r),gate=new Promise<void>(r=>release=r);
  await page.route('**/v1/brands/current',async route=>{const response=await route.fetch();entered();await gate;await route.fulfill({response});});
  try{await page.goto(origin+'/app/brand');await ready;await words.waitFor({timeout:5000});assert.equal(await words.isEnabled(),false);}finally{release();await page.unrouteAll({behavior:'wait'});}
  await page.waitForFunction(()=>document.querySelector<HTMLInputElement>('.voice-rule-controls input')?.value==='2');assert.equal(await exclamations.inputValue(),'0');
  let posts=0;page.on('request',request=>{if(new URL(request.url()).pathname==='/v1/brands'&&request.method()==='POST')posts++;});
  for(const invalid of['0','1.5','201']){await words.fill(invalid);assert.equal(await words.evaluate((input:HTMLInputElement)=>input.checkValidity()),false);await save.click();assert.equal(posts,0);assert.equal(await words.inputValue(),invalid);}
  await words.fill('4');await context.setOffline(true);await save.click();await page.getByRole('alert').filter({hasText:/Failed to fetch|fetch failed/i}).first().waitFor();assert.equal(await words.inputValue(),'4');assert.equal(await exclamations.inputValue(),'0');await context.setOffline(false);
  const beforeLost=(await db.query('SELECT count(*)::int AS n FROM brands WHERE workspace_id=$1',[workspace])).rows[0].n;
  let acceptedId='',acknowledged!:()=>void;const acknowledgedSave=new Promise<void>(r=>acknowledged=r);await page.route('**/v1/brands',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}const response=await route.fetch();acceptedId=(await response.json()).brand.id;acknowledged();await route.abort('failed');});
  const postsBefore=posts;await save.evaluate((button:HTMLButtonElement)=>{button.click();button.click();});await acknowledgedSave;await page.getByRole('alert').filter({hasText:/Failed to fetch|fetch failed/i}).first().waitFor();await page.waitForFunction(()=>{const button=document.querySelector<HTMLButtonElement>('.brand-form button.primary');return !!button&&!button.disabled;});assert.equal(posts,postsBefore+1);assert.ok(acceptedId);assert.equal((await db.query('SELECT count(*)::int AS n FROM brands WHERE workspace_id=$1',[workspace])).rows[0].n,beforeLost+1);
  await page.unroute('**/v1/brands');await save.click();await page.getByRole('status').filter({hasText:'Brand version 3 saved.'}).waitFor();assert.equal((await call('brands/current')).j.brand.id,acceptedId);assert.equal((await db.query('SELECT count(*)::int AS n FROM brands WHERE workspace_id=$1',[workspace])).rows[0].n,beforeLost+1);
  await page.reload();await page.waitForFunction(()=>document.querySelector<HTMLInputElement>('.voice-rule-controls input')?.value==='4');assert.equal(await exclamations.inputValue(),'0');assert.deepEqual((await call('brands/current')).j.brand.data.tone_rules,{max_sentence_words:4,max_exclamations:0});
  await words.fill('');await exclamations.fill('');await save.click();await page.getByRole('status').filter({hasText:'Brand version 4 saved.'}).waitFor();const unset=(await call('brands/current')).j.brand;assert.deepEqual(unset.data.tone_rules,{});await page.reload();await save.waitFor();await page.waitForFunction(()=>{const fields=document.querySelector<HTMLFieldSetElement>('.brand-fields');return !!fields&&!fields.disabled;});assert.equal(await words.inputValue(),'');assert.equal(await exclamations.inputValue(),'');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('.voice-rule-controls').scrollIntoViewIfNeeded();await page.screenshot({path:'output/playwright/lettercape-voice-guard-mobile.png'});
  await page.route('**/v1/brands/current',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'FIXTURE_INITIAL_READ',message:'Controlled initial kit read failure'}})}));await page.reload();await page.getByRole('alert').filter({hasText:'Controlled initial kit read failure'}).waitFor();await page.waitForFunction(()=>{const fields=document.querySelector<HTMLFieldSetElement>('.brand-fields');return !!fields&&!fields.disabled;});await words.fill('5');assert.equal(await words.inputValue(),'5');await page.unroute('**/v1/brands/current');await page.reload();await page.waitForFunction(()=>{const fields=document.querySelector<HTMLFieldSetElement>('.brand-fields');return !!fields&&!fields.disabled;});assert.equal(await words.inputValue(),'');
  const unsetEmail=(await call('emails','POST',{title:'Unset rules pinned',spec:{...spec,brand_kit_version_id:unset.id}})).j.email,unsetRevision=(await call('emails/'+unsetEmail.id+'/revisions','POST',{},randomUUID(),workspace,unsetEmail.doc_version)).j.revision,unsetReport=(await call('email-revisions/'+unsetRevision.id+'/preflight','POST',{})).j.report;assert.equal(unsetReport.findings.some((f:{code:string})=>f.code.startsWith('VOICE_')),false);
  const pinnedAgain=(await call('email-revisions/'+newRevision.id+'/preflight','POST',{})).j.report;assert.equal(pinnedAgain.findings.filter((f:{code:string})=>f.code.startsWith('VOICE_')).length,2);
  await page.goto(origin+'/app/emails/'+newEmail.id);await page.getByRole('button',{name:'Review and check',exact:true}).click();await page.locator('.preflight-panel').getByText('VOICE SENTENCE LENGTH',{exact:true}).waitFor();await page.locator('.preflight-panel').getByText('VOICE EXCLAMATIONS',{exact:true}).waitFor();assert.equal(await page.locator('.preflight-panel').getByText('Location: copy',{exact:true}).count(),2);assert.match(await page.locator('.preflight-panel').innerText(),/Rules static-3/);
  await page.setViewportSize({width:1280,height:900});await page.goto(origin+'/app/brand');await save.waitFor();await page.waitForFunction(()=>{const fields=document.querySelector<HTMLFieldSetElement>('.brand-fields');return !!fields&&!fields.disabled;});
  let held!:()=>void,releaseRead!:()=>void;const heldRead=new Promise<void>(r=>held=r),readGate=new Promise<void>(r=>releaseRead=r);await page.route('**/v1/brands/current',async route=>{if(route.request().headers()['x-workspace-id']!==workspace){await route.continue();return;}const response=await route.fetch();held();await readGate;await route.fulfill({response});});
  try{await page.reload();await heldRead;await page.getByLabel('Active brand workspace').selectOption(other);await page.getByRole('heading',{name:'Make something worth opening.',exact:true}).waitFor();releaseRead();await page.unrouteAll({behavior:'wait'});assert.equal(await page.locator('.voice-rule-controls').count(),0);await page.getByRole('link',{name:'Brand',exact:true}).click();await page.waitForFunction(()=>{const fields=document.querySelector<HTMLFieldSetElement>('.brand-fields');return !!fields&&!fields.disabled;});assert.equal(await page.getByLabel('Brand name',{exact:true}).inputValue(),'Foreign own kit');assert.equal(await words.inputValue(),'');assert.equal(await exclamations.inputValue(),'');await db.query('DELETE FROM brands WHERE workspace_id=$1',[other]);await page.reload();await page.waitForFunction(()=>{const fields=document.querySelector<HTMLFieldSetElement>('.brand-fields');return !!fields&&!fields.disabled;});assert.equal(await page.getByLabel('Brand name',{exact:true}).inputValue(),'');assert.equal(await save.isDisabled(),true);}finally{releaseRead();await page.unrouteAll({behavior:'wait'});}
 }

 console.log('Voice Guard actual HTTP API PASS: optional strict configured limits, immutable v1/v2 pins, located static-3 findings, stale rule-set approval blocked, foreign and role/key writes denied. No provider/model/rewrite/send calls. Chromium controls, loading fence, invalid/offline/repeated/lost acknowledgment saves, immutable reload/unset pins, located editor findings, mobile and workspace interruption PASS when browser enabled.');
}finally{await browser?.close();for(const table of['campaigns','preflights','revisions','emails','outbox','api_rate_events','api_keys','idempotency','audit_events','memberships','brands'])await db.query(`DELETE FROM ${table} WHERE workspace_id=ANY($1::uuid[])`,[[workspace,other]]);await db.query('DELETE FROM auth_sessions WHERE user_id=$1',[user]);await db.query('DELETE FROM workspaces WHERE id=ANY($1::uuid[])',[[workspace,other]]);await db.end();}
