import assert from 'node:assert/strict';
import { randomUUID, randomBytes } from 'node:crypto';
import pg from 'pg';
import env from '@next/env';
import { digest } from '../src/server/audit';
import { chromium } from 'playwright';
env.loadEnvConfig(process.cwd());
const origin = process.env.APP_ORIGIN ?? 'http://127.0.0.1:3000';
if (process.env.LOCAL_DEVELOPMENT !== 'true' || !['127.0.0.1', 'localhost'].includes(new URL(origin).hostname)) throw new Error('Local derivation fixtures only');
const db = new pg.Pool({ connectionString: process.env.MIGRATION_DATABASE_URL }), w = randomUUID(), other = randomUUID(), user = 'derive-http-' + randomUUID(), cookie = randomBytes(32).toString('hex');
let browser: Awaited<ReturnType<typeof chromium.launch>> | undefined;
async function call(path: string, method = 'GET', body?: unknown, key = randomUUID(), version?: number, workspace = w) {
  const r = await fetch(origin + '/v1/' + path, { method, headers: { Cookie: 'mailcraft_local_session=' + cookie, 'X-Workspace-Id': workspace, Origin: origin, 'Content-Type': 'application/json', 'Idempotency-Key': key, ...(version ? { 'If-Match': String(version) } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) });
  return { r, j: await r.json() };
}
try {
  await db.query('INSERT INTO workspaces(id,name)VALUES($1,$3),($2,$3)', [w, other, 'Derivation HTTP fixture']);
  await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$3,'Owner'),($2,$3,'Owner')", [w, other, user]);
  await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,now()+interval '1 hour')", [digest(cookie), user]);
  await call('brands', 'POST', { name: 'Fixture', website: 'https://example.org', description: 'Fixture', voice: 'Clear', accent: '#0B625D', background: '#F7F6F2', font_stack: 'Arial, sans-serif', address: 'Fixture address', forbidden_phrases: [], approved_claims: [], provenance: [] });
  const parent = (await call('emails', 'POST', { title: 'Lineage parent fixture' })).j.email;
  const source = (await call(`emails/${parent.id}/revisions`, 'POST', {}, randomUUID(), 1)).j.revision;
  const key = randomUUID(), body = { title: 'Remixed fixture' };
  const remix = await call(`email-revisions/${source.id}/remix`, 'POST', body, key);
  assert.equal(remix.r.status, 201);
  assert.deepEqual(remix.j.email.spec, parent.spec);
  assert.equal(remix.j.lineage.source_revision_id, source.id);
  assert.equal((await call(`email-revisions/${source.id}/remix`, 'POST', body, key)).j.email.id, remix.j.email.id);
  assert.equal((await call(`email-revisions/${source.id}/remix`, 'POST', { title: 'Changed intent' }, key)).r.status, 409);
  assert.equal((await call(`email-revisions/${source.id}/remix`)).r.status, 405);
  assert.equal((await call(`email-revisions/${source.id}/remix`, 'POST', body, randomUUID(), undefined, other)).r.status, 404);
  assert.equal((await call(`email-revisions/${source.id}/localize`, 'POST', { title: 'Unknown', locale: 'xx-ZZ' })).r.status, 422);
  const arabic = await call(`email-revisions/${source.id}/localize`, 'POST', { title: 'Arabic locale fixture', locale: 'ar-SA' });
  assert.equal(arabic.r.status, 201);
  assert.equal(arabic.j.email.spec.direction, 'rtl');
  assert.deepEqual(arabic.j.email.spec.sections, parent.spec.sections);
  assert.equal(arabic.j.lineage.translation_status, 'manual_review_required');
  const childCopy = structuredClone(arabic.j.email.spec);
  assert.equal((await call(`emails/${arabic.j.email.id}/draft`, 'PATCH', { spec: { ...childCopy, locale: 'fr-FR' } }, randomUUID(), 1)).r.status, 409);
  await call(`emails/${parent.id}/draft`, 'PATCH', { spec: { ...parent.spec, subject: 'Changed source' } }, randomUUID(), 1);
  const stale = (await call(`emails/${arabic.j.email.id}`)).j.email;
  assert.equal(stale.lineage.source_status, 'outdated'); assert.deepEqual(stale.spec, childCopy);
  const first = await call(`emails/${parent.id}/derivatives?limit=1`);
  assert.equal(first.r.status, 200); assert.equal(first.j.total_count, 2); assert.equal(first.j.has_more, true);
  const next = await call(`emails/${parent.id}/derivatives?limit=1&after=${encodeURIComponent(first.j.next_cursor)}`);
  assert.equal(next.j.data.length, 1); assert.notEqual(next.j.data[0].id, first.j.data[0].id);
  assert.equal((await call(`emails/${remix.j.email.id}/derivatives?after=${encodeURIComponent(first.j.next_cursor)}`)).r.status, 400);
  for (const role of ['Viewer', 'Billing']) {
    await db.query('UPDATE memberships SET role=$1 WHERE workspace_id=$2 AND user_id=$3', [role, w, user]);
    assert.equal((await call(`email-revisions/${source.id}/remix`, 'POST', body)).r.status, 403);
    assert.equal((await call(`email-revisions/${source.id}/localize`, 'POST', { title: 'Denied locale', locale: 'fr-FR' })).r.status, 403);
  }
  await db.query("UPDATE memberships SET role='Owner' WHERE workspace_id=$1 AND user_id=$2", [w, user]);
  browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
  await context.addInitScript((workspace) => localStorage.setItem('mailcraft.workspace', workspace), w);
  await context.addCookies([{ name: 'mailcraft_local_session', value: cookie, url: origin, sameSite: 'Strict' }]);
  const page = await context.newPage();
  await page.goto(origin + '/app/emails/' + parent.id);
  const panel = page.locator('.derived-panel');
  await panel.getByRole('heading', { name: 'Remixes and language drafts' }).waitFor();
  await panel.getByLabel('New draft title').fill('French browser draft');
  await panel.getByLabel('Target language').selectOption('fr-FR');
  await context.setOffline(true);
  await panel.getByRole('button', { name: 'Create locale draft', exact: true }).click();
  await page.getByRole('alert').filter({ hasText: /offline|save|network|fetch|Failed|acknowledge/i }).first().waitFor();
  assert.equal(await panel.getByLabel('New draft title').inputValue(), 'French browser draft');
  assert.equal(await panel.getByLabel('Target language').inputValue(), 'fr-FR');
  await context.setOffline(false);
  let requests = 0;
  page.on('request', (r) => { if (r.method() === 'POST' && new URL(r.url()).pathname.endsWith('/localize')) requests++; });
  await panel.getByRole('button', { name: 'Create locale draft', exact: true }).evaluate((el) => { (el as HTMLButtonElement).click(); (el as HTMLButtonElement).click(); });
  await page.getByRole('heading', { name: 'French browser draft', exact: true }).waitFor();
  assert.equal(requests, 1);
  await page.locator('.derived-panel').getByText(/translation and language review are still required/).waitFor();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  const frenchId = new URL(page.url()).pathname.split('/').at(-1)!;
  const sourceNow = (await call('emails/' + parent.id)).j.email;
  await call(`emails/${parent.id}/draft`, 'PATCH', { spec: { ...sourceNow.spec, subject: 'Later parent edit' } }, randomUUID(), sourceNow.doc_version);
  if (!process.argv.includes('--review-reload')) {
    await page.getByLabel('Subject', { exact: true }).fill('Local child edits after parent drift');
    await page.getByRole('button', { name: 'Save', exact: true }).click();
    await page.getByRole('status').filter({ hasText: 'Saved' }).waitFor();
    await page.locator('.derived-panel').getByText(/Source changed\. This draft remains intact/).waitFor({ timeout: 5000 });
    // A stale offline backup must retain its spec, but not replace fresh server lineage.
    const savedChild = (await call('emails/' + frenchId)).j.email;
    await page.evaluate(({ workspace, child }) => localStorage.setItem('mailcraft.draft.' + workspace + '.' + child.id, JSON.stringify({ ...child, spec: { ...child.spec, subject: 'Recovered child edits' }, lineage: { ...child.lineage, source_status: 'current' } })), { workspace: w, child: savedChild });
    await page.reload();
    await page.getByLabel('Subject', { exact: true }).filter({ visible: true }).waitFor();
    assert.equal(await page.getByLabel('Subject', { exact: true }).inputValue(), 'Recovered child edits');
    await page.locator('.derived-panel').getByText(/Source changed\. This draft remains intact/).waitFor({ timeout: 5000 });
  }
  await page.reload();
  await page.locator('.derived-panel').getByText(/Source changed\. This draft remains intact/).waitFor();
  if (process.argv.includes('--review-reload')) assert.equal((await call('emails/' + frenchId)).j.email.spec.subject, 'Changed source');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Saved' }).waitFor();
  await page.locator('iframe[title="Email browser simulation"]').scrollIntoViewIfNeeded();
  await page.frameLocator('iframe[title="Email browser simulation"]').getByText('Your next story starts here', { exact: true }).waitFor();
  await page.evaluate(() => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => resolve(true)))));
  await page.screenshot({ path: 'output/playwright/lettercape-source-lineage-mobile.png', fullPage: true });
  await page.locator('.derived-panel a').filter({ hasText: 'Lineage parent fixture' }).click();
  await page.getByRole('heading', { name: 'Lineage parent fixture', exact: true }).waitFor();
  await page.locator('.derived-panel').getByRole('link', { name: 'French browser draft', exact: true }).waitFor();
  await page.locator('.derived-panel').getByLabel('New draft title').fill('Lost remix fixture');
  let lostOnce = true;
  await page.route('**/remix', async (route) => {
    if (!lostOnce) return route.continue();
    lostOnce = false;
    await route.fetch(); // authoritative child exists, acknowledgment is lost
    await route.abort('failed');
  });
  await page.getByRole('button', { name: 'Create remix', exact: true }).click();
  await page.getByRole('alert').filter({ hasText: /acknowledge|fetch|Failed|network/i }).waitFor();
  assert.equal(await page.getByLabel('New draft title').inputValue(), 'Lost remix fixture');
  await page.reload();
  await page.getByRole('heading', { name: 'Lineage parent fixture', exact: true }).waitFor();
  await page.getByLabel('New draft title').fill('Lost remix fixture');
  await page.getByRole('button', { name: 'Create remix', exact: true }).click();
  await page.getByRole('heading', { name: 'Lost remix fixture', exact: true }).waitFor();
  assert.equal(Number((await db.query('SELECT count(*) FROM emails WHERE workspace_id=$1 AND title=$2', [w, 'Lost remix fixture'])).rows[0].count), 1, 'retry must retain the frozen source and command identity after acknowledgment loss');
  await page.unroute('**/remix');
  await page.locator('.derived-panel a').filter({ hasText: 'Lineage parent fixture' }).click();
  await page.getByRole('heading', { name: 'Lineage parent fixture', exact: true }).waitFor();
  await page.getByLabel('New draft title').fill('Delayed remix fixture');
  let entered!: () => void, release!: () => void;
  const ready = new Promise<void>((resolve) => { entered = resolve; }), gate = new Promise<void>((resolve) => { release = resolve; });
  await page.route('**/remix', async (route) => { const response = await route.fetch(); entered(); await gate; await route.fulfill({ response }); });
  await page.getByRole('button', { name: 'Create remix', exact: true }).click();
  await ready;
  await page.getByLabel('Subject', { exact: true }).fill('Updated during derived request');
  release();
  await page.getByRole('alert').filter({ hasText: /source changed while the new draft/ }).waitFor();
  assert.equal(new URL(page.url()).pathname, '/app/emails/' + parent.id);
  assert.equal(await page.getByLabel('Subject', { exact: true }).inputValue(), 'Updated during derived request');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Saved' }).waitFor();
  assert.equal((await call('emails/' + parent.id)).j.email.spec.subject, 'Updated during derived request');
  assert.equal(Number((await db.query('SELECT count(*) FROM emails WHERE workspace_id=$1 AND title=$2', [w, 'Delayed remix fixture'])).rows[0].count), 1);
  await page.unroute('**/remix');
  await page.getByLabel('New draft title').fill('Workspace-fenced remix fixture');
  let enteredSwitch!: () => void, releaseSwitch!: () => void, fulfilledSwitch!: () => void;
  const readySwitch = new Promise<void>((resolve) => { enteredSwitch = resolve; }), gateSwitch = new Promise<void>((resolve) => { releaseSwitch = resolve; }), finishedSwitch = new Promise<void>((resolve) => { fulfilledSwitch = resolve; });
  await page.route('**/remix', async (route) => { const response = await route.fetch(); enteredSwitch(); await gateSwitch; await route.fulfill({ response }); fulfilledSwitch(); });
  await page.getByRole('button', { name: 'Create remix', exact: true }).click();
  await readySwitch;
  await page.getByRole('button', { name: 'Open navigation' }).click();
  await page.getByLabel('Active brand workspace').selectOption(other);
  await page.getByRole('heading', { name: 'Make something worth opening.', exact: true }).waitFor();
  releaseSwitch(); await finishedSwitch;
  await page.evaluate(() => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => resolve(true)))));
  assert.equal(await page.getByLabel('Active brand workspace').inputValue(), other);
  assert.ok(await page.getByRole('heading', { name: 'Make something worth opening.', exact: true }).isVisible());
  console.log('Frozen remix/locale lineage, replay/mismatch, source drift, locale identity, foreign role/tenant and signed paging pass; translation calls zero.');
} finally {
  await browser?.close();
  for (const table of ['email_lineage', 'render_downloads', 'idempotency', 'audit_events', 'revisions', 'emails', 'brands', 'memberships']) await db.query(`DELETE FROM ${table} WHERE workspace_id=ANY($1::uuid[])`, [[w, other]]);
  await db.query('DELETE FROM auth_sessions WHERE user_id=$1', [user]);
  await db.query('DELETE FROM workspaces WHERE id=ANY($1::uuid[])', [[w, other]]);
  await db.end();
}
