import assert from'node:assert/strict';import{randomUUID,randomBytes}from'node:crypto';import pg from'pg';import env from'@next/env';import{digest}from'../src/server/audit';
env.loadEnvConfig(process.cwd());const origin=process.env.APP_ORIGIN??'http://127.0.0.1:3000';if(process.env.LOCAL_DEVELOPMENT!=='true'||!['127.0.0.1','localhost'].includes(new URL(origin).hostname))throw Error('Owned local UTM fixtures only');
const db=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL}),w=randomUUID(),other=randomUUID(),user='utm-'+randomUUID(),cookie=randomBytes(32).toString('hex'),tracking={utm_source:'newsletter',utm_medium:'email',utm_campaign:'été 日本 & sale'};
async function call(path:string,method='GET',body?:unknown,version?:number,workspace=w){const response=await fetch(origin+'/v1/'+path,{method,headers:{Cookie:'mailcraft_local_session='+cookie,'X-Workspace-Id':workspace,Origin:origin,'Content-Type':'application/json','Idempotency-Key':randomUUID(),...(version?{'If-Match':String(version)}:{})},body:body===undefined?undefined:JSON.stringify(body)});const result=await response.json();return{response,result};}
async function download(id:string,format='html',workspace=w){return fetch(origin+'/v1/email-revisions/'+id+'/download?format='+format,{headers:{Cookie:'mailcraft_local_session='+cookie,'X-Workspace-Id':workspace}});}
try{
 await db.query('INSERT INTO workspaces(id,name)VALUES($1,$3),($2,$3)',[w,other,'UTM owned fixture']);await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$3,'Owner'),($2,$3,'Owner')",[w,other,user]);await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,now()+interval '1 hour')",[digest(cookie),user]);
 const brand=await call('brands','POST',{name:'Fixture',website:'https://example.org',description:'Fixture',voice:'Clear',accent:'#0B625D',background:'#F7F6F2',font_stack:'Arial, sans-serif',address:'Fixture address',forbidden_phrases:[],approved_claims:[],provenance:[]});assert.equal(brand.response.status,201);
 const initial=await call('emails','POST',{title:'UTM frozen fixture'});assert.equal(initial.response.status,200);const email=initial.result.email;assert.equal(email.spec.tracking,undefined);
 const original=await call('emails/'+email.id+'/revisions','POST',{},1);assert.equal(original.response.status,200);const old=original.result.revision;
 const oldHtml=await(await download(old.id)).text(),oldText=await(await download(old.id,'txt')).text();const campaign=await call('campaigns','POST',{name:'Original pin',revision_id:old.id});assert.equal(campaign.response.status,200);const pin=(await db.query('SELECT * FROM campaigns WHERE workspace_id=$1',[w])).rows[0];
 const spec={...email.spec,tracking};const save=await call('emails/'+email.id+'/draft','PATCH',{spec},1);assert.equal(save.response.status,200,'explicit tracking policy must be accepted');assert.deepEqual(save.result.email.spec.tracking,tracking);assert.deepEqual(save.result.email.spec.sections,email.spec.sections);
 const preview=await call('emails/'+email.id+'/preview','POST',{spec});assert.equal(preview.response.status,200);assert.equal(preview.result.artifact.manifest.link_policy,'utm-explicit-1');assert.ok(preview.result.artifact.html.includes('utm_source=newsletter'));assert.ok(preview.result.artifact.text.includes('utm_source=newsletter'));
 const tracked=await call('emails/'+email.id+'/revisions','POST',{},2);assert.equal(tracked.response.status,200);const revision=tracked.result.revision;assert.notEqual(revision.artifact_hash,old.artifact_hash);assert.deepEqual(revision.spec.sections,email.spec.sections);assert.deepEqual(revision.spec.tracking,tracking);
 const frozen=await download(revision.id);assert.equal(frozen.headers.get('x-artifact-hash'),revision.artifact_hash);assert.equal(await frozen.text(),revision.html);assert.equal(await(await download(revision.id,'txt')).text(),revision.plaintext);assert.equal(await(await download(old.id)).text(),oldHtml);assert.equal(await(await download(old.id,'txt')).text(),oldText);assert.deepEqual((await db.query('SELECT * FROM campaigns WHERE id=$1',[pin.id])).rows[0],pin);
 for(const bad of[{...tracking,utm_term:'hidden'},{...tracking,utm_campaign:'\n'},{...tracking,utm_source:'x'.repeat(129)}])assert.equal((await call('emails/'+email.id+'/draft','PATCH',{spec:{...spec,tracking:bad}},2)).response.status,422);
 const conflict={...spec,sections:[{id:'bad',type:'button',label:'Conflict',href:'https://example.com/?utm_source=other'}]};const refused=await call('emails/'+email.id+'/draft','PATCH',{spec:conflict},2);assert.equal(refused.response.status,422);assert.ok(refused.result.error.details.some((d:{path:string[]})=>d.path.includes('tracking')));assert.equal((await call('emails/'+email.id)).result.email.doc_version,2);
 const raw={...spec,editing_mode:'raw_html',raw_html:'<p>Raw <a href="https://example.org/raw?x=a%20b&amp;flag=#part">Offer</a></p><img src="https://example.org/image?x=1" /><a href="{{UNSUBSCRIBE_URL}}">Exit</a>'};const rawPreview=await call('emails/'+email.id+'/preview','POST',{spec:raw});assert.equal(rawPreview.response.status,200);assert.ok(rawPreview.result.artifact.html.includes('x=a%20b&amp;flag=&amp;utm_source=newsletter'));assert.ok(rawPreview.result.artifact.text.includes('https://example.org/raw?x=a%20b&flag=&utm_source=newsletter'));assert.ok(!rawPreview.result.artifact.html.includes('image?x=1&amp;utm_'));
 assert.equal((await call('emails/'+email.id+'/preview','POST',{spec:{...raw,raw_html:'<a href="https://example.org/{{PRODUCT}}">Unsupported</a>'}})).response.status,422);
 assert.equal((await call('emails/'+email.id,'GET',undefined,undefined,other)).response.status,404);assert.equal((await download(revision.id,'html',other)).status,404);
 await db.query("UPDATE memberships SET role='Viewer' WHERE workspace_id=$1 AND user_id=$2",[w,user]);assert.equal((await call('emails/'+email.id+'/draft','PATCH',{spec:email.spec},2)).response.status,403);assert.equal((await call('emails/'+email.id+'/revisions','POST',{},2)).response.status,403);assert.equal((await download(revision.id)).status,403);await db.query("UPDATE memberships SET role='Owner' WHERE workspace_id=$1 AND user_id=$2",[w,user]);
 const remix=await call('email-revisions/'+revision.id+'/remix','POST',{title:'Explicit tracked remix'});assert.equal(remix.response.status,201);assert.deepEqual(remix.result.email.spec.tracking,tracking);assert.equal(remix.result.revision.artifact_hash,revision.artifact_hash);
 const restored=await call('emails/'+email.id+'/restore','POST',{revision_id:old.id},2);assert.equal(restored.response.status,200);assert.equal(restored.result.email.spec.tracking,undefined);assert.equal((await call('emails/'+email.id+'/preview','POST',{spec:restored.result.email.spec})).result.artifact.hash,old.artifact_hash);assert.equal(await(await download(revision.id)).text(),revision.html);assert.deepEqual((await db.query('SELECT * FROM campaigns WHERE id=$1',[pin.id])).rows[0],pin);
 if(process.argv.includes('--review-missing')){const missing={...email.spec,tracking,editing_mode:'raw_html'};const denied=await call('emails/'+email.id+'/draft','PATCH',{spec:missing},3);assert.equal(denied.response.status,422);assert.ok(denied.result.error.details.some((d:{path:string[]})=>d.path.includes('raw_html')));assert.equal((await call('emails/'+email.id)).result.email.doc_version,3);console.log('Owned missing raw source semantic422/no version advance PASS.');}
 if(process.argv.includes('--review-raw')){const raw={...email.spec,tracking,editing_mode:'raw_html',raw_html:'<p><a href="https://example.org">one<p>two</a>'};const created=await call('emails','POST',{title:'Reconstructed raw owned fixture',spec:raw});assert.equal(created.response.status,200);const preview=await call('emails/'+created.result.email.id+'/preview','POST',{spec:created.result.email.spec});assert.equal(preview.response.status,200);const checkpoint=await call('emails/'+created.result.email.id+'/revisions','POST',{},1);assert.equal(checkpoint.response.status,200);assert.equal(checkpoint.result.revision.artifact_hash,preview.result.artifact.hash);assert.ok(checkpoint.result.revision.html.includes('utm_source=newsletter'));console.log('Owned reconstructed raw create/preview/checkpoint/hash PASS.');}
 if(process.argv.includes('--review-url')){for(const href of['https:example.com/offer','https:/example.com/offer','https:'+String.fromCharCode(92)+'example.com/offer']){const spec={...email.spec,tracking,sections:[{id:'b',type:'button',label:'Link',href}]};assert.equal((await call('emails/'+email.id+'/draft','PATCH',{spec},3)).response.status,422);assert.equal((await call('emails/'+email.id)).result.email.doc_version,3);}console.log('Owned abbreviated HTTPS semantic422/no destination/version mutation PASS.');}
 if(process.argv.includes('--review-proposal')||process.argv.includes('--review-working')||process.argv.includes('--review-links')){const{runUTMReviewBrowser}=await import('./utm-review-browser');await runUTMReviewBrowser({origin,workspace:w,other,cookie,user,email:email.id,db,mode:process.argv.includes('--review-proposal')?'proposal':process.argv.includes('--review-links')?'links':'working'});}
 if(process.argv.includes('--browser')){const{runUTMBrowser}=await import('./utm-browser');await runUTMBrowser({origin,workspace:w,other,cookie,user,email:email.id,db});}
 console.log('Owned UTM HTTP PASS: explicit strict policy, immutable source/frozen HTML+text/hash/campaign pin, semantic422/no version advance, raw query/entity/slot preservation, tenant/Viewer denial, tracked remix and defaultoff restore; zero provider/collector/send calls.');
}finally{for(const table of['campaign_revisions','campaigns','email_lineage','render_downloads','idempotency','audit_events','revisions','emails','brands','api_rate_events','memberships'])await db.query('DELETE FROM '+table+' WHERE workspace_id=ANY($1::uuid[])',[[w,other]]);await db.query('DELETE FROM auth_sessions WHERE user_id=$1',[user]);await db.query('DELETE FROM workspaces WHERE id=ANY($1::uuid[])',[[w,other]]);await db.end();}
