import assert from'node:assert/strict';import{randomBytes,randomUUID,createHash}from'node:crypto';import{spawn,type ChildProcess}from'node:child_process';import{open,readFile}from'node:fs/promises';import{chromium}from'playwright';
import{sourceDatabase}from'./smoke-source-truth';import{blankSpec}from'../src/domain/email';import{createEmail,checkpoint}from'../src/server/emails';import{digest}from'../src/server/audit';
const origin='http://127.0.0.1:3004';
await sourceDatabase(async({db,p,brand,tx})=>{
 const spec=blankSpec(brand,'Owned ESP fixture');spec.subject='Owned frozen subject';spec.sections=spec.sections.map(b=>b.type==='button'?{...b,href:'https://example.org/offer'}:b.type==='legal_footer'?{...b,address:'123 Fixture Road'}:b);
 const email=await tx(c=>createEmail(c,p,'Owned Mailchimp preparation',spec)),frozen=await tx(c=>checkpoint(c,p,email.id,1));
 const other=await tx(c=>createEmail(c,p,'Owned empty preparation',{...spec,subject:'Other subject'}));
 const cookie=randomBytes(32).toString('hex'),viewer='esp-viewer-'+randomUUID(),viewerCookie=randomBytes(32).toString('hex');
 await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,'Viewer')",[p.workspace,viewer]);
 for(const [actor,value]of[[p.user,cookie],[viewer,viewerCookie]])await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,clock_timestamp()+interval '1 hour')",[digest(value),actor]);
 const runtime=new URL(process.env.DATABASE_URL!);runtime.pathname=new URL(db.options.connectionString!).pathname;assert.match(runtime.pathname,/^\/creation_fixture_[a-f0-9]{32}$/);
 const log=await open('/tmp/lettercape-esp-app.log','w');let app:ChildProcess|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
 try{
  app=spawn(process.execPath,['node_modules/next/dist/bin/next','dev','--hostname','127.0.0.1','--port','3004'],{env:{PATH:process.env.PATH,NODE_ENV:'development',LOCAL_DEVELOPMENT:'true',APP_ORIGIN:origin,DATABASE_URL:runtime.toString(),MIGRATION_DATABASE_URL:db.options.connectionString!,PREFERENCE_SIGNING_SECRET:randomBytes(32).toString('hex'),NEXT_TELEMETRY_DISABLED:'1'},stdio:['ignore',log.fd,log.fd]});
  for(let n=0;n<120;n++){if(app.exitCode!==null)throw Error('Owned ESP app exited');try{if((await fetch(origin)).ok)break;}catch{}if(n===119)throw Error('Owned ESP app unavailable');await new Promise(r=>setTimeout(r,250));}
  browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);await context.addInitScript(w=>{if(top===window)localStorage.setItem('mailcraft.workspace',w);},p.workspace);
  let external=0;await context.route(url=>url.origin!==origin&&url.protocol!=='blob:'&&url.protocol!=='data:',r=>{external++;return r.abort();});const page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  const headers={'X-Workspace-Id':p.workspace,'X-Actor-Id':p.user},endpoint=origin+'/v1/email-revisions/'+frozen.id+'/destination-review?destination=mailchimp';
  const before=(await db.query('SELECT html,plaintext,artifact_hash,spec,manifest FROM revisions WHERE id=$1',[frozen.id])).rows[0];
  const reviewResponse=await context.request.get(endpoint,{headers});assert.equal(reviewResponse.status(),200);const review=(await reviewResponse.json()).review;assert.equal(review.remote_export_enabled,false);assert.equal(review.source_artifact_hash,frozen.artifact_hash);assert.equal(review.blockers.length,7);
  for(const format of ['html','txt']){const r=await context.request.get(origin+'/v1/email-revisions/'+frozen.id+'/destination-artifact?destination=mailchimp&format='+format,{headers});assert.equal(r.status(),200);const body=await r.body();assert.equal(createHash('sha256').update(body).digest('hex'),format==='html'?review.html_sha256:review.text_sha256);assert.ok(body.toString().includes('*|UNSUB|*'));assert.ok(!body.toString().includes('{{UNSUBSCRIBE_URL}}'));assert.equal(r.headers()['x-remote-export-enabled'],'false');assert.equal(r.headers()['cache-control'],'no-store');}
  assert.deepEqual((await db.query('SELECT html,plaintext,artifact_hash,spec,manifest FROM revisions WHERE id=$1',[frozen.id])).rows[0],before);
  assert.equal((await context.request.post(endpoint,{headers:{...headers,Origin:origin},data:{}})).status(),405);
  for(const suffix of ['&destination=mailchimp','&unexpected=x','&format=html'])assert.equal((await context.request.get(endpoint+suffix,{headers})).status(),422);
  assert.equal((await context.request.get(endpoint.replace('mailchimp','brevo'),{headers})).status(),422);
  assert.equal((await context.request.get(endpoint,{headers:{...headers,'X-Actor-Id':viewer}})).status(),409);
  assert.equal((await context.request.get(endpoint,{headers:{...headers,'X-Workspace-Id':randomUUID()}})).status(),404);
  // Real scoped bearer grants are fixture-only and never leave the loopback app.
  for(const scopes of [['emails:read'],['emails:export']]){const token='lc_'+randomBytes(32).toString('hex');await db.query("INSERT INTO api_keys(workspace_id,id,key_hash,name,scopes,created_by,expires_at)VALUES($1,$2,$3,'fixture',$4,$5,clock_timestamp()+interval '1 hour')",[p.workspace,randomUUID(),digest(token),JSON.stringify(scopes),p.user]);assert.equal((await context.request.get(endpoint,{headers:{Authorization:'Bearer '+token}})).status(),scopes[0]==='emails:export'?200:403);}
  const blockedSpec={...spec,sections:spec.sections.map(b=>b.type==='legal_footer'?{...b,address:''}:b)},blocked=await tx(c=>createEmail(c,p,'Owned missing footer',blockedSpec)),blockedRevision=await tx(c=>checkpoint(c,p,blocked.id,1));assert.equal((await context.request.get(endpoint.replace(frozen.id,blockedRevision.id),{headers})).status(),409);
  assert.equal((await db.query('SELECT count(*)::int n FROM operations')).rows[0].n,0);console.log('Actual current-authority/scope/foreign workspace/method/query refusal; immutable native HTML/text hashes and zero remote operations PASS.');
  await page.goto(origin+'/app/emails/'+email.id);await page.getByRole('textbox',{name:'Subject',exact:true}).waitFor();await page.getByLabel('ESP destination').selectOption('mailchimp');const panel=page.getByRole('region',{name:'Mailchimp preparation'});await panel.waitFor();assert.equal(await panel.getByRole('status').count(),0);
  const revisionCount=Number((await db.query('SELECT count(*) n FROM revisions WHERE email_id=$1',[email.id])).rows[0].n);
  await panel.getByRole('button',{name:'Review Mailchimp preparation',exact:true}).evaluate((b:HTMLButtonElement)=>{b.click();b.click();});await panel.getByRole('status').waitFor();assert.equal(Number((await db.query('SELECT count(*) n FROM revisions WHERE email_id=$1',[email.id])).rows[0].n),revisionCount+1);
  const downloadPromise=page.waitForEvent('download');await panel.getByRole('button',{name:'Download Mailchimp HTML',exact:true}).click();const download=await downloadPromise;const path=await download.path();assert.ok(path);const downloaded=await readFile(path);assert.ok(downloaded.toString().includes('*|UNSUB|*'));assert.equal(await download.failure(),null);
  console.log('Actual editor freeze/double-click admission/native mapped download and honest missing-provider evidence PASS.');
  await page.route('**/destination-review?destination=mailchimp',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'FIXTURE_UNAVAILABLE',message:'Owned destination temporarily unavailable'}})}));await panel.getByRole('button',{name:'Refresh Mailchimp preparation',exact:true}).click();await page.getByRole('alert').filter({hasText:'Owned destination temporarily unavailable'}).waitFor();assert.equal(await panel.getByRole('status').count(),0);await page.unroute('**/destination-review?destination=mailchimp');
  await panel.getByRole('button',{name:'Review Mailchimp preparation',exact:true}).click();await panel.getByRole('status').waitFor();
  let release!:()=>void;const held=new Promise<void>(r=>release=r);let arrived!:()=>void;const fetched=new Promise<void>(r=>arrived=r);await page.route('**/destination-review?destination=mailchimp',async route=>{const response=await route.fetch();arrived();await held;try{await route.fulfill({response});}catch{}});await panel.getByRole('button',{name:'Refresh Mailchimp preparation',exact:true}).click();await fetched;await page.getByRole('textbox',{name:'Subject',exact:true}).fill('Newer local subject');release();await page.unroute('**/destination-review?destination=mailchimp');await panel.getByRole('button',{name:'Review Mailchimp preparation',exact:true}).waitFor();assert.equal(await panel.getByRole('status').count(),0);assert.equal(await page.getByRole('textbox',{name:'Subject',exact:true}).inputValue(),'Newer local subject');
  await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('status').filter({hasText:'Saved · v2'}).waitFor();await panel.getByRole('button',{name:'Review Mailchimp preparation',exact:true}).click();await panel.getByRole('status').waitFor();
  let releaseDownload!:()=>void;const heldDownload=new Promise<void>(r=>releaseDownload=r);let arriveDownload!:()=>void;const fetchedDownload=new Promise<void>(r=>arriveDownload=r);let staleDownloads=0;page.on('download',()=>staleDownloads++);
  await page.route('**/destination-artifact?destination=mailchimp&format=html',async route=>{const response=await route.fetch();arriveDownload();await heldDownload;try{await route.fulfill({response});}catch{}});await panel.getByRole('button',{name:'Download Mailchimp HTML',exact:true}).click();await fetchedDownload;await page.goto(origin+'/app/emails/'+other.id);releaseDownload();await page.unroute('**/destination-artifact?destination=mailchimp&format=html');await page.getByRole('textbox',{name:'Subject',exact:true}).waitFor();assert.equal(staleDownloads,0);await page.getByLabel('ESP destination').selectOption('mailchimp');assert.equal(await panel.getByRole('status').count(),0);
  console.log('Actual error/retry/local-edit result fence and held-download navigation prevent stale adoption PASS.');
  // Cancel the selection interval before a review controller exists, while the
  // first real checkpoint response is held. Returning to the same destination
  // must neither dispatch/adopt that review nor revive its checkpoint failure.
  for(const failCheckpoint of [false,true]){
   const freshEmail=await tx(c=>createEmail(c,p,'Owned initial-freeze cancellation',spec));
   await page.goto(origin+'/app/emails/'+freshEmail.id);await page.getByRole('textbox',{name:'Subject',exact:true}).waitFor();await page.getByLabel('ESP destination').selectOption('mailchimp');
   assert.equal((await db.query('SELECT count(*)::int n FROM revisions WHERE email_id=$1',[freshEmail.id])).rows[0].n,0);assert.equal(await panel.getByRole('status').count(),0);
   let releaseFreeze!:()=>void,arriveFreeze!:()=>void,staleReviews=0;
   const heldFreeze=new Promise<void>(r=>releaseFreeze=r),fetchedFreeze=new Promise<void>(r=>arriveFreeze=r),checkpointRoute='**/emails/'+freshEmail.id+'/revisions';
   const countReview=(request:import('playwright').Request)=>{if(request.url().includes('/destination-review?destination=mailchimp'))staleReviews++;};page.on('request',countReview);
   await page.route(checkpointRoute,async route=>{const response=await route.fetch();assert.equal(response.status(),200);arriveFreeze();await heldFreeze;await route.fulfill(failCheckpoint?{status:503,contentType:'application/json',body:JSON.stringify({error:{code:'FIXTURE_FREEZE_UNAVAILABLE',message:'Owned stale checkpoint failure'}})}:{response});});
   try{
    await panel.getByRole('button',{name:'Review Mailchimp preparation',exact:true}).click();await fetchedFreeze;
    await page.getByLabel('ESP destination').selectOption('klaviyo');await page.getByLabel('ESP destination').selectOption('mailchimp');releaseFreeze();
    await page.waitForFunction(()=>{const b=document.querySelector<HTMLButtonElement>('section[aria-label="Mailchimp preparation"] button');return b&&!b.disabled;});
    assert.equal(staleReviews,0,'Cancelled initial freeze must issue zero stale destination reviews');assert.equal(await panel.getByRole('status').count(),0,'Cancelled initial freeze must adopt zero preparations');assert.equal(await page.getByRole('alert').filter({hasText:'Owned stale checkpoint failure'}).count(),0,'Cancelled initial freeze must adopt zero stale errors');
    assert.equal((await db.query('SELECT count(*)::int n FROM revisions WHERE email_id=$1',[freshEmail.id])).rows[0].n,1,'Completed immutable checkpoint remains in history');
   }finally{releaseFreeze();await page.unroute(checkpointRoute);page.off('request',countReview);}
   let freshCheckpoints=0;const countFreshCheckpoint=(request:import('playwright').Request)=>{if(request.method()==='POST'&&new URL(request.url()).pathname==='/v1/emails/'+freshEmail.id+'/revisions')freshCheckpoints++;};page.on('request',countFreshCheckpoint);
   try{await panel.getByRole('button',{name:'Review Mailchimp preparation',exact:true}).click();await panel.getByRole('status').waitFor();assert.equal(freshCheckpoints,failCheckpoint?1:0,'Fresh explicit review reuses an acknowledged freeze or replays the unacknowledged checkpoint');}finally{page.off('request',countFreshCheckpoint);}
   assert.equal((await db.query('SELECT count(*)::int n FROM revisions WHERE email_id=$1',[freshEmail.id])).rows[0].n,1,'Acknowledged reuse and idempotent checkpoint replay preserve the same completed history');
  }
  console.log('Actual initial-freeze destination round trips suppress stale review dispatch/adoption/errors, preserve history and allow fresh explicit review PASS.');
  await page.goto(origin+'/app/emails/'+other.id);await page.getByRole('textbox',{name:'Subject',exact:true}).waitFor();await page.getByLabel('ESP destination').selectOption('mailchimp');
  // A provider selection is a new async-result scope, independent of editor content.
  await panel.getByRole('button',{name:'Review Mailchimp preparation',exact:true}).click();await panel.getByRole('status').waitFor();
  let releaseSelection!:()=>void;const holdSelection=new Promise<void>(r=>releaseSelection=r);let arriveSelection!:()=>void;const fetchedSelection=new Promise<void>(r=>arriveSelection=r);
  await page.route('**/destination-review?destination=mailchimp',async route=>{const response=await route.fetch();arriveSelection();await holdSelection;try{await route.fulfill({response});}catch{}});
  await panel.getByRole('button',{name:'Refresh Mailchimp preparation',exact:true}).click();await fetchedSelection;await page.getByLabel('ESP destination').selectOption('klaviyo');releaseSelection();await page.unroute('**/destination-review?destination=mailchimp');
  const kp=page.getByRole('region',{name:'Klaviyo preparation'});await kp.getByRole('button',{name:'Review Klaviyo preparation',exact:true}).waitFor();assert.equal(await kp.getByRole('status').count(),0);
  await kp.getByRole('button',{name:'Review Klaviyo preparation',exact:true}).click();await kp.getByRole('status').waitFor();
  const kd=page.waitForEvent('download');await kp.getByRole('button',{name:'Download Klaviyo HTML',exact:true}).click();const kdownload=await kd;const kpath=await kdownload.path();assert.ok(kpath);const kbytes=await readFile(kpath);assert.ok(kbytes.toString().includes('{% unsubscribe_link %}'));assert.ok(!kbytes.toString().includes('*|UNSUB|*'));
  await page.getByLabel('ESP destination').selectOption('mailchimp');assert.equal(await panel.getByRole('status').count(),0);await panel.getByRole('button',{name:'Review Mailchimp preparation',exact:true}).click();await panel.getByRole('status').waitFor();
  let releaseSelectedDownload!:()=>void;const holdSelectedDownload=new Promise<void>(r=>releaseSelectedDownload=r);let arriveSelectedDownload!:()=>void;const fetchedSelectedDownload=new Promise<void>(r=>arriveSelectedDownload=r);const beforeSelectedDownload=staleDownloads;
  await page.route('**/destination-artifact?destination=mailchimp&format=html',async route=>{const response=await route.fetch();arriveSelectedDownload();await holdSelectedDownload;try{await route.fulfill({response});}catch{}});
  await panel.getByRole('button',{name:'Download Mailchimp HTML',exact:true}).click();await fetchedSelectedDownload;await page.getByLabel('ESP destination').selectOption('klaviyo');releaseSelectedDownload();await page.unroute('**/destination-artifact?destination=mailchimp&format=html');
  await kp.getByRole('button',{name:'Review Klaviyo preparation',exact:true}).waitFor();assert.equal(staleDownloads,beforeSelectedDownload);await page.getByLabel('ESP destination').selectOption('mailchimp');
  console.log('Actual destination-selection review/download interruptions and distinct native mappings PASS.');
  await page.setViewportSize({width:390,height:844});await panel.getByRole('button',{name:'Review Mailchimp preparation',exact:true}).click();await panel.getByRole('status').waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/lettercape-mailchimp-mobile.png'});
  await context.addCookies([{name:'mailcraft_local_session',value:viewerCookie,url:origin,sameSite:'Strict'}]);await page.reload();await page.getByLabel('ESP destination').selectOption('mailchimp');await panel.waitFor();assert.equal(await panel.getByRole('button').count(),0);assert.ok(await panel.innerText().then(s=>s.includes('Editing permission is required')));assert.equal((await context.request.get(endpoint,{headers:{'X-Workspace-Id':p.workspace,'X-Actor-Id':viewer}})).status(),403);
  assert.equal(external,0);assert.deepEqual(errors,[]);console.log('Actual390px no-overflow/Viewer denial, zero instrumented external calls/page errors PASS.');
 }finally{await browser?.close();if(app&&app.exitCode===null){app.kill('SIGTERM');await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{app!.kill('SIGKILL');reject(Error('Owned ESP app required forced termination'));},10000);app!.once('exit',()=>{clearTimeout(timer);resolve();});});}await log.close();}
});console.log('Owned ESP fixture database and app cleaned up PASS.');
