import assert from 'node:assert/strict';
import {randomUUID,randomBytes} from 'node:crypto';
import {spawn} from 'node:child_process';
import {mkdir,open} from 'node:fs/promises';
import pg from 'pg';
import {createServer} from 'node:net';
import {chromium} from 'playwright';
import {digest} from '../src/server/audit';
import {sourceDatabase} from './smoke-source-truth';

// The isolated mode uses the guarded mirror loader and drops its own database.
// CI may provide APP_ORIGIN + MIGRATION_DATABASE_URL; only UUID-owned rows are removed.
async function qualify(origin:string,connection:string){
 if(process.env.LOCAL_DEVELOPMENT!=='true'||!['localhost','127.0.0.1'].includes(new URL(origin).hostname)||!['localhost','127.0.0.1','postgres'].includes(new URL(connection).hostname))throw Error('Owned loopback fixture required');
 const db=new pg.Pool({connectionString:connection}),w=randomUUID(),other=randomUUID(),user='template-http-'+randomUUID(),cookie=randomBytes(32).toString('hex');
 let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
 async function call(path:string,method='GET',body?:unknown,key=randomUUID(),workspace=w,bearer?:string,extra:Record<string,string>={}){
  const r=await fetch(origin+'/v1/'+path,{method,headers:{Origin:origin,'Content-Type':'application/json','Idempotency-Key':key,...(bearer?{Authorization:'Bearer '+bearer}:{Cookie:'mailcraft_local_session='+cookie,'X-Workspace-Id':workspace}),...extra},body:body===undefined?undefined:JSON.stringify(body)});const text=await r.text();let j;try{j=JSON.parse(text);}catch{if(r.status===405)return{r,j:null};throw Error('Non-JSON template fixture response: '+method+' '+path+' HTTP '+r.status);}return{r,j};
 }
 try{
  await db.query("INSERT INTO workspaces(id,name)VALUES($1,'Template HTTP fixture'),($2,'Template foreign fixture')",[w,other]);
  await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$3,'Owner'),($2,$3,'Owner')",[w,other,user]);
  await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,now()+interval '1 hour')",[digest(cookie),user]);
  assert.deepEqual((await call('templates')).j.data,[]);
  await call('brands','POST',{name:'Template fixture',website:'https://example.org',description:'Fixture',voice:'Clear',accent:'#0B625D',background:'#F7F6F2',font_stack:'Arial, sans-serif',address:'Fixture address',forbidden_phrases:[],approved_claims:[],provenance:[]});
  const parent=(await call('emails','POST',{title:'Frozen template source'})).j.email;
  const revision=(await call(`emails/${parent.id}/revisions`,'POST',{},randomUUID(),w,undefined,{'If-Match':'1'})).j.revision;
  const body={name:'HTTP frozen template',source_revision_id:revision.id,expected_artifact_hash:revision.artifact_hash},key=randomUUID();
  const registered=await call('templates','POST',body,key);assert.equal(registered.r.status,201);const t=registered.j.template;
  assert.equal((await call('templates','POST',body,key)).j.template.id,t.id);
  assert.equal((await call('templates','POST',{...body,name:'Changed'},key)).r.status,409);
  assert.equal((await call('templates','POST',{...body,unexpected:true})).r.status,422);
  assert.equal((await call('templates','POST',{...body,expected_artifact_hash:'0'.repeat(64)})).r.status,409);
  assert.equal((await call('templates/'+t.id)).r.status,200);
  assert.equal((await call('templates/'+t.id,'GET',undefined,randomUUID(),other)).r.status,404);
  assert.equal((await call('templates?actor='+user)).r.status,422);
  assert.equal((await call('templates?limit=101')).r.status,422);
  assert.equal((await call('templates','GET',undefined,randomUUID(),w,undefined,{'X-Actor-Id':'foreign'})).r.status,409);
  for(const path of['templates',`templates/${t.id}`,`templates/${t.id}/archive`,`templates/${t.id}/remix`])assert.equal((await call(path,'PUT',{})).r.status,405);
  assert.equal((await call(`templates/${t.id}/archive`)).r.status,405);assert.equal((await call(`templates/${t.id}/remix`)).r.status,405);
  const reader=(await call('api-keys','POST',{name:'Template reader',scopes:['emails:read'],expires_in_days:1})).j.secret;
  assert.equal((await call('templates','GET',undefined,randomUUID(),w,reader)).r.status,200);assert.equal((await call('templates','POST',body,randomUUID(),w,reader)).r.status,403);
  for(const role of['Viewer','Billing']){await db.query('UPDATE memberships SET role=$1 WHERE workspace_id=$2 AND user_id=$3',[role,w,user]);assert.equal((await call('templates')).r.status,role==='Viewer'?200:403);assert.equal((await call('templates','POST',body)).r.status,403);assert.equal((await call('templates','POST',body,key)).r.status,403);}
  await db.query("UPDATE memberships SET role='Owner'WHERE workspace_id=$1 AND user_id=$2",[w,user]);
  for(let i=0;i<2;i++)assert.equal((await call('templates','POST',{...body,name:'Paging '+i})).r.status,201);
  const first=(await call('templates?limit=1')).j;assert.equal(first.data.length,1);assert.equal(first.has_more,true);const cursor=encodeURIComponent(first.next_cursor);
  assert.equal((await call('templates?limit=1&after='+cursor)).j.data.length,1);assert.equal((await call('templates?state=archived&after='+cursor)).r.status,400);assert.equal((await call('templates?after='+cursor,'GET',undefined,randomUUID(),other)).r.status,400);
  await call(`emails/${parent.id}/draft`,'PATCH',{spec:{...parent.spec,subject:'Later source edit'}},randomUUID(),w,undefined,{'If-Match':'1'});
  const remixBody={title:'HTTP separate draft',expected_version:1,expected_artifact_hash:t.artifact_hash},remixKey=randomUUID();
  const child=await call(`templates/${t.id}/remix`,'POST',remixBody,remixKey);assert.equal(child.r.status,201);assert.deepEqual(child.j.email.spec,parent.spec);assert.equal(child.j.lineage.source_revision_id,revision.id);
  assert.equal((await call(`templates/${t.id}/remix`,'POST',remixBody,remixKey)).j.email.id,child.j.email.id);
  assert.equal((await db.query('SELECT count(*)::int n FROM emails WHERE workspace_id=$1 AND title=$2',[w,remixBody.title])).rows[0].n,1);
  assert.equal((await call(`templates/${t.id}/archive`,'POST',{expected_version:2})).r.status,412);
  const archiveKey=randomUUID();assert.equal((await call(`templates/${t.id}/archive`,'POST',{expected_version:1},archiveKey)).j.template.version,2);assert.equal((await call(`templates/${t.id}/archive`,'POST',{expected_version:1})).r.status,412);assert.equal((await call(`templates/${t.id}/remix`,'POST',remixBody)).r.status,409);assert.equal((await call(`templates/${t.id}/remix`,'POST',remixBody,remixKey)).j.email.id,child.j.email.id);
  for(const mode of ['raw_html','custom_html']){
   const authored='\ufeff<!--owned exact source-->\r\n<DIV data-owned="yes">H &amp; é</DIV>\n<!--[if mso]>VML<![endif]-->';
   const original=(await call('emails','POST',{title:'Exact '+mode})).j.email;
   const updated=await call(`emails/${original.id}/draft`,'PATCH',{spec:mode==='raw_html'?{...original.spec,editing_mode:'raw_html',raw_html:authored}:{...original.spec,sections:[{id:randomUUID(),type:'custom_html',html:authored}]}},randomUUID(),w,undefined,{'If-Match':'1'});assert.equal(updated.r.status,200);
   const frozen=(await call(`emails/${original.id}/revisions`,'POST',{},randomUUID(),w,undefined,{'If-Match':String(updated.j.email.doc_version)})).j.revision;
   const exact=(await call('templates','POST',{name:'Exact '+mode,source_revision_id:frozen.id,expected_artifact_hash:frozen.artifact_hash})).j.template;
   const derived=await call(`templates/${exact.id}/remix`,'POST',{title:'Exact child '+mode,expected_version:1,expected_artifact_hash:exact.artifact_hash});assert.equal(derived.r.status,201);assert.deepEqual(derived.j.email.spec,updated.j.email.spec);
  }
  console.log('PASS HTTP: five routes, methods, strict bodies/query, actor, roles/scopes, foreign scope, signed paging, frozen source, replay/one child, archive CAS.');
  browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844}});await context.addInitScript(workspace=>{if(window.top===window&&!localStorage.getItem('mailcraft.workspace'))localStorage.setItem('mailcraft.workspace',workspace);},w);await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);const page=await context.newPage();
  const sourceHead=(await call('emails/'+parent.id)).j.email;await call(`emails/${parent.id}/revisions`,'POST',{},randomUUID(),w,undefined,{'If-Match':String(sourceHead.doc_version)});
  await page.goto(origin+'/app/emails/'+parent.id);await page.getByRole('button',{name:'History',exact:true}).click();const save=page.getByRole('region',{name:'Save frozen revision as template'}).first();await save.getByLabel('Template name').fill('Browser original registration');const secondSave=page.getByRole('region',{name:'Save frozen revision as template'}).nth(1);await secondSave.getByLabel('Template name').fill('Second mounted intent');await page.screenshot({path:'/tmp/lettercape-template-browser/two-save-controls-mobile.png',fullPage:true});
  const registrationRequests:{key:string;body:unknown}[]=[];let lose=true;
  await page.route('**/v1/templates',async route=>{if(route.request().method()!=='POST')return route.continue();registrationRequests.push({key:route.request().headers()['idempotency-key'],body:route.request().postDataJSON()});const response=await route.fetch();if(lose){lose=false;assert.equal(response.status(),201);await route.abort('failed');}else await route.fulfill({response});});
  await page.getByRole('region',{name:'Save frozen revision as template'}).evaluateAll(elements=>{for(const element of elements){const button=element.querySelector<HTMLButtonElement>('button');button?.click();button?.click();}});await save.getByRole('alert').waitFor();console.log('Registration alert:',await save.getByRole('alert').innerText());assert.equal(registrationRequests.length,1);await save.getByLabel('Template name').fill('Changed registration intent');await page.reload();await page.getByRole('button',{name:'History',exact:true}).click();await save.getByRole('button',{name:'Retry original command'}).click();await save.getByRole('status').waitFor();assert.deepEqual(registrationRequests[1],registrationRequests[0]);assert.equal((await db.query('SELECT count(*)::int n FROM email_templates WHERE workspace_id=$1 AND name=$2',[w,'Browser original registration'])).rows[0].n,1);await page.unroute('**/v1/templates');
  await page.goto(origin+'/app/templates');const catalogue=page.getByRole('region',{name:'Email templates'});await catalogue.getByRole('button',{name:'View template Browser original registration',exact:true}).focus();await page.keyboard.press('Enter');const detail=page.getByRole('region',{name:'Template details'});await detail.getByLabel('New draft title').fill('Browser original child');await page.screenshot({path:'/tmp/lettercape-template-browser/owner-detail-mobile.png',fullPage:true});
  const requests:{key:string;body:unknown}[]=[];lose=true;await page.route('**/v1/templates/*/remix',async route=>{requests.push({key:route.request().headers()['idempotency-key'],body:route.request().postDataJSON()});const response=await route.fetch();if(lose){lose=false;assert.equal(response.status(),201);await route.abort('failed');}else await route.fulfill({response});});
  await detail.getByRole('button',{name:'Create separate draft',exact:true}).evaluate(el=>{(el as HTMLButtonElement).click();(el as HTMLButtonElement).click();});await catalogue.getByRole('alert').waitFor();assert.equal(requests.length,1);await detail.getByLabel('New draft title').fill('Changed child intent');await page.goto(origin+'/app/emails/'+parent.id);await page.goto(origin+'/app/templates');await page.reload();await catalogue.getByRole('button',{name:'Retry original command'}).click();await page.getByRole('heading',{name:'Browser original child',exact:true}).waitFor();assert.deepEqual(requests[1],requests[0]);assert.equal((await db.query('SELECT count(*)::int n FROM emails WHERE workspace_id=$1 AND title=$2',[w,'Browser original child'])).rows[0].n,1);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('.derived-panel').getByText('Loading derived drafts…',{exact:true}).waitFor({state:'hidden'});await page.getByRole('button',{name:'Preview',exact:true}).click();await page.frameLocator('iframe[title="Email browser simulation"]').getByText('Your next story starts here',{exact:true}).waitFor();await page.locator('iframe[title="Email browser simulation"]').scrollIntoViewIfNeeded();await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r(true)))));await page.locator('iframe[title="Email browser simulation"]').screenshot({path:'/tmp/lettercape-template-browser/separate-draft-preview-mobile.png'});await page.screenshot({path:'/tmp/lettercape-template-browser/separate-draft-mobile.png',fullPage:true});await page.unroute('**/v1/templates/*/remix');
  await page.goto(origin+'/app/templates');await catalogue.getByRole('button',{name:'View template Paging 0',exact:true}).click();await detail.getByLabel('New draft title').fill('Rejected archived child');
  let entered!:()=>void,release!:()=>void;const ready=new Promise<void>(r=>entered=r),gate=new Promise<void>(r=>release=r);
  await page.route('**/v1/templates/*/remix',async route=>{entered();await gate;await route.continue();});
  await detail.getByRole('button',{name:'Create separate draft',exact:true}).click();await ready;
  const archiveTarget=(await call('templates?limit=100')).j.data.find((item:{name:string})=>item.name==='Paging 0');assert.ok(archiveTarget);assert.equal((await call(`templates/${archiveTarget.id}/archive`,'POST',{expected_version:1})).r.status,200);release();
  await catalogue.getByRole('button',{name:'Dismiss rejected command',exact:true}).waitFor();assert.equal((await db.query('SELECT count(*)::int n FROM emails WHERE workspace_id=$1 AND title=$2',[w,'Rejected archived child'])).rows[0].n,0);await page.reload();await catalogue.getByRole('button',{name:'Dismiss rejected command',exact:true}).waitFor();await catalogue.getByRole('button',{name:'Dismiss rejected command',exact:true}).click();assert.equal(await catalogue.getByRole('button',{name:'Retry original command'}).count(),0);await page.unroute('**/v1/templates/*/remix');await page.reload();await catalogue.getByRole('button',{name:'View template Browser original registration',exact:true}).waitFor();
  await catalogue.getByRole('button',{name:'View template Paging 1',exact:true}).click();
  let archiveEntered!:()=>void,archiveRelease!:()=>void;const archiveReady=new Promise<void>(r=>archiveEntered=r),archiveGate=new Promise<void>(r=>archiveRelease=r);
  await page.route('**/v1/templates/*/archive',async route=>{archiveEntered();await archiveGate;await route.continue();});await detail.getByRole('button',{name:'Archive template',exact:true}).click();await archiveReady;
  const staleTarget=(await call('templates?limit=100')).j.data.find((item:{name:string})=>item.name==='Paging 1');assert.equal((await call(`templates/${staleTarget.id}/archive`,'POST',{expected_version:1})).r.status,200);archiveRelease();await catalogue.getByRole('button',{name:'Dismiss rejected command',exact:true}).waitFor();await page.reload();await catalogue.getByRole('button',{name:'Dismiss rejected command',exact:true}).waitFor();await catalogue.getByRole('button',{name:'Dismiss rejected command',exact:true}).click();await page.unroute('**/v1/templates/*/archive');await catalogue.getByRole('button',{name:'View template Browser original registration',exact:true}).click();await detail.getByLabel('New draft title').fill('After rejected command dismissal');await detail.getByRole('button',{name:'Create separate draft',exact:true}).click();await page.getByRole('heading',{name:'After rejected command dismissal',exact:true}).waitFor();assert.equal((await db.query('SELECT count(*)::int n FROM emails WHERE workspace_id=$1 AND title=$2',[w,'After rejected command dismissal'])).rows[0].n,1);
  await page.goto(origin+'/app/templates');await catalogue.getByRole('button',{name:'View template Browser original registration',exact:true}).click();await detail.getByLabel('New draft title').fill('Held successful workspace child');
  const heldRequests:{key:string;body:unknown;workspace:string;actor:string}[]=[];let heldChild='',hold=true;
  let successEntered!:()=>void,successRelease!:()=>void,successFinished!:()=>void;const successReady=new Promise<void>(r=>successEntered=r),successGate=new Promise<void>(r=>successRelease=r),successDone=new Promise<void>(r=>successFinished=r);
  await page.route('**/v1/templates/*/remix',async route=>{heldRequests.push({key:route.request().headers()['idempotency-key'],body:route.request().postDataJSON(),workspace:route.request().headers()['x-workspace-id'],actor:route.request().headers()['x-actor-id']});const response=await route.fetch();assert.equal(response.status(),201);if(hold){hold=false;heldChild=(await response.json()).email.id;successEntered();await successGate;await route.fulfill({response});successFinished();}else await route.fulfill({response});});
  await detail.getByRole('button',{name:'Create separate draft',exact:true}).click();await successReady;
  const originalReceipt=await page.evaluate(scope=>localStorage.getItem('lettercape.template.'+JSON.stringify(scope)),[w,user]);assert.ok(originalReceipt);const savedCommand=JSON.parse(originalReceipt);assert.equal(savedCommand.actor,user);assert.equal(savedCommand.workspace,w);assert.equal(savedCommand.key,heldRequests[0].key);assert.deepEqual(savedCommand.body,heldRequests[0].body);
  await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.locator('#workspace').selectOption(other);await page.getByRole('heading',{name:'Make something worth opening.',exact:true}).waitFor();successRelease();await successDone;await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r(true)))));
  assert.equal(new URL(page.url()).pathname,'/app');assert.equal(await page.locator('#workspace').inputValue(),other);assert.equal(await page.evaluate(scope=>localStorage.getItem('lettercape.template.'+JSON.stringify(scope)),[w,user]),originalReceipt);assert.equal(await page.evaluate(scope=>localStorage.getItem('lettercape.template.'+JSON.stringify(scope)),[other,user]),null);
  await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.locator('#workspace').selectOption(w);await page.goto(origin+'/app/templates');await catalogue.getByRole('button',{name:'Retry original command',exact:true}).click();await page.getByRole('heading',{name:'Held successful workspace child',exact:true}).waitFor();assert.equal(new URL(page.url()).pathname,'/app/emails/'+heldChild);assert.deepEqual(heldRequests[1],heldRequests[0]);assert.equal(await page.evaluate(scope=>localStorage.getItem('lettercape.template.'+JSON.stringify(scope)),[w,user]),null);assert.equal((await db.query('SELECT count(*)::int n FROM emails WHERE workspace_id=$1 AND title=$2',[w,'Held successful workspace child'])).rows[0].n,1);await page.unroute('**/v1/templates/*/remix');
  console.log('PASS held committed success: workspace switch prevents stale navigation/ack; exact original actor/workspace receipt retries to one original child.');
  const asset=randomUUID(),variant=randomUUID(),op=randomUUID(),upload=randomUUID(),rights=randomUUID(),scan=randomUUID(),assetHash='a'.repeat(64);
  await db.query("INSERT INTO assets(workspace_id,id,created_by,source_sha256,state)VALUES($1,$2,$3,$4,'ready_private')",[w,asset,user,assetHash]);
  await db.query("INSERT INTO operations(workspace_id,id,type,input,created_by)VALUES($1,$2,'asset.upload','{}',$3)",[w,op,user]);
  await db.query("INSERT INTO asset_uploads(workspace_id,id,asset_id,operation_id,created_by,principal,token_hash,expected_sha256,expected_bytes,intent)VALUES($1,$2,$3,$4,$5,'{}','fixture',$6,8,'{}')",[w,upload,asset,op,user,assetHash]);
  await db.query("INSERT INTO asset_rights(workspace_id,id,asset_id,upload_id,actor,terms_version,attested,source_sha256)VALUES($1,$2,$3,$4,$5,'local-upload-attestation-v1',true,$6)",[w,rights,asset,upload,user,assetHash]);
  await db.query("INSERT INTO asset_scans(workspace_id,id,asset_id,operation_id,sha256,status,engine,database_sha256,database_built_at,completed_at,receipt)VALUES($1,$2,$3,$4,$5,'clean','fixture',$5,clock_timestamp(),clock_timestamp(),'{}')",[w,scan,asset,op,assetHash]);
  await db.query("INSERT INTO asset_variants(workspace_id,id,asset_id,object_key,sha256,bytes,mime,width,height,frames,role,processing_profile,storage_profile,rights_id,source_scan_id,scan_id,receipt)VALUES($1,$2,$3,$4,$5,8,'image/png',1,1,1,'static','fixture','local-private-v1',$6,$7,$7,'{}')",[w,variant,asset,w+'_'+variant+'_variant',assetHash,rights,scan]);
  const assetSource=await call('emails','POST',{title:'Private asset source',spec:{...parent.spec,schema_version:'1.1',editing_mode:'raw_html',raw_html:'<p>Private source</p>',asset_registry:[{asset_id:asset,variant_id:variant}]}});assert.equal(assetSource.r.status,200);
  const assetRevision=(await call(`emails/${assetSource.j.email.id}/revisions`,'POST',{},randomUUID(),w,undefined,{'If-Match':'1'})).j.revision;
  const assetTemplate=(await call('templates','POST',{name:'Private asset recovery template',source_revision_id:assetRevision.id,expected_artifact_hash:assetRevision.artifact_hash})).j.template;
  const historicalBody={title:'Historical private asset child',expected_version:1,expected_artifact_hash:assetTemplate.artifact_hash},historicalKey=randomUUID();const historical=await call(`templates/${assetTemplate.id}/remix`,'POST',historicalBody,historicalKey);assert.equal(historical.r.status,201);
  await db.query("UPDATE assets SET state='deleted'WHERE workspace_id=$1 AND id=$2",[w,asset]);assert.equal((await call(`templates/${assetTemplate.id}/remix`,'POST',historicalBody,historicalKey)).j.email.id,historical.j.email.id);
  await page.goto(origin+'/app/templates');await catalogue.getByRole('button',{name:'View template Private asset recovery template',exact:true}).click();await detail.getByLabel('New draft title').fill('Refused private asset child');
  const assetRequests:{key:string;body:unknown}[]=[];let loseAsset=true;
  await page.route('**/v1/templates/*/remix',async route=>{assetRequests.push({key:route.request().headers()['idempotency-key'],body:route.request().postDataJSON()});const response=await route.fetch();assert.equal(response.status(),409);assert.equal((await response.json()).error.code,'ASSET_NOT_READY');if(loseAsset){loseAsset=false;await route.abort('failed');}else await route.fulfill({response});});
  await detail.getByRole('button',{name:'Create separate draft',exact:true}).click();await catalogue.getByRole('alert').waitFor();const ambiguousAssetReceipt=await page.evaluate(scope=>localStorage.getItem('lettercape.template.'+JSON.stringify(scope)),[w,user]);assert.ok(ambiguousAssetReceipt);await page.reload();assert.equal(await page.evaluate(scope=>localStorage.getItem('lettercape.template.'+JSON.stringify(scope)),[w,user]),ambiguousAssetReceipt);await catalogue.getByRole('button',{name:'Retry original command',exact:true}).click();await catalogue.getByRole('alert').waitFor();assert.deepEqual(assetRequests[1],assetRequests[0]);assert.equal((await db.query('SELECT count(*)::int n FROM emails WHERE workspace_id=$1 AND title=$2',[w,'Refused private asset child'])).rows[0].n,0);assert.equal((await db.query('SELECT count(*)::int n FROM idempotency WHERE workspace_id=$1 AND key=$2',[w,assetRequests[0].key])).rows[0].n,0);
  await page.screenshot({path:'/tmp/lettercape-template-browser/asset-refusal-before-dismiss-mobile.png',fullPage:true});await catalogue.getByRole('button',{name:'Dismiss rejected command',exact:true}).waitFor({timeout:4000});await page.reload();await catalogue.getByRole('button',{name:'Dismiss rejected command',exact:true}).click();await page.unroute('**/v1/templates/*/remix');await catalogue.getByRole('button',{name:'View template Browser original registration',exact:true}).click();await detail.getByLabel('New draft title').fill('Healthy draft after asset refusal');await detail.getByRole('button',{name:'Create separate draft',exact:true}).click();await page.getByRole('heading',{name:'Healthy draft after asset refusal',exact:true}).waitFor();assert.equal((await db.query('SELECT count(*)::int n FROM emails WHERE workspace_id=$1 AND title=$2',[w,'Healthy draft after asset refusal'])).rows[0].n,1);assert.equal((await call(`templates/${assetTemplate.id}/remix`,'POST',historicalBody,historicalKey)).j.email.id,historical.j.email.id);await page.getByRole('heading',{name:'Healthy draft after asset refusal',exact:true}).waitFor();await page.screenshot({path:'/tmp/lettercape-template-browser/healthy-after-asset-refusal-mobile.png',fullPage:true});console.log('PASS asset refusal recovery: real409, zero child/receipt, exact command reload/retry, deliberate dismiss, healthy reuse and historical replay.');
  await db.query("UPDATE memberships SET role='Viewer'WHERE workspace_id=$1 AND user_id=$2",[w,user]);await page.goto(origin+'/app/templates');await catalogue.getByRole('button',{name:'View template Browser original registration',exact:true}).click();await detail.waitFor();assert.equal(await catalogue.getByRole('button',{name:'Create separate draft'}).count(),0);assert.equal(await catalogue.getByRole('button',{name:'Archive template',exact:true}).count(),0);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/lettercape-template-browser/viewer-catalogue-mobile.png',fullPage:true});
  let errorOnce=true;await page.route('**/v1/templates?**',async route=>{if(errorOnce){errorOnce=false;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'FIXTURE_UNAVAILABLE',message:'Owned catalogue retry fixture'}})});}else await route.continue();});await catalogue.getByRole('button',{name:'Refresh templates',exact:true}).click();await catalogue.getByRole('alert').waitFor();await catalogue.getByRole('button',{name:'Refresh templates',exact:true}).click();await catalogue.getByRole('button',{name:'View template Browser original registration',exact:true}).waitFor();await page.unroute('**/v1/templates?**');
  await page.evaluate(workspace=>localStorage.setItem('mailcraft.workspace',workspace),other);await page.reload();await page.getByText('No active templates yet.',{exact:false}).waitFor();await page.screenshot({path:'/tmp/lettercape-template-browser/empty-mobile.png',fullPage:true});
  console.log('PASS Chromium: editor history registration, committed lost responses/reload/navigation/exact original keys+bodies, repeated synchronous clicks, separate draft, Viewer, empty/error/retry, keyboard and 390px.');
 }finally{await browser?.close();const cleanup=await db.connect();try{await cleanup.query('BEGIN');await cleanup.query("SET LOCAL session_replication_role='replica'");for(const table of['asset_draft_references','asset_revision_references','asset_variants','asset_rights','asset_scans','media_jobs','asset_object_staging','asset_uploads','assets','asset_quotas','outbox','usage_ledger','operations','email_templates','email_lineage','render_downloads','idempotency','audit_events','api_rate_events','api_keys','revisions','emails','brands','memberships'])await cleanup.query(`DELETE FROM ${table} WHERE workspace_id=ANY($1::uuid[])`,[[w,other]]);await cleanup.query('DELETE FROM auth_sessions WHERE user_id=$1',[user]);await cleanup.query('DELETE FROM workspaces WHERE id=ANY($1::uuid[])',[[w,other]]);await cleanup.query('COMMIT');}catch(error){await cleanup.query('ROLLBACK');throw error;}finally{cleanup.release();await db.end();}}
}
await mkdir('/tmp/lettercape-template-browser',{recursive:true});
if(process.env.APP_ORIGIN&&!process.argv.includes('--isolated'))await qualify(process.env.APP_ORIGIN,process.env.MIGRATION_DATABASE_URL!);
else await sourceDatabase(async({db})=>{
 await new Promise<void>((resolve,reject)=>{const probe=createServer();probe.once('error',reject);probe.listen(3014,'127.0.0.1',()=>probe.close(()=>resolve()));});
 const origin='http://127.0.0.1:3014',connection=db.options.connectionString!,runtime=new URL(process.env.DATABASE_URL!);runtime.pathname=new URL(connection).pathname;
 const log=await open('/tmp/lettercape-template-browser/server.log','w');const app=spawn(process.execPath,['node_modules/next/dist/bin/next','dev','--hostname','127.0.0.1','--port','3014'],{env:{...process.env,APP_ORIGIN:origin,DATABASE_URL:runtime.toString(),MIGRATION_DATABASE_URL:connection,LOCAL_DEVELOPMENT:'true',NEXT_TELEMETRY_DISABLED:'1'},stdio:['ignore',log.fd,log.fd]});console.log('Owned template server PID',app.pid,'port 3014');
 try{const deadline=Date.now()+90000;while(true){if(app.exitCode!==null)throw Error('Owned template server exited');try{if((await fetch(origin+'/status')).ok)break;}catch{}if(Date.now()>deadline)throw Error('Owned template server readiness timeout');await new Promise(r=>setTimeout(r,250));}await qualify(origin,connection);}finally{app.kill('SIGTERM');await new Promise<void>(resolve=>{if(app.exitCode!==null)resolve();else app.once('exit',()=>resolve());});await log.close();console.log('Owned template server stopped; disposable database drop follows.');}
});
