import assert from'node:assert/strict';import{randomUUID,randomBytes}from'node:crypto';import{spawn,type ChildProcess}from'node:child_process';import{open,mkdir}from'node:fs/promises';import{chromium}from'playwright';import{sourceDatabase}from'./smoke-source-truth';import{blankSpec,type EmailSpec}from'../src/domain/email';import{createEmail}from'../src/server/emails';import{digest}from'../src/server/audit';import type{Brand}from'../src/domain/brand';
const origin='http://127.0.0.1:3048';
await sourceDatabase(async({db,p,brand,tx})=>{
 const old:Brand={name:'Pinned old kit',website:'',description:'',voice:'',accent:'#0B625D',background:'#F7F6F2',font_stack:'Arial, sans-serif',address:'',forbidden_phrases:['risk free'],approved_claims:[],provenance:[],tone_rules:{max_sentence_words:3,max_exclamations:0}},newer={...old,name:'Current different kit',forbidden_phrases:['NEWKIT_ONLY'],tone_rules:{}};
 await db.query('UPDATE brands SET data=$1 WHERE id=$2',[old,brand]);await db.query('INSERT INTO brands(workspace_id,version,data)SELECT $1,n,$2 FROM generate_series(2,102)n',[p.workspace,newer]);const latest=(await db.query('SELECT id FROM brands WHERE workspace_id=$1 ORDER BY version DESC LIMIT 1',[p.workspace])).rows[0].id;
 const s:EmailSpec={...blankSpec(brand,'Fixture'),subject:'Plain subject',preheader:'Plain',sections:[{id:'body',type:'text',text:'Plain original'},{id:'columns',type:'columns',columns:[[{id:'nested',type:'text',text:'Nested!'},{id:'alt',type:'image',src:'https://example.org/image.png',alt:'Risk free',decorative:false}],[]]}]};
 const create=(title:string,spec:EmailSpec)=>tx(c=>createEmail(c,p,title,spec));const doc=await create('Live voice draft',s),newPin=await create('New pin fixture',{...s,brand_kit_version_id:latest}),raw=await create('Raw voice fixture',{...s,editing_mode:'raw_html',raw_html:'\ufeff<p>Original</p>\r\n'}),rtl=await create('RTL voice fixture',{...s,locale:'he-IL',direction:'rtl',subject:'שלום'}),many=await create('Many voice fields',{...s,sections:Array.from({length:55},(_,i)=>({id:'row:"'+i,type:'text',text:'risk free'}))}),unsetId=randomUUID();await db.query('INSERT INTO brands(workspace_id,id,version,data)VALUES($1,$2,103,$3)',[p.workspace,unsetId,{...old,forbidden_phrases:[],tone_rules:{}}]);const unset=await create('Unset voice fixture',{...s,brand_kit_version_id:unsetId});
 const cookie=randomBytes(32).toString('hex');await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,clock_timestamp()+interval '1 hour')",[digest(cookie),p.user]);const runtime=new URL(process.env.DATABASE_URL!);runtime.pathname=new URL(db.options.connectionString!).pathname;assert.match(runtime.pathname,/^\/creation_fixture_[a-f0-9]{32}$/);
 const log=await open('/tmp/lettercape-live-voice-app.log','w');let app:ChildProcess|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
 try{
 app=spawn(process.execPath,['node_modules/next/dist/bin/next','dev','--hostname','127.0.0.1','--port','3048'],{env:{PATH:process.env.PATH,NODE_ENV:'development',LOCAL_DEVELOPMENT:'true',APP_ORIGIN:origin,DATABASE_URL:runtime.toString(),MIGRATION_DATABASE_URL:db.options.connectionString!,NEXT_TELEMETRY_DISABLED:'1',AI_GENERATION_ALLOWANCE:'0',PREFERENCE_SIGNING_SECRET:'owned-live-voice-fixture-only-32bytes'},stdio:['ignore',log.fd,log.fd]});for(let n=0;n<160;n++){if(app.exitCode!==null)throw Error('Owned voice app exited');try{if((await fetch(origin)).ok)break;}catch{}if(n===159)throw Error('Owned voice app unavailable');await new Promise(r=>setTimeout(r,250));}
 browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:320,height:1000}});context.setDefaultTimeout(10000);await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);await context.addInitScript(workspace=>{if(window.top===window)localStorage.setItem('mailcraft.workspace',workspace);},p.workspace);let external=0,brandReads=0,mutations=0;const errors:string[]=[],warnings:string[]=[];
 await context.route(url=>url.origin!==origin&&url.protocol!=='blob:'&&url.protocol!=='data:',route=>{external++;return route.abort();});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(/same key|unique.*key/i.test(m.text()))warnings.push(m.text());});page.on('request',r=>{if(r.url().includes('/v1/brands?'))brandReads++;if(r.method()!=='GET'&&!r.url().includes('/draft')&&!r.url().includes('/preview'))mutations++;});await page.route('**/v1/emails/*/draft',route=>route.abort());
 const recovery=(email:string)=>page.evaluate(async scope=>new Promise<string|undefined>((resolve,reject)=>{const request=indexedDB.open('lettercape-source-recovery-1');request.onerror=()=>reject(request.error);request.onsuccess=()=>{const database=request.result,tx=database.transaction('slots','readonly'),get=tx.objectStore('slots').get(JSON.stringify([scope.workspace,scope.actor,scope.email]));tx.oncomplete=()=>{database.close();resolve(JSON.stringify(get.result));};tx.onerror=()=>reject(tx.error);};}),{workspace:p.workspace,actor:p.user,email});
 const records=async()=>(await db.query("SELECT json_build_object('emails',(SELECT md5(string_agg(md5(to_jsonb(t)::text),'' ORDER BY md5(to_jsonb(t)::text)))FROM emails t),'revisions',(SELECT md5(string_agg(md5(to_jsonb(t)::text),'' ORDER BY md5(to_jsonb(t)::text)))FROM revisions t),'provenance',(SELECT md5(string_agg(md5(to_jsonb(t)::text),'' ORDER BY md5(to_jsonb(t)::text)))FROM email_source_provenance t),'audits',(SELECT md5(string_agg(md5(to_jsonb(t)::text),'' ORDER BY md5(to_jsonb(t)::text)))FROM audit_events t),'commands',(SELECT md5(string_agg(md5(to_jsonb(t)::text),'' ORDER BY md5(to_jsonb(t)::text)))FROM idempotency t),'brands',(SELECT md5(string_agg(md5(to_jsonb(t)::text),'' ORDER BY md5(to_jsonb(t)::text)))FROM brands t)) AS value")).rows[0].value;
 const until=async(check:()=>Promise<boolean>)=>{for(let n=0;n<100;n++){if(await check())return;await new Promise(r=>setTimeout(r,50));}throw Error('Owned voice condition unavailable');};const recoveredCommand=async(email:string,value:string)=>until(async()=>{const slot=await recovery(email);if(!slot)return false;const saved=JSON.parse(slot);return !!saved.command&&JSON.stringify(saved.draft.spec).includes(value);});const body=()=>page.getByRole('textbox',{name:'Body text',exact:true}).first(),panel=page.getByRole('region',{name:'Live mechanical Voice Guard',exact:true}),row=(field:string)=>panel.locator('[data-live-voice-location='+JSON.stringify(field)+']');
 const openVoice=async()=>{await page.getByRole('button',{name:'Show live Voice Guard',exact:true}).click();};const oldRules=async()=>{await panel.getByRole('button',{name:'Search older brand versions',exact:true}).click();await panel.getByText('Pinned kit · v1',{exact:true}).waitFor();};
 await page.goto(origin+'/app/emails/'+doc.id);await body().waitFor();await body().fill('risk free!!!');await recoveredCommand(doc.id,'risk free!!!');const original=await records(),savedRecovery=await recovery(doc.id),originalCommand=JSON.parse(savedRecovery!).command;
 assert.equal(await page.getByRole('button',{name:'Show live Voice Guard',exact:true}).count(),1,'Unsaved editor must offer live mechanical feedback without creating a checkpoint');await openVoice();await panel.getByRole('button',{name:'Search older brand versions',exact:true}).waitFor();assert.equal(await panel.locator('[data-live-voice-location]').count(),0);await oldRules();await row(JSON.stringify(['block','body','text'])).getByText('risk free!!!',{exact:true}).first().waitFor();await row(JSON.stringify(['block','nested','text'])).waitFor();await row(JSON.stringify(['block','alt','alt'])).waitFor();assert.equal(await panel.getByText('Current different kit',{exact:true}).count(),0);assert.deepEqual(await records(),original);assert.equal(await recovery(doc.id),savedRecovery);assert.equal(mutations,0);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mkdir('output/live-voice-guard',{recursive:true});await panel.screenshot({path:'output/live-voice-guard/structured-mobile.png'});
 console.log('Actual unsaved copy/nested alt findings use old pinned kit beyond first100versions and preserve documents/checkpoints/command recovery PASS.');
 await body().fill('Plain updated copy');await recoveredCommand(doc.id,'Plain updated copy');await row(JSON.stringify(['block','body','text'])).waitFor({state:'hidden'});const recoveryAfterEdit=await recovery(doc.id);assert.deepEqual(await records(),original);const pinned=(await context.request.get(origin+'/v1/brands?limit=100',{headers:{'X-Workspace-Id':p.workspace}}));assert.equal(pinned.status(),200);const firstPage=await pinned.json();const olderResponse=await context.request.get(origin+'/v1/brands?limit=100&after='+encodeURIComponent(firstPage.next_cursor),{headers:{'X-Workspace-Id':p.workspace}});assert.equal(olderResponse.status(),200);const olderPage=await olderResponse.json();assert.ok(olderPage.data.some((b:{id:string})=>b.id===brand));
 const url='**/v1/brands?*';let release!:()=>void,started!:()=>void,done!:()=>void;let gate=new Promise<void>(r=>release=r),seen=new Promise<void>(r=>started=r),finished=new Promise<void>(r=>done=r);await page.route(url,async route=>{started();await gate;try{await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(olderPage)});}catch{}finally{done();}});const readsBefore=brandReads;await panel.getByRole('button',{name:'Refresh pinned rules',exact:true}).evaluate(node=>{(node as HTMLButtonElement).click();(node as HTMLButtonElement).click();});await seen;assert.equal(brandReads,readsBefore+1);assert.equal(await panel.locator('[data-live-voice-location]').count(),0);await body().fill('Current risk free');release();await finished;await row(JSON.stringify(['block','body','text'])).getByText('Current risk free',{exact:true}).waitFor();assert.equal(await panel.getByText('risk free!!!',{exact:true}).count(),0);await page.unroute(url);await recoveredCommand(doc.id,'Current risk free');assert.deepEqual(await records(),original);
 console.log('Live findings follow current edits during held kit read; repeated refresh creates one read and never shows captured stale copy PASS.');
 const retryRecovery=await recovery(doc.id);assert.equal(JSON.parse(retryRecovery!).command,originalCommand);await page.route(url,route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'Owned kit unavailable',code:'FIXTURE_UNAVAILABLE'}})}));await panel.getByRole('button',{name:'Refresh pinned rules',exact:true}).click();await panel.getByRole('alert').filter({hasText:'Owned kit unavailable'}).waitFor();assert.equal(await panel.locator('[data-live-voice-location]').count(),0);await page.unroute(url);
 for(const payload of[{...olderPage,data:olderPage.data.map((b:{id:string})=>b.id===brand?{...b,workspace_id:randomUUID()}:b)},{...olderPage,data:[{id:brand,version:1,data:{...old,tone_rules:{max_exclamations:-1}}}]}]){await page.route(url,route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(payload)}));await panel.getByRole('button',{name:'Refresh pinned rules',exact:true}).click();await panel.getByRole('alert').filter({hasText:'could not be verified'}).waitFor();assert.equal(await panel.locator('[data-live-voice-location]').count(),0);await page.unroute(url);}
 await page.route(url,route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data:[],has_more:false,next_cursor:null,total_count:0})}));await panel.getByRole('button',{name:'Refresh pinned rules',exact:true}).click();await panel.getByText('Pinned kit unavailable in this workspace.',{exact:false}).waitFor();assert.equal(await panel.locator('[data-live-voice-location]').count(),0);await page.unroute(url);
 await context.setOffline(true);await panel.getByRole('button',{name:'Refresh pinned rules',exact:true}).click();await panel.getByRole('alert').waitFor();await context.setOffline(false);await panel.getByRole('button',{name:'Refresh pinned rules',exact:true}).click();await oldRules();assert.equal(await recovery(doc.id),retryRecovery);assert.deepEqual(await records(),original);
 console.log('Actual503/malformed/wrong-workspace/offline kit reads show unavailable feedback; retry preserves current source and original recovery PASS.');
 const repeated={data:firstPage.data,has_more:true,next_cursor:'repeated-owned-cursor',total_count:103};await page.route(url,route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(repeated)}));await panel.getByRole('button',{name:'Refresh pinned rules',exact:true}).click();await panel.getByRole('button',{name:'Search older brand versions',exact:true}).click();await panel.getByRole('alert').filter({hasText:'could not be verified'}).waitFor();assert.equal(await panel.locator('[data-live-voice-location]').count(),0);await page.unroute(url);await panel.getByRole('button',{name:'Refresh pinned rules',exact:true}).click();await oldRules();
 gate=new Promise<void>(r=>release=r);seen=new Promise<void>(r=>started=r);finished=new Promise<void>(r=>done=r);await page.route(url,async route=>{started();await gate;try{await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(olderPage)});}catch{}finally{done();}});await panel.getByRole('button',{name:'Refresh pinned rules',exact:true}).click();await seen;await panel.getByRole('button',{name:'Hide live Voice Guard',exact:true}).click();release();await finished;assert.equal(await panel.count(),0);await page.unroute(url);await openVoice();await oldRules();assert.equal(await recovery(doc.id),retryRecovery);
 console.log('Repeated cursors are refused, and close/reopen fences late valid rules without changing source or recovery PASS.');
 gate=new Promise<void>(r=>release=r);seen=new Promise<void>(r=>started=r);finished=new Promise<void>(r=>done=r);await page.route(url,async route=>{started();await gate;try{await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(olderPage)});}catch{}finally{done();}});await panel.getByRole('button',{name:'Refresh pinned rules',exact:true}).click();await seen;await page.goto(origin+'/app/emails/'+newPin.id);release();await finished;await page.unroute(url);assert.equal(await panel.count(),0);await openVoice();await panel.getByText('Pinned kit · v102',{exact:true}).waitFor();await panel.getByText('No supported mechanical issues found.',{exact:true}).waitFor();await page.goto(origin+'/app/emails/'+doc.id);await body().waitFor();assert.equal(await body().inputValue(),'Current risk free');assert.equal(await recovery(doc.id),retryRecovery);await openVoice();await oldRules();assert.deepEqual(await records(),original);
 console.log('Navigation to different pinned kit fences old responses; reentry restores unsaved original-command recovery PASS.');
 await page.goto(origin+'/app/emails/'+many.id);await page.getByRole('textbox',{name:'Subject',exact:true}).waitFor();await openVoice();await oldRules();assert.equal(await panel.locator('[data-live-voice-location]').count(),20);await panel.getByRole('button',{name:'Next voice findings',exact:true}).focus();await page.keyboard.press('Enter');await panel.getByText('Page 2 of 3',{exact:true}).waitFor();await page.keyboard.press('Enter');await panel.getByText('Page 3 of 3',{exact:true}).waitFor();assert.equal(await panel.locator('[data-live-voice-location]').count(),15);await panel.getByText('Block 55 [row:"54] · Body text',{exact:true}).waitFor();await panel.getByRole('button',{name:'Previous voice findings',exact:true}).focus();await page.keyboard.press('Enter');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 console.log('All55located findings remain reachable on20-row keyboard pages with stable quote-ID rows and320px reflow PASS.');
 await page.goto(origin+'/app/emails/'+raw.id);await page.getByRole('textbox',{name:'Subject',exact:true}).waitFor();await page.getByRole('group',{name:'Editor view',exact:true}).getByRole('button',{name:'HTML',exact:true}).click();const input=page.getByRole('textbox',{name:'Raw HTML source',exact:true});await input.fill('\ufeff<script>globalThis.__liveVoiceExecuted=true</script><style>risk free!!!</style><p>Risk<strong> free</strong></p><p>One two<br>three four</p>\r\n<img src="https://example.org/image.png" alt="Hello!">');await recoveredCommand(raw.id,'__liveVoiceExecuted');const rawRecovery=await recovery(raw.id);await openVoice();await oldRules();assert.equal(await panel.locator('[data-live-voice-code="VOICE_FORBIDDEN"]').count(),1);assert.equal(await panel.locator('[data-live-voice-code="VOICE_EXCLAMATIONS"]').count(),1);await panel.getByText('CSS visibility',{exact:false}).waitFor();assert.equal(await page.evaluate(()=>(window as unknown as{__liveVoiceExecuted?:boolean}).__liveVoiceExecuted),undefined);assert.equal(await recovery(raw.id),rawRecovery);await input.fill('<p>'+('é'.repeat(32769))+'</p>');await panel.getByText('65,536 UTF-8 bytes',{exact:false}).waitFor();assert.equal(await panel.locator('[data-live-voice-location]').count(),0);assert.equal(await input.inputValue(),'<p>'+('é'.repeat(32769))+'</p>');await panel.screenshot({path:'output/live-voice-guard/raw-mobile.png'});
 console.log('Inert raw Unicode/CRLF/inline/alt extraction has clear CSS limits and oversized coverage refusal with exact source retained PASS.');
 await page.goto(origin+'/app/emails/'+rtl.id);await body().waitFor();await body().fill('مرحبا عالم جديد رابع؟');await openVoice();await oldRules();const rtlRow=row(JSON.stringify(['block','body','text']));await rtlRow.waitFor();assert.equal(await rtlRow.locator('pre').getAttribute('dir'),'rtl');assert.equal(await rtlRow.locator('pre').getAttribute('lang'),'he-IL');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await panel.screenshot({path:'output/live-voice-guard/rtl-mobile.png'});
 await page.goto(origin+'/app/emails/'+unset.id);await page.getByRole('textbox',{name:'Subject',exact:true}).waitFor();await openVoice();await panel.getByText('Pinned kit · v103',{exact:true}).waitFor();await panel.getByText('No brand phrase or numeric limits are configured.',{exact:true}).waitFor();await panel.getByText('No supported mechanical issues found.',{exact:true}).waitFor();assert.equal(await panel.locator('[data-live-voice-location]').count(),0);await panel.getByText('No AI evaluation or send approval.',{exact:false}).waitFor();await panel.getByRole('button',{name:'Hide live Voice Guard',exact:true}).click();await body().fill('Transient\u0000draft');assert.equal(await body().inputValue(),'Transient\u0000draft');assert.equal(await page.getByRole('button',{name:'Show live Voice Guard',exact:true}).count(),1,'Unsupported unsaved input must leave the closed-panel editor available');await openVoice();await panel.getByRole('alert').filter({hasText:'This draft could not be checked.'}).waitFor();assert.equal(await panel.locator('[data-live-voice-location]').count(),0);assert.equal(await body().inputValue(),'Transient\u0000draft');await body().fill('Corrected ordinary copy');await panel.getByText('No supported mechanical issues found.',{exact:true}).waitFor();await body().evaluate(node=>{const input=node as HTMLTextAreaElement;Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value')!.set!.call(input,'Transient'+String.fromCharCode(0xd800)+'draft');input.dispatchEvent(new Event('input',{bubbles:true}));});await panel.getByRole('alert').filter({hasText:'This draft could not be checked.'}).waitFor();assert.equal(await body().evaluate(node=>(node as HTMLTextAreaElement).value.charCodeAt(9)),0xd800);await panel.getByRole('button',{name:'Hide live Voice Guard',exact:true}).click();assert.equal(await body().evaluate(node=>(node as HTMLTextAreaElement).value.charCodeAt(9)),0xd800);await body().fill('Corrected ordinary copy');await openVoice();await panel.getByText('No supported mechanical issues found.',{exact:true}).waitFor();
 console.log('Transient NUL/unpaired-surrogate copy retains the closed and open editor, unavailable feedback and exact correctable input PASS.');
 assert.deepEqual(await records(),original);assert.equal(mutations,0);assert.equal(recoveryAfterEdit?.includes('Plain updated copy'),true);assert.deepEqual(errors,[]);assert.deepEqual(warnings,[]);assert.equal(external,0);
 console.log('RTL/mobile/unset and no-finding states preserve source and clearly distinguish mechanical feedback from frozen preflight and AI approval PASS.');
 }finally{await browser?.close();if(app&&app.exitCode===null){app.kill('SIGTERM');await new Promise<void>(resolve=>app!.once('exit',()=>resolve()));}await log.close();}
});console.log('Owned live-voice app stopped and disposable database removed PASS.');
