import assert from'node:assert/strict';import{randomUUID,randomBytes}from'node:crypto';import pg from'pg';import env from'@next/env';import{digest}from'../src/server/audit';import{chromium}from'playwright';env.loadEnvConfig(process.cwd());
const origin=process.env.APP_ORIGIN??'http://127.0.0.1:3003';if(process.env.LOCAL_DEVELOPMENT!=='true'||!['localhost','127.0.0.1'].includes(new URL(origin).hostname))throw new Error('Owned local lifecycle fixture required.');const db=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL}),workspace=randomUUID(),user='lifecycle-review-'+randomUUID(),cookie=randomBytes(32).toString('hex'),email=randomUUID(),revision=randomUUID(),hash=digest('Owned synthetic lifecycle content');let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
const timing={local_time:'2026-11-01T01:30',time_zone:'America/New_York',utc_offset:'-04:00',utc:'2026-11-01T05:30:00.000Z'};
async function call(path:string,method='GET',body?:unknown){const response=await fetch(origin+'/v1/'+path,{method,headers:{Origin:origin,'Content-Type':'application/json','Idempotency-Key':randomUUID(),Cookie:'mailcraft_local_session='+cookie,'X-Workspace-Id':workspace},body:body===undefined?undefined:JSON.stringify(body)});assert.ok(response.ok,'Owned lifecycle API fixture failed');return response.json();}
try{
 await db.query("INSERT INTO workspaces(id,name)VALUES($1,'Lifecycle fixture')",[workspace]);await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,'Owner')",[workspace,user]);await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,clock_timestamp()+interval '1 hour')",[digest(cookie),user]);
 // This is disclosed synthetic immutable fixture data; no compiler/provider acceptance claim.
 await db.query("INSERT INTO emails(workspace_id,id,title,spec,created_by)VALUES($1,$2,'Owned lifecycle content','{}',$3)",[workspace,email,user]);await db.query("INSERT INTO revisions(workspace_id,id,email_id,revision_no,spec,html,plaintext,artifact_hash,manifest,created_by)VALUES($1,$2,$3,1,'{}','<p>Owned lifecycle content</p>','Owned lifecycle content',$4,'{}',$5)",[workspace,revision,email,hash,user]);browser=await chromium.launch({headless:true});
 const selected=['review','cancel','version','delayed','uncertain','uncertain-uncommitted'].filter(mode=>process.argv.includes('--'+mode)),modes=selected.length?selected:['review','cancel','version','delayed','uncertain','uncertain-uncommitted'];
 for(const mode of modes){const id=randomUUID(),name='Original '+mode,intent={revision_id:revision,artifact_hash:hash,audience:[],provider:null,sender:null,topic:'marketing',schedule:null,tracking:false,planned_timing:timing};await db.query('INSERT INTO campaigns(workspace_id,id,name,revision_id,intent,digest,created_by)VALUES($1,$2,$3,$4,$5,$6,$7)',[workspace,id,name,revision,JSON.stringify(intent),digest(intent),user]);const context=await browser.newContext();await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);await context.addInitScript(w=>localStorage.setItem('mailcraft.workspace',w),workspace);const page=await context.newPage(),box=page.locator('[data-campaign-configuration="'+id+'"]'),card=page.locator('.campaign-card').filter({has:box}),field=box.getByLabel('Configuration name',{exact:true}),save=box.getByRole('button',{name:'Save draft configuration',exact:true});let posts=0;page.on('request',request=>{if(new URL(request.url()).pathname==='/v1/campaigns/'+id+'/configuration'&&request.method()==='POST')posts++;});
  let release!:()=>void,entered!:()=>void;const gate=new Promise<void>(r=>release=r),ready=new Promise<void>(r=>entered=r);if(mode==='delayed')await page.route('**/v1/campaigns/'+id,async route=>{const response=await route.fetch();entered();await gate;await route.fulfill({response});});
  try{await page.goto(origin+'/app/campaigns');if(mode==='delayed')await ready;else{await page.waitForFunction(({id,name})=>{const field=document.querySelector<HTMLInputElement>('[data-campaign-configuration="'+id+'"] input');return !!field&&!field.disabled&&field.value===name;},{id,name});await field.fill('Unsaved '+mode);await box.getByLabel('Planned local minute',{exact:true}).fill('2026-11-01T01:45');}
   if(mode==='uncertain'||mode==='uncertain-uncommitted'){const committed=mode==='uncertain';let originalKey='',originalBody='';await page.route('**/v1/campaigns/'+id+'/configuration',async route=>{originalKey=route.request().headers()['idempotency-key'];originalBody=route.request().postData()??'';if(!committed){await route.abort('failed');return;}const response=await route.fetch();assert.equal(response.status(),200);await route.abort('failed');});await save.click();await box.getByRole('alert').waitFor();await page.unrouteAll({behavior:'wait'});assert.equal((await call('campaigns/'+id)).campaign.version,committed?2:1);await card.getByRole('button',{name:'Cancel remaining work',exact:true}).click();await card.locator('.section-heading .badge').filter({hasText:'cancelled'}).waitFor();const retry=box.getByRole('button',{name:'Retry original configuration',exact:true});assert.equal(await field.inputValue(),'Unsaved '+mode);assert.equal(await save.isDisabled(),true);assert.equal(await retry.isEnabled(),true,'Cancellation must preserve original receipt recovery while fresh edits remain disabled');let retryKey='',retryBody='';await page.route('**/v1/campaigns/'+id+'/configuration',async route=>{retryKey=route.request().headers()['idempotency-key'];retryBody=route.request().postData()??'';await route.continue();});await retry.click();if(committed)await box.getByRole('status').filter({hasText:'Draft configuration saved.'}).waitFor();else await box.getByRole('alert').filter({hasText:'Only draft or review-pending campaigns can change configuration.'}).waitFor();assert.equal(retryKey,originalKey);assert.equal(retryBody,originalBody);await page.unrouteAll({behavior:'wait'});assert.equal((await call('campaigns/'+id)).campaign.state,'cancelled');assert.equal((await call('campaigns/'+id)).campaign.version,committed?2:1);assert.equal((await call('campaigns/'+id+'/configurations')).total_count,committed?2:1);assert.equal(await field.isDisabled(),true);assert.equal(await retry.count(),0);
   }else if(mode==='version'){const sibling=await call('campaigns','POST',{name:'Reload trigger '+mode,revision_id:revision});await page.reload();await page.waitForFunction(({id,name})=>document.querySelector<HTMLInputElement>('[data-campaign-configuration="'+id+'"] input')?.value===name,{id,name:'Unsaved '+mode});assert.equal(await box.getByLabel('Planned local minute',{exact:true}).inputValue(),'2026-11-01T01:45');await field.fill('Unsaved '+mode);await call('campaigns/'+id+'/configuration','POST',{expected_version:1,name:'New remote version',revision_id:revision,planned_timing:null});await page.locator('.campaign-card').filter({has:page.getByRole('heading',{name:'Reload trigger '+mode,exact:true})}).getByRole('button',{name:'Request review',exact:true}).click();await card.getByRole('heading',{name:'New remote version',exact:true}).waitFor();assert.equal(await field.inputValue(),'Unsaved '+mode);assert.equal(await save.isDisabled(),true,'Known newer configuration must not silently advance the form base');assert.match(await box.innerText(),/form.*v1|base.*v1/i);assert.equal(posts,0);await box.getByRole('button',{name:'Reload saved configuration',exact:true}).click();await page.waitForFunction(id=>document.querySelector<HTMLInputElement>('[data-campaign-configuration="'+id+'"] input')?.value==='New remote version',id);assert.equal((await call('campaigns/'+id)).campaign.version,2);assert.ok(sibling.campaign.id);
   }else{await card.getByRole('button',{name:'Request review',exact:true}).click();await card.locator('.section-heading .badge').filter({hasText:'review pending'}).waitFor();if(mode==='review'){await box.locator('p').filter({hasText:/Configuration v1 · review pending/}).waitFor({timeout:4000});assert.equal(await field.inputValue(),'Unsaved '+mode);assert.equal(await box.getByLabel('Configuration frozen revision',{exact:true}).inputValue(),revision);assert.equal(await box.getByLabel('Planned local minute',{exact:true}).inputValue(),'2026-11-01T01:45');assert.equal(await save.isEnabled(),true);await save.click();await box.getByRole('status').filter({hasText:'Draft configuration saved.'}).waitFor();assert.equal((await call('campaigns/'+id)).campaign.state,'draft');assert.equal((await call('campaigns/'+id)).campaign.version,2);
    }else{await card.getByRole('button',{name:'Cancel remaining work',exact:true}).click();await card.locator('.section-heading .badge').filter({hasText:'cancelled'}).waitFor();if(mode==='delayed'){release();await page.unrouteAll({behavior:'wait'});}await box.locator('p').filter({hasText:/Configuration v1 · cancelled/}).waitFor({timeout:4000});assert.equal(await field.isEnabled(),false);assert.equal(await save.isDisabled(),true);if(mode==='cancel'){assert.equal(await field.inputValue(),'Unsaved '+mode);assert.equal(await box.getByLabel('Planned local minute',{exact:true}).inputValue(),'2026-11-01T01:45');}await save.evaluate((button:HTMLButtonElement)=>{button.click();button.click();});assert.equal(posts,0);assert.equal((await call('campaigns/'+id)).campaign.state,'cancelled');}
   }
  }finally{release();await page.unrouteAll({behavior:'wait'});await context.close();}
  console.log('Owned lifecycle HTTP/Chromium PASS '+mode+': current state/controls, unchanged typed settings and explicit base; no provider calls.');
 }
}finally{await browser?.close();for(const table of['campaigns','revisions','emails','idempotency','audit_events','memberships'])await db.query('DELETE FROM '+table+' WHERE workspace_id=$1',[workspace]);await db.query('DELETE FROM auth_sessions WHERE user_id=$1',[user]);await db.query('DELETE FROM workspaces WHERE id=$1',[workspace]);await db.end();}
