import assert from 'node:assert/strict';
import { randomUUID, randomBytes } from 'node:crypto';
import pg from 'pg';
import env from '@next/env';
import { digest } from '../src/server/audit';
import { validateApiResponse } from './api-validation';
env.loadEnvConfig(process.cwd());
const origin=process.env.APP_ORIGIN??'http://127.0.0.1:3003';
if(process.env.LOCAL_DEVELOPMENT!=='true'||!['localhost','127.0.0.1'].includes(new URL(origin).hostname))throw new Error('Owned loopback calendar fixture required.');
const db=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL}),workspace=randomUUID(),other=randomUUID(),user='calendar-http-'+randomUUID(),cookie=randomBytes(32).toString('hex'),email=randomUUID(),revision=randomUUID();
async function call(path:string,method='GET',body?:unknown,key:string=randomUUID(),w:string=workspace,bearer?:string){const r=await fetch(origin+'/v1/'+path,{method,headers:{Origin:origin,'Content-Type':'application/json','Idempotency-Key':key,...(bearer?{Authorization:'Bearer '+bearer}:{Cookie:'mailcraft_local_session='+cookie,'X-Workspace-Id':w})},body:body===undefined?undefined:JSON.stringify(body)});return{r,j:await r.json()};}
try{
 await db.query("INSERT INTO workspaces(id,name)VALUES($1,'Calendar HTTP fixture'),($2,'Calendar HTTP foreign')",[workspace,other]);
 for(const w of[workspace,other])await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,'Owner')",[w,user]);
 await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,clock_timestamp()+interval '1 hour')",[digest(cookie),user]);
 // Disclosed synthetic frozen content isolates calendar behavior; no compiler/provider claim.
 const hash=digest('Owned synthetic calendar content');await db.query("INSERT INTO emails(workspace_id,id,title,spec,created_by)VALUES($1,$2,'Owned calendar content','{}',$3)",[workspace,email,user]);await db.query("INSERT INTO revisions(workspace_id,id,email_id,revision_no,spec,html,plaintext,artifact_hash,manifest,created_by)VALUES($1,$2,$3,1,'{}','<p>Owned content</p>','Owned content',$4,'{}',$5)",[workspace,revision,email,hash,user]);
 const initial=await call('workspace-preferences');assert.equal(initial.r.status,200,'Calendar preference read is implemented');validateApiResponse('getWorkspacePreferences',200,initial.j);assert.equal(initial.j.preferences.time_zone,'UTC');assert.equal(initial.j.preferences.version,1);
 const ids:string[]=[];for(const[name,local_time,time_zone,utc_offset]of[['First fold','2026-11-01T01:30','America/New_York','-04:00'],['Second fold','2026-11-01T01:30','America/New_York','-05:00'],['Month crossing','2026-11-01T00:15','Asia/Kathmandu','+05:45']]as const){const made=await call('campaigns','POST',{name,revision_id:revision});assert.equal(made.r.status,200);ids.push(made.j.campaign.id);const configured=await call('campaigns/'+made.j.campaign.id+'/configuration','POST',{expected_version:1,name,revision_id:revision,planned_timing:{local_time,time_zone,utc_offset}});assert.equal(configured.r.status,200);}
 const originals=(await db.query('SELECT id,intent,digest,version,planned_at FROM campaigns WHERE workspace_id=$1 ORDER BY id',[workspace])).rows;
 const november=await call('campaigns/calendar?month=2026-11&limit=1');assert.equal(november.r.status,200);validateApiResponse('getCampaignCalendar',200,november.j);assert.equal(november.j.total_count,2);assert.equal(november.j.time_zone,'UTC');assert.equal(november.j.data[0].name,'Second fold');assert.equal(november.j.data[0].display.local_time,'06:30');assert.equal(november.j.has_more,true);
 const next=await call('campaigns/calendar?month=2026-11&limit=1&after='+encodeURIComponent(november.j.next_cursor));assert.equal(next.r.status,200);assert.equal(next.j.data[0].name,'First fold');assert.equal(next.j.has_more,false);assert.equal(next.j.data[0].intent,undefined);assert.equal(next.j.data[0].audience,undefined);assert.equal(next.j.data[0].provider,undefined);
 const october=await call('campaigns/calendar?month=2026-10');assert.equal(october.j.total_count,1);assert.equal(october.j.data[0].display.local_date,'2026-10-31');assert.equal(october.j.data[0].planned_timing.local_time,'2026-11-01T00:15');assert.equal((await call('campaigns/calendar?month=2026-12')).j.total_count,0);
 assert.equal((await call('campaigns/calendar?month=2026-10&after='+encodeURIComponent(november.j.next_cursor))).j.error.code,'INVALID_CURSOR');assert.equal((await call('campaigns/calendar?month=2026-11&after='+encodeURIComponent(november.j.next_cursor),'GET',undefined,randomUUID(),other)).j.error.code,'INVALID_CURSOR');assert.equal((await call('campaigns/calendar?month=2026-11','GET',undefined,randomUUID(),other)).j.total_count,0);
 for(const query of['','?month=2026-2','?month=0000-01','?month=2026-11&time_zone=UTC','?month=2026-11&month=2026-10','?month=2026-11&created_after=2026-01-01T00:00:00Z'])assert.equal((await call('campaigns/calendar'+query)).r.status,422);
 assert.equal((await call('campaigns/calendar','POST',{})).r.status,405);assert.equal((await call('workspace-preferences/timezone')).r.status,405);assert.equal((await call('workspace-preferences/timezone%2Fother','POST',{})).r.status,404);
 const body={expected_version:1,time_zone:'Asia/Kathmandu'},key=randomUUID();for(const extra of[{approval:{}},{workspace_id:other},{timezone_version:7},{status:'active'}])assert.equal((await call('workspace-preferences/timezone','POST',{...body,...extra})).r.status,422);
 assert.equal((await call('workspace-preferences/timezone','POST',{...body,time_zone:'Mars/Phobos'})).r.status,422);assert.equal((await call('workspace-preferences/timezone','POST',{...body,time_zone:'+05:45'})).r.status,422);
 const changed=await call('workspace-preferences/timezone','POST',body,key);assert.equal(changed.r.status,200);validateApiResponse('setWorkspaceTimezone',200,changed.j);assert.equal(changed.j.changed,true);assert.equal(changed.j.preferences.version,2);assert.equal(changed.j.preferences.time_zone,'Asia/Kathmandu');assert.equal((await call('workspace-preferences/timezone','POST',body,key)).j.preferences.version,2);assert.equal((await call('workspace-preferences/timezone','POST',{...body,time_zone:'UTC'},key)).j.error.code,'IDEMPOTENCY_MISMATCH');assert.equal((await call('workspace-preferences/timezone','POST',{...body,time_zone:'UTC'})).j.error.code,'VERSION_CONFLICT');const noop=await call('workspace-preferences/timezone','POST',{...body,expected_version:2});assert.equal(noop.j.changed,false);assert.equal(noop.j.preferences.version,2);
 assert.equal((await call('campaigns/calendar?month=2026-11&after='+encodeURIComponent(november.j.next_cursor))).j.error.code,'INVALID_CURSOR');const regrouped=await call('campaigns/calendar?month=2026-11');assert.equal(regrouped.j.total_count,3);assert.equal(regrouped.j.timezone_version,2);
 const newer=await call('workspace-preferences/timezone','POST',{expected_version:2,time_zone:'America/New_York'});assert.equal(newer.j.preferences.version,3);const replay=await call('workspace-preferences/timezone','POST',body,key);assert.equal(replay.j.preferences.version,3);assert.equal(replay.j.preferences.time_zone,'America/New_York');const folds=(await call('campaigns/calendar?month=2026-11')).j.data;assert.equal(folds.length,2);assert.deepEqual(folds.map((row:{display:{local_time:string;utc_offset:string}})=>[row.display.local_time,row.display.utc_offset]),[['01:30','-05:00'],['01:30','-04:00']]);
 assert.deepEqual((await db.query('SELECT id,intent,digest,version,planned_at FROM campaigns WHERE workspace_id=$1 ORDER BY id',[workspace])).rows,originals);
 for(const role of['Editor','Viewer','Billing']){await db.query('UPDATE memberships SET role=$1 WHERE workspace_id=$2 AND user_id=$3',[role,workspace,user]);assert.equal((await call('workspace-preferences/timezone','POST',{expected_version:3,time_zone:'UTC'})).r.status,403);assert.equal((await call('workspace-preferences')).r.status,role==='Billing'?403:200);assert.equal((await call('campaigns/calendar?month=2026-11')).r.status,role==='Billing'?403:200);}await db.query("UPDATE memberships SET role='Owner'WHERE workspace_id=$1 AND user_id=$2",[workspace,user]);
 const reader=(await call('api-keys','POST',{name:'Owned calendar reader',scopes:['campaigns:read'],expires_in_days:1})).j.secret;assert.equal((await call('campaigns/calendar?month=2026-11','GET',undefined,randomUUID(),workspace,reader)).r.status,200);assert.equal((await call('workspace-preferences/timezone','POST',{expected_version:3,time_zone:'UTC'},randomUUID(),workspace,reader)).j.error.code,'SESSION_REQUIRED');assert.equal((await call('workspace-preferences','GET',undefined,randomUUID(),workspace,reader)).j.error.code,'SESSION_REQUIRED');const wrong=(await call('api-keys','POST',{name:'Owned wrong calendar scope',scopes:['emails:read'],expires_in_days:1})).j.secret;assert.equal((await call('campaigns/calendar?month=2026-11','GET',undefined,randomUUID(),workspace,wrong)).r.status,403);
 if(!process.argv.includes('--api')){const{verifyCalendarBrowser}=await import('./calendar-browser');await verifyCalendarBrowser({origin,workspace,other,cookie,revision,call,db,user});}
 console.log('Owned calendar HTTP PASS: strict metadata, fold/month grouping, signed scope/tenant/month/timezone-version cursors, manager CAS/replay/no-op, frozen campaign preservation; no provider calls.');
}finally{for(const table of['api_rate_events','api_keys','campaigns','revisions','emails','idempotency','audit_events','memberships'])await db.query('DELETE FROM '+table+' WHERE workspace_id=ANY($1::uuid[])',[[workspace,other]]);await db.query('DELETE FROM auth_sessions WHERE user_id=$1',[user]);await db.query('DELETE FROM workspaces WHERE id=ANY($1::uuid[])',[[workspace,other]]);await db.end();}
