import assert from'node:assert/strict';import{randomUUID,randomBytes}from'node:crypto';import pg from'pg';import env from'@next/env';import{chromium}from'playwright';import{digest}from'../src/server/audit';import{tenant,closeDb}from'../src/server/db';import{persistWebhookEndpoint}from'../src/server/webhook-endpoints';import{parseWebhookVault}from'../src/server/webhook-secrets';import{recordEvent}from'../src/server/events';import{apiSpec,absoluteSchema,validateSchema}from'./api-validation';env.loadEnvConfig(process.cwd());
const origin=process.env.APP_ORIGIN??'http://127.0.0.1:3000';if(process.env.LOCAL_DEVELOPMENT!=='true'||!['127.0.0.1','localhost'].includes(new URL(origin).hostname))throw new Error('Owned local history fixtures only');
const db=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL}),workspace=randomUUID(),other=randomUUID(),user='webhook-history-'+randomUUID(),cookie=randomBytes(32).toString('hex');let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
const fixtureLock=await db.connect();await fixtureLock.query("SELECT pg_advisory_lock(hashtextextended('lettercape.fixture.webhook-queue',0))");
async function call(path:string,method='GET',body?:unknown,key=randomUUID(),w=workspace,bearer?:string){const r=await fetch(origin+'/v1/'+path,{method,headers:{Origin:origin,'Content-Type':'application/json','Idempotency-Key':key,...(bearer?{Authorization:'Bearer '+bearer}:{Cookie:'mailcraft_local_session='+cookie,'X-Workspace-Id':w})},body:body===undefined?undefined:JSON.stringify(body)});return{r,j:await r.json()};}
try{
 await db.query("INSERT INTO workspaces(id,name)VALUES($1,'History HTTP fixture'),($2,'History foreign')",[workspace,other]);await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$3,'Owner'),($2,$3,'Owner')",[workspace,other,user]);await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,now()+interval '1 hour')",[digest(cookie),user]);
 const initial=await call('webhook-deliveries');assert.equal(initial.r.status,200,'Scoped durable delivery history exists');validateSchema(absoluteSchema(apiSpec.components.schemas.WebhookDeliveriesPage),initial.j);assert.deepEqual(initial.j.data,[]);assert.equal(initial.j.configuration.delivery_enabled,false);
 browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844}});await context.addInitScript((w)=>localStorage.setItem('mailcraft.workspace',w),workspace);await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);const page=await context.newPage();await page.goto(origin+'/app/settings');const panel=page.locator('.webhook-history-panel');await panel.getByText('No webhook delivery receipt yet.',{exact:true}).waitFor();
 const raw=process.env.WEBHOOK_ENCRYPTION_KEYS_JSON??JSON.stringify({fixture:randomBytes(32).toString('hex')}),vault=parseWebhookVault(raw,process.env.WEBHOOK_ENCRYPTION_ACTIVE_KEY??'fixture');const endpoint=await tenant(workspace,user,(tx)=>persistWebhookEndpoint(tx,{workspace,user,role:'Owner'},{name:'History fixture',url:'https://example.org/hook?private=never-show',subscriptions:['contact.unsubscribed']},vault,new Date().toISOString()));await db.query("UPDATE webhook_endpoints SET status='enabled',version=version+1 WHERE workspace_id=$1",[workspace]);
 const ids:string[]=[];
 for(let i=0;i<26;i++){const contact=randomUUID();await db.query("INSERT INTO contacts(workspace_id,id,email_original,email_lookup,subscription,consent_version)VALUES($1,$2,$3,$3,'unsubscribed',2)",[workspace,contact,contact+'@example.org']);await db.query("INSERT INTO suppressions(workspace_id,contact_id,reason)VALUES($1,$2,'unsubscribe')",[workspace,contact]);const event=await tenant(workspace,user,(tx)=>recordEvent(tx,workspace,{type:'contact.unsubscribed',aggregate:{type:'contact',id:contact,version:2},data:{contact_id:contact,scope:'marketing',reason:'recipient_opt_out'}}));ids.push((await db.query("INSERT INTO webhook_deliveries(workspace_id,endpoint_id,event_id,state,attempt_number,error_class)VALUES($1,$2,$3,'terminal',1,'http_terminal')RETURNING id",[workspace,endpoint.endpoint.id,event.id])).rows[0].id);}
 const delivery=ids.at(-1)!;await db.query("INSERT INTO webhook_attempts(workspace_id,delivery_id,attempt_number,phase,status_code,error_class)SELECT $1,$2,n,'settled',400,'http_terminal' FROM generate_series(1,101)n",[workspace,delivery]);await db.query('UPDATE webhook_deliveries SET attempt_number=101 WHERE workspace_id=$1 AND id=$2',[workspace,delivery]);
 const first=await call('webhook-deliveries');validateSchema(absoluteSchema(apiSpec.components.schemas.WebhookDeliveriesPage),first.j);assert.equal(first.j.total_count,26);assert.equal(first.j.data.length,25);assert.equal(first.j.has_more,true);assert.ok(!JSON.stringify(first.j).includes('never-show'));assert.equal(first.j.data.some((row:Record<string,unknown>)=>'lease_token'in row||'event_body'in row||'wrapped_secret'in row),false);
 const older=await call('webhook-deliveries?after='+encodeURIComponent(first.j.next_cursor));assert.equal(older.j.data.length,1);assert.equal(new Set([...first.j.data,...older.j.data].map((r:{id:string})=>r.id)).size,26);
 assert.equal((await call('webhook-deliveries?state=pending&after='+encodeURIComponent(first.j.next_cursor))).r.status,400);assert.equal((await call('webhook-deliveries?after='+encodeURIComponent(first.j.next_cursor), 'GET',undefined,randomUUID(),other)).r.status,400);
 assert.equal((await call('webhook-deliveries/'+delivery,'GET',undefined,randomUUID(),other)).r.status,404);const attempts=await call('webhook-deliveries/'+delivery+'/attempts');validateSchema(absoluteSchema(apiSpec.components.schemas.WebhookAttemptsPage),attempts.j);assert.equal(attempts.j.total_count,101);assert.equal(attempts.j.data.length,25);const attempts2=await call('webhook-deliveries/'+delivery+'/attempts?after='+encodeURIComponent(attempts.j.next_cursor));assert.equal(new Set([...attempts.j.data,...attempts2.j.data].map((r:{id:string})=>r.id)).size,50);
 assert.equal((await call('webhook-deliveries/'+ids[0]+'/attempts?after='+encodeURIComponent(attempts.j.next_cursor))).r.status,400);
 for(const role of['Viewer','Editor','Billing']){await db.query('UPDATE memberships SET role=$1 WHERE workspace_id=$2',[role,workspace]);assert.equal((await call('webhook-deliveries')).r.status,403);assert.equal((await call('webhook-deliveries/'+delivery+'/attempts')).r.status,403);}await db.query("UPDATE memberships SET role='Owner'WHERE workspace_id=$1",[workspace]);
 const reader=(await call('api-keys','POST',{name:'History reader',scopes:['webhooks:read'],expires_in_days:1})).j.secret,writer=(await call('api-keys','POST',{name:'History writer',scopes:['webhooks:write'],expires_in_days:1})).j.secret;
 assert.equal((await call('%77ebhook-deliveries','GET',undefined,randomUUID(),workspace,reader)).r.status,200);assert.equal((await call('webhook-deliveries/'+delivery+'/replay','POST',{expected_attempt:1,acknowledge_duplicate_effect:true},randomUUID(),workspace,reader)).r.status,403);
 await context.setOffline(true);await panel.getByRole('button',{name:'Reload webhook delivery history',exact:true}).click();await panel.getByRole('alert').filter({hasText:/fetch|network|Failed/i}).waitFor();await context.setOffline(false);await panel.getByRole('button',{name:'Reload webhook delivery history',exact:true}).evaluate((element)=>{(element as HTMLButtonElement).click();(element as HTMLButtonElement).click();});await panel.getByText('26 deliveries',{exact:true}).waitFor();await panel.getByRole('button',{name:'Load older webhook deliveries',exact:true}).click();await panel.locator('article').nth(25).waitFor();assert.equal(await panel.locator('article').count(),26);
 await panel.getByRole('button',{name:'Read attempts for '+delivery,exact:true}).click();await panel.getByRole('button',{name:'Load older webhook attempts',exact:true}).waitFor();await panel.getByRole('button',{name:'Load older webhook attempts',exact:true}).click();
 const replayBody={expected_attempt:1,acknowledge_duplicate_effect:true};
 if(initial.j.configuration.key_configured){
  assert.equal((await call('webhook-deliveries/'+ids[0]+'/replay','POST',{expected_attempt:1,acknowledge_duplicate_effect:false})).r.status,422);const key=randomUUID();assert.equal((await call('webhook-deliveries/'+ids[0]+'/replay','POST',replayBody,key,workspace,writer)).r.status,200);assert.equal((await call('webhook-deliveries/'+ids[0]+'/replay','POST',replayBody,key,workspace,writer)).j.delivery.state,'pending');
  let lost=true;const observed:{key:string|undefined;input:unknown}[]=[];const path='**/v1/webhook-deliveries/'+delivery+'/replay';await page.route(path,async(route)=>{observed.push({key:route.request().headers()['idempotency-key'],input:route.request().postDataJSON()});if(!lost)return route.continue();lost=false;await route.fetch();await route.abort('failed');});
  await panel.getByLabel(/I reviewed the failure and receiver deduplication/).check();await panel.getByRole('button',{name:'Replay failed delivery '+delivery,exact:true}).click();await panel.getByRole('alert').filter({hasText:/fetch|network|Failed/i}).waitFor();await page.reload();await panel.getByRole('button',{name:'Recover pending replay for '+delivery,exact:true}).waitFor();await panel.getByLabel(/I reviewed the failure and receiver deduplication/).check();await panel.getByRole('button',{name:'Recover pending replay for '+delivery,exact:true}).evaluate((element)=>{(element as HTMLButtonElement).click();(element as HTMLButtonElement).click();});await panel.getByRole('status').filter({hasText:/Replay command acknowledged.*pending/i}).waitFor();assert.equal(observed.length,2);assert.deepEqual(observed[0],observed[1]);await page.unroute(path);assert.equal((await db.query("SELECT count(*)::int AS n FROM audit_events WHERE workspace_id=$1 AND action='webhook.delivery.replay'AND resource_id=$2",[workspace,delivery])).rows[0].n,1);assert.equal((await db.query('SELECT count(*)::int AS n FROM webhook_attempts WHERE workspace_id=$1 AND delivery_id=$2',[workspace,delivery])).rows[0].n,101);
  // Another operator advances the attempt after this view was read. Definite CAS
  // rejection releases recovery; reload starts a new command against the current attempt.
  const stale=ids[1],stalePath='**/v1/webhook-deliveries/'+stale+'/replay',staleObserved:{key:string|undefined;input:unknown}[]=[];
  await db.query("UPDATE webhook_deliveries SET attempt_number=2 WHERE workspace_id=$1 AND id=$2",[workspace,stale]);
  await page.route(stalePath,async(route)=>{staleObserved.push({key:route.request().headers()['idempotency-key'],input:route.request().postDataJSON()});await route.continue();});
  await panel.getByLabel(/I reviewed the failure and receiver deduplication/).check();await panel.getByRole('button',{name:'Replay failed delivery '+stale,exact:true}).click();await panel.getByRole('alert').filter({hasText:/This replay had no effect because its attempt changed/}).waitFor();
  await page.reload();await panel.getByRole('button',{name:'Replay failed delivery '+stale,exact:true}).waitFor();assert.equal(await panel.getByRole('button',{name:'Recover pending replay for '+stale,exact:true}).count(),0);
  await panel.getByLabel(/I reviewed the failure and receiver deduplication/).check();await panel.getByRole('button',{name:'Replay failed delivery '+stale,exact:true}).click();await panel.getByRole('status').filter({hasText:/Replay command acknowledged.*pending/i}).waitFor();
  assert.equal(staleObserved.length,2);assert.notEqual(staleObserved[0].key,staleObserved[1].key);assert.deepEqual(staleObserved.map((r)=>r.input),[{expected_attempt:1,acknowledge_duplicate_effect:true},{expected_attempt:2,acknowledge_duplicate_effect:true}]);assert.equal((await db.query("SELECT count(*)::int AS n FROM audit_events WHERE workspace_id=$1 AND action='webhook.delivery.replay'AND resource_id=$2",[workspace,stale])).rows[0].n,1);await page.unroute(stalePath);
 }else{assert.equal((await call('webhook-deliveries/'+delivery+'/replay','POST',{...replayBody,expected_attempt:101})).r.status,503);assert.equal(await panel.getByRole('button',{name:'Replay failed delivery '+delivery,exact:true}).isDisabled(),true);}
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await panel.scrollIntoViewIfNeeded();await page.screenshot({path:'output/playwright/lettercape-webhook-history-mobile.png',fullPage:false});
 let entered!:()=>void,release!:()=>void;const ready=new Promise<void>((r)=>{entered=r;}),gate=new Promise<void>((r)=>{release=r;});await page.route('**/v1/webhook-deliveries',async(route)=>{const response=await route.fetch();entered();await gate;await route.fulfill({response});});await panel.getByRole('button',{name:'Reload webhook delivery history',exact:true}).click();await ready;await page.getByRole('button',{name:'Open navigation'}).click();await page.getByLabel('Active brand workspace').selectOption(other);await page.getByRole('heading',{name:'Make something worth opening.',exact:true}).waitFor();release();await page.evaluate(()=>new Promise((r)=>requestAnimationFrame(()=>requestAnimationFrame(()=>r(true)))));assert.equal(await page.locator('.webhook-history-panel').count(),0);
 console.log('Actual26 synthetic durable receipts/101 immutable attempts, redacted scoped signed paging, role/encoded/scope/foreign guards and Chromium empty/offline/repeat/mobile/workspace pass; configured='+initial.j.configuration.key_configured+'; external deliveries0.');
}finally{await browser?.close();for(const table of['webhook_attempts','webhook_deliveries','webhook_queue_state','webhook_signing_keys','webhook_endpoints','outbox','suppressions','contacts','api_rate_events','api_keys','idempotency','audit_events','memberships'])await db.query(`DELETE FROM ${table} WHERE workspace_id=ANY($1::uuid[])`,[[workspace,other]]);await db.query('DELETE FROM auth_sessions WHERE user_id=$1',[user]);await db.query('DELETE FROM workspaces WHERE id=ANY($1::uuid[])',[[workspace,other]]);await fixtureLock.query("SELECT pg_advisory_unlock(hashtextextended('lettercape.fixture.webhook-queue',0))");fixtureLock.release();await db.end();await closeDb();}
