import assert from'node:assert/strict';import{randomUUID,randomBytes}from'node:crypto';import pg from'pg';import env from'@next/env';import{digest}from'../src/server/audit';import{blankSpec}from'../src/domain/email';import{chromium}from'playwright';env.loadEnvConfig(process.cwd());
const origin=process.env.APP_ORIGIN??'http://127.0.0.1:3003';if(process.env.LOCAL_DEVELOPMENT!=='true'||!['localhost','127.0.0.1'].includes(new URL(origin).hostname))throw new Error('Owned local campaign review fixture required.');const db=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL}),workspace=randomUUID(),user='campaign-review-'+randomUUID(),cookie=randomBytes(32).toString('hex');let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
async function call(path:string,method='GET',body?:unknown,version?:number){const response=await fetch(origin+'/v1/'+path,{method,headers:{Origin:origin,'Content-Type':'application/json','Idempotency-Key':randomUUID(),Cookie:'mailcraft_local_session='+cookie,'X-Workspace-Id':workspace,...(version?{'If-Match':'"draft-'+version+'"'}:{})},body:body===undefined?undefined:JSON.stringify(body)});assert.ok(response.ok,'Owned review setup failed');return response.json();}
try{
 await db.query("INSERT INTO workspaces(id,name)VALUES($1,'Campaign review fixture')",[workspace]);await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,'Owner')",[workspace,user]);await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,clock_timestamp()+interval '1 hour')",[digest(cookie),user]);
 const brand=(await call('brands','POST',{name:'Review fixture',website:'',description:'Owned fixture',voice:'Plain',accent:'#0B625D',background:'#F7F6F2',font_stack:'Arial, sans-serif',address:'Reserved fixture address',approved_claims:[],forbidden_phrases:[],provenance:[]})).brand,spec=blankSpec(brand.id,'Review fixture'),email=(await call('emails','POST',{title:'Owned review content',spec})).email,revision=(await call('emails/'+email.id+'/revisions','POST',{},email.doc_version)).revision;
 browser=await chromium.launch({headless:true});
 for(const mode of process.argv.includes('--refresh')?['refresh']:process.argv.includes('--storage')?['storage']:['refresh','storage']){
  const campaign=(await call('campaigns','POST',{name:'Original '+mode,revision_id:revision.id})).campaign,path='campaigns/'+campaign.id,context=await browser.newContext();await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);await context.addInitScript(({w,unavailable})=>{localStorage.setItem('mailcraft.workspace',w);if(unavailable)Object.defineProperty(window,'sessionStorage',{get(){throw new DOMException('Controlled unavailable storage','SecurityError');}});},{w:workspace,unavailable:mode==='storage'});const page=await context.newPage();
  const box=page.locator('[data-campaign-configuration="'+campaign.id+'"]'),field=box.getByLabel('Configuration name',{exact:true}),save=box.getByRole('button',{name:'Save draft configuration',exact:true});await page.goto(origin+'/app/campaigns');await page.waitForFunction(({id,value})=>document.querySelector<HTMLInputElement>('[data-campaign-configuration="'+id+'"] input')?.value===value,{id:campaign.id,value:'Original '+mode});await field.fill('Saved '+mode);
  const keys:string[]=[],statuses:number[]=[];let postAccepted=false,failRead=true;page.on('request',request=>{if(new URL(request.url()).pathname==='/v1/'+path+'/configuration'&&request.method()==='POST')keys.push(request.headers()['idempotency-key']);});
  await page.route('**/v1/'+path+'/configuration',async route=>{const response=await route.fetch();statuses.push(response.status());postAccepted=response.ok();if(mode==='storage'&&keys.length===1)await route.abort('failed');else await route.fulfill({response});});
  if(mode==='refresh')await page.route('**/v1/'+path,async route=>{if(postAccepted&&failRead){failRead=false;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'FIXTURE_POST_ACK_READ',message:'Controlled saved-configuration refresh failure'}})});}else await route.continue();});
  await save.click();await box.getByRole('alert').waitFor();assert.equal((await call(path)).campaign.version,2);assert.equal(await field.inputValue(),'Saved '+mode);assert.equal(await field.isEnabled(),false);const retried=page.waitForResponse(response=>new URL(response.url()).pathname==='/v1/'+path+'/configuration'&&response.request().method()==='POST');await box.getByRole('button',{name:'Retry original configuration',exact:true}).click();await retried;assert.equal(keys.length,2);assert.equal(keys[0],keys[1],mode+' recovery must retain the exact original command key');await box.getByRole('status').filter({hasText:'Draft configuration saved.'}).waitFor();assert.deepEqual(statuses,[200,200]);assert.equal((await call(path)).campaign.version,2);assert.equal((await call(path+'/configurations')).total_count,2);await context.close();
  console.log('Campaign owned HTTP/Chromium review recovery PASS: '+mode+' original key, acknowledged version2, exactly two snapshots; no provider requests.');
 }
}finally{await browser?.close();for(const table of['campaigns','preflights','revisions','emails','outbox','api_rate_events','api_keys','idempotency','audit_events','memberships','brands'])await db.query('DELETE FROM '+table+' WHERE workspace_id=$1',[workspace]);await db.query('DELETE FROM auth_sessions WHERE user_id=$1',[user]);await db.query('DELETE FROM workspaces WHERE id=$1',[workspace]);await db.end();}
