import assert from'node:assert/strict';
import {randomUUID,randomBytes}from'node:crypto';
import pg from'pg';
import env from'@next/env';
import {blankSpec}from'../src/domain/email';
import {digest}from'../src/server/audit';
import {validateSchema,apiSpec}from'./api-validation';
env.loadEnvConfig(process.cwd());
const origin=process.env.APP_ORIGIN??'http://127.0.0.1:3003';if(process.env.LOCAL_DEVELOPMENT!=='true'||!['127.0.0.1','localhost'].includes(new URL(origin).hostname))throw Error('Owned loopback conversion fixture required.');
const db=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL}),workspace=randomUUID(),other=randomUUID(),brand=randomUUID(),email=randomUUID(),foreign=randomUUID(),actors=new Map<string,{user:string;cookie:string}>();
async function call(path:string,body?:unknown,role='Owner',headers:Record<string,string>={},method=body===undefined?'GET':'POST',tenant=workspace){const actor=actors.get(role)!;const response=await fetch(origin+'/v1/'+path,{method,headers:{Cookie:'mailcraft_local_session='+actor.cookie,'X-Workspace-Id':tenant,Origin:origin,'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});return {status:response.status,body:await response.json()};}
const source={...blankSpec(brand,'Owned conversion'),editing_mode:'raw_html' as const,raw_html:'<h1>Exact title</h1><p>Exact original copy</p><table><tbody><tr><td>Opaque layout preserved</td></tr></tbody></table>'};
try{
 await db.query("INSERT INTO workspaces(id,name)VALUES($1,'Owned conversion API'),($2,'Owned foreign conversion API')",[workspace,other]);
 for(const role of['Owner','Admin','Editor','Viewer','Billing']){const user='conversion-api-'+role+'-'+randomUUID(),cookie=randomBytes(32).toString('hex');actors.set(role,{user,cookie});await db.query('INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,$3)',[workspace,user,role]);await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,clock_timestamp()+interval '1hour')",[digest(cookie),user]);}
 await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,'Owner')",[other,actors.get('Owner')!.user]);await db.query("INSERT INTO brands(workspace_id,id,version,data)VALUES($1,$2,1,'{}')",[workspace,brand]);await db.query('INSERT INTO emails(workspace_id,id,title,spec,created_by)VALUES($1,$2,$3,$4,$5)',[workspace,email,'Owned conversion API',JSON.stringify(source),actors.get('Owner')!.user]);const foreignBrand=randomUUID();await db.query("INSERT INTO brands(workspace_id,id,version,data)VALUES($1,$2,1,'{}')",[other,foreignBrand]);await db.query('INSERT INTO emails(workspace_id,id,title,spec,created_by)VALUES($1,$2,$3,$4,$5)',[other,foreign,'Foreign conversion',JSON.stringify({...source,brand_kit_version_id:foreignBrand}),actors.get('Owner')!.user]);
 const path='emails/'+email,prepare=path+'/conversion-proposal',accept=path+'/convert-to-blocks';
 assert.equal((await call(prepare,{expected_version:1},'Viewer')).status,403);assert.equal((await call(prepare,{expected_version:1},'Billing')).status,403);assert.equal((await call('emails/'+foreign+'/conversion-proposal',{expected_version:1})).status,404);assert.equal((await call(prepare,{expected_version:1},'Owner',{'X-Actor-Id':'different-account'})).body.error.code,'ACTOR_CHANGED');
 for(const body of[{expected_version:'1'},{expected_version:1,credentials:'forged'},{expected_version:0}])assert.equal((await call(prepare,body)).status,422);assert.equal((await call(prepare+'?extra=1',{expected_version:1})).status,422);
 const prepared=await call(prepare,{expected_version:1},'Editor');assert.equal(prepared.status,200);const projection=apiSpec.paths['/v1/emails/{id}/conversion-proposal'].post.responses[200].content['application/json'].schema;validateSchema(projection,prepared.body);const proposal=prepared.body.proposal;assert.equal(proposal.status,'available');assert.equal(proposal.original_html,source.raw_html);assert.equal((await db.query('SELECT count(*)::int AS n FROM revisions WHERE workspace_id=$1',[workspace])).rows[0].n,0);assert.equal((await db.query('SELECT doc_version FROM emails WHERE id=$1',[email])).rows[0].doc_version,1);
 for(const role of['Owner','Admin'])assert.equal((await call(prepare,{expected_version:1},role)).status,200);
 const body={expected_version:1,source_hash:proposal.source_hash,proposal_hash:proposal.proposal_hash,acknowledge_layout_change:true},key=randomUUID(),headers={'Idempotency-Key':key,'If-Match':'"draft-1"','X-Actor-Id':actors.get('Owner')!.user};
 assert.equal((await call(accept,{...body,acknowledge_layout_change:false},'Owner',headers)).status,422);assert.equal((await call(accept,{...body,provider_verified:true},'Owner',headers)).status,422);assert.equal((await call(accept,body,'Owner',{'Idempotency-Key':key})).status,428);assert.equal((await call(accept,{...body,source_hash:'0'.repeat(64)},'Owner',{...headers,'Idempotency-Key':randomUUID()})).body.error.code,'CONVERSION_SOURCE_CHANGED');
 const keys=[]as string[];
 for(const scopes of[['emails:read'],['emails:write']]){const receipt=await call('api-keys',{name:'Owned conversion '+scopes[0],scopes,expires_in_days:1},'Owner',{'Idempotency-Key':randomUUID()});assert.equal(receipt.status,201);keys.push(receipt.body.secret);}
 const bearer=async(secret:string,target:string,command:unknown,h:Record<string,string>={})=>{const r=await fetch(origin+'/v1/'+target,{method:'POST',headers:{Authorization:'Bearer '+secret,'Content-Type':'application/json',...h},body:JSON.stringify(command)});return{status:r.status,body:await r.json()};};assert.equal((await bearer(keys[0],prepare,{expected_version:1})).status,403);assert.equal((await bearer(keys[1],prepare,{expected_version:1})).status,200);
 const saved=await call(accept,body,'Owner',headers);assert.equal(saved.status,200);validateSchema(apiSpec.paths['/v1/emails/{id}/convert-to-blocks'].post.responses[200].content['application/json'].schema,saved.body);assert.equal(saved.body.email.doc_version,2);assert.equal(saved.body.email.spec.editing_mode,'structured');assert.ok(saved.body.email.spec.sections.some((x:{type:string;html?:string})=>x.type==='custom_html'&&x.html?.includes('Opaque layout preserved')));const history=(await db.query('SELECT spec,source_doc_version FROM revisions WHERE email_id=$1 ORDER BY revision_no',[email])).rows;assert.equal(history.length,2);assert.deepEqual(history[0].spec,source);assert.equal(history[0].source_doc_version,1);assert.deepEqual(history[1].spec,saved.body.email.spec);assert.equal(history[1].source_doc_version,2);
 const nextSpec={...saved.body.email.spec,subject:'Current truth after conversion'};assert.equal((await call(path+'/draft',{spec:nextSpec},'Owner',{'If-Match':'"draft-2"'},'PATCH')).status,200);const replay=await call(accept,body,'Owner',headers);assert.equal(replay.status,200);assert.deepEqual(replay.body.email,saved.body.email);assert.equal((await call(path)).body.email.doc_version,3);assert.equal((await call(path)).body.email.spec.subject,'Current truth after conversion');assert.equal((await db.query('SELECT count(*)::int AS n FROM revisions WHERE email_id=$1',[email])).rows[0].n,2);assert.equal((await call(accept,{...body,proposal_hash:'f'.repeat(64)},'Owner',headers)).body.error.code,'IDEMPOTENCY_MISMATCH');assert.equal((await call(accept,body,'Owner',{...headers,'Idempotency-Key':randomUUID()})).status,412);
 await db.query("UPDATE memberships SET role='Viewer'WHERE workspace_id=$1 AND user_id=$2",[workspace,actors.get('Owner')!.user]);assert.equal((await call(accept,body,'Owner',headers)).status,403);
 console.log('Owned conversion HTTP PASS: strict source/version/hash/layout ack/query/actor guards, current roles and bearer scopes, no mutation on proposal/tamper, atomic raw checkpoint, one structured head, historical same-key receipt/current truth separation and revocation refusal; zero external provider calls.');
}finally{
 const cleanup=await db.connect();try{await cleanup.query('BEGIN');await cleanup.query('SELECT id FROM emails WHERE workspace_id=ANY($1::uuid[])FOR UPDATE',[[workspace,other]]);for(const table of['render_downloads','preflights','idempotency','audit_events','api_rate_events','api_keys','revisions','emails','brands','memberships'])await cleanup.query('DELETE FROM '+table+' WHERE workspace_id=ANY($1::uuid[])',[[workspace,other]]);await cleanup.query('DELETE FROM workspaces WHERE id=ANY($1::uuid[])',[[workspace,other]]);await cleanup.query('DELETE FROM auth_sessions WHERE user_id=ANY($1::text[])',[[...actors.values()].map(x=>x.user)]);await cleanup.query('COMMIT');}catch(e){await cleanup.query('ROLLBACK');throw e;}finally{cleanup.release();await db.end();}
}
