import assert from'node:assert/strict';import{randomBytes,randomUUID}from'node:crypto';import{spawn,type ChildProcess}from'node:child_process';import{open,mkdir}from'node:fs/promises';import{chromium}from'playwright';
import{sourceDatabase}from'./smoke-source-truth';import{blankSpec}from'../src/domain/email';import{createEmail,saveDraft,checkpoint}from'../src/server/emails';import{digest}from'../src/server/audit';
const origin='http://127.0.0.1:3046';
await sourceDatabase(async({db,p,brand,tx})=>{
 const spec=blankSpec(brand,'Compare fixture');spec.sections.push({id:'compare-columns',type:'columns',columns:[[{id:'compare-copy',type:'text',text:'Original nested text'}],[{id:'compare-raw',type:'custom_html',html:'<!--literal-->\r\n<p>é 😀</p>'}]]});
 const doc=await tx(c=>createEmail(c,p,'Compare saved fixture',spec)),a=await tx(c=>checkpoint(c,p,doc.id,1)),next=structuredClone(spec);next.subject='Second checkpoint';const changedColumns=next.sections.find(block=>block.type==='columns');assert.ok(changedColumns?.type==='columns');changedColumns.columns=[[{id:'compare-raw',type:'custom_html',html:'<!--changed literal-->\r\n<p>é 😀</p>'}],[{id:'compare-copy',type:'text',text:'Changed nested text'}]];await tx(c=>saveDraft(c,p,doc.id,1,next));const b=await tx(c=>checkpoint(c,p,doc.id,2));await tx(c=>saveDraft(c,p,doc.id,2,{...next,subject:'Third checkpoint'}));const c=await tx(t=>checkpoint(t,p,doc.id,3));
 const collision=await tx(t=>createEmail(t,p,'Collision fixture',{...spec,sections:[{id:'a',type:'text',text:'old'},{id:'a:text',type:'text',text:'removed'},{id:'a%3Atext',type:'text',text:'percent'},{id:'a:"字段',type:'text',text:'unicode'},{id:'col',type:'columns',columns:[[],[]]},{id:'col:column_count',type:'text',text:'removed column ID'}]})),collisionA=await tx(t=>checkpoint(t,p,collision.id,1));await tx(t=>saveDraft(t,p,collision.id,1,{...collision.spec,sections:[{id:'a',type:'text',text:'new'},{id:'a%3Atext',type:'text',text:'changed percent'},{id:'a:"字段',type:'text',text:'changed unicode'},{id:'col',type:'columns',columns:[[]]}]}));const collisionB=await tx(t=>checkpoint(t,p,collision.id,2));
 const older=await tx(t=>createEmail(t,p,'Older checkpoint fixture',spec));let olderFirst='',olderSecond='';for(let n=0;n<27;n++){const frozen=await tx(t=>checkpoint(t,p,older.id,1));if(n===0)olderFirst=frozen.id;if(n===1)olderSecond=frozen.id;}
 const retained=await tx(t=>createEmail(t,p,'Retained inactive fixture',{...spec,sections:[{id:'retained-literal',type:'divider'}]})),retainedA=await tx(t=>checkpoint(t,p,retained.id,1));await tx(t=>saveDraft(t,p,retained.id,1,{...retained.spec,raw_html:'(Absent)',sections:[{id:'retained-literal',type:'custom_html',html:'(Absent)'}]}));const retainedB=await tx(t=>checkpoint(t,p,retained.id,2));
 const rtl=await tx(t=>createEmail(t,p,'Hebrew comparison fixture',{...spec,locale:'he-IL',direction:'rtl'})),rtlA=await tx(t=>checkpoint(t,p,rtl.id,1));await tx(t=>saveDraft(t,p,rtl.id,1,{...rtl.spec,subject:'שלום חדש'}));const rtlB=await tx(t=>checkpoint(t,p,rtl.id,2));
 const rawSource='\ufeff<p>Source é 😀</p>\r\n<script>globalThis.__comparisonExecuted=true</script>',raw=await tx(t=>createEmail(t,p,'Raw comparison fixture',{...spec,editing_mode:'raw_html',raw_html:rawSource})),rawA=await tx(t=>checkpoint(t,p,raw.id,1));await tx(t=>saveDraft(t,p,raw.id,1,{...raw.spec,raw_html:rawSource.replace('\r\n','\n')+'<!--new-->'}));const rawB=await tx(t=>checkpoint(t,p,raw.id,2));
 const bigSource='<p>'+ 'A'.repeat(10000)+'</p><!--late BEFORE-->',big=await tx(t=>createEmail(t,p,'Large comparison fixture',{...spec,editing_mode:'raw_html',raw_html:bigSource})),bigA=await tx(t=>checkpoint(t,p,big.id,1));await tx(t=>saveDraft(t,p,big.id,1,{...big.spec,raw_html:bigSource.replace('BEFORE','AFTER')}));const bigB=await tx(t=>checkpoint(t,p,big.id,2));
 const empty=await tx(t=>createEmail(t,p,'No checkpoint fixture',spec)),foreign=randomUUID();await db.query("INSERT INTO workspaces(id,name)VALUES($1,'Foreign comparison fixture')",[foreign]);
 const cookie=randomBytes(32).toString('hex');await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,clock_timestamp()+interval '1 hour')",[digest(cookie),p.user]);const runtime=new URL(process.env.DATABASE_URL!);runtime.pathname=new URL(db.options.connectionString!).pathname;assert.match(runtime.pathname,/^\/creation_fixture_[a-f0-9]{32}$/);
 const before=(await db.query("SELECT json_build_object('emails',(SELECT md5(string_agg(md5(to_jsonb(t)::text),'' ORDER BY md5(to_jsonb(t)::text)))FROM emails t),'revisions',(SELECT md5(string_agg(md5(to_jsonb(t)::text),'' ORDER BY md5(to_jsonb(t)::text)))FROM revisions t),'provenance',(SELECT md5(string_agg(md5(to_jsonb(t)::text),'' ORDER BY md5(to_jsonb(t)::text)))FROM email_source_provenance t),'audits',(SELECT count(*) FROM audit_events),'commands',(SELECT count(*) FROM idempotency)) AS value")).rows[0].value;
 const log=await open('/tmp/lettercape-comparison-app.log','w');let app:ChildProcess|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
 try{
 app=spawn(process.execPath,['node_modules/next/dist/bin/next','dev','--hostname','127.0.0.1','--port','3046'],{env:{PATH:process.env.PATH,NODE_ENV:'development',LOCAL_DEVELOPMENT:'true',APP_ORIGIN:origin,DATABASE_URL:runtime.toString(),MIGRATION_DATABASE_URL:db.options.connectionString!,NEXT_TELEMETRY_DISABLED:'1',AI_GENERATION_ALLOWANCE:'0',PREFERENCE_SIGNING_SECRET:'owned-comparison-fixture-signing-only-32bytes'},stdio:['ignore',log.fd,log.fd]});for(let n=0;n<160;n++){if(app.exitCode!==null)throw Error('Owned comparison app exited');try{if((await fetch(origin)).ok)break;}catch{}if(n===159)throw Error('Owned comparison app unavailable');await new Promise(r=>setTimeout(r,250));}
 browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:320,height:1000}});await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);await context.addInitScript(workspace=>{if(window.top===window)localStorage.setItem('mailcraft.workspace',workspace);},p.workspace);context.setDefaultTimeout(10000);let external=0;await context.route(url=>url.origin!==origin&&url.protocol!=='blob:'&&url.protocol!=='data:',route=>{external++;return route.abort();});const page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const keyWarnings:string[]=[];page.on('console',m=>{if(/same key|unique.*key/i.test(m.text()))keyWarnings.push(m.text());});page.on('dialog',d=>d.accept());
 const query=(email:string,first:string,second:string)=>'/v1/revision-comparisons?'+new URLSearchParams({email_id:email,before:first,after:second});const get=async(path:string,extra:Record<string,string>={})=>context.request.get(origin+path,{headers:{'X-Workspace-Id':p.workspace,'X-Actor-Id':p.user,...extra}});
 for(const[first,second]of[[a.id,b.id],[a.id,a.id],[rawA.id,rawB.id]]){const res=await get(query(first===rawA.id?raw.id:doc.id,first,second));assert.equal(res.status(),200);const receipt=(await res.json()).comparison;assert.equal(receipt.before.id,first);assert.equal(receipt.after.id,second);}
 for(const suffix of['&extra=1','&before='+a.id,'&email_id='+doc.id])assert.equal((await get(query(doc.id,a.id,b.id)+suffix)).status(),422);assert.equal((await get(query(doc.id,a.id,rawB.id))).status(),404);assert.equal((await get(query(doc.id,a.id,randomUUID()))).status(),404);assert.equal((await get(query(doc.id,a.id,b.id),{'X-Actor-Id':'other-fixture'})).status(),409);assert.equal((await get(query(doc.id,a.id,b.id),{'X-Workspace-Id':foreign})).status(),404);assert.equal((await context.request.post(origin+query(doc.id,a.id,b.id),{headers:{Origin:origin,'X-Workspace-Id':p.workspace}})).status(),405);
 for(const[mail,first,second]of[[doc.id,a.id.toUpperCase(),b.id],[doc.id,a.id,b.id.toUpperCase()],[doc.id.toUpperCase(),a.id,b.id],[doc.id.toUpperCase(),a.id.toUpperCase(),b.id.slice(0,18).toUpperCase()+b.id.slice(18)]]){const res=await get(query(mail,first,second));assert.equal(res.status(),200);const receipt=(await res.json()).comparison;assert.equal(receipt.email_id,doc.id);assert.equal(receipt.before.id,a.id);assert.equal(receipt.after.id,b.id);}assert.equal((await get(query(doc.id,a.id,b.id),{'X-Actor-Id':p.user.toUpperCase()})).status(),409);
 console.log('Actual uppercase/mixed UUID comparison queries return canonical records and actor case remains exact PASS.');
 console.log('Actual strict duplicate/unknown query, immutable/same/raw reads, foreign/missing/actor and method refusals PASS.');
 await page.goto(origin+'/app/emails/'+doc.id);await page.getByRole('textbox',{name:'Subject',exact:true}).waitFor();await page.route('**/v1/emails/*/draft',r=>r.abort('failed'));await page.getByRole('textbox',{name:'Subject',exact:true}).fill('Retained unsaved comparison edit');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('button',{name:'History',exact:true}).click();const panel=page.getByRole('region',{name:'Saved checkpoint comparison',exact:true}),blockChange=(id:string,kind:string,field?:string)=>panel.locator('[data-revision-change='+JSON.stringify(JSON.stringify(['block',id,kind,...(field?[field]:[])]))+']');await panel.getByRole('button',{name:'Open checkpoint comparison',exact:true}).click();await panel.getByLabel('Before checkpoint',{exact:true}).selectOption(a.id);await panel.getByLabel('After checkpoint',{exact:true}).selectOption(b.id);
 let comparisons=0;page.on('request',r=>{if(r.url().includes('/v1/revision-comparisons?'))comparisons++;});await panel.getByRole('button',{name:'Compare checkpoints',exact:true}).focus();await page.keyboard.press('Enter');await panel.getByRole('status').filter({hasText:'Compared v1 → v2'}).waitFor();assert.equal(await page.getByRole('textbox',{name:'Subject',exact:true}).inputValue(),'Retained unsaved comparison edit');await blockChange('compare-copy','field','text').getByText('Changed nested text',{exact:true}).waitFor();assert.ok(await blockChange('compare-copy','position').count());const recoveryBefore=await page.evaluate(scope=>localStorage.getItem('lettercape.revision-comparison.'+JSON.stringify(scope)),[p.workspace,p.user,doc.id]);assert.ok(recoveryBefore);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 console.log('Actual keyboard structured comparison, nested move/literal distinction and failed-save local draft preservation at320px PASS.');
 const count=comparisons;await panel.getByRole('button',{name:'Compare checkpoints',exact:true}).evaluate(button=>{(button as HTMLButtonElement).click();(button as HTMLButtonElement).click();});await panel.getByRole('status').filter({hasText:'Compared v1 → v2'}).waitFor();assert.equal(comparisons,count+1);
 let entered!:()=>void,release!:()=>void;const waiting=new Promise<void>(r=>entered=r),gate=new Promise<void>(r=>release=r);let hold=true;await page.route('**/v1/revision-comparisons?**',async route=>{if(!hold)return route.continue();hold=false;const response=await route.fetch();entered();await gate;await route.fulfill({response}).catch(()=>{});});await panel.getByRole('button',{name:'Compare checkpoints',exact:true}).click();await waiting;await panel.getByLabel('After checkpoint',{exact:true}).selectOption(c.id);assert.equal(await panel.locator('[data-compared-after]').count(),0);await panel.getByRole('button',{name:'Compare checkpoints',exact:true}).click();await panel.getByRole('status').filter({hasText:'Compared v1 → v3'}).waitFor();release();await page.unroute('**/v1/revision-comparisons?**');assert.equal(await panel.locator('[data-compared-after]').getAttribute('data-compared-after'),c.id);await page.reload();await panel.getByRole('status').filter({hasText:'Compared v1 → v3'}).waitFor();assert.equal(await page.getByRole('textbox',{name:'Subject',exact:true}).inputValue(),'Retained unsaved comparison edit');
 console.log('Actual repeated-click single read, changed-selection cancellation/stale fence and metadata reload with independent uncertain-save recovery PASS.');
 await page.goto(origin+'/app/emails/'+raw.id);await page.getByRole('button',{name:'History',exact:true}).click();await panel.getByRole('button',{name:'Open checkpoint comparison',exact:true}).click();await panel.getByLabel('Before checkpoint',{exact:true}).selectOption(rawA.id);await panel.getByLabel('After checkpoint',{exact:true}).selectOption(rawB.id);await panel.getByRole('button',{name:'Compare checkpoints',exact:true}).click();await panel.getByRole('status').filter({hasText:'Compared v1 → v2'}).waitFor();assert.ok((await panel.locator('[data-revision-change="raw_html"]').innerText()).includes('\\r\\n'));assert.equal(await page.evaluate(()=>Reflect.get(globalThis,'__comparisonExecuted')),undefined);assert.equal(await panel.locator('script,iframe,img').count(),0);
 await mkdir('output/revision-comparison',{recursive:true});await panel.screenshot({path:'output/revision-comparison/raw-mobile.png'});
 await page.goto(origin+'/app/emails/'+big.id);await page.getByRole('button',{name:'History',exact:true}).click();await panel.getByRole('button',{name:'Open checkpoint comparison',exact:true}).click();await panel.getByLabel('Before checkpoint',{exact:true}).selectOption(bigA.id);await panel.getByLabel('After checkpoint',{exact:true}).selectOption(bigB.id);await panel.getByRole('button',{name:'Compare checkpoints',exact:true}).click();await panel.getByRole('status').filter({hasText:'Compared v1 → v2'}).waitFor();const literal=panel.locator('[data-revision-change="raw_html"]');assert.ok((await literal.innerText()).includes('late BEFORE'));assert.ok((await literal.innerText()).includes('late AFTER'));assert.ok((await literal.innerText()).includes('Excerpt near'));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 console.log('Actual inert exact raw CRLF/Unicode and large late-change excerpts without executing HTML or overflowing mobile PASS.');
 await page.goto(origin+'/app/emails/'+empty.id);await page.getByRole('button',{name:'History',exact:true}).click();await panel.getByRole('button',{name:'Open checkpoint comparison',exact:true}).click();await panel.getByText('No saved checkpoints to compare.',{exact:false}).waitFor();await page.goto(origin+'/app/emails/'+doc.id);await panel.getByRole('status').filter({hasText:'Compared v1 → v3'}).waitFor();assert.equal(await page.getByRole('textbox',{name:'Subject',exact:true}).inputValue(),'Retained unsaved comparison edit');
 let once=true;await page.route('**/v1/revision-comparisons?**',async route=>{if(once){once=false;return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'FIXTURE_UNAVAILABLE',message:'Comparison fixture unavailable'}})});}return route.continue();});await panel.getByRole('button',{name:'Compare checkpoints',exact:true}).click();await panel.getByRole('alert').filter({hasText:'Comparison fixture unavailable'}).waitFor();await panel.getByRole('button',{name:'Compare checkpoints',exact:true}).click();await panel.getByRole('status').filter({hasText:'Compared v1 → v3'}).waitFor();await page.unroute('**/v1/revision-comparisons?**');
 await db.query("UPDATE memberships SET role='Viewer' WHERE workspace_id=$1 AND user_id=$2",[p.workspace,p.user]);await page.reload();await panel.getByRole('status').filter({hasText:'Compared v1 → v3'}).waitFor();assert.equal(await page.getByRole('textbox',{name:'Subject',exact:true}).getAttribute('readonly'),'');await panel.getByLabel('After checkpoint',{exact:true}).selectOption(a.id);await panel.getByRole('button',{name:'Compare checkpoints',exact:true}).click();await panel.getByText('No stored authoring differences between these checkpoints.',{exact:true}).waitFor();assert.equal((await get(query(doc.id,a.id,b.id))).status(),200);await db.query("UPDATE memberships SET role='Billing' WHERE workspace_id=$1 AND user_id=$2",[p.workspace,p.user]);assert.equal((await get(query(doc.id,a.id,b.id))).status(),403);await db.query("UPDATE memberships SET role='Owner' WHERE workspace_id=$1 AND user_id=$2",[p.workspace,p.user]);
 await page.setViewportSize({width:1440,height:1100});await page.reload();await panel.getByRole('status').filter({hasText:'Compared v1 → v1'}).waitFor();await panel.getByLabel('After checkpoint',{exact:true}).selectOption(b.id);await panel.getByRole('button',{name:'Compare checkpoints',exact:true}).click();await panel.getByRole('status').filter({hasText:'Compared v1 → v2'}).waitFor();const unchangedToggle=panel.getByRole('checkbox',{name:'Show unchanged fields',exact:true});await unchangedToggle.focus();await page.keyboard.press('Space');assert.equal(await unchangedToggle.isChecked(),true);assert.ok(await panel.locator('[data-revision-change="locale"]').count());await page.keyboard.press('Space');assert.equal(await unchangedToggle.isChecked(),false);await panel.screenshot({path:'output/revision-comparison/structured-desktop.png'});
await page.evaluate(scope=>localStorage.setItem('lettercape.revision-comparison.'+JSON.stringify([scope.workspace,scope.actor,scope.email]),JSON.stringify({before:scope.before,after:scope.after,open:true})),{workspace:p.workspace,actor:p.user,email:older.id,before:olderFirst,after:olderSecond});await page.goto(origin+'/app/emails/'+older.id);await panel.getByRole('status').filter({hasText:'Compared v1 → v2'}).waitFor();assert.equal(await panel.getByLabel('Before checkpoint',{exact:true}).inputValue(),olderFirst);await panel.getByRole('button',{name:'Load older comparison checkpoints',exact:true}).click();await page.waitForFunction(()=>document.querySelector<HTMLSelectElement>('select[aria-label="Before checkpoint"]')?.options.length===28);assert.equal(await panel.getByLabel('Before checkpoint',{exact:true}).inputValue(),olderFirst);
 await page.setViewportSize({width:320,height:1000});await page.goto(origin+'/app/emails/'+rtl.id);await page.getByRole('button',{name:'History',exact:true}).click();await panel.getByRole('button',{name:'Open checkpoint comparison',exact:true}).click();await panel.getByLabel('Before checkpoint',{exact:true}).selectOption(rtlA.id);await panel.getByLabel('After checkpoint',{exact:true}).selectOption(rtlB.id);await panel.getByRole('button',{name:'Compare checkpoints',exact:true}).click();await panel.getByRole('status').filter({hasText:'Compared v1 → v2'}).waitFor();await panel.locator('[data-revision-change="subject"]').getByText('שלום חדש',{exact:true}).waitFor();assert.equal(await panel.locator('[data-revision-change="subject"] pre').last().getAttribute('dir'),'rtl');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await panel.screenshot({path:'output/revision-comparison/rtl-mobile.png'});
 await page.evaluate(()=>{const original=Storage.prototype.setItem;(window as unknown as {restoreComparisonStorage:()=>void}).restoreComparisonStorage=()=>{Storage.prototype.setItem=original;};Storage.prototype.setItem=function(key,value){if(key.startsWith('lettercape.revision-comparison.'))throw new DOMException('Owned fixture quota','QuotaExceededError');return original.call(this,key,value);};});await panel.getByLabel('After checkpoint',{exact:true}).selectOption(rtlA.id);await panel.getByRole('alert').filter({hasText:'selection cannot be saved'}).waitFor();await panel.getByRole('button',{name:'Compare checkpoints',exact:true}).click();await panel.getByText('No stored authoring differences between these checkpoints.',{exact:true}).waitFor();await page.evaluate(()=>(window as unknown as {restoreComparisonStorage:()=>void}).restoreComparisonStorage());
 await page.goto(origin+'/app/emails/'+retained.id);await page.getByRole('button',{name:'History',exact:true}).click();await panel.getByRole('button',{name:'Open checkpoint comparison',exact:true}).click();await panel.getByLabel('Before checkpoint',{exact:true}).selectOption(retainedA.id);await panel.getByLabel('After checkpoint',{exact:true}).selectOption(retainedB.id);await panel.getByRole('button',{name:'Compare checkpoints',exact:true}).click();await panel.getByRole('status').filter({hasText:'Compared v1 → v2: 3 authoring changes.'}).waitFor();const retainedRow=panel.locator('[data-revision-change="raw_html"]');await retainedRow.getByText('No stored value.',{exact:true}).waitFor();await retainedRow.getByText('Retained raw HTML source (inactive in structured checkpoints)',{exact:false}).waitFor();assert.equal(await retainedRow.locator('pre').innerText(),'"(Absent)"');assert.equal(await blockChange('retained-literal','field','html').locator('pre').innerText(),'"(Absent)"');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.evaluate(scope=>localStorage.setItem('lettercape.revision-comparison.'+JSON.stringify([scope.workspace,scope.actor,scope.email]),JSON.stringify({before:scope.before.toUpperCase(),after:scope.after.toUpperCase(),open:true})),{workspace:p.workspace,actor:p.user,email:collision.id,before:collisionA.id,after:collisionB.id});await page.goto(origin+'/app/emails/'+collision.id);await panel.getByRole('status').filter({hasText:'Compared v1 → v2'}).waitFor();assert.equal(await panel.getByLabel('Before checkpoint',{exact:true}).inputValue(),collisionA.id);assert.equal(await panel.getByLabel('After checkpoint',{exact:true}).inputValue(),collisionB.id);const changedKeys=await panel.locator('[data-revision-change]').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('data-revision-change')));assert.equal(new Set(changedKeys).size,changedKeys.length);for(let n=0;n<3;n++){await panel.getByRole('checkbox',{name:'Show unchanged fields',exact:true}).check();const allKeys=await panel.locator('[data-revision-change]').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('data-revision-change')));assert.equal(new Set(allKeys).size,allKeys.length);await panel.getByRole('checkbox',{name:'Show unchanged fields',exact:true}).uncheck();assert.deepEqual(await panel.locator('[data-revision-change]').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('data-revision-change'))),changedKeys);await blockChange('a','field','text').getByText('new',{exact:true}).waitFor();assert.ok((await blockChange('a:text','presence').innerText()).includes('\"text\":\"removed\"'));await blockChange('a%3Atext','field','text').getByText('changed percent',{exact:true}).waitFor();await blockChange('a:"字段','field','text').getByText('changed unicode',{exact:true}).waitFor();assert.equal(await blockChange('col','column_count').getByText('1',{exact:true}).count(),1);}await panel.getByLabel('After checkpoint',{exact:true}).selectOption(collisionA.id);await panel.getByRole('button',{name:'Compare checkpoints',exact:true}).click();await panel.getByText('No stored authoring differences between these checkpoints.',{exact:true}).waitFor();await panel.getByLabel('After checkpoint',{exact:true}).selectOption(collisionB.id);await panel.getByRole('button',{name:'Compare checkpoints',exact:true}).click();await blockChange('a','field','text').getByText('new',{exact:true}).waitFor();assert.equal(new Set(await panel.locator('[data-revision-change]').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('data-revision-change')))).size,changedKeys.length);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await panel.screenshot({path:'output/revision-comparison/collision-mobile.png'});assert.deepEqual(keyWarnings,[]);
 console.log('Actual uppercase recovered checkpoint pair, stable colon/percent/quoted Unicode identities, repeated toggles and changed selection without key warnings PASS.');
 console.log('Actual inactive structured source and literal absence additions remain visible and distinct PASS.');
 console.log('Actual older-page recovered selections, paging, Hebrew320px and metadata quota failure with working comparison PASS.');
  const after=(await db.query("SELECT json_build_object('emails',(SELECT md5(string_agg(md5(to_jsonb(t)::text),'' ORDER BY md5(to_jsonb(t)::text)))FROM emails t),'revisions',(SELECT md5(string_agg(md5(to_jsonb(t)::text),'' ORDER BY md5(to_jsonb(t)::text)))FROM revisions t),'provenance',(SELECT md5(string_agg(md5(to_jsonb(t)::text),'' ORDER BY md5(to_jsonb(t)::text)))FROM email_source_provenance t),'audits',(SELECT count(*) FROM audit_events),'commands',(SELECT count(*) FROM idempotency)) AS value")).rows[0].value;assert.deepEqual(after,before);assert.equal(external,0);assert.deepEqual(errors,[]);
 console.log('Actual empty/error/retry, navigation selection/draft recovery, Viewer same-checkpoint reads, Billing refusal, desktop and unchanged records/zero external requests/page errors PASS.');
 }finally{await browser?.close();if(app&&app.exitCode===null){app.kill('SIGTERM');await new Promise<void>(resolve=>app!.once('exit',()=>resolve()));}await log.close();}
});console.log('Owned comparison app stopped and disposable database removed PASS.');
