import assert from 'node:assert/strict';import {randomBytes,randomUUID}from'node:crypto';import{spawn,type ChildProcess}from'node:child_process';import{open,mkdir}from'node:fs/promises';import{chromium}from'playwright';import{sourceDatabase}from'./smoke-source-truth';import{digest}from'../src/server/audit';
const origin='http://127.0.0.1:3042';
await sourceDatabase(async({db,p})=>{
 const cookie=randomBytes(32).toString('hex');await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,clock_timestamp()+interval '1 hour')",[digest(cookie),p.user]);
 const viewer='planning-viewer-'+randomUUID(),viewerCookie=randomBytes(32).toString('hex');await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,'Viewer')",[p.workspace,viewer]);await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,clock_timestamp()+interval '1 hour')",[digest(viewerCookie),viewer]);
 const originalMembers=(await db.query('SELECT * FROM memberships ORDER BY id')).rows,originalSessions=(await db.query('SELECT * FROM auth_sessions ORDER BY token_hash')).rows;
 const runtime=new URL(process.env.DATABASE_URL!);runtime.pathname=new URL(db.options.connectionString!).pathname;assert.match(runtime.pathname,/^\/creation_fixture_[a-f0-9]{32}$/);
 const log=await open('/tmp/lettercape-invitation-app.log','w');let app:ChildProcess|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
 try{
  app=spawn(process.execPath,['node_modules/next/dist/bin/next','dev','--hostname','127.0.0.1','--port','3042'],{env:{PATH:process.env.PATH,NODE_ENV:'development',LOCAL_DEVELOPMENT:'true',APP_ORIGIN:origin,DATABASE_URL:runtime.toString(),MIGRATION_DATABASE_URL:db.options.connectionString!,PREFERENCE_SIGNING_SECRET:process.env.PREFERENCE_SIGNING_SECRET,NEXT_TELEMETRY_DISABLED:'1',AI_GENERATION_ALLOWANCE:'0'},stdio:['ignore',log.fd,log.fd]});
  for(let n=0;n<120;n++){if(app.exitCode!==null)throw Error('Owned invitation app exited');try{if((await fetch(origin)).ok)break;}catch{}if(n===119)throw Error('Owned invitation app unavailable');await new Promise(r=>setTimeout(r,250));}
  browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:1000}});await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);await context.addInitScript(w=>{if(window.top===window)localStorage.setItem('mailcraft.workspace',w);},p.workspace);
  let external=0;await context.route(url=>url.origin!==origin&&url.protocol!=='data:'&&url.protocol!=='blob:',route=>{external++;return route.abort();});context.setDefaultTimeout(15000);
  const page=await context.newPage(),errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(origin+'/app/settings');await page.getByRole('heading',{name:'Team members',exact:true}).waitFor();
  const panel=page.getByRole('region',{name:'Invitation planning',exact:true});await panel.waitFor();
  await panel.getByText('No saved invitation requests.',{exact:true}).waitFor();await panel.getByText('Not sent. Acceptance is disabled.',{exact:true}).waitFor();
  assert.equal(await panel.getByRole('button',{name:'Send invitation',exact:true}).isDisabled(),true);assert.equal(await panel.getByRole('button',{name:'Accept invitation',exact:true}).isDisabled(),true);
  const email=panel.getByRole('textbox',{name:'Recipient email (unverified)',exact:true}),notes=panel.getByRole('textbox',{name:'Planning notes',exact:true});
  await email.fill('not-an-email');await panel.getByRole('button',{name:'Save planning request',exact:true}).click();assert.equal((await db.query('SELECT count(*)::int n FROM invitation_requests')).rows[0].n,0);
  await email.fill('synthetic@example.test');await panel.getByRole('combobox',{name:'Proposed role',exact:true}).selectOption('Editor');await notes.fill('Literal <note> مرحبا é 😀');await panel.getByLabel('Review deadline (UTC, optional)',{exact:true}).fill('2020-01-01T07:00');
  const endpoint=origin+'/v1/invitation-requests',captured:Array<{key:string|undefined;body:string|null}>=[];
  await page.route(endpoint,async route=>{if(route.request().method()!=='POST')return route.continue();captured.push({key:route.request().headers()['idempotency-key'],body:route.request().postData()});await route.fetch();await route.fulfill({status:503,json:{error:{code:'FIXTURE_ACK_LOST',message:'Owned planning acknowledgment lost'}}});});
  await panel.getByRole('button',{name:'Save planning request',exact:true}).evaluate((button:HTMLButtonElement)=>{button.click();button.click();});await panel.getByRole('alert').filter({hasText:'Owned planning acknowledgment lost'}).waitFor();assert.equal(captured.length,1);
  assert.equal(await email.isDisabled(),true);assert.equal((await db.query('SELECT count(*)::int n FROM invitation_requests')).rows[0].n,1);assert.equal((await db.query('SELECT count(*)::int n FROM invitation_request_history')).rows[0].n,1);
  await page.unroute(endpoint);await page.route(endpoint,async route=>{if(route.request().method()==='POST')captured.push({key:route.request().headers()['idempotency-key'],body:route.request().postData()});await route.continue();});
  await panel.getByRole('button',{name:'Retry same planning command',exact:true}).focus();await page.keyboard.press('Enter');try{await panel.getByRole('status').filter({hasText:'Planning request confirmed'}).waitFor({timeout:5000});}catch(e){console.error('Planning confirmation diagnostic:',await panel.getByRole('alert').allTextContents());throw e;}await page.unroute(endpoint);assert.deepEqual(captured[1],captured[0]);
  const row=await db.query('SELECT * FROM invitation_requests'),id=row.rows[0].id;assert.equal(row.rows[0].notes,'Literal <note> مرحبا é 😀');assert.equal(row.rows[0].version,1);
  const card=panel.locator(`[data-invitation-request="${id}"]`);await card.getByText('Review deadline passed',{exact:true}).waitFor();
  console.log('Actual empty/invalid states, rapid create, lost receipt/same-key keyboard retry and planning-only deadline PASS.');

  await card.getByRole('button',{name:'Edit request',exact:true}).click();await notes.fill('Retained local proposal');
  const request=await context.request.post(origin+'/v1/invitation-requests/'+id+'/update',{headers:{origin,'x-workspace-id':p.workspace,'x-actor-id':p.user,'idempotency-key':randomUUID()},data:{email:'synthetic@example.test',role:'Editor',notes:'Other saved version',review_due_at:null,expected_version:1}});assert.equal(request.status(),200);
  await panel.getByRole('button',{name:'Save request changes',exact:true}).click();await panel.getByRole('alert').filter({hasText:'This planning request changed'}).waitFor();assert.equal(await notes.inputValue(),'Retained local proposal');
  await panel.getByRole('button',{name:'Reload current request',exact:true}).click();await panel.getByRole('status').filter({hasText:'Loaded current planning version'}).waitFor();assert.equal(await notes.inputValue(),'Other saved version');await notes.fill('Corrected proposal');await panel.getByRole('button',{name:'Save request changes',exact:true}).click();await panel.getByRole('status').filter({hasText:'Planning request confirmed'}).waitFor();assert.equal((await db.query('SELECT version FROM invitation_requests WHERE id=$1',[id])).rows[0].version,3);
  await card.getByRole('button',{name:'Withdraw request',exact:true}).evaluate((button:HTMLButtonElement)=>{button.click();button.click();});await card.getByText('Withdrawn',{exact:true}).waitFor();assert.equal((await db.query('SELECT version FROM invitation_requests WHERE id=$1',[id])).rows[0].version,4);
  await card.getByRole('button',{name:'Reopen request',exact:true}).focus();await page.keyboard.press('Enter');await card.getByRole('button',{name:'Edit request',exact:true}).waitFor();
  await card.getByRole('button',{name:'View request history',exact:true}).click();const history=panel.getByRole('region',{name:'Planning request history',exact:true});await history.getByText('Literal <note> مرحبا é 😀',{exact:true}).waitFor();assert.equal(await history.locator('[data-invitation-history]').count(),5);
  await page.reload();await panel.waitFor();await card.getByText('Corrected proposal',{exact:true}).waitFor();await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('link',{name:'Emails',exact:true}).click();await page.waitForURL(origin+'/app/emails');await page.goBack();await panel.waitFor();await card.getByText('Corrected proposal',{exact:true}).waitFor();
  console.log('Actual CAS refusal/local-field retention, explicit reload/correction, repeated withdraw/reopen, immutable history and navigation/reload PASS.');

  const before=(await db.query('SELECT * FROM invitation_requests ORDER BY id')).rows,hbefore=(await db.query('SELECT * FROM invitation_request_history ORDER BY id')).rows;
  for(const action of ['send','accept']){const res=await context.request.post(origin+'/v1/invitation-requests/'+id+'/'+action,{headers:{origin,'x-workspace-id':p.workspace,'x-actor-id':p.user},data:{}});assert.equal(res.status(),409);assert.equal((await res.json()).error.code,action==='send'?'INVITATION_DELIVERY_DISABLED':'INVITATION_ACCEPTANCE_DISABLED');}
  assert.deepEqual((await db.query('SELECT * FROM invitation_requests ORDER BY id')).rows,before);assert.deepEqual((await db.query('SELECT * FROM invitation_request_history ORDER BY id')).rows,hbefore);
  assert.deepEqual((await db.query('SELECT * FROM memberships ORDER BY id')).rows,originalMembers);assert.deepEqual((await db.query('SELECT * FROM auth_sessions ORDER BY token_hash')).rows,originalSessions);
  await page.route(endpoint,route=>route.request().method()==='GET'?route.fulfill({status:503,json:{error:{code:'FIXTURE_READ_FAILED',message:'Owned planning list unavailable'}}}):route.continue());await panel.getByRole('button',{name:'Refresh requests',exact:true}).click();await panel.getByRole('alert').filter({hasText:'Owned planning list unavailable'}).waitFor();await page.unroute(endpoint);await panel.getByRole('button',{name:'Refresh requests',exact:true}).click();await panel.getByRole('alert').filter({hasText:'Owned planning list unavailable'}).waitFor({state:'hidden'});await card.getByText('Corrected proposal',{exact:true}).waitFor();
  for(const width of [390,320]){await page.setViewportSize({width,height:1000});await panel.scrollIntoViewIfNeeded();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.ok(await panel.locator('input,textarea,select,button').evaluateAll(nodes=>nodes.every(node=>{const r=node.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+1;})));}
  await mkdir('output/invitation-planning',{recursive:true});await page.screenshot({path:'output/invitation-planning/mobile.png'});await page.setViewportSize({width:1440,height:1000});await panel.scrollIntoViewIfNeeded();await page.screenshot({path:'output/invitation-planning/desktop.png'});
  const viewerContext=await browser.newContext({viewport:{width:390,height:1000}});await viewerContext.addCookies([{name:'mailcraft_local_session',value:viewerCookie,url:origin,sameSite:'Strict'}]);await viewerContext.addInitScript(w=>{if(window.top===window)localStorage.setItem('mailcraft.workspace',w);},p.workspace);await viewerContext.route(url=>url.origin!==origin&&url.protocol!=='data:'&&url.protocol!=='blob:',route=>{external++;return route.abort();});
  const viewerPage=await viewerContext.newPage();await viewerPage.goto(origin+'/app/settings');await viewerPage.getByText('Owner or Admin access is required to manage members.',{exact:true}).waitFor();assert.equal(await viewerPage.getByRole('region',{name:'Invitation planning',exact:true}).count(),0);
  const denied=await viewerContext.request.post(endpoint,{headers:{origin,'x-workspace-id':p.workspace,'x-actor-id':viewer,'idempotency-key':randomUUID()},data:{request_id:randomUUID(),email:'viewer-proposal@example.test',role:'Editor'}});assert.equal(denied.status(),403);await viewerContext.close();
  assert.deepEqual((await db.query('SELECT * FROM memberships ORDER BY id')).rows,originalMembers);assert.deepEqual((await db.query('SELECT * FROM auth_sessions ORDER BY token_hash')).rows,originalSessions);assert.equal((await db.query('SELECT count(*)::int n FROM invitation_requests')).rows[0].n,1);
  console.log('Actual Viewer management refusal and absence of planning controls preserve synthetic memberships/session rows PASS.');
  assert.deepEqual(errors,[]);assert.equal(external,0);console.log('Actual disabled send/accept refusals, unchanged memberships/sessions, list error/retry,320px/desktop and zero external requests/page errors PASS.');
 }finally{if(browser)await browser.close();if(app&&app.exitCode===null){const exited=new Promise<void>(resolve=>app!.once('exit',()=>resolve()));app.kill('SIGTERM');await Promise.race([exited,new Promise<void>(resolve=>setTimeout(resolve,5000))]);if(app.exitCode===null){app.kill('SIGKILL');await exited;}}await log.close();}
});
console.log('Owned invitation planning app stopped and disposable database removed PASS.');
