import assert from'node:assert/strict';import{randomUUID,randomBytes}from'node:crypto';import pg from'pg';import env from'@next/env';import{chromium}from'playwright';import{digest}from'../src/server/audit';env.loadEnvConfig(process.cwd());
const origin=process.env.APP_ORIGIN??'http://127.0.0.1:3003';if(process.env.LOCAL_DEVELOPMENT!=='true'||!['127.0.0.1','localhost'].includes(new URL(origin).hostname))throw new Error('Owned loopback Voice review fixture required.');const db=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL}),workspace=randomUUID(),user='voice-review-'+randomUUID(),cookie=randomBytes(32).toString('hex'),operation=randomUUID();let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;const checks:string[]=[];
const kit={name:'Saved original',website:'',description:'Owned fixture',voice:'Plain',accent:'#0B625D',background:'#F7F6F2',font_stack:'Arial, sans-serif',address:'Fixture address',approved_claims:[],forbidden_phrases:[],provenance:[],tone_rules:{max_sentence_words:20}},proposal={...kit,name:'Chosen recovered proposal',tone_rules:{max_sentence_words:5}};
async function current(){const response=await fetch(origin+'/v1/brands/current',{headers:{Cookie:'mailcraft_local_session='+cookie,'X-Workspace-Id':workspace},signal:AbortSignal.timeout(15000)});assert.equal(response.status,200);return(await response.json()).brand;}
try{
 await db.query("INSERT INTO workspaces(id,name)VALUES($1,'Voice review browser')",[workspace]);await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,'Owner')",[workspace,user]);await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,clock_timestamp()+interval '1 hour')",[digest(cookie),user]);await db.query('INSERT INTO brands(workspace_id,version,data)VALUES($1,1,$2)',[workspace,JSON.stringify(kit)]);
 // Completed result is explicitly synthetic owned recovery data: no extraction or provider was called.
 await db.query("INSERT INTO operations(workspace_id,id,type,state,input,result,created_by,completed_at)VALUES($1,$2,'brand.extract','succeeded',$3,$4,$5,clock_timestamp())",[workspace,operation,JSON.stringify({url:'https://example.org/owned-fixture'}),JSON.stringify({proposal}),user]);
 browser=await chromium.launch({headless:true});const context=await browser.newContext();await context.addInitScript(w=>localStorage.setItem('mailcraft.workspace',w),workspace);await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);let page=await context.newPage(),words=page.getByLabel('Maximum words per sentence',{exact:true});
 if(!process.argv.includes('--save')&&!process.argv.includes('--proposal')){
  let reads=0,entered!:()=>void,release!:()=>void;const held=new Promise<void>(r=>entered=r),gate=new Promise<void>(r=>release=r);await page.route('**/v1/brands/current',async route=>{const nth=++reads,response=await route.fetch();if(nth===1){entered();await gate;}await route.fulfill({response});});
  try{await page.goto(origin+'/app/brand');await held;await page.waitForFunction(()=>{const fields=document.querySelector<HTMLFieldSetElement>('.brand-fields');return !!fields&&!fields.disabled;});assert.ok(reads>=2,'Exercise the abandoned Strict Mode effect alongside the active read.');await words.fill('10');release();await page.unrouteAll({behavior:'wait'});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r(true)))));assert.equal(await words.inputValue(),'10','An abandoned initial effect must not overwrite later edits.');checks.push('abandoned Strict Mode initial read cannot overwrite later edits');}finally{release();await page.unrouteAll({behavior:'wait'});}
 }
 if(!process.argv.includes('--save')&&!process.argv.includes('--strict')){
  let entered!:()=>void,release!:()=>void;const held=new Promise<void>(r=>entered=r),gate=new Promise<void>(r=>release=r);await page.route('**/v1/brands/current',async route=>{const response=await route.fetch();entered();await gate;await route.fulfill({response});});
  try{await page.goto(origin+'/app/brand');await held;await page.getByRole('button',{name:'Inspect operation '+operation,exact:true}).click();const adopt=page.getByRole('button',{name:'Review completed proposal',exact:true});await adopt.waitFor();assert.equal(await adopt.isDisabled(),true,'Adoption must wait for the initial kit read just like other edits.');}finally{release();await page.unrouteAll({behavior:'wait'});}
  await page.waitForFunction(()=>document.querySelector<HTMLInputElement>('.voice-rule-controls input')?.value==='20');await page.getByRole('button',{name:'Review completed proposal',exact:true}).click();assert.equal(await words.inputValue(),'5');assert.equal(await page.getByLabel('Brand name',{exact:true}).inputValue(),proposal.name);await page.getByRole('button',{name:'Confirm brand version',exact:true}).click();await page.getByRole('status').filter({hasText:'Brand version 2 saved.'}).waitFor();assert.equal((await current()).data.tone_rules.max_sentence_words,5);checks.push('recovered proposal adoption waits for initial kit read, then selected5 persists');
 }
 if(!process.argv.includes('--proposal')&&!process.argv.includes('--strict')){
  await page.close();page=await context.newPage();words=page.getByLabel('Maximum words per sentence',{exact:true});const prior=await current();await page.goto(origin+'/app/brand');await page.waitForFunction(value=>document.querySelector<HTMLInputElement>('.voice-rule-controls input')?.value===String(value),prior.data.tone_rules.max_sentence_words);assert.equal(await words.isEnabled(),true);await words.fill('10');let entered!:()=>void,release!:()=>void;const held=new Promise<void>(r=>entered=r),gate=new Promise<void>(r=>release=r);await page.route('**/v1/brands',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}const submitted=JSON.parse(route.request().postData()??'{}').tone_rules?.max_sentence_words;const response=await route.fetch();const observed=await response.json();console.log('Owned fixture save probe',JSON.stringify({submitted,status:response.status(),returned:observed.brand?.data?.tone_rules?.max_sentence_words,version:observed.brand?.version}));entered();await gate;await route.fulfill({response});});
  try{await page.getByRole('button',{name:'Confirm brand version',exact:true}).click();await held;assert.equal(await words.isDisabled(),true,'An acknowledged version must describe the unchanged submitted form.');const observedCurrent=await current();console.log('Owned fixture current probe',JSON.stringify({displayed:await words.inputValue(),stored:observedCurrent.data.tone_rules.max_sentence_words,version:observedCurrent.version}));assert.equal(observedCurrent.data.tone_rules.max_sentence_words,10);}finally{release();await page.unrouteAll({behavior:'wait'});}
  await page.getByRole('status').filter({hasText:'Brand version '+(prior.version+1)+' saved.'}).waitFor();assert.equal(await words.inputValue(),'10');assert.equal(await words.isEnabled(),true);assert.equal((await current()).version,prior.version+1);checks.push('submitted snapshot10 remains frozen/displayed/persisted until acknowledgment');
 }
 assert.ok(checks.length);console.log('Voice review owned HTTP/Chromium PASS: '+checks.join('; ')+'. Synthetic recovery fixture; external reads/model requests/sends0.');
}finally{await browser?.close();for(const table of['outbox','operations','api_rate_events','idempotency','audit_events','memberships','brands'])await db.query(`DELETE FROM ${table} WHERE workspace_id=$1`,[workspace]);await db.query('DELETE FROM auth_sessions WHERE user_id=$1',[user]);await db.query('DELETE FROM workspaces WHERE id=$1',[workspace]);await db.end();}
