import assert from 'node:assert/strict';
import {randomUUID,randomBytes} from 'node:crypto';
import pg from 'pg';
import env from '@next/env';
import {chromium} from 'playwright';
import {digest} from '../src/server/audit';
import {blankSpec} from '../src/domain/email';
env.loadEnvConfig(process.cwd());
const origin=process.env.APP_ORIGIN??'http://127.0.0.1:3003';
if(process.env.LOCAL_DEVELOPMENT!=='true'||!['127.0.0.1','localhost'].includes(new URL(origin).hostname))throw Error('Owned loopback conversion fixture required.');
const db=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL}),workspace=randomUUID(),user='conversion-ui-'+randomUUID(),otherUser='conversion-other-'+randomUUID(),cookie=randomBytes(32).toString('hex'),otherCookie=randomBytes(32).toString('hex'),brand=randomUUID(),email=randomUUID();
const source={...blankSpec(brand,'Owned conversion'),editing_mode:'raw_html' as const,sections:[],raw_html:'<p>Keep the exact raw source</p><div>Opaque safe fragment</div>'};
let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
try {
 await db.query("INSERT INTO workspaces(id,name)VALUES($1,'Owned conversion UI')",[workspace]);await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,'Owner'),($1,$3,'Owner')",[workspace,user,otherUser]);await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,clock_timestamp()+interval '1 hour'),($3,$4,clock_timestamp()+interval '1 hour')",[digest(cookie),user,digest(otherCookie),otherUser]);
 await db.query("INSERT INTO brands(workspace_id,id,version,data)VALUES($1,$2,1,'{}')",[workspace,brand]);await db.query('INSERT INTO emails(workspace_id,id,title,spec,created_by)VALUES($1,$2,$3,$4,$5)',[workspace,email,'Owned conversion UI',JSON.stringify(source),user]);
 browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);await context.addInitScript(w=>localStorage.setItem('mailcraft.workspace',w),workspace);const page=await context.newPage();let dialogMode='accept',dialogs=0;page.on('dialog',dialog=>{dialogs++;return dialogMode==='accept'?dialog.accept():dialog.dismiss();});
 await page.goto(origin+'/app/emails/'+email);await page.getByRole('textbox',{name:'Subject',exact:true}).waitFor();
 const panel=page.getByRole('region',{name:'Block conversion',exact:true}),review=panel.getByRole('button',{name:'Review block conversion',exact:true});
 assert.equal(await review.count(),1,'Raw editor must expose explicit block conversion review; absent control RED.');
 assert.equal(await review.isEnabled(),true);
 const accept=panel.getByRole('button',{name:'Accept block conversion',exact:true}),ack=panel.getByRole('checkbox',{name:'I reviewed both previews and acknowledge that block rendering can change layout.',exact:true});
 const preparePattern='**/v1/emails/*/conversion-proposal',acceptPattern='**/v1/emails/*/convert-to-blocks';
 const commands:{email:string;body:string;key:string}[]=[];page.on('request',request=>{if(request.url().endsWith('/convert-to-blocks'))commands.push({email:new URL(request.url()).pathname.split('/')[3],body:request.postData()??'',key:request.headers()['idempotency-key']});});
 async function seed(raw_html=source.raw_html){const id=randomUUID();await db.query('INSERT INTO emails(workspace_id,id,title,spec,created_by)VALUES($1,$2,$3,$4,$5)',[workspace,id,'Owned conversion case',JSON.stringify({...source,raw_html}),user]);return id;}
 async function open(id:string){await page.goto(origin+'/app/emails/'+id);await page.getByRole('textbox',{name:'Subject',exact:true}).waitFor();await review.waitFor();await page.waitForFunction(()=>{const button=Array.from(document.querySelectorAll('button')).find(button=>button.textContent==='Review block conversion');return !!button&&!button.disabled;});}
 async function available(){await review.click();await panel.locator('iframe[title="Proposed block conversion preview"]').waitFor();assert.equal(await accept.isDisabled(),true);await ack.check();assert.equal(await accept.isEnabled(),true);}
 async function truth(id:string){return(await db.query('SELECT doc_version,spec FROM emails WHERE workspace_id=$1 AND id=$2',[workspace,id])).rows[0];}
 // Preparing from dirty text must use the version acknowledged by the callback's flush.
 await page.getByRole('textbox',{name:'Subject',exact:true}).fill('Post-flush conversion source');await available();assert.ok((await truth(email)).doc_version>1);assert.match(await panel.innerText(),new RegExp('Saved source v'+(await truth(email)).doc_version));
 await page.getByRole('textbox',{name:'Subject',exact:true}).fill('Newer local text');await panel.getByRole('status').filter({hasText:'The source changed after this proposal'}).waitFor();assert.equal(await accept.isDisabled(),true);await panel.getByRole('button',{name:'Discard conversion proposal',exact:true}).click();assert.equal((await truth(email)).spec.editing_mode,'raw_html');
 // Delay a prepared response, then change source: no stale proposal may replace the editor.
 const delayed=await seed();await open(delayed);let release!:()=>void,entered!:()=>void;const gate=new Promise<void>(resolve=>release=resolve),ready=new Promise<void>(resolve=>entered=resolve);let preparations=0;
 await page.route(preparePattern,async route=>{preparations++;const response=await route.fetch();entered();await gate;await route.fulfill({response});});
 try{await review.evaluate((button:HTMLButtonElement)=>{button.click();button.click();});await ready;await page.getByRole('textbox',{name:'Subject',exact:true}).fill('Local text during delayed proposal');release();await page.getByRole('alert').filter({hasText:'draft changed during conversion review'}).waitFor();assert.equal(preparations,1);assert.equal(await page.getByRole('textbox',{name:'Subject',exact:true}).inputValue(),'Local text during delayed proposal');assert.equal(await panel.locator('iframe[title="Proposed block conversion preview"]').count(),0);}finally{release();await page.unroute(preparePattern);}
 // Unsupported source is a report; it leaves raw source and revision count untouched.
 const unsupported=await seed('<!-- email-only conditional construct --><p>Preserve unsupported source</p>');await open(unsupported);await review.click();await panel.getByRole('status').filter({hasText:'Conversion is unavailable for this source'}).waitFor();assert.equal(await accept.isDisabled(),true);assert.equal((await truth(unsupported)).spec.raw_html,'<!-- email-only conditional construct --><p>Preserve unsupported source</p>');assert.equal((await db.query('SELECT count(*)::int AS n FROM revisions WHERE email_id=$1',[unsupported])).rows[0].n,0);
 // Preparation error is visible and retryable without changing the document.
 const failure=await seed();await open(failure);await page.route(preparePattern,route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'CONTROLLED_PREPARE_FAILURE',message:'Controlled conversion preparation failure'}})}));await review.click();await page.getByRole('alert').filter({hasText:'Controlled conversion preparation failure'}).waitFor();assert.equal((await truth(failure)).doc_version,1);await page.unroute(preparePattern);await available();
 // Actual accepted command loses acknowledgment; reload and account changes cannot create another command.
 let accepted!:()=>void;const acceptedSave=new Promise<void>(resolve=>accepted=resolve);
 await page.route(acceptPattern,async route=>{const response=await route.fetch();assert.equal(response.status(),200);accepted();await route.abort('failed');});const before=commands.length;await accept.evaluate((button:HTMLButtonElement)=>{button.click();button.click();});await acceptedSave;const retry=panel.getByRole('button',{name:'Retry original conversion',exact:true});await retry.waitFor();await panel.getByRole('alert').waitFor();assert.equal(commands.length,before+1);assert.equal((await truth(failure)).spec.editing_mode,'structured');await page.unroute(acceptPattern);
 await page.reload();await retry.waitFor();assert.equal(await retry.isEnabled(),true);
 await context.addCookies([{name:'mailcraft_local_session',value:otherCookie,url:origin,sameSite:'Strict'}]);await page.reload();await panel.waitFor();assert.equal(await retry.count(),0,'Another actor must not recover this original acceptance.');
 await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);await page.reload();await retry.waitFor();await retry.click();await panel.getByRole('status').filter({hasText:'Conversion acknowledged.'}).waitFor();assert.deepEqual(commands.at(-1),commands.at(-2));assert.equal((await truth(failure)).doc_version,2);
 const history=(await db.query('SELECT spec FROM revisions WHERE email_id=$1 ORDER BY revision_no',[failure])).rows;assert.ok(history.some(row=>row.spec.editing_mode==='raw_html'&&row.spec.raw_html===source.raw_html));assert.ok(history.some(row=>row.spec.editing_mode==='structured'));assert.equal(await retry.count(),0);
 // A successful receipt followed by failed current-truth read stays unresolved until the exact retry.
 const readFailure=await seed();await open(readFailure);await available();await page.route('**/v1/emails/'+readFailure,route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'CONTROLLED_CURRENT_READ_FAILURE',message:'Controlled current truth read failure'}})}));await accept.click();await retry.waitFor();await panel.getByRole('alert').filter({hasText:'Controlled current truth read failure'}).waitFor();assert.equal((await truth(readFailure)).doc_version,2);await page.unroute('**/v1/emails/'+readFailure);await retry.click();await panel.getByRole('status').filter({hasText:'Conversion acknowledged.'}).waitFor();assert.deepEqual(commands.at(-1),commands.at(-2));
 // Current-role denial retains the command and fences repeat submission until reload.
 const denied=await seed();await open(denied);await available();await db.query("UPDATE memberships SET role='Viewer'WHERE workspace_id=$1 AND user_id=$2",[workspace,user]);await accept.click();await panel.getByRole('status').filter({hasText:'Current permission was denied.'}).waitFor();assert.equal(await retry.isDisabled(),true);assert.equal((await truth(denied)).doc_version,1);await page.reload();await retry.waitFor();assert.equal(await retry.isDisabled(),true);await db.query("UPDATE memberships SET role='Owner'WHERE workspace_id=$1 AND user_id=$2",[workspace,user]);await page.reload();await retry.waitFor();await retry.click();await panel.getByRole('status').filter({hasText:'Conversion acknowledged.'}).waitFor();
 // Storage quota preserves tab recovery and requires unload confirmation rather than silently dropping the original.
 const quota=await seed();await open(quota);await available();await page.evaluate(()=>{const original=Storage.prototype.setItem;(window as unknown as {conversionStorageRestore:()=>void}).conversionStorageRestore=()=>{Storage.prototype.setItem=original;};Storage.prototype.setItem=function(key,value){if(key.startsWith('lettercape.conversion.'))throw new DOMException('Controlled storage quota','QuotaExceededError');original.call(this,key,value);};});await page.route(acceptPattern,route=>route.abort('failed'));await accept.click();await retry.waitFor();await panel.getByRole('alert').filter({hasText:'Browser storage is unavailable.'}).waitFor();dialogMode='dismiss';const priorDialogs=dialogs;await page.reload().catch(()=>{});assert.ok(dialogs>priorDialogs);assert.equal(await retry.count(),1);dialogMode='accept';await page.evaluate(()=>(window as unknown as {conversionStorageRestore:()=>void}).conversionStorageRestore());await page.unroute(acceptPattern);await retry.click();await panel.getByRole('status').filter({hasText:'Conversion acknowledged.'}).waitFor();assert.deepEqual(commands.at(-1),commands.at(-2));
 // Actual390px proposal previews stack and load no remote image/link resources.
 const mobile=await seed('<p>Mobile static preview</p><a href="https://conversion-link.example.test">Safe link</a><img src="https://conversion-image.example.test/pixel.png" alt="Static remote image" />');let remoteRequests=0;
 // Chromium reports request events for CSP-blocked attempts; interception proves no network request escaped CSP.
 await context.route(url=>url.hostname.endsWith('.example.test'),route=>{remoteRequests++;return route.abort('blockedbyclient');});
 page.on('requestfailed',request=>{if(new URL(request.url()).hostname.endsWith('.example.test'))console.log('Conversion preview blocked attempt:',request.failure()?.errorText);});
 await open(mobile);await available();await page.setViewportSize({width:390,height:844});await panel.scrollIntoViewIfNeeded();const originalFrame=panel.locator('iframe[title="Original raw conversion preview"]'),proposedFrame=panel.locator('iframe[title="Proposed block conversion preview"]'),originalBox=await originalFrame.boundingBox(),proposedBox=await proposedFrame.boundingBox();assert.ok(originalBox&&proposedBox&&proposedBox.y>=originalBox.y+originalBox.height);assert.equal(await originalFrame.getAttribute('sandbox'),'');assert.equal(await originalFrame.getAttribute('tabindex'),'-1');assert.equal(await originalFrame.evaluate(frame=>getComputedStyle(frame).pointerEvents),'none');assert.equal(remoteRequests,0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'/tmp/lettercape-conversion-mobile.png'});
 console.log('Owned conversion Chromium PASS: postflush source context, stale/delayed/repeated proposal, unsupported/error source preservation, repeated lost acknowledgment exact body/key across reload and actor isolation, current-truth read failure retry, role denial/recovery, storage quota/unload guard, immutable original/new checkpoints and390px static previews without remote image/link requests.');
}catch(error){console.error('CONVERSION_UI_FIXTURE_FAILURE',error);throw error;}finally{
 await browser?.close();const cleanup=await db.connect();try{await cleanup.query('BEGIN');await cleanup.query('SELECT id FROM emails WHERE workspace_id=$1 FOR UPDATE',[workspace]);for(const table of['render_downloads','preflights','idempotency','audit_events','revisions','emails','brands','memberships'])await cleanup.query('DELETE FROM '+table+' WHERE workspace_id=$1',[workspace]);await cleanup.query('DELETE FROM workspaces WHERE id=$1',[workspace]);await cleanup.query('DELETE FROM auth_sessions WHERE user_id=ANY($1::text[])',[[user,otherUser]]);await cleanup.query('COMMIT');}catch(error){await cleanup.query('ROLLBACK');throw error;}finally{cleanup.release();await db.end();}
}
