import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {spawn,type ChildProcess} from 'node:child_process';
import {open,mkdtemp,rm} from 'node:fs/promises';
import {chromium} from 'playwright';
import {sourceDatabase} from './smoke-source-truth';
import {createEmail} from '../src/server/emails';
import {blankSpec} from '../src/domain/email';
import {digest} from '../src/server/audit';

const origin='http://127.0.0.1:3004';
await sourceDatabase(async({db,p,brand,tx})=>{
 const source='\uFEFF<!-- exact -->\r\n<DIV title="é">e\u0301 &amp; 😀</DIV>\n<script>globalThis.__sourceRan=true;fetch("/__source_execution")</script>\r<!--[if mso]><v:roundrect>VML retained</v:roundrect><![endif]-->';
 const raw=await tx(c=>createEmail(c,p,'Owned exact source',{...blankSpec(brand,'Owned'),editing_mode:'raw_html',raw_html:source})),structured=await tx(c=>createEmail(c,p,'Owned source fork',blankSpec(brand,'Owned'))),cookie=randomBytes(32).toString('hex');
 await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at) VALUES($1,$2,clock_timestamp()+interval '1 hour')",[digest(cookie),p.user]);
 const runtime=new URL(process.env.DATABASE_URL!);runtime.pathname=new URL(db.options.connectionString!).pathname;
 assert.ok(runtime.pathname.startsWith('/creation_fixture_'));
 const media=process.argv.includes('--media')||process.argv.includes('--media-ui'),store=media?await mkdtemp('/tmp/lettercape-source-media-store-'):undefined;
 const log=await open('/tmp/lettercape-source-editor-app.log','w');let worker:ChildProcess|undefined;let app:ChildProcess|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
 try{
  app=spawn(process.execPath,['node_modules/next/dist/bin/next','dev','--hostname','127.0.0.1','--port','3004'],{env:{PATH:process.env.PATH,NODE_ENV:'development',LOCAL_DEVELOPMENT:'true',APP_ORIGIN:origin,DATABASE_URL:runtime.toString(),MIGRATION_DATABASE_URL:db.options.connectionString!,NEXT_TELEMETRY_DISABLED:'1',...(store?{ASSET_STORE_ROOT:store}:{})},stdio:['ignore',log.fd,log.fd]});
  for(let n=0;n<120;n++){if(app.exitCode!==null)throw Error('Owned source app exited before readiness');try{const response=await fetch(origin);if(response.ok)break;}catch{}if(n===119)throw Error('Owned source app did not become ready');await new Promise(r=>setTimeout(r,250));}
  if(media){
   const config={APP_ORIGIN:origin,DATABASE_URL:runtime.toString(),MIGRATION_DATABASE_URL:db.options.connectionString!,LOCAL_DEVELOPMENT:'true',SOURCE_TRUTH_FIXTURE:'true',ASSET_STORE_ROOT:store!,MEDIA_LOCAL_FIXTURES_ONLY:'true',MEDIA_DECODER_IMAGE:process.env.MEDIA_DECODER_IMAGE!,MEDIA_SCANNER_IMAGE:process.env.MEDIA_SCANNER_IMAGE!,MEDIA_SCAN_DATABASE_ROOT:process.env.MEDIA_SCAN_DATABASE_ROOT!,MEDIA_SCAN_SNAPSHOT_SHA256:process.env.MEDIA_SCAN_SNAPSHOT_SHA256!};
   for(const key of ['MEDIA_DECODER_IMAGE','MEDIA_SCANNER_IMAGE','MEDIA_SCAN_DATABASE_ROOT','MEDIA_SCAN_SNAPSHOT_SHA256']as const)assert.ok(config[key],'Explicit qualified media configuration required');
   worker=spawn(process.execPath,['--import','tsx','scripts/media-worker.ts'],{env:{PATH:process.env.PATH,NODE_ENV:'development',...config},stdio:['ignore',log.fd,log.fd]});
   const code=await new Promise<number>(resolve=>{const child=spawn(process.execPath,['--import','tsx',...(process.argv.includes('--media-ui')?['scripts/assets-browser.ts','--qualified']:['scripts/smoke-asset-export.ts','--gif','--settlement'])],{env:{...process.env,...config},stdio:'inherit'});child.once('error',()=>resolve(1));child.once('exit',c=>resolve(c??1));});if(code!==0)throw Error('Actual source/media export integration failed');console.log(process.argv.includes('--media-ui')?'Actual source receipt/private GIF picker/recovery integration PASS.':'Actual source fork/private GIF fallback/projection/immutable export integration PASS.');return;
  }
  if(process.argv.includes('--baseline')){
   const cases=[['scripts/smoke-editor.ts'],['scripts/smoke-code-editor.ts'],['scripts/smoke-conversion-api.ts'],['scripts/smoke-conversion.ts'],['scripts/conversion-review-browser.ts'],['scripts/conversion-review-browser.ts','--preview'],['scripts/smoke-utm.ts','--browser','--review-missing','--review-raw','--review-url'],['scripts/smoke-preflight.ts']];
   const from=process.argv.find(a=>a.startsWith('--baseline-from='))?.split('=')[1];const selected=from?cases.slice(cases.findIndex(args=>args[0].endsWith('/'+from))):cases;if(from&&!cases.some(args=>args[0].endsWith('/'+from)))throw Error('Unknown owned baseline fixture');
   for(const args of selected){const code=await new Promise<number>(resolve=>{const child=spawn(process.execPath,['--import','tsx',...args],{env:{...process.env,APP_ORIGIN:origin,DATABASE_URL:runtime.toString(),MIGRATION_DATABASE_URL:db.options.connectionString!,SOURCE_TRUTH_FIXTURE:'true'},stdio:'inherit'});child.once('error',()=>resolve(1));child.once('exit',code=>resolve(code??1));});if(code!==0)throw Error('Source baseline regression failed: '+args.join(' '));}
   console.log('Actual selected baseline regression PASS: '+selected.map(args=>args.join(' ')).join(', '));return;
  }
  browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);await context.addInitScript(w=>{if(top===window)localStorage.setItem('mailcraft.workspace',w);},p.workspace);
  let sentinel=0,external=0;const errors:string[]=[];context.on('request',r=>{if(new URL(r.url()).pathname==='/__source_execution')sentinel++;});await context.route(url=>url.origin!==origin&&url.protocol!=='data:'&&url.protocol!=='blob:',route=>{external++;return route.abort('blockedbyclient');});
  const page=await context.newPage();page.on('dialog',d=>d.accept());page.on('pageerror',e=>errors.push(e.message));

  if(process.argv.includes('--fragments')){
   const fragment='\uFEFF<!-- exact -->\r\n<DIV onclick="globalThis.__fragmentRan=true"><script>globalThis.__fragmentRan=true;fetch("/__source_execution")</script><a href="https://example.com/?utm_source=other">Go</a><!--[if mso]><v:rect>VML</v:rect><![endif]--></DIV>\r';
   const spec={...blankSpec(brand,'Owned'),tracking:{utm_source:'source',utm_medium:'email',utm_campaign:'test'},sections:[{id:'opaque',type:'custom_html' as const,html:fragment}]};
   const headers={'Origin':origin,'X-Workspace-Id':p.workspace,'X-Actor-Id':p.user,'Content-Type':'application/json','Idempotency-Key':randomBytes(16).toString('hex')};
   const created=await context.request.post(origin+'/v1/emails',{headers,data:{title:'Owned custom source',spec}});assert.equal(created.status(),200);const doc=(await created.json()).email;
   assert.deepEqual(doc.spec,spec);await page.goto(origin+'/app/emails/'+doc.id);await page.getByRole('textbox',{name:'Subject',exact:true}).waitFor();await page.getByRole('region',{name:'Raw source diagnostics'}).getByText(/VML_FIDELITY_UNSUPPORTED/).waitFor();
   const preview=await context.request.post(origin+'/v1/emails/'+doc.id+'/preview',{headers,data:{spec}});assert.equal(preview.status(),200);const artifact=(await preview.json()).artifact;assert.equal(artifact.manifest.fragment_projection.delivery_status,'blocked');assert.equal(artifact.manifest.spec.sections[0].html,fragment);assert.ok(!artifact.preview_html.includes('<script')&&!artifact.preview_html.includes('href='));
   const isolated=await context.newPage();await isolated.setContent(artifact.preview_html);assert.equal(await isolated.evaluate(()=>Reflect.get(window,'__fragmentRan')),undefined);await isolated.close();
   await page.getByRole('textbox',{name:'Subject',exact:true}).fill('Exact custom source saved');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('status').filter({hasText:'Saved · v2'}).waitFor();
   assert.equal((await db.query('SELECT spec FROM emails WHERE id=$1',[doc.id])).rows[0].spec.sections[0].html,fragment);
   const checkpoint=await context.request.post(origin+'/v1/emails/'+doc.id+'/revisions',{headers:{...headers,'Idempotency-Key':randomBytes(16).toString('hex'),'If-Match':'draft-2'},data:{}});assert.equal(checkpoint.status(),200);const revision=(await checkpoint.json()).revision;
   assert.equal(revision.manifest.spec.sections[0].html,fragment);const rendered=await context.request.get(origin+'/v1/email-revisions/'+revision.id+'/download?format=html',{headers});assert.equal(rendered.status(),409);
   const reportResponse=await context.request.post(origin+'/v1/email-revisions/'+revision.id+'/preflight',{headers:{...headers,'Idempotency-Key':randomBytes(16).toString('hex')},data:{}});assert.equal(reportResponse.status(),200);const report=(await reportResponse.json()).report;assert.equal(report.state,'blocked');assert.equal(report.rule_set_version,'static-source-5');assert.ok(report.findings.some((f:{code:string;location:string})=>f.code==='VML_FIDELITY_UNSUPPORTED'&&f.location.startsWith('opaque:')));
   let refusedForkRequests=0;page.on('request',r=>{if(r.url().endsWith('/source-fork'))refusedForkRequests++;});await page.getByRole('button',{name:'HTML',exact:true}).first().click();await page.getByRole('button',{name:'Edit raw HTML',exact:true}).dblclick();await page.getByRole('alert').filter({hasText:'Correct the blocking source diagnostics before switching modes'}).waitFor();assert.equal(refusedForkRequests,0);assert.equal(await page.getByRole('button',{name:'Retry original save acknowledgment',exact:true}).count(),0);
   const refusedBlocked=await context.request.post(origin+'/v1/emails/'+doc.id+'/source-fork',{headers:{...headers,'Idempotency-Key':randomBytes(16).toString('hex'),'If-Match':'draft-2'},data:{expected_artifact_hash:revision.artifact_hash}});assert.equal(refusedBlocked.status(),409);assert.equal((await refusedBlocked.json()).error.code,'SOURCE_PROJECTION_BLOCKED');assert.equal((await db.query('SELECT doc_version FROM emails WHERE id=$1',[doc.id])).rows[0].doc_version,2);assert.equal((await db.query('SELECT count(*)::int n FROM revisions WHERE email_id=$1',[doc.id])).rows[0].n,1);
   const unavailableSpec={...spec,tracking:undefined,sections:[{id:'first',type:'custom_html' as const,html:'<br>'.repeat(11000)},{id:'second',type:'custom_html' as const,html:'<br>'.repeat(11000)}]};
   const unavailableCreate=await context.request.post(origin+'/v1/emails',{headers:{...headers,'Idempotency-Key':randomBytes(16).toString('hex')},data:{title:'Owned bounded custom source',spec:unavailableSpec}});assert.equal(unavailableCreate.status(),200);const unavailable=(await unavailableCreate.json()).email;
   const limited=await context.request.post(origin+'/v1/emails/'+unavailable.id+'/preview',{headers,data:{spec:unavailable.spec}});assert.equal(limited.status(),200);const limitedArtifact=(await limited.json()).artifact;assert.equal(limitedArtifact.preview_html,null);assert.equal(limitedArtifact.html,'');assert.equal(limitedArtifact.manifest.fragment_projection.delivery_status,'unavailable');assert.equal(limitedArtifact.manifest.spec.sections[1].html,unavailableSpec.sections[1].html);
   await page.goto(origin+'/app/emails/'+unavailable.id);await page.getByRole('textbox',{name:'Subject',exact:true}).waitFor();await page.getByRole('region',{name:'Raw source diagnostics'}).getByText(/RAW_PROJECTION_LIMIT/).waitFor();await page.getByRole('button',{name:'HTML',exact:true}).first().click();await page.getByRole('button',{name:'Edit raw HTML',exact:true}).dblclick();await page.getByRole('alert').filter({hasText:'Generated source is unavailable'}).waitFor();assert.equal(refusedForkRequests,0);assert.equal(await page.getByRole('button',{name:'Retry original save acknowledgment',exact:true}).count(),0);
   const refusedUnavailable=await context.request.post(origin+'/v1/emails/'+unavailable.id+'/source-fork',{headers:{...headers,'Idempotency-Key':randomBytes(16).toString('hex'),'If-Match':'draft-1'},data:{expected_artifact_hash:limitedArtifact.hash}});assert.equal(refusedUnavailable.status(),409);assert.equal((await refusedUnavailable.json()).error.code,'SOURCE_PROJECTION_UNAVAILABLE');assert.equal((await db.query('SELECT doc_version FROM emails WHERE id=$1',[unavailable.id])).rows[0].doc_version,1);assert.equal((await db.query('SELECT count(*)::int n FROM revisions WHERE email_id=$1',[unavailable.id])).rows[0].n,0);console.log('Actual repeated blocked/unavailable fork clicks retain structured source, capture no recovery command, dispatch no fork; direct HTTP independently refuses without checkpoint/version mutation PASS.');
   assert.equal(sentinel,0);assert.equal(external,0);assert.deepEqual(errors,[]);console.log('Actual HTTP/browser custom fragment exact save/checkpoint/hash, inert preview, located preflight/rendered block and aggregate unavailable source preservation PASS.');return;
  }
  const saved=()=>page.getByRole('status').filter({hasText:/Saved · v/});
  const openRaw=async()=>{await page.goto(origin+'/app/emails/'+raw.id);await page.getByRole('textbox',{name:'Subject',exact:true}).waitFor();await page.getByRole('button',{name:'HTML',exact:true}).first().click();const switcher=page.getByRole('button',{name:'Use basic editor',exact:true});if(await switcher.count())await switcher.click();await page.locator('textarea[aria-label="Raw HTML source"]').waitFor();};
  await openRaw();const input=page.getByRole('textbox',{name:'Raw HTML source',exact:true}),subject=page.getByRole('textbox',{name:'Subject',exact:true});
  const pattern='**/v1/emails/'+raw.id+'/draft';let sent=0,key='',body='';
  await page.route(pattern,async route=>{sent++;key=route.request().headers()['idempotency-key'];body=route.request().postData()!;const response=await route.fetch();const json=await response.json();json.receipt.command_id='wrong-original-command';await route.fulfill({response,json});});
  await input.focus();const mac=await page.evaluate(()=>/Mac/.test(navigator.platform));await page.keyboard.press(mac?'Meta+ArrowDown':'Control+End');await page.keyboard.insertText('X');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('status').filter({hasText:'Save failed'}).waitFor();assert.equal(sent,1);
  assert.equal(JSON.parse(body).spec.raw_html,source+'X');assert.equal((await db.query('SELECT doc_version FROM emails WHERE id=$1',[raw.id])).rows[0].doc_version,2);assert.equal(await saved().count(),0,'wrong200 receipt cannot mark Saved');
  await page.unroute(pattern);let retryKey='',retryBody='';await page.route(pattern,async route=>{retryKey=route.request().headers()['idempotency-key'];retryBody=route.request().postData()!;await route.continue();});
  await page.getByRole('button',{name:'Retry original save acknowledgment',exact:true}).click();await saved().waitFor();assert.equal(retryKey,key);assert.equal(retryBody,body);assert.equal((await db.query('SELECT doc_version FROM emails WHERE id=$1',[raw.id])).rows[0].doc_version,2);await page.unroute(pattern);
  console.log('Actual wrong200 receipt refused; explicit original key/payload replay validated, no duplicate version PASS.');
  // Real commit with the response lost, then reload and explicit original replay.
  let lostKey='',lostBody='';await page.route(pattern,async route=>{lostKey=route.request().headers()['idempotency-key'];lostBody=route.request().postData()!;await route.fetch();await route.abort('connectionreset');});
  await subject.fill('Lost acknowledgment source');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('status').filter({hasText:'Save failed'}).waitFor();await page.unroute(pattern);await page.reload();await page.getByRole('button',{name:'Retry original save acknowledgment',exact:true}).waitFor();assert.equal(await saved().count(),0);
  await page.route(pattern,async route=>{assert.equal(route.request().headers()['idempotency-key'],lostKey);assert.equal(route.request().postData(),lostBody);await route.continue();});await page.getByRole('button',{name:'Retry original save acknowledgment',exact:true}).click();await saved().waitFor();assert.equal((await db.query('SELECT doc_version FROM emails WHERE id=$1',[raw.id])).rows[0].doc_version,3);await page.unroute(pattern);
  console.log('Actual committed/lost response → actor-scoped IndexedDB reload → explicit same original command PASS.');
  // Later typing while the original actual receipt is held must remain local.
  let release!:()=>void,arrive!:()=>void;const hold=new Promise<void>(r=>{release=r;}),arrival=new Promise<void>(r=>{arrive=r;});let calls=0;
  await page.route(pattern,async route=>{calls++;if(calls===1){const response=await route.fetch();arrive();await hold;await route.fulfill({response});}else await route.abort();});
  await subject.fill('First held snapshot');await page.getByRole('button',{name:'Save',exact:true}).click();await arrival;await subject.fill('Later typed source stays local');release();await page.getByRole('status').filter({hasText:'Unsaved changes'}).waitFor();assert.equal(await subject.inputValue(),'Later typed source stays local');
  assert.equal((await db.query("SELECT spec->>'subject' AS value FROM emails WHERE id=$1",[raw.id])).rows[0].value,'First held snapshot');await page.unroute(pattern);await page.getByRole('button',{name:'Save',exact:true}).click();await saved().waitFor();
  console.log('Held actual receipt preserves later typing and advances only the acknowledged base PASS.');
  // Source attachment remains exact while rendered delivery and preflight are blocked.
  const proof=await page.evaluate(async({workspace,id,actor})=>{const headers={'Content-Type':'application/json','X-Workspace-Id':workspace,'X-Actor-Id':actor},head=await(await fetch('/v1/emails/'+id,{headers})).json();const revision=await(await fetch('/v1/emails/'+id+'/revisions',{method:'POST',headers:{...headers,'If-Match':'"draft-'+head.email.doc_version+'"','Idempotency-Key':crypto.randomUUID()},body:'{}'})).json();const base='/v1/email-revisions/'+revision.revision.id;const attachment=await fetch(base+'/download?format=source',{headers}),html=await fetch(base+'/download?format=html',{headers}),report=await(await fetch(base+'/preflight',{method:'POST',headers:{...headers,'Idempotency-Key':crypto.randomUUID()},body:'{}'})).json();return{source:Array.from(new Uint8Array(await attachment.arrayBuffer())),mime:attachment.headers.get('content-type'),disposition:attachment.headers.get('content-disposition'),htmlStatus:html.status,report};},{workspace:p.workspace,id:raw.id,actor:p.user});
  assert.deepEqual(Buffer.from(proof.source),Buffer.from(source+'X'));assert.equal(proof.htmlStatus,409);assert.match(proof.disposition!,/attachment/);assert.match(proof.mime!,/text\/plain/);assert.equal(proof.report.report.state,'blocked');assert.ok(proof.report.report.findings.some((f:{code:string})=>f.code==='VML_FIDELITY_UNSUPPORTED'));
  console.log('Exact inert attachment, blocked rendered export and blocking source preflight PASS.');
  await page.goto(origin+'/app/emails/'+structured.id);await subject.waitFor();await page.getByRole('button',{name:'HTML',exact:true}).first().click();let forks=0;page.on('request',r=>{if(r.url().endsWith('/source-fork'))forks++;});await page.getByRole('button',{name:'Edit raw HTML',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[aria-label=\"Raw HTML source\"]')||Array.from(document.querySelectorAll('.alert.danger[role=\"alert\"]')).some(e=>e.textContent?.trim()));if(!await page.getByRole('textbox',{name:'Raw HTML source',exact:true}).count())throw Error('Actual fork refused: '+await page.getByRole('alert').allTextContents());assert.equal(forks,1);const fork=(await db.query('SELECT spec,doc_version FROM emails WHERE id=$1',[structured.id])).rows[0];assert.equal(fork.doc_version,2);assert.equal(fork.spec.editing_mode,'raw_html');assert.ok(fork.spec.raw_html.includes('<html'));assert.equal((await db.query("SELECT origin FROM email_source_provenance WHERE email_id=$1",[structured.id])).rows[0].origin,'structured_fork');
  console.log('Actual server-authoritative structured fork/checkpoint/validated receipt PASS.');
  // Empty source is an acknowledged inert document, with a blocking projection.
  const switcher=page.getByRole('button',{name:'Use basic editor',exact:true});if(await switcher.count())await switcher.click();const forkInput=page.getByRole('textbox',{name:'Raw HTML source',exact:true});await forkInput.fill('');await page.getByRole('button',{name:'Save',exact:true}).click();await saved().waitFor();assert.equal((await db.query('SELECT spec,doc_version FROM emails WHERE id=$1',[structured.id])).rows[0].spec.raw_html,'');await page.getByRole('region',{name:'Raw source diagnostics',exact:true}).getByText(/RAW_SOURCE_EMPTY/).waitFor();
  console.log('Actual empty source saves exactly, remains editable and blocks projection delivery PASS.');
  const interrupted=await tx(c=>createEmail(c,p,'Owned interrupted fork',blankSpec(brand,'Owned')));await page.goto(origin+'/app/emails/'+interrupted.id);await subject.waitFor();await page.getByRole('button',{name:'HTML',exact:true}).first().click();const forkPattern='**/v1/emails/'+interrupted.id+'/source-fork';let forkKey='',forkBody='',forkRequests=0;await page.route(forkPattern,async route=>{forkRequests++;forkKey=route.request().headers()['idempotency-key'];forkBody=route.request().postData()!;await route.fetch();await route.abort('connectionreset');});await page.getByRole('button',{name:'Edit raw HTML',exact:true}).click();await page.getByRole('button',{name:'Retry original save acknowledgment',exact:true}).waitFor();await page.locator('.alert.danger[role="alert"]').waitFor();await page.unroute(forkPattern);await page.reload();await page.getByRole('button',{name:'Retry original save acknowledgment',exact:true}).waitFor();await page.route(forkPattern,async route=>{forkRequests++;assert.equal(route.request().headers()['idempotency-key'],forkKey);assert.equal(route.request().postData(),forkBody);await route.continue();});await page.getByRole('button',{name:'Retry original save acknowledgment',exact:true}).dblclick();await saved().waitFor();assert.equal(forkRequests,2);assert.equal((await db.query('SELECT doc_version FROM emails WHERE id=$1',[interrupted.id])).rows[0].doc_version,2);assert.equal((await db.query('SELECT count(*)::int AS n FROM revisions WHERE email_id=$1',[interrupted.id])).rows[0].n,1);await page.unroute(forkPattern);
  console.log('Actual fork committed/lost response → reload → repeated explicit original action/key/body replay; one checkpoint/version PASS.');

  // A real response committed by Owner cannot mutate state after the cookie
  // changes to Viewer; the fresh current-head read checks the actual actor.
  const viewer='source-viewer-'+randomBytes(8).toString('hex'),viewerCookie=randomBytes(32).toString('hex');await db.query("INSERT INTO memberships(workspace_id,user_id,role) VALUES($1,$2,'Viewer')",[p.workspace,viewer]);await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at) VALUES($1,$2,clock_timestamp()+interval '1 hour')",[digest(viewerCookie),viewer]);
  await page.goto(origin+'/app/emails/'+raw.id);await subject.waitFor();let actorRelease!:()=>void,actorArrive!:()=>void;const actorHold=new Promise<void>(r=>{actorRelease=r;}),actorArrival=new Promise<void>(r=>{actorArrive=r;});await page.route(pattern,async route=>{const response=await route.fetch();actorArrive();await actorHold;await route.fulfill({response});});await subject.fill('Owned held actor snapshot');await page.getByRole('button',{name:'Save',exact:true}).click();await actorArrival;await context.addCookies([{name:'mailcraft_local_session',value:viewerCookie,url:origin,sameSite:'Strict'}]);actorRelease();await page.getByRole('status').filter({hasText:'Save failed'}).waitFor();assert.equal(await saved().count(),0);await page.unroute(pattern);await page.reload();await subject.waitFor();assert.equal(await page.getByRole('button',{name:'Save',exact:true}).isDisabled(),true);assert.equal(await page.getByRole('button',{name:'Retry original save acknowledgment',exact:true}).count(),0);assert.equal(await subject.inputValue(),'Owned held actor snapshot');
  console.log('Actual Owner receipt held across Viewer cookie switch refuses Saved; Viewer reload is read-only and adopts no Owner recovery command PASS.');
  await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/lettercape-source-editor-mobile.png'});assert.equal(sentinel,0);assert.equal(external,0);assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>Reflect.get(window,'__sourceRan')),undefined);
  console.log('Actual native source editor mobile/navigation/no source execution/no external requests PASS.');
 }finally{await browser?.close();if(worker&&worker.exitCode===null){worker.kill('SIGTERM');await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Owned media worker did not confirm shutdown; reconciliation required')),20000);worker!.once('exit',()=>{clearTimeout(timer);resolve();});});}if(app&&app.exitCode===null){app.kill('SIGTERM');await new Promise<void>(resolve=>{app!.once('exit',()=>resolve());setTimeout(()=>{app!.kill('SIGKILL');resolve();},5000);});}await log.close();if(store)await rm(store,{recursive:true});}
});
console.log('Owned source application stopped and generated database dropped PASS.');
