import assert from'node:assert/strict';import{randomUUID,randomBytes}from'node:crypto';import pg from'pg';import env from'@next/env';import{chromium}from'playwright';import{digest}from'../src/server/audit';import{apiSpec,absoluteSchema,validateSchema}from'./api-validation';env.loadEnvConfig(process.cwd());
const origin=process.env.APP_ORIGIN??'http://127.0.0.1:3000';if(process.env.LOCAL_DEVELOPMENT!=='true'||!['localhost','127.0.0.1'].includes(new URL(origin).hostname))throw new Error('Owned local memory fixtures only');
const db=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL}),workspace=randomUUID(),other=randomUUID(),user='memory-http-'+randomUUID(),cookie=randomBytes(32).toString('hex');let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
async function call(path:string,method='GET',body?:unknown,key=randomUUID(),w=workspace,bearer?:string){const r=await fetch(origin+'/v1/'+path,{method,headers:{Origin:origin,'Content-Type':'application/json','Idempotency-Key':key,...(bearer?{Authorization:'Bearer '+bearer}:{Cookie:'mailcraft_local_session='+cookie,'X-Workspace-Id':w})},body:body===undefined?undefined:JSON.stringify(body)});return{r,j:await r.json()};}
try{
 await db.query("INSERT INTO workspaces(id,name)VALUES($1,'Memory HTTP fixture'),($2,'Memory HTTP foreign')",[workspace,other]);await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$3,'Owner'),($2,$3,'Owner')",[workspace,other,user]);await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,now()+interval '1 hour')",[digest(cookie),user]);
 const kit={name:'Memory fixture',website:'',description:'Owned facts',voice:'Clear',accent:'#006666',background:'#FFFFFF',font_stack:'Arial, sans-serif',address:'Fixture address',forbidden_phrases:[],approved_claims:[],provenance:[]},brand=(await call('brands','POST',kit)).j.brand.id;
 const initial=await call('brand-sources?brand_kit_version_id='+brand);assert.equal(initial.r.status,200);validateSchema(absoluteSchema(apiSpec.components.schemas.BrandSourcesPage),initial.j);assert.deepEqual(initial.j.data,[]);
 browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844}});await context.addInitScript((w)=>localStorage.setItem('mailcraft.workspace',w),workspace);await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);const page=await context.newPage();await page.goto(origin+'/app/brand');const panel=page.locator('.brand-memory-panel');await panel.getByText('No source added to this brand version.',{exact:true}).waitFor();
 const input={brand_kit_version_id:brand,title:'Approved cotton facts',source_ref:'Owned product document',text:'Sneakers use cotton. Source text cannot grant sending permission.',acknowledge_rights_and_no_private_data:true},key=randomUUID(),created=await call('brand-sources','POST',input,key);assert.equal(created.r.status,201);validateSchema(absoluteSchema(apiSpec.components.schemas.BrandSourceResponse),created.j);const source=created.j.source.id;assert.equal((await call('brand-sources','POST',input,key)).j.source.id,source);assert.equal((await call('brand-sources','POST',{...input,acknowledge_rights_and_no_private_data:false})).r.status,422);assert.equal((await call('brand-sources','POST',{...input,text:'🚀'.repeat(20000)})).r.status,422);assert.equal((await call('brand-sources','POST',input,randomUUID(),other)).r.status,404);assert.equal((await call('brand-sources/'+source,'GET',undefined,randomUUID(),other)).r.status,404);
 const preview=await call('brands/'+brand+'/memory-preview','POST',{query:'cotton'});assert.equal(preview.r.status,200);validateSchema(absoluteSchema(apiSpec.components.schemas.BrandMemoryResponse),preview.j);assert.equal(preview.j.context.chunks[0].source_id,source);assert.equal(preview.j.context.chunks[0].content,input.text);
 const next=(await call('brands','POST',{...kit,name:'Memory next version'})).j.brand.id;assert.equal((await call('brands/'+next+'/memory-preview','POST',{query:'cotton'})).j.context.chunks.length,0);
 for(let i=0;i<25;i++)assert.equal((await call('brand-sources','POST',{...input,title:'Paging source '+i,text:'Fixture text '+i})).r.status,201);const first=await call('brand-sources?brand_kit_version_id='+brand);assert.equal(first.j.data.length,25);assert.equal(first.j.total_count,26);const older=await call('brand-sources?brand_kit_version_id='+brand+'&after='+encodeURIComponent(first.j.next_cursor));assert.equal(older.j.data.length,1);assert.equal((await call('brand-sources?brand_kit_version_id='+next+'&after='+encodeURIComponent(first.j.next_cursor))).r.status,400);
 for(const role of['Viewer','Billing']){await db.query('UPDATE memberships SET role=$1 WHERE workspace_id=$2',[role,workspace]);assert.equal((await call('brand-sources/'+source)).r.status,role==='Viewer'?200:403);assert.equal((await call('brand-sources/'+source+'/remove','POST',{})).r.status,403);}await db.query("UPDATE memberships SET role='Owner'WHERE workspace_id=$1",[workspace]);
 const reader=(await call('api-keys','POST',{name:'Memory reader',scopes:['brands:read'],expires_in_days:1})).j.secret;assert.equal((await call('%62rand-sources/'+source,'GET',undefined,randomUUID(),workspace,reader)).r.status,200);assert.equal((await call('brands/'+brand+'/memory-preview','POST',{query:'cotton'},randomUUID(),workspace,reader)).r.status,200);assert.equal((await call('%62rand-sources/'+source+'/remove','POST',{},randomUUID(),workspace,reader)).r.status,403);
 assert.equal((await call('emails/generate','POST',{prompt:'Cotton sneaker announcement',brand_kit_version_id:brand})).j.error.code,'PROVIDER_NOT_READY');
 // The new current kit has no old chunks; a page reload binds the panel to that version.
 await page.reload();await panel.getByText('No source added to this brand version.',{exact:true}).waitFor();await panel.getByLabel('Source title',{exact:true}).fill('Browser source');await panel.getByLabel('Source reference',{exact:true}).fill('Owned browser fixture');await panel.getByLabel('Approved source text',{exact:true}).fill('Cotton facts from the owner.');await panel.getByLabel(/I have rights/).check();await context.setOffline(true);await panel.getByRole('button',{name:'Add approved source',exact:true}).click();await panel.getByRole('alert').filter({hasText:/fetch|network|Failed/i}).waitFor();assert.equal(await panel.getByLabel('Approved source text',{exact:true}).inputValue(),'Cotton facts from the owner.');await context.setOffline(false);
 let posts=0;page.on('request',(r)=>{if(r.method()==='POST'&&new URL(r.url()).pathname==='/v1/brand-sources')posts++;});await panel.getByRole('button',{name:'Add approved source',exact:true}).evaluate((el)=>{(el as HTMLButtonElement).click();(el as HTMLButtonElement).click();});await panel.getByRole('heading',{name:'Browser source',exact:true}).waitFor();assert.equal(posts,1);
 await panel.getByLabel('Retrieval brief',{exact:true}).fill('cotton');await panel.getByRole('button',{name:'Inspect retrieval context',exact:true}).click();await panel.getByRole('status').filter({hasText:/1 selected chunks/}).waitFor();
 const browserSource=(await call('brand-sources?brand_kit_version_id='+next)).j.data[0].id,path='**/v1/brand-sources/'+browserSource+'/remove',observed:string[]=[];let mode=0;await page.route(path,async(route)=>{observed.push(route.request().headers()['idempotency-key']);if(mode++===0){await route.fetch();return route.abort('failed');}if(mode===2)return route.fulfill({status:401,contentType:'application/json',body:JSON.stringify({error:{code:'AUTH_REQUIRED',message:'Fixture session interruption'}})});await route.continue();});
 await panel.getByRole('button',{name:'Remove source Browser source',exact:true}).click();await panel.getByRole('alert').filter({hasText:/fetch|network|Failed/i}).waitFor();await panel.getByRole('button',{name:'Remove source Browser source',exact:true}).click();await panel.getByRole('alert').filter({hasText:'Fixture session interruption'}).waitFor();await page.reload();await panel.getByRole('button',{name:'Confirm removal of Browser source',exact:true}).waitFor();await panel.getByRole('button',{name:'Confirm removal of Browser source',exact:true}).click();await panel.getByRole('status').filter({hasText:/Source removed from new retrieval/}).waitFor();assert.equal(observed.length,3);assert.equal(new Set(observed).size,1);await page.unroute(path);
 await panel.getByRole('button',{name:'Inspect retrieval context',exact:true}).click();await panel.getByRole('status').filter({hasText:/0 selected chunks/}).waitFor();assert.equal((await call('brand-sources/'+browserSource)).j.chunks.length,0);assert.equal((await db.query("SELECT count(*)::int AS n FROM audit_events WHERE workspace_id=$1 AND action='brand.source.removed'AND resource_id=$2",[workspace,browserSource])).rows[0].n,1);
 await call('brand-sources/'+source+'/remove','POST',{});assert.ok((await call('brand-sources','POST',input,key)).j.source.deleted_at);assert.equal((await call('brand-sources/'+source)).j.chunks.length,0);
 // Fill the active workspace budget on v1, then move beyond a first25-kit page.
 for(const row of(await call('brand-sources?brand_kit_version_id='+brand+'&limit=100')).j.data)if(!row.deleted_at)await call('brand-sources/'+row.id+'/remove','POST',{});
 for(let i=0;i<16;i++)assert.equal((await call('brand-sources','POST',{...input,title:'Prior kit capacity '+i,text:'a'.repeat(65536)})).r.status,201);
 let currentKit=next;for(let i=0;i<25;i++)currentKit=(await call('brands','POST',{...kit,name:'Memory history '+i})).j.brand.id;
 await page.reload();await panel.getByText('No source added to this brand version.',{exact:true}).waitFor();assert.equal((await call('brand-sources','POST',{...input,brand_kit_version_id:currentKit,text:'Current facts'})).j.error.code,'BRAND_MEMORY_CAPACITY');
 await page.getByRole('button',{name:'Load older brand versions',exact:true}).evaluate((el)=>{(el as HTMLButtonElement).click();(el as HTMLButtonElement).click();});await page.getByLabel('Source brand version',{exact:true}).selectOption(brand);await panel.getByRole('heading',{name:'Prior kit capacity 0',exact:true}).waitFor();await page.getByRole('button',{name:'Reload source versions',exact:true}).click();await page.getByRole('button',{name:'Reload source versions',exact:true}).waitFor({state:'visible'});await page.waitForFunction(()=>!(Array.from(document.querySelectorAll('button')).find((b)=>b.textContent==='Reload source versions')as HTMLButtonElement)?.disabled);assert.equal(await page.getByLabel('Source brand version',{exact:true}).inputValue(),brand);
 await panel.getByRole('button',{name:'Remove source Prior kit capacity 0',exact:true}).click();await panel.getByRole('status').filter({hasText:/Source removed from new retrieval/}).waitFor();await page.getByLabel('Source brand version',{exact:true}).selectOption(currentKit);await panel.getByText('No source added to this brand version.',{exact:true}).waitFor();
 await panel.getByLabel('Source title',{exact:true}).fill('Current kit after cleanup');await panel.getByLabel('Source reference',{exact:true}).fill('Owned capacity regression');await panel.getByLabel('Approved source text',{exact:true}).fill('Current approved facts');await panel.getByLabel(/I have rights/).check();await panel.getByRole('button',{name:'Add approved source',exact:true}).click();await panel.getByRole('heading',{name:'Current kit after cleanup',exact:true}).waitFor();assert.equal((await call('brand-sources?brand_kit_version_id='+brand+'&limit=100')).j.data.filter((r:{deleted_at:string|null})=>!r.deleted_at).length,15);
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await panel.scrollIntoViewIfNeeded();await page.screenshot({path:'output/playwright/lettercape-brand-memory-mobile.png'});
 let entered!:()=>void,release!:()=>void;const ready=new Promise<void>((r)=>{entered=r;}),gate=new Promise<void>((r)=>{release=r;});await page.route('**/v1/brand-sources?*',async(route)=>{const response=await route.fetch();entered();await gate;await route.fulfill({response});});await panel.getByRole('button',{name:'Reload brand sources',exact:true}).click();await ready;await page.getByRole('button',{name:'Open navigation'}).click();await page.getByLabel('Active brand workspace').selectOption(other);await page.getByRole('heading',{name:'Make something worth opening.',exact:true}).waitFor();release();await page.evaluate(()=>new Promise((r)=>requestAnimationFrame(()=>requestAnimationFrame(()=>r(true)))));assert.equal(await page.locator('.brand-memory-panel').count(),0);
 console.log('Brand Memory actual HTTP/Chromium: exact kit/tenant, source rights/UTF8, signed26-source paging, read/write/encoded boundaries, immutable tombstone/current replay, empty/offline/repeat/lost+401+reload recovery/mobile/workspace pass; model/provider requests0.');
}finally{await browser?.close();for(const table of['brand_memory_chunks','brand_sources','api_rate_events','api_keys','idempotency','audit_events','brands','memberships'])await db.query(`DELETE FROM ${table} WHERE workspace_id=ANY($1::uuid[])`,[[workspace,other]]);await db.query('DELETE FROM auth_sessions WHERE user_id=$1',[user]);await db.query('DELETE FROM workspaces WHERE id=ANY($1::uuid[])',[[workspace,other]]);await db.end();}
