import {sourceFixtureQuery,waitSourceDraft} from './fixtures/email-source-context';
import assert from 'node:assert/strict';
import {randomUUID,randomBytes} from 'node:crypto';
import pg from 'pg';
import env from '@next/env';
import {chromium} from 'playwright';
import {digest} from '../src/server/audit';
import {blankSpec} from '../src/domain/email';
env.loadEnvConfig(process.cwd());
const origin=process.env.APP_ORIGIN??'http://127.0.0.1:3003';
const app=new URL(origin);
assert.ok(process.env.LOCAL_DEVELOPMENT==='true'&&app.protocol==='http:'&&app.hostname==='127.0.0.1'&&(['3002','3003'].includes(app.port)||(app.port==='3000'&&process.env.CI==='true')||(app.port==='3004'&&process.env.SOURCE_TRUTH_FIXTURE==='true'&&new URL(process.env.MIGRATION_DATABASE_URL!).pathname.startsWith('/creation_fixture_'))),'Owned loopback code editor fixture required.');
for(const name of ['DATABASE_URL','MIGRATION_DATABASE_URL']){const value=new URL(process.env[name]!);assert.equal(value.hostname,'127.0.0.1');assert.equal(value.port,'55439');}
const db=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL}),workspace=randomUUID(),other=randomUUID(),user='code-editor-'+randomUUID(),viewer='code-viewer-'+randomUUID(),cookie=randomBytes(32).toString('hex'),viewerCookie=randomBytes(32).toString('hex'),brand=randomUUID(),otherBrand=randomUUID(),email=randomUUID(),generated=randomUUID(),otherEmail=randomUUID();
const initial='<p>Owned Monaco source Ω</p>',source={...blankSpec(brand,'Owned code editor'),editing_mode:'raw_html' as const,sections:[],raw_html:initial};
let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
try{
 await db.query("INSERT INTO workspaces(id,name)VALUES($1,'Owned code editor'),($2,'Owned other code editor')",[workspace,other]);
 await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$3,'Owner'),($2,$3,'Owner'),($1,$4,'Viewer')",[workspace,other,user,viewer]);
 await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,clock_timestamp()+interval '1 hour'),($3,$4,clock_timestamp()+interval '1 hour')",[digest(cookie),user,digest(viewerCookie),viewer]);
 await db.query("INSERT INTO brands(workspace_id,id,version,data)VALUES($1,$2,1,'{}'),($3,$4,1,'{}')",[workspace,brand,other,otherBrand]);
 for(const [w,id,title,spec] of [[workspace,email,'Owned Monaco raw',source],[workspace,generated,'Owned Monaco compiled',blankSpec(brand,'Owned code editor')],[other,otherEmail,'Other isolated Monaco',{...source,brand_kit_version_id:otherBrand,raw_html:'<p>Other workspace source</p>'}]] as const)await sourceFixtureQuery(db,w,user,'INSERT INTO emails(workspace_id,id,title,spec,created_by)VALUES($1,$2,$3,$4,$5)',[w,id,title,JSON.stringify(spec),user]);
 browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);await context.addInitScript(w=>{if(window.top!==window)return;if(!localStorage.getItem('mailcraft.workspace'))localStorage.setItem('mailcraft.workspace',w);},workspace);let sourceRequests=0;context.on('request',request=>{if(new URL(request.url()).pathname==='/__code-source-execution-sentinel')sourceRequests++;});const page=await context.newPage();const primaryErrors:string[]=[];page.on('pageerror',error=>{primaryErrors.push(error.message);console.error('CODE_EDITOR_PRIMARY_PAGE_ERROR',page.url(),error.stack);});page.on('console',message=>{if(message.type()==='error')console.log('CODE_EDITOR_PRIMARY_CONSOLE_ERROR',message.text());});page.on('dialog',dialog=>dialog.accept());
 await page.goto(origin+'/app/emails/'+email);await page.getByRole('textbox',{name:'Subject',exact:true}).waitFor();await page.getByRole('button',{name:'HTML',exact:true}).first().click();
 assert.equal(await page.getByRole('button',{name:'Use basic editor',exact:true}).count(),1,'HTML tab must offer the enhanced editor switch; absent control RED.');
 const raw=page.getByRole('textbox',{name:'Raw HTML source',exact:true});
 const mac=await page.evaluate(()=>/Mac/.test(navigator.platform)),home=mac?'Meta+ArrowUp':'Control+Home',end=mac?'Meta+ArrowDown':'Control+End';
 async function modelCount(){return page.evaluate(async()=>{const manifest=await(await fetch('/code-editor/manifest.json')).json();return(await import(manifest.module)).getActiveModelCount();});}
 async function enhanced(){await page.locator('.html-code-editor .monaco-editor').waitFor({state:'visible'});assert.equal(await raw.count(),1,'Exactly one accessible source field');assert.equal(await page.locator('.html-code-editor > textarea').count(),0,'Real Monaco must replace the basic textarea');assert.equal(await modelCount(),1,'Exactly one live Monaco model');}
 async function basic(){const control=page.getByRole('button',{name:'Use basic editor',exact:true});if(await control.count())await control.click();await page.locator('.html-code-editor > textarea').waitFor({state:'visible'});assert.equal(await modelCount(),0,'Basic switch disposes all Monaco models');return raw.inputValue();}
 async function enhance(){await page.getByRole('button',{name:'Use enhanced editor',exact:true}).click();await enhanced();}
 async function open(id=email){await page.goto(origin+'/app/emails/'+id);await page.getByRole('textbox',{name:'Subject',exact:true}).waitFor();await page.getByRole('button',{name:'HTML',exact:true}).first().click();}
 async function save(){await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('status').filter({hasText:/Saved/}).waitFor();}
 const requests:string[]=[];page.on('request',request=>{if(request.url().includes('/code-editor/'))requests.push(request.url());});
 let external=0;await context.route(url=>url.origin!==origin,route=>{external++;return route.abort('blockedbyclient');});
 await enhanced();console.log('Monaco enhanced initialization PASS.');
 await raw.focus();await page.keyboard.press('ControlOrMeta+A');await page.keyboard.insertText('<p>Keyboard Monaco edit Ω</p>');assert.equal(await basic(),'<p>Keyboard Monaco edit Ω</p>','Exact keyboard callback source before server sanitization');await enhance();await save();
 assert.equal((await db.query('SELECT spec FROM emails WHERE workspace_id=$1 AND id=$2',[workspace,email])).rows[0].spec.raw_html,'<p>Keyboard Monaco edit Ω</p>');
 console.log('Monaco keyboard save database truth PASS.');await page.reload();await page.getByRole('textbox',{name:'Subject',exact:true}).waitFor();await page.getByRole('button',{name:'HTML',exact:true}).first().click();await enhanced();
 assert.equal(await basic(),'<p>Keyboard Monaco edit Ω</p>');await enhance();
 await raw.focus();await page.keyboard.press(end);await page.keyboard.insertText('X');await page.getByRole('button',{name:'Undo',exact:true}).click();assert.equal(await basic(),'<p>Keyboard Monaco edit Ω</p>');await enhance();
 // Source syntax is data, including mixed endings, Unicode and executable-looking text.
 const exact='<p>First Ω</p>\r\n<div>Second 👩🏽‍💻</div>\n<p>Third</p>\r<script>window.__codeSourceRan=true</script><img src="/__code-source-execution-sentinel" onerror="window.__codeSourceRan=true">',exactEmail=randomUUID();
 await sourceFixtureQuery(db,workspace,user,'INSERT INTO emails(workspace_id,id,title,spec,created_by)VALUES($1,$2,$3,$4,$5)',[workspace,exactEmail,'Owned mixed source preservation',JSON.stringify({...source,raw_html:exact}),user]);
 await page.route('**/v1/emails/'+exactEmail+'/draft',route=>route.abort());await open(exactEmail);await enhanced();assert.equal(await basic(),exact.replace(/\r\n?|\n/g,'\n'));await enhance();
 await raw.focus();await page.keyboard.press(home);await page.keyboard.insertText('Enhanced prefix');

 await waitSourceDraft(page,{workspace,actor:user,email:exactEmail},'raw_html','Enhanced prefix'+exact);
 await basic();await raw.focus();await page.keyboard.press(home);await page.keyboard.insertText('Basic prefix');await waitSourceDraft(page,{workspace,actor:user,email:exactEmail},'raw_html','Basic prefixEnhanced prefix'+exact);
 await enhance();await raw.focus();await page.keyboard.press(home);await page.keyboard.insertText('Again');await waitSourceDraft(page,{workspace,actor:user,email:exactEmail},'raw_html','AgainBasic prefixEnhanced prefix'+exact);assert.equal(await page.evaluate(()=>Reflect.get(window,'__codeSourceRan')),undefined);
 console.log('Enhanced/basic exact mixed source edits PASS.');
 const bomEmail=randomUUID(),bomSource='\uFEFF<p>BOM Ω</p>\r\n<div>Preserved ending</div>';
 await sourceFixtureQuery(db,workspace,user,'INSERT INTO emails(workspace_id,id,title,spec,created_by)VALUES($1,$2,$3,$4,$5)',[workspace,bomEmail,'Owned leading BOM source',JSON.stringify({...source,raw_html:bomSource}),user]);await page.route('**/v1/emails/'+bomEmail+'/draft',route=>route.abort());await open(bomEmail);await enhanced();await raw.focus();await page.keyboard.press(end);await page.keyboard.insertText('X');await waitSourceDraft(page,{workspace,actor:user,email:bomEmail},'raw_html',bomSource+'X');
 await basic();await raw.focus();await page.keyboard.press(end);await page.keyboard.insertText('Y');await waitSourceDraft(page,{workspace,actor:user,email:bomEmail},'raw_html',bomSource+'XY');await enhance();await raw.focus();await page.keyboard.press(home);await page.keyboard.insertText('Z');await waitSourceDraft(page,{workspace,actor:user,email:bomEmail},'raw_html','\uFEFFZ'+bomSource.slice(1)+'XY');console.log('Enhanced/basic leading BOM exact source edits PASS.');
 await open();await enhanced();await basic();await raw.fill('<p>Stable saved source</p>');await save();
 // A fresh page holds the manifest while newer basic edits remain authoritative.
 const delayed=await context.newPage();delayed.on('dialog',dialog=>dialog.accept());
 let release!:()=>void;const held=new Promise<void>(resolve=>{release=resolve;});let arrived!:()=>void;const arrival=new Promise<void>(resolve=>{arrived=resolve;});
 await delayed.route('**/code-editor/manifest.json',async route=>{arrived();await held;await route.continue();});
 await delayed.goto(origin+'/app/emails/'+email);await delayed.getByRole('textbox',{name:'Subject',exact:true}).waitFor();await delayed.getByRole('button',{name:'HTML',exact:true}).first().click();await arrival;
 const delayedRaw=delayed.locator('textarea[aria-label="Raw HTML source"]'),delayedSource='<p>Newer basic while loading Ω</p>';await delayedRaw.fill(delayedSource);await delayedRaw.evaluate(element=>{(element as HTMLTextAreaElement).setSelectionRange(5,9);element.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));});release();await delayed.waitForFunction(()=>Boolean(document.querySelector('.monaco-editor')?.getBoundingClientRect().height)||Array.from(document.querySelectorAll('p')).some(element=>element.textContent?.includes('Enhanced editor ready')));
 assert.equal(await delayedRaw.count(),1,'Automatic enhancement must retain the actively composed basic field');assert.equal(await delayedRaw.evaluate(element=>element===document.activeElement),true);assert.deepEqual(await delayedRaw.evaluate(element=>[(element as HTMLTextAreaElement).selectionStart,(element as HTMLTextAreaElement).selectionEnd]),[5,9]);await delayed.keyboard.insertText('X');assert.equal(await delayedRaw.inputValue(),delayedSource.slice(0,5)+'X'+delayedSource.slice(9));await delayedRaw.dispatchEvent('compositionend',{data:'X'});assert.equal(await delayed.locator('.monaco-editor').count(),0,'Composition end must not steal an actively focused field');await delayedRaw.fill(delayedSource);await delayed.getByRole('textbox',{name:'Subject',exact:true}).focus();await delayed.locator('.html-code-editor .monaco-editor').waitFor({state:'visible'});await delayed.getByRole('button',{name:'Use basic editor',exact:true}).click();assert.equal(await delayedRaw.inputValue(),'<p>Newer basic while loading Ω</p>');await delayed.getByRole('button',{name:'Save',exact:true}).click();await delayed.getByRole('status').filter({hasText:/Saved/}).waitFor();await delayed.close();
 console.log('Native I1 focused basic typing/selection and simulated composition retained through ready; blur adopts latest source PASS.');await open();await enhanced();assert.equal(await basic(),'<p>Newer basic while loading Ω</p>');
 for(const navigation of [false,true]){
  const cancelledPage=await context.newPage();cancelledPage.on('dialog',dialog=>dialog.accept());let finish!:()=>void,started!:()=>void;const wait=new Promise<void>(resolve=>{finish=resolve;}),start=new Promise<void>(resolve=>{started=resolve;});
  await cancelledPage.route('**/code-editor/manifest.json',async route=>{started();await wait;await route.continue();});await cancelledPage.goto(origin+'/app/emails/'+email);await cancelledPage.getByRole('textbox',{name:'Subject',exact:true}).waitFor();await cancelledPage.getByRole('button',{name:'HTML',exact:true}).first().click();await start;await cancelledPage.locator('textarea[aria-label="Raw HTML source"]').focus();await cancelledPage.locator('textarea[aria-label="Raw HTML source"]').dispatchEvent('compositionstart');
  if(navigation)await cancelledPage.getByRole('button',{name:'Preview',exact:true}).first().click();else await cancelledPage.getByRole('button',{name:'Use basic editor',exact:true}).click();
  const completed=cancelledPage.waitForResponse(response=>response.url().endsWith('/editor.js'));finish();await completed;await cancelledPage.waitForFunction(async()=>{const manifest=await(await fetch('/code-editor/manifest.json')).json();return(await import(manifest.module)).getActiveModelCount()===0;});assert.equal(await cancelledPage.locator('.monaco-editor').count(),0,'Cancelled loading must not resurrect an editor');await cancelledPage.close();console.log('Cancelled loading mode/navigation PASS.',navigation);
 }
 // Fail executable assets on a new document so no cached loader hides failure.
 for(const asset of ['manifest.json','editor.css','editor.js','html.worker.js']){
  const failedId=randomUUID();await sourceFixtureQuery(db,workspace,user,'INSERT INTO emails(workspace_id,id,title,spec,created_by)VALUES($1,$2,$3,$4,$5)',[workspace,failedId,'Owned asset failure '+asset,JSON.stringify({...source,raw_html:'<p>Newer basic while loading Ω</p>'}),user]);
  const failed=await context.newPage();failed.on('dialog',dialog=>dialog.accept());await failed.route('**/code-editor/**/'+asset,route=>route.abort());if(asset==='manifest.json')await failed.route('**/code-editor/manifest.json',route=>route.abort());
  await failed.goto(origin+'/app/emails/'+failedId);await failed.getByRole('textbox',{name:'Subject',exact:true}).waitFor();await failed.getByRole('button',{name:'HTML',exact:true}).first().click();await failed.getByText('Enhanced editor unavailable. Basic editor preserves your source.',{exact:true}).waitFor();
  const field=failed.getByRole('textbox',{name:'Raw HTML source',exact:true});assert.equal(await field.inputValue(),'<p>Newer basic while loading Ω</p>');await field.fill('<p>Retained basic failure work '+asset+'</p>');assert.equal(await field.inputValue(),'<p>Retained basic failure work '+asset+'</p>');await failed.close();console.log('Asset failure fallback PASS.',asset);
 }
 const runtimeFailed=await context.newPage();runtimeFailed.on('dialog',dialog=>dialog.accept());let workerRequests=0;
 await runtimeFailed.route('**/code-editor/**/html.worker.js',route=>++workerRequests===1?route.continue():route.abort());await runtimeFailed.goto(origin+'/app/emails/'+email);await runtimeFailed.getByRole('textbox',{name:'Subject',exact:true}).waitFor();await runtimeFailed.getByRole('button',{name:'HTML',exact:true}).first().click();await runtimeFailed.locator('.html-code-editor .monaco-editor').waitFor({state:'visible'});await runtimeFailed.getByRole('textbox',{name:'Raw HTML source',exact:true}).focus();await runtimeFailed.keyboard.press('Control+Space');await runtimeFailed.getByText('Enhanced editor unavailable. Basic editor preserves your source.',{exact:true}).waitFor();assert.ok(workerRequests>=2,'Real Worker request must fail after successful worker preflight');assert.equal(await runtimeFailed.getByRole('textbox',{name:'Raw HTML source',exact:true}).inputValue(),'<p>Newer basic while loading Ω</p>');await runtimeFailed.close();
 // Use an isolated low-level instance of the actual bundled adapter for disposal proof.
 const lifecycle=await page.evaluate(async()=>{
  const manifest=await(await fetch('/code-editor/manifest.json')).json();
  const runtime=await import(manifest.module);const host=document.createElement('div');host.style.height='200px';document.body.append(host);
  let callbacks=0;const value='<p>Lifecycle source</p>';const editor=runtime.create(host,{value,readOnly:false,label:'Owned lifecycle test'},()=>callbacks++);const same=editor.getValue()===value;const live=runtime.getActiveModelCount();editor.dispose();editor.dispose();const nodes=host.childElementCount,disposed=runtime.getActiveModelCount();host.remove();return{same,nodes,callbacks,live,disposed};
 });assert.deepEqual(lifecycle,{same:true,nodes:0,callbacks:0,live:1,disposed:0});
 for(let index=0;index<3;index++){await enhance();await raw.focus();await page.keyboard.press('Escape');assert.equal(await page.getByRole('button',{name:'Use basic editor',exact:true}).evaluate(node=>node===document.activeElement),true);assert.equal(await basic(),'<p>Newer basic while loading Ω</p>');}
 await enhance();await page.getByRole('button',{name:'Preview',exact:true}).first().click();assert.equal(await page.locator('.monaco-editor').count(),0);assert.equal(await modelCount(),0,'HTML tab navigation disposes the model');await page.getByRole('button',{name:'HTML',exact:true}).first().click();await enhanced();
 // Generated source and a current Viewer cannot edit through real Monaco.
 const probeCompiledPreviewRace=process.argv.includes('--probe-compiled-preview-race');
 const generatedPreviewUrl=origin+'/v1/emails/'+generated+'/preview';
 let releaseGeneratedPreview!:()=>void,generatedPreviewHeld!:()=>void;
 const generatedPreviewGate=new Promise<void>(resolve=>{releaseGeneratedPreview=resolve;});
 const generatedPreviewArrival=new Promise<void>(resolve=>{generatedPreviewHeld=resolve;});
 if(probeCompiledPreviewRace)await page.route(generatedPreviewUrl,async route=>{
  const response=await route.fetch();generatedPreviewHeld();await generatedPreviewGate;await route.fulfill({response});
 });
 const generatedPreviewResponse=page.waitForResponse(response=>response.url()===generatedPreviewUrl&&response.request().method()==='POST');
 await open(generated);await page.locator('.html-code-editor .monaco-editor').waitFor({state:'visible'});
 const compiled=page.getByRole('textbox',{name:'Compiled HTML source',exact:true});
 assert.equal(await compiled.getAttribute('aria-readonly'),'true');
 await page.getByRole('button',{name:'Use basic editor',exact:true}).click();
 if(probeCompiledPreviewRace){await generatedPreviewArrival;assert.equal(await compiled.inputValue(),'','Held preview must expose the initial empty field');releaseGeneratedPreview();}
 const generatedResponse=await generatedPreviewResponse;assert.equal(generatedResponse.status(),200);
 const generatedHtml=(await generatedResponse.json()).artifact.html;assert.equal(typeof generatedHtml,'string');assert.ok(generatedHtml.includes('Owned code editor'));
 await page.waitForFunction(expected=>{const field=document.querySelector('textarea[aria-label="Compiled HTML source"]');return field instanceof HTMLTextAreaElement&&field.value===expected;},generatedHtml);
 if(probeCompiledPreviewRace){console.log('Compiled preview race probe adopted exact generated artifact before read-only baseline.');await page.unroute(generatedPreviewUrl);}
 const compiledBefore=await compiled.inputValue();assert.equal(compiledBefore,generatedHtml);
 const generatedBefore=(await db.query('SELECT spec,doc_version FROM emails WHERE workspace_id=$1 AND id=$2',[workspace,generated])).rows[0];
 assert.equal(await compiled.evaluate(node=>(node as HTMLTextAreaElement).readOnly),true);
 await page.getByRole('button',{name:'Use enhanced editor',exact:true}).click();await page.locator('.html-code-editor .monaco-editor').waitFor({state:'visible'});
 await compiled.focus();await page.keyboard.press('ControlOrMeta+A');await page.keyboard.insertText('Generated source must remain read-only');
 await page.getByRole('button',{name:'Use basic editor',exact:true}).click();assert.equal(await compiled.inputValue(),compiledBefore);
 assert.deepEqual((await db.query('SELECT spec,doc_version FROM emails WHERE workspace_id=$1 AND id=$2',[workspace,generated])).rows[0],generatedBefore,'Read-only keyboard attempt must not mutate the generated document');
 assert.equal(await page.getByRole('button',{name:'Edit raw HTML',exact:true}).isEnabled(),true);
 const importPattern='**/v1/emails/'+generated+'/source-fork';await page.route(importPattern,async route=>{await new Promise(resolve=>setTimeout(resolve,400));await route.continue();});await page.getByRole('button',{name:'Edit raw HTML',exact:true}).click();await raw.waitFor();await page.unroute(importPattern);assert.equal((await db.query('SELECT spec FROM emails WHERE workspace_id=$1 AND id=$2',[workspace,generated])).rows[0].spec.editing_mode,'raw_html');await enhanced();
 await context.addCookies([{name:'mailcraft_local_session',value:viewerCookie,url:origin,sameSite:'Strict'}]);await open();await enhanced();assert.equal(await raw.getAttribute('aria-readonly'),'true');const beforeViewer=(await db.query('SELECT spec FROM emails WHERE workspace_id=$1 AND id=$2',[workspace,email])).rows[0].spec.raw_html;await raw.focus();await page.keyboard.press('ControlOrMeta+A');await page.keyboard.insertText('Viewer must not mutate');assert.equal(await basic(),beforeViewer);assert.equal((await db.query('SELECT spec FROM emails WHERE workspace_id=$1 AND id=$2',[workspace,email])).rows[0].spec.raw_html,beforeViewer);
 console.log('Readonly compiled/checkpoint and Viewer attempted keyboard mutation PASS.');await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);await open();await enhanced();await page.locator('#workspace').selectOption(other);await page.waitForURL(origin+'/app');assert.equal(await modelCount(),0,'Workspace navigation disposes the old actor model');await open(otherEmail);await enhanced();assert.equal(await basic(),'<p>Other workspace source</p>');await page.locator('#workspace').selectOption(workspace);await page.waitForURL(origin+'/app');await open();await enhanced();assert.equal(await basic(),beforeViewer);console.log('Actor/workspace navigation source isolation PASS.');
 // Mobile begins with basic mode, with no Monaco requests or horizontal overflow.
 const mobileContext=await browser.newContext({viewport:{width:390,height:844}});await mobileContext.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);await mobileContext.addInitScript(w=>{if(window.top===window)localStorage.setItem('mailcraft.workspace',w);},workspace);const mobile=await mobileContext.newPage();let mobileAssets=0;mobile.on('request',request=>{if(request.url().includes('/code-editor/'))mobileAssets++;});await mobile.goto(origin+'/app/emails/'+email);await mobile.getByRole('textbox',{name:'Subject',exact:true}).waitFor();await mobile.getByRole('button',{name:'HTML',exact:true}).first().click();await mobile.getByRole('button',{name:'Use enhanced editor',exact:true}).waitFor();assert.equal(await mobile.getByRole('textbox',{name:'Raw HTML source',exact:true}).inputValue(),beforeViewer);assert.equal(await mobile.locator('.monaco-editor').count(),0);assert.equal(mobileAssets,0);const mobileRaw=mobile.getByRole('textbox',{name:'Raw HTML source',exact:true});await mobileRaw.fill('<p>Mobile basic edit Ω</p>');await mobile.getByRole('button',{name:'Save',exact:true}).click();await mobile.getByRole('status').filter({hasText:/Saved/}).waitFor();assert.equal((await db.query('SELECT spec FROM emails WHERE workspace_id=$1 AND id=$2',[workspace,email])).rows[0].spec.raw_html,'<p>Mobile basic edit Ω</p>');assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.locator('.html-code-editor').scrollIntoViewIfNeeded();await mobile.screenshot({path:'/tmp/lettercape-code-editor-mobile.png'});await mobile.locator('.html-code-editor').screenshot({path:'/tmp/lettercape-code-editor-mobile-panel.png'});await mobileContext.close();console.log('390px basic editor actual edit/save/no overflow/no asset requests PASS.');await open();await enhanced();await basic();
 // Trigger language assistance, then verify local CSS, module, font and workers.
 await enhance();await raw.focus();await page.keyboard.press(end);await page.keyboard.press('Control+Space');for(let attempt=0;attempt<40&&!page.workers().some(worker=>worker.url().endsWith('/html.worker.js'));attempt++)await page.waitForTimeout(100);await page.keyboard.press('Escape');
 const manifest=await(await context.request.get(origin+'/code-editor/manifest.json')).json();for(const key of ['module','stylesheet','editor_worker','html_worker']){const response=await context.request.get(origin+manifest[key]);assert.equal(response.status(),200);assert.equal(new URL(response.url()).origin,origin);}
 const font=await page.evaluate(async stylesheet=>{const css=await(await fetch(stylesheet)).text();const reference=/url\(["']?([^\)"']+\.ttf)["']?\)/.exec(css)?.[1];if(!reference)throw Error('Local code editor font missing');const url=new URL(reference,new URL(stylesheet,location.origin));const response=await fetch(url);return{origin:url.origin,status:response.status};},manifest.stylesheet);assert.deepEqual(font,{origin,status:200});
 const workerUrls=page.workers().map(worker=>worker.url());assert.ok(workerUrls.some(url=>url.endsWith('/editor.worker.js')),'Actual editor Worker instantiated');assert.ok(workerUrls.some(url=>url.endsWith('/html.worker.js')),'Actual HTML language Worker instantiated');assert.ok(workerUrls.every(url=>new URL(url).origin===origin));assert.ok(requests.every(url=>new URL(url).origin===origin));assert.equal(external,0);assert.equal(sourceRequests,0,'HTML source must not request executable image sentinel');assert.equal(await page.evaluate(()=>Reflect.get(window,'__codeSourceRan')),undefined);await page.screenshot({path:'/tmp/lettercape-code-editor-desktop.png'});assert.deepEqual(primaryErrors,[],'Primary editor must not raise uncaught page errors');console.log('Primary editor uncaught page errors zero; console diagnostics retained above.');
 console.log('Owned Monaco Chromium PASS: real keyboard edit/save/reload/undo; exact Unicode/mixed endings; delayed latest basic source; manifest/style/module/worker failures; switches, adapter disposal and navigation; readonly generated and Viewer; actor/workspace isolation; Escape;390px basic/no overflow; local workers/font/CSS/module and no source execution.');
}catch(error){console.error('CODE_EDITOR_FIXTURE_FAILURE',error);throw error;}finally{
 await browser?.close();const cleanup=await db.connect();try{await cleanup.query('BEGIN');await cleanup.query('SELECT id FROM emails WHERE workspace_id=ANY($1::uuid[]) FOR UPDATE',[[workspace,other]]);for(const table of ['email_source_provenance','render_downloads','preflights','idempotency','audit_events','revisions','emails','brands','memberships'])await cleanup.query('DELETE FROM '+table+' WHERE workspace_id=ANY($1::uuid[])',[[workspace,other]]);await cleanup.query('DELETE FROM workspaces WHERE id=ANY($1::uuid[])',[[workspace,other]]);await cleanup.query('DELETE FROM auth_sessions WHERE user_id=ANY($1::text[])',[[user,viewer]]);await cleanup.query('COMMIT');assert.equal((await db.query('SELECT count(*)::int AS n FROM workspaces WHERE id=ANY($1::uuid[])',[[workspace,other]])).rows[0].n,0);assert.equal((await db.query('SELECT count(*)::int AS n FROM auth_sessions WHERE user_id=ANY($1::text[])',[[user,viewer]])).rows[0].n,0);console.log('Owned code editor exact fixture cleanup PASS.');}catch(error){await cleanup.query('ROLLBACK');throw error;}finally{cleanup.release();await db.end();}
}
