import assert from'node:assert/strict';import{randomUUID,randomBytes}from'node:crypto';import pg from'pg';import env from'@next/env';import{digest}from'../src/server/audit';import{blankSpec}from'../src/domain/email';import{apiSpec,absoluteSchema,validateSchema}from'./api-validation';env.loadEnvConfig(process.cwd());
const origin=process.env.APP_ORIGIN??'http://127.0.0.1:3003';if(process.env.LOCAL_DEVELOPMENT!=='true'||!['127.0.0.1','localhost'].includes(new URL(origin).hostname))throw new Error('Owned local Voice Guard fixture required.');const db=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL}),workspace=randomUUID(),other=randomUUID(),user='voice-http-'+randomUUID(),cookie=randomBytes(32).toString('hex');let browser:Awaited<ReturnType<(typeof import('playwright'))['chromium']['launch']>>|undefined;
async function call(path:string,method='GET',body?:unknown,key=randomUUID(),w=workspace,version?:number,bearer?:string){const r=await fetch(origin+'/v1/'+path,{method,headers:{Origin:origin,'Content-Type':'application/json','Idempotency-Key':key,...(bearer?{Authorization:'Bearer '+bearer}:{Cookie:'mailcraft_local_session='+cookie,'X-Workspace-Id':w}),...(version?{'If-Match':'"draft-'+version+'"'}:{})},body:body===undefined?undefined:JSON.stringify(body)});return{r,j:await r.json()};}
const kit={name:'Voice fixture',website:'',description:'Owned fixture',voice:'Plain',accent:'#0B625D',background:'#F7F6F2',font_stack:'Arial, sans-serif',address:'Reserved fixture address',approved_claims:[],forbidden_phrases:[],provenance:[]};
try{
 await db.query("INSERT INTO workspaces(id,name)VALUES($1,'Voice HTTP fixture'),($2,'Voice HTTP foreign')",[workspace,other]);for(const w of[workspace,other])await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,'Owner')",[w,user]);await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,clock_timestamp()+interval '1 hour')",[digest(cookie),user]);const first=(await call('brands','POST',kit)).j.brand.id,spec=blankSpec(first,kit.name);spec.subject='Plain';spec.preheader='Plain';spec.sections=[{id:'copy',type:'text',text:'One two three!'}];const email=(await call('emails','POST',{title:'Old kit pinned',spec})).j.email,revision=(await call('emails/'+email.id+'/revisions','POST',{},randomUUID(),workspace,email.doc_version)).j.revision;assert.ok(revision?.id);
 // Synthetic passing row is owned fixture data, never a vendor or GA acceptance claim.
 await db.query("INSERT INTO preflights(workspace_id,revision_id,artifact_hash,state,findings,rule_set_version)VALUES($1,$2,$3,'passed','[]','static-2')",[workspace,revision.id,revision.artifact_hash]);const campaign=(await call('campaigns','POST',{name:'Owned stale-rule fixture',revision_id:revision.id})).j.campaign;assert.ok(campaign?.id);const blocked=await call('campaigns/'+campaign.id+'/approve','POST',{});assert.equal(blocked.r.status,422);assert.equal(blocked.j.error.code,'PREFLIGHT_BLOCKED');
 const rules={max_sentence_words:2,max_exclamations:0},key=randomUUID(),next=await call('brands','POST',{...kit,tone_rules:rules},key);assert.equal(next.r.status,201);validateSchema(absoluteSchema(apiSpec.components.schemas.BrandResponse),next.j);assert.deepEqual(next.j.brand.data.tone_rules,rules);assert.equal((await call('brands','POST',{...kit,tone_rules:rules},key)).j.brand.id,next.j.brand.id);assert.equal((await call('brands','POST',{...kit,tone_rules:{regex:'.*'}})).r.status,422);
 const oldReport=(await call('email-revisions/'+revision.id+'/preflight','POST',{})).j.report;assert.equal(oldReport.rule_set_version,'static-3');assert.equal(oldReport.findings.some((f:{code:string})=>f.code==='VOICE_SENTENCE_LENGTH'||f.code==='VOICE_EXCLAMATIONS'),false);assert.equal((await db.query('SELECT data FROM brands WHERE id=$1',[first])).rows[0].data.tone_rules,undefined);
 const nextSpec={...spec,brand_kit_version_id:next.j.brand.id},newEmail=(await call('emails','POST',{title:'New kit pinned',spec:nextSpec})).j.email,newRevision=(await call('emails/'+newEmail.id+'/revisions','POST',{},randomUUID(),workspace,newEmail.doc_version)).j.revision,report=(await call('email-revisions/'+newRevision.id+'/preflight','POST',{})).j.report;assert.equal(report.rule_set_version,'static-3');assert.deepEqual(report.findings.filter((f:{code:string})=>['VOICE_SENTENCE_LENGTH','VOICE_EXCLAMATIONS'].includes(f.code)).map((f:{code:string;location:string})=>[f.code,f.location]),[['VOICE_SENTENCE_LENGTH','copy'],['VOICE_EXCLAMATIONS','copy']]);assert.notEqual(report.state,'passed');assert.equal((await call('brands','POST',{...kit,name:'Foreign own kit'},randomUUID(),other)).r.status,201);assert.equal((await call('emails','POST',{title:'Foreign pinned kit',spec:nextSpec},randomUUID(),other)).r.status,404);
 for(const role of['Viewer','Billing']){await db.query('UPDATE memberships SET role=$1 WHERE workspace_id=$2 AND user_id=$3',[role,workspace,user]);assert.equal((await call('brands','POST',{...kit,tone_rules:rules})).r.status,403);}await db.query("UPDATE memberships SET role='Owner'WHERE workspace_id=$1 AND user_id=$2",[workspace,user]);const reader=(await call('api-keys','POST',{name:'Owned tone reader',scopes:['brands:read'],expires_in_days:1})).j.secret;assert.equal((await call('brands','POST',{...kit,tone_rules:rules},randomUUID(),workspace,undefined,reader)).r.status,403);
 if(!process.argv.includes('--api')){const{chromium}=await import('playwright');browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844}});await context.addInitScript(w=>localStorage.setItem('mailcraft.workspace',w),workspace);await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);const page=await context.newPage();await page.goto(origin+'/app/brand');await page.getByLabel('Maximum words per sentence',{exact:true}).waitFor({timeout:5000});assert.equal(await page.getByLabel('Maximum words per sentence',{exact:true}).inputValue(),'2');}
 console.log('Voice Guard actual HTTP API PASS: optional strict configured limits, immutable v1/v2 pins, located static-3 findings, stale rule-set approval blocked, foreign and role/key writes denied. No provider/model/rewrite/send calls. Browser controls remain to implement.');
}finally{await browser?.close();for(const table of['campaigns','preflights','revisions','emails','outbox','api_rate_events','api_keys','idempotency','audit_events','memberships','brands'])await db.query(`DELETE FROM ${table} WHERE workspace_id=ANY($1::uuid[])`,[[workspace,other]]);await db.query('DELETE FROM auth_sessions WHERE user_id=$1',[user]);await db.query('DELETE FROM workspaces WHERE id=ANY($1::uuid[])',[[workspace,other]]);await db.end();}
