import assert from 'node:assert/strict';import {randomBytes,randomUUID} from 'node:crypto';import {spawn,type ChildProcess} from 'node:child_process';import {open} from 'node:fs/promises';import {chromium} from 'playwright';
import {sourceDatabase} from './smoke-source-truth';import {blankSpec} from '../src/domain/email';import {createEmail,checkpoint,saveDraft} from '../src/server/emails';import {deriveEmail} from '../src/server/derivation';import {digest} from '../src/server/audit';import type {EmailSpec} from '../src/domain/email-schema';
const origin='http://127.0.0.1:3004';
await sourceDatabase(async({db,p,brand,tx})=>{
 const original:EmailSpec={...blankSpec(brand,'Owned'),subject:'Original subject',preheader:'Original preheader',sections:[{id:'hero',type:'hero',heading:'Original heading',text:'Original body'},{id:'cta',type:'button',label:'Original CTA',href:'https://example.com/original'},{id:'offer',type:'product_card',title:'Original product',description:'Original description',price:'USD 10',href:'https://example.com/original-product'},{id:'opaque',type:'custom_html',html:'<p>Original opaque</p>'},{id:'footer',type:'legal_footer',identity:'Owned',address:'Original address',unsubscribe_slot:true}]};
 const parent=await tx(c=>createEmail(c,p,'Owned locale parent',original)),frozen=await tx(c=>checkpoint(c,p,parent.id,1)),child=await tx(c=>deriveEmail(c,p,frozen.id,{kind:'locale',title:'Owned French',locale:'fr-FR'}));
 const manual:EmailSpec={...child.email.spec,subject:'Sujet manuel',preheader:'Aperçu manuel',sections:child.email.spec.sections.map(b=>b.type==='hero'?{...b,heading:'Titre manuel',text:'Corps manuel'}:b.type==='button'?{...b,label:'CTA manuel',href:'https://example.com/manual'}:b.type==='product_card'?{...b,title:'Produit manuel',description:'Description manuelle',price:'EUR 9',href:'https://example.com/manual-product'}:b)};
 await tx(c=>saveDraft(c,p,child.email.id,1,manual));let parentVersion=2;
 let changed:EmailSpec={...original,subject:'Updated subject',preheader:'Updated preheader',sections:original.sections.map(b=>b.type==='hero'?{...b,heading:'Updated heading',text:'Updated body'}:b.type==='button'?{...b,label:'Updated CTA',href:'https://example.com/updated'}:b.type==='product_card'?{...b,title:'Updated product',description:'Updated description',price:'GBP 12',href:'https://example.com/updated-product'}:b.type==='custom_html'?{...b,html:'\ufeff<script>globalThis.__localeRan=true;fetch("/__locale_execution")</script>\r\n'}:b)};
 await tx(c=>saveDraft(c,p,parent.id,1,changed));
 const cookie=randomBytes(32).toString('hex'),viewer='locale-viewer-'+randomUUID(),viewerCookie=randomBytes(32).toString('hex');await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,'Viewer')",[p.workspace,viewer]);for(const [actor,value]of [[p.user,cookie],[viewer,viewerCookie]])await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,clock_timestamp()+interval '1 hour')",[digest(value),actor]);
 const runtime=new URL(process.env.DATABASE_URL!);runtime.pathname=new URL(db.options.connectionString!).pathname;assert.match(runtime.pathname,/^\/creation_fixture_[a-f0-9]{32}$/);const log=await open('/tmp/lettercape-locale-app.log','w');let app:ChildProcess|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
 try{
  app=spawn(process.execPath,['node_modules/next/dist/bin/next','dev','--hostname','127.0.0.1','--port','3004'],{env:{PATH:process.env.PATH,NODE_ENV:'development',LOCAL_DEVELOPMENT:'true',APP_ORIGIN:origin,DATABASE_URL:runtime.toString(),MIGRATION_DATABASE_URL:db.options.connectionString!,NEXT_TELEMETRY_DISABLED:'1'},stdio:['ignore',log.fd,log.fd]});
  for(let n=0;n<120;n++){if(app.exitCode!==null)throw Error('Owned locale app exited');try{if((await fetch(origin)).ok)break;}catch{}if(n===119)throw Error('Owned locale app unavailable');await new Promise(r=>setTimeout(r,250));}
  browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);await context.addInitScript(w=>{if(top===window)localStorage.setItem('mailcraft.workspace',w);},p.workspace);let execution=0,external=0;context.on('request',r=>{if(r.url().includes('/__locale_execution'))execution++;});await context.route(url=>url.origin!==origin&&url.protocol!=='blob:'&&url.protocol!=='data:',r=>{external++;return r.abort();});const page=await context.newPage();page.on('dialog',d=>d.accept());const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/app/emails/'+child.email.id);await page.getByRole('textbox',{name:'Subject',exact:true}).waitFor();const region=page.getByRole('region',{name:'Locale source comparison'});await region.waitFor();const endpoint=origin+'/v1/emails/'+child.email.id+'/locale-source',headers={'X-Workspace-Id':p.workspace,'X-Actor-Id':p.user};
  const counts=(await db.query('SELECT (SELECT count(*)FROM revisions) revisions,(SELECT count(*)FROM audit_events) audits')).rows;
  const result=await context.request.get(endpoint,{headers});assert.equal(result.status(),200);assert.equal((await result.json()).comparison.parent.doc_version,2);assert.equal((await context.request.get(endpoint,{headers:{...headers,'X-Actor-Id':viewer}})).status(),409);assert.equal((await context.request.post(endpoint,{headers:{...headers,Origin:origin},data:{}})).status(),405);assert.equal((await context.request.get(origin+'/v1/emails/'+parent.id+'/locale-source',{headers})).status(),409);
  let requests=0;await page.route(endpoint,async route=>{requests++;const response=await route.fetch();await new Promise(r=>setTimeout(r,200));await route.fulfill({response});});await region.getByRole('button',{name:'Compare current source',exact:true}).evaluate((button:HTMLButtonElement)=>{button.click();button.click();});await region.getByRole('checkbox',{name:'Copy source Subject',exact:true}).waitFor();assert.equal(requests,1);await page.unroute(endpoint);assert.equal(await region.getByRole('checkbox').evaluateAll(items=>items.filter(i=>(i as HTMLInputElement).checked).length),0);assert.ok((await region.innerText()).includes('<script>globalThis.__localeRan'));assert.equal(await page.evaluate(()=>Reflect.get(window,'__localeRan')),undefined);assert.deepEqual((await db.query('SELECT (SELECT count(*)FROM revisions) revisions,(SELECT count(*)FROM audit_events) audits')).rows,counts);
  await region.getByRole('checkbox',{name:'Copy source Subject',exact:true}).check();changed={...changed,subject:'Newer subject'};await tx(c=>saveDraft(c,p,parent.id,parentVersion++,changed));await region.getByRole('button',{name:'Copy selected source text to draft',exact:true}).click();await region.getByRole('alert').filter({hasText:'parent or saved locale draft changed'}).waitFor();assert.deepEqual((await db.query('SELECT spec FROM emails WHERE id=$1',[child.email.id])).rows[0].spec,manual);assert.equal(await page.getByRole('textbox',{name:'Subject',exact:true}).inputValue(),'Sujet manuel');console.log('Actual parent drift refuses selective copy without changing manual target PASS.');
  await region.getByRole('button',{name:'Compare current source',exact:true}).click();await region.getByRole('checkbox',{name:'Copy source Subject',exact:true}).waitFor();for(const name of ['Subject','hero · heading','cta · label','offer · title'])await region.getByRole('checkbox',{name:'Copy source '+name,exact:true}).check();await region.getByRole('button',{name:'Copy selected source text to draft',exact:true}).evaluate((b:HTMLButtonElement)=>{b.click();b.click();});await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('status').filter({hasText:'Saved · v3'}).waitFor();const saved=(await db.query('SELECT spec,doc_version FROM emails WHERE id=$1',[child.email.id])).rows[0];assert.equal(saved.doc_version,3);assert.equal(saved.spec.subject,'Newer subject');assert.equal(saved.spec.preheader,'Aperçu manuel');assert.equal(saved.spec.sections[0].heading,'Updated heading');assert.equal(saved.spec.sections[0].text,'Corps manuel');assert.equal(saved.spec.sections[1].label,'Updated CTA');assert.equal(saved.spec.sections[1].href,'https://example.com/manual');assert.equal(saved.spec.sections[2].price,'EUR 9');assert.equal(saved.spec.sections[2].href,'https://example.com/manual-product');assert.equal(saved.spec.sections[2].description,'Description manuelle');assert.deepEqual(saved.spec.sections[3],manual.sections[3]);assert.deepEqual(saved.spec.sections[4],manual.sections[4]);assert.equal(saved.spec.locale,'fr-FR');await page.reload();await region.waitFor();assert.equal(await page.getByRole('textbox',{name:'Subject',exact:true}).inputValue(),'Newer subject');assert.equal((await context.request.get(endpoint,{headers}).then(r=>r.json())).comparison.source_status,'outdated');console.log('Actual repeated selected manual copy/CAS save/reload preserves unselected translations, URLs, price, legal/source/locale and original stale lineage PASS.');
  await page.route(endpoint,route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'FIXTURE_UNAVAILABLE',message:'Owned comparison unavailable'}})}));await region.getByRole('button',{name:'Compare current source',exact:true}).click();await region.getByRole('alert').filter({hasText:'Owned comparison unavailable'}).waitFor();assert.equal(await region.getByRole('checkbox').count(),0);await page.unroute(endpoint);await region.getByRole('button',{name:'Compare current source',exact:true}).click();await region.getByText('Original parent checkpoint',{exact:false}).waitFor();
  let release!:()=>void;const held=new Promise<void>(r=>release=r);let arrived!:()=>void;const fetched=new Promise<void>(r=>arrived=r);await page.route(endpoint,async route=>{const response=await route.fetch();arrived();await held;try{await route.fulfill({response});}catch{}});await region.getByRole('button',{name:'Refresh source comparison',exact:true}).click();await fetched;await page.getByRole('textbox',{name:'Subject',exact:true}).fill('Later local edit');release();await page.unroute(endpoint);await region.getByRole('button',{name:'Compare current source',exact:true}).waitFor();assert.equal(await region.getByRole('checkbox').count(),0);assert.equal(await page.getByRole('textbox',{name:'Subject',exact:true}).inputValue(),'Later local edit');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('status').filter({hasText:'Saved · v4'}).waitFor();console.log('Actual failed comparison/retry and delayed response after newer local typing do not adopt stale source PASS.');
  await page.setViewportSize({width:390,height:844});await region.getByRole('button',{name:'Compare current source',exact:true}).click();await region.getByText('Original parent checkpoint',{exact:false}).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/lettercape-locale-mobile.png'});
  // Current source with no changes and a held result after navigation are explicit states.
  const freshRevision=await tx(c=>checkpoint(c,p,parent.id,parentVersion)),freshChild=await tx(c=>deriveEmail(c,p,freshRevision.id,{kind:'locale',title:'Owned current Hebrew',locale:'he-IL'}));
  await page.goto(origin+'/app/emails/'+freshChild.email.id);await region.waitFor();await region.getByRole('button',{name:'Compare current source',exact:true}).click();await region.getByRole('status').filter({hasText:'No source text or block change'}).waitFor();assert.equal(await region.getByRole('checkbox').count(),0);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  let releaseNavigation!:()=>void;const heldNavigation=new Promise<void>(r=>releaseNavigation=r);let arrivedNavigation!:()=>void;const fetchedNavigation=new Promise<void>(r=>arrivedNavigation=r);const freshEndpoint=origin+'/v1/emails/'+freshChild.email.id+'/locale-source';await page.route(freshEndpoint,async route=>{const response=await route.fetch();arrivedNavigation();await heldNavigation;try{await route.fulfill({response});}catch{}});await region.getByRole('button',{name:'Refresh source comparison',exact:true}).click();await fetchedNavigation;await page.goto(origin+'/app/emails/'+child.email.id);releaseNavigation();await page.unroute(freshEndpoint);await region.waitFor();assert.equal(await region.getByRole('checkbox').count(),0);await region.getByRole('button',{name:'Compare current source',exact:true}).click();await region.getByText('Original parent checkpoint',{exact:false}).waitFor();assert.ok((await region.innerText()).includes('locale saved v4'));console.log('Actual unchanged-source empty state, Hebrew mobile direction and held-result navigation fence PASS.');
  await context.addCookies([{name:'mailcraft_local_session',value:viewerCookie,url:origin,sameSite:'Strict'}]);await page.reload();await region.waitFor();await region.getByRole('button',{name:'Compare current source',exact:true}).click();await region.getByText('Original parent checkpoint',{exact:false}).waitFor();assert.equal(await region.getByRole('checkbox').count(),0);assert.equal(await region.getByRole('button',{name:'Copy selected source text to draft',exact:true}).count(),0);assert.equal(await page.getByRole('textbox',{name:'Subject',exact:true}).evaluate(e=>(e as HTMLInputElement).readOnly),true);assert.equal((await context.request.get(endpoint,{headers:{'X-Workspace-Id':p.workspace,'X-Actor-Id':viewer}})).status(),200);
  assert.equal(execution,0);assert.equal(external,0);assert.deepEqual(errors,[]);console.log('Actual Viewer compare/read-only,390px navigation/no overflow, inert hostile source/zero external calls and strict HTTP methods/actor fences PASS.');
 }finally{await browser?.close();if(app&&app.exitCode===null){app.kill('SIGTERM');await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{app!.kill('SIGKILL');reject(Error('Owned locale app required forced termination'));},10000);app!.once('exit',()=>{clearTimeout(timer);resolve();});});}await log.close();console.log('Owned locale app stopped; generated database cleanup follows.');}
});
console.log('Owned locale comparison fixture database dropped PASS.');
