import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {spawn,type ChildProcess} from 'node:child_process';
import {open,mkdir,readFile} from 'node:fs/promises';
import {chromium} from 'playwright';
import {sourceDatabase} from './smoke-source-truth';
import {blankSpec,type Block} from '../src/domain/email';
import {createEmail} from '../src/server/emails';
import {digest} from '../src/server/audit';
const origin='http://127.0.0.1:3038';
await sourceDatabase(async({db,p,brand,tx})=>{
 const spec=blankSpec(brand,'Column content fixture'),literal='<!--retained column-->\r\n<p>é 😀</p>';
 spec.sections.push({id:'columns',type:'columns',columns:[[{id:'literal',type:'custom_html',html:literal},{id:'text',type:'text',text:'Column copy'}],[{id:'button',type:'button',label:'Column action',href:'https://example.com'}]]});
 const doc=await tx(c=>createEmail(c,p,'Column content fixture',spec));
 const emptySpec={...spec,sections:[{id:'empty',type:'columns',columns:[[],[]]}] as Block[]},empty=await tx(c=>createEmail(c,p,'Empty columns fixture',emptySpec));
 const fullSpec={...spec,sections:[{id:'full',type:'columns',columns:[Array.from({length:20},(_,n)=>({id:'full-'+n,type:'text',text:'Full column '+n})),[{id:'other',type:'text',text:'Other column'}]]}] as Block[]},full=await tx(c=>createEmail(c,p,'Full column fixture',fullSpec));
 const rtlSpec={...spec,locale:'ar-SA' as const,direction:'rtl' as const,sections:spec.sections.map(block=>block.type==='columns'?{...block,columns:block.columns.map(nodes=>nodes.map(node=>node.type==='text'?{...node,text:'مرحبا بكم'}:node))}:block)},rtl=await tx(c=>createEmail(c,p,'Arabic columns fixture',rtlSpec));
 const budgetSpec={...emptySpec,sections:[...emptySpec.sections,...Array.from({length:199},(_,n)=>({id:'budget-'+n,type:'divider' as const}))]},budget=await tx(c=>createEmail(c,p,'Node budget fixture',budgetSpec));
 const cookie=randomBytes(32).toString('hex');await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,clock_timestamp()+interval '1 hour')",[digest(cookie),p.user]);
 const runtime=new URL(process.env.DATABASE_URL!);runtime.pathname=new URL(db.options.connectionString!).pathname;assert.match(runtime.pathname,/^\/creation_fixture_[a-f0-9]{32}$/);
 const log=await open('/tmp/lettercape-column-editor-app.log','w');let app:ChildProcess|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
 try{
  app=spawn(process.execPath,['node_modules/next/dist/bin/next','dev','--hostname','127.0.0.1','--port','3038'],{env:{PATH:process.env.PATH,NODE_ENV:'development',LOCAL_DEVELOPMENT:'true',APP_ORIGIN:origin,DATABASE_URL:runtime.toString(),MIGRATION_DATABASE_URL:db.options.connectionString!,PREFERENCE_SIGNING_SECRET:process.env.PREFERENCE_SIGNING_SECRET,NEXT_TELEMETRY_DISABLED:'1',AI_GENERATION_ALLOWANCE:'0'},stdio:['ignore',log.fd,log.fd]});
  for(let n=0;n<120;n++){if(app.exitCode!==null)throw Error('Owned column app exited');try{if((await fetch(origin)).ok)break;}catch{}if(n===119)throw Error('Owned column app unavailable');await new Promise(r=>setTimeout(r,250));}
  browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:1000},acceptDownloads:true});await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);await context.addInitScript(workspace=>{if(window.top===window)localStorage.setItem('mailcraft.workspace',workspace);},p.workspace);context.setDefaultTimeout(15000);
  let external=0;await context.route(url=>url.origin!==origin&&url.protocol!=='data:'&&url.protocol!=='blob:',route=>{external++;return route.abort();});
  const page=await context.newPage(),errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  const openEmail=async(id:string)=>{await page.goto(origin+'/app/emails/'+id);await page.getByRole('region',{name:'Linear email Outline',exact:true}).waitFor();};
  const child=(id:string)=>page.locator(`[data-linear-child="${id}"]`),columns=()=>page.locator('[data-linear-block="columns"]');
  const col=(n:number)=>columns().getByRole('group',{name:'Column '+n,exact:true});const order=(n:number)=>col(n).locator('[data-linear-child]').evaluateAll(nodes=>nodes.map(node=>node.getAttribute('data-linear-child')));
  const save=async()=>{await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('status').filter({hasText:/^Saved · v/}).waitFor();};
  const draft=async(id=doc.id)=>(await db.query('SELECT spec,doc_version FROM emails WHERE id=$1',[id])).rows[0];
  await openEmail(doc.id);await col(1).getByRole('button',{name:'Add block to column 1',exact:true}).waitFor();
  await col(1).getByLabel('Block type for column 1',{exact:true}).selectOption('text');await col(1).getByRole('button',{name:'Add block to column 1',exact:true}).evaluate(button=>{(button as HTMLButtonElement).click();(button as HTMLButtonElement).click();});
  assert.equal((await order(1)).length,4);assert.equal(new Set(await order(1)).size,4);const added=(await order(1))[2]!;
  await child(added).getByRole('textbox',{name:'Body text',exact:true}).fill('Added nested copy');await save();await page.reload();await columns().waitFor();assert.equal(await child(added).getByRole('textbox',{name:'Body text',exact:true}).inputValue(),'Added nested copy');
  assert.equal((await draft()).spec.sections.at(-1).columns[0][0].html,literal);console.log('Actual rapid nested Add, stable IDs, child edit/save/reload and exact retained CRLF/Unicode PASS.');
  await child('literal').getByLabel('Column for custom_html 1 in column 1',{exact:true}).focus();await child('literal').getByLabel('Column for custom_html 1 in column 1',{exact:true}).selectOption({value:'1'});assert.deepEqual(await order(2),['button','literal']);assert.equal(await child('literal').getByLabel('Column for custom_html 2 in column 2',{exact:true}).evaluate(control=>control===document.activeElement),true,'Transfer must retain focus on the moved block');
  await child('literal').getByLabel('Position of custom_html 2 in column 2',{exact:true}).focus();await page.keyboard.press('1');await page.keyboard.press('Tab');await page.waitForFunction(()=>document.querySelector('[data-linear-block="columns"] fieldset[data-column-index="1"] [data-linear-child]')?.getAttribute('data-linear-child')==='literal');
  await child('literal').getByRole('button',{name:'Move custom_html 1 in column 2 down',exact:true}).focus();await page.keyboard.press('Enter');assert.deepEqual(await order(2),['button','literal']);await save();
  await child('literal').getByRole('button',{name:'Delete custom_html 2 in column 2',exact:true}).evaluate(button=>{(button as HTMLButtonElement).click();(button as HTMLButtonElement).click();});assert.deepEqual(await order(2),['button']);await page.getByRole('button',{name:'Undo',exact:true}).click();assert.deepEqual(await order(2),['button','literal']);await save();assert.equal((await draft()).spec.sections.at(-1).columns[1][1].html,literal);
  console.log('Native keyboard position/down, cross-column transfer, repeated deletion and single-step Undo PASS.');
  await child('button').getByRole('textbox',{name:'Destination URL',exact:true}).fill('https://');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('alert').filter({hasText:'Complete block'}).waitFor();assert.equal((await draft()).spec.sections.at(-1).columns[1][0].href,'https://example.com');await child('button').getByRole('textbox',{name:'Destination URL',exact:true}).fill('https://example.com/corrected');await save();await page.reload();await columns().waitFor();assert.equal(await child('button').getByRole('textbox',{name:'Destination URL',exact:true}).inputValue(),'https://example.com/corrected');
  for(const format of ['HTML','TXT']){const [download]=await Promise.all([page.waitForEvent('download'),page.locator('.export-panel').getByRole('button',{name:format,exact:true}).click()]);assert.equal(await download.failure(),null);const contents=await readFile((await download.path())!,'utf8'),revision=(await db.query('SELECT html,plaintext FROM revisions WHERE email_id=$1 ORDER BY revision_no DESC LIMIT 1',[doc.id])).rows[0];assert.equal(contents,format==='HTML'?revision.html:revision.plaintext);}
  console.log('Actual nested partial-input refusal/correction and byte-exact frozen HTML/TXT exports PASS.');
  await mkdir('output/column-editor',{recursive:true});await page.setViewportSize({width:320,height:1000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await columns().scrollIntoViewIfNeeded();await columns().screenshot({path:'output/column-editor/mobile.png'});
  await openEmail(empty.id);const emptyColumn=page.locator('[data-linear-block="empty"]').getByRole('group',{name:'Column 1',exact:true});await emptyColumn.getByText('This column has no blocks.',{exact:true}).waitFor();
  for(const type of ['hero','text','image','button','divider','social','legal_footer','product_card','custom_html']){await emptyColumn.getByLabel('Block type for column 1',{exact:true}).selectOption(type);await emptyColumn.getByRole('button',{name:'Add block to column 1',exact:true}).click();}assert.equal(await emptyColumn.locator('[data-linear-child]').count(),9);await save();assert.equal((await draft(empty.id)).spec.sections[0].columns[0].length,9);
  await openEmail(full.id);assert.equal(await page.locator('[data-linear-block="full"]').getByRole('button',{name:'Add block to column 1',exact:true}).isDisabled(),true);assert.equal(await child('other').getByLabel('Column for text 1 in column 2',{exact:true}).locator('option[value="0"]').evaluate((option:HTMLOptionElement)=>option.disabled),true);
  await openEmail(budget.id);assert.equal(await page.getByRole('button',{name:'Add block to column 1',exact:true}).isDisabled(),true);
  console.log('Actual empty-column add/all nine child types, 20-child and 200-node limit display PASS.');
  await openEmail(rtl.id);assert.equal(await child('text').getByRole('textbox',{name:'Body text',exact:true}).getAttribute('lang'),'ar-SA');assert.equal(await child('text').getByRole('textbox',{name:'Body text',exact:true}).getAttribute('dir'),'rtl');assert.equal(await child('button').getByRole('textbox',{name:'Destination URL',exact:true}).getAttribute('dir'),'ltr');assert.equal(await child('text').getByLabel('Column for text 2 in column 1',{exact:true}).evaluate(control=>getComputedStyle(control).direction),'ltr');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('[data-linear-block="columns"]').screenshot({path:'output/column-editor/rtl.png'});
  await db.query("UPDATE memberships SET role='Viewer' WHERE workspace_id=$1 AND user_id=$2",[p.workspace,p.user]);await openEmail(doc.id);assert.equal(await child('button').getByRole('textbox',{name:'Destination URL',exact:true}).getAttribute('readonly'),'');for(const control of await columns().locator('button,select').all())assert.equal(await control.isDisabled(),true);await columns().screenshot({path:'output/column-editor/viewer.png'});await db.query("UPDATE memberships SET role='Owner' WHERE workspace_id=$1 AND user_id=$2",[p.workspace,p.user]);
  await page.setViewportSize({width:1440,height:1100});await page.goto(origin+'/app/emails/'+doc.id);await page.locator('.outline-select').filter({hasText:'columns'}).click();await page.locator('.inspector').getByRole('button',{name:'Add block to column 2',exact:true}).click();await save();assert.equal((await draft()).spec.sections.at(-1).columns[1].length,3);assert.equal((await draft()).spec.sections.at(-1).columns[1][1].html,literal);await page.locator('.inspector').screenshot({path:'output/column-editor/desktop.png'});
  assert.equal(external,0);assert.deepEqual(errors,[]);console.log('Actual copyable Viewer controls, desktop inspector parity and zero page errors/external requests PASS.');
 }finally{await browser?.close();if(app&&app.exitCode===null){app.kill('SIGTERM');await new Promise<void>(resolve=>app!.once('exit',()=>resolve()));}await log.close();}
});
console.log('Owned column editor app stopped and disposable database removed PASS.');
