import{validateApiResponse}from'./api-validation';
import assert from'node:assert/strict';import{randomUUID,randomBytes}from'node:crypto';import pg from'pg';import env from'@next/env';import{digest}from'../src/server/audit';import{blankSpec}from'../src/domain/email';
env.loadEnvConfig(process.cwd());
const origin=process.env.APP_ORIGIN??'http://127.0.0.1:3003';if(process.env.LOCAL_DEVELOPMENT!=='true'||!['localhost','127.0.0.1'].includes(new URL(origin).hostname))throw new Error('Owned local campaign fixture required.');
let browser:Awaited<ReturnType<(typeof import('playwright'))['chromium']['launch']>>|undefined;
const db=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL}),workspace=randomUUID(),other=randomUUID(),user='campaign-http-'+randomUUID(),cookie=randomBytes(32).toString('hex');
async function call(path:string,method='GET',body?:unknown,key=randomUUID(),w=workspace,bearer?:string){const r=await fetch(origin+'/v1/'+path,{method,headers:{Origin:origin,'Content-Type':'application/json','Idempotency-Key':key,...(bearer?{Authorization:'Bearer '+bearer}:{Cookie:'mailcraft_local_session='+cookie,'X-Workspace-Id':w})},body:body===undefined?undefined:JSON.stringify(body)});return{r,j:await r.json()};}
const kit={name:'Campaign fixture',website:'',description:'Owned fixture',voice:'Plain',accent:'#0B625D',background:'#F7F6F2',font_stack:'Arial, sans-serif',address:'Reserved fixture address',approved_claims:[],forbidden_phrases:[],provenance:[]};
try{
 await db.query("INSERT INTO workspaces(id,name)VALUES($1,'Campaign HTTP fixture'),($2,'Campaign HTTP foreign')",[workspace,other]);for(const w of[workspace,other])await db.query("INSERT INTO memberships(workspace_id,user_id,role)VALUES($1,$2,'Owner')",[w,user]);await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,clock_timestamp()+interval '1 hour')",[digest(cookie),user]);
 async function frozen(w=workspace){const brand=(await call('brands','POST',kit,randomUUID(),w)).j.brand,spec=blankSpec(brand.id,kit.name),email=(await call('emails','POST',{title:'Owned configuration content',spec},randomUUID(),w)).j.email;const checkpoint=await fetch(origin+'/v1/emails/'+email.id+'/revisions',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','Idempotency-Key':randomUUID(),Cookie:'mailcraft_local_session='+cookie,'X-Workspace-Id':w,'If-Match':'"draft-'+email.doc_version+'"'},body:'{}'});return(await checkpoint.json()).revision;}
 const first=await frozen(),second=await frozen(),foreign=await frozen(other),created=await call('campaigns','POST',{name:'Original campaign',revision_id:first.id}),campaign=created.j.campaign;assert.equal(created.r.status,200);assert.ok(campaign.id);
 const boundaryId=randomUUID(),privateIntent={revision_id:first.id,artifact_hash:first.artifact_hash,audience:[{id:randomUUID(),eligible:false,reason:'Synthetic recipient hold'}],provider:{private_token:'synthetic-only-provider-field'},sender:{private_identity:'synthetic-only-sender-field'},private_extra:'synthetic-only-arbitrary-field',planned_timing:null};await db.query('INSERT INTO campaigns(workspace_id,id,name,revision_id,intent,digest,created_by)VALUES($1,$2,$3,$4,$5,$6,$7)',[workspace,boundaryId,'Owned metadata boundary',first.id,JSON.stringify(privateIntent),digest(privateIntent),user]);const boundary=(await call('campaigns/'+boundaryId)).j.campaign;for(const field of['audience','provider','sender','private_extra'])assert.equal(boundary.intent[field],undefined,'New detail must redact '+field);assert.equal(boundary.audience_count,1);assert.equal(boundary.eligible_count,0);const boundarySave=(await call('campaigns/'+boundaryId+'/configuration','POST',{expected_version:1,name:'Owned boundary edit',revision_id:second.id,planned_timing:null})).j.campaign;for(const field of['audience','provider','sender','private_extra'])assert.equal(boundarySave.intent[field],undefined,'New command response must redact '+field);assert.equal(boundarySave.audience_count,1);assert.deepEqual((await db.query('SELECT intent FROM campaigns WHERE id=$1',[boundaryId])).rows[0].intent.provider,privateIntent.provider);
 const path='campaigns/'+campaign.id,detail=await call(path);assert.equal(detail.r.status,200);assert.equal(detail.j.campaign.id,campaign.id);assert.equal(detail.j.campaign.version,1);validateApiResponse('getCampaign',detail.r.status,detail.j);
 const initial=(await call(path+'/configurations')).j;validateApiResponse('listCampaignConfigurations',200,initial);assert.equal(initial.total_count,1);assert.equal(initial.data[0].origin,'runtime_change');assert.equal(initial.data[0].actor_id,user);assert.equal(initial.data[0].intent,undefined);assert.equal(initial.data[0].audience,undefined);
 const timing={local_time:'2026-11-01T01:30',time_zone:'America/New_York',utc_offset:'-04:00'},body={expected_version:1,name:'Planned campaign',revision_id:second.id,planned_timing:timing},key=randomUUID();
 for(const extra of[{provider:'ses'},{sender:'invented'},{approval:{}},{state:'scheduled'},{audience:[]},{digest:'invented'}])assert.equal((await call(path+'/configuration','POST',{...body,...extra})).r.status,422);
 assert.equal((await call(path+'/configuration','POST',{...body,revision_id:foreign.id})).r.status,404);assert.equal((await call(path+'/configuration','POST',{...body,revision_id:randomUUID()})).r.status,404);assert.equal((await call(path+'/configuration','POST',{...body,planned_timing:{local_time:'2026-03-08T02:30',time_zone:'America/New_York',utc_offset:'-05:00'}})).j.error.code,'INVALID_CAMPAIGN_TIMING');assert.equal((await call(path)).j.campaign.version,1);
 const saved=await call(path+'/configuration','POST',body,key);assert.equal(saved.r.status,200);validateApiResponse('configureCampaign',saved.r.status,saved.j);assert.equal(saved.j.changed,true);assert.equal(saved.j.campaign.version,2);assert.equal(saved.j.campaign.revision_id,second.id);assert.equal(saved.j.campaign.intent.artifact_hash,second.artifact_hash);assert.deepEqual(saved.j.campaign.intent.planned_timing,{...timing,utc:'2026-11-01T05:30:00.000Z'});const stored=(await db.query('SELECT * FROM campaigns WHERE id=$1',[campaign.id])).rows[0];assert.equal(stored.intent.schedule,null);assert.equal(stored.intent.provider,null);assert.equal(stored.intent.sender,null);assert.equal(stored.intent.tracking,false);assert.deepEqual(stored.intent.audience,campaign.intent.audience);assert.equal(stored.approval,null);for(const field of['audience','provider','sender','schedule','tracking'])assert.equal(saved.j.campaign.intent[field],undefined);assert.equal(saved.j.campaign.approval,undefined);assert.equal(saved.j.campaign.state,'draft');
 const replay=await call(path+'/configuration','POST',body,key);assert.equal(replay.j.campaign.version,2);assert.equal((await call(path+'/configuration','POST',{...body,name:'Changed payload'},key)).j.error.code,'IDEMPOTENCY_MISMATCH');assert.equal((await call(path+'/configuration','POST',{...body,name:'Stale different'})).j.error.code,'VERSION_CONFLICT');const noop=await call(path+'/configuration','POST',{...body,expected_version:2});assert.equal(noop.j.changed,false);assert.equal(noop.j.campaign.version,2);assert.equal((await call(path+'/configurations')).j.total_count,2);
 await call(path+'/submit-review','POST',{});const changed=await call(path+'/configuration','POST',{...body,expected_version:2,name:'Review reset',planned_timing:{...timing,utc_offset:'-05:00'}});assert.equal(changed.j.campaign.version,3);assert.equal(changed.j.campaign.state,'draft');assert.equal(changed.j.campaign.intent.planned_timing.utc,'2026-11-01T06:30:00.000Z');assert.notEqual(changed.j.campaign.digest,saved.j.campaign.digest);
 const page=(await call(path+'/configurations?limit=1')).j;assert.equal(page.total_count,3);assert.equal(page.has_more,true);assert.equal(page.data[0].revision_no,3);assert.equal(typeof page.next_cursor,'string');const next=(await call(path+'/configurations?limit=1&after='+encodeURIComponent(page.next_cursor))).j;assert.equal(next.data[0].revision_no,2);assert.equal((await call(path+'/configurations?after='+encodeURIComponent(page.next_cursor)+'x')).j.error.code,'INVALID_CURSOR');const sibling=(await call('campaigns','POST',{name:'Sibling',revision_id:first.id})).j.campaign;assert.equal((await call('campaigns/'+sibling.id+'/configurations?after='+encodeURIComponent(page.next_cursor))).j.error.code,'INVALID_CURSOR');
 assert.equal((await call(path,'GET',undefined,randomUUID(),other)).r.status,404);assert.equal((await call(path+'/configuration','POST',{...body,expected_version:3},randomUUID(),other)).r.status,404);assert.equal((await call(path+'/configurations','GET',undefined,randomUUID(),other)).r.status,404);assert.equal((await call(path+'/unknown')).r.status,404);assert.equal((await call(path+'%2fconfiguration')).r.status,404);assert.equal((await call(path+'/configuration')).r.status,405);assert.equal((await call(path+'/configurations','POST',{})).r.status,405);
 for(const role of['Viewer','Billing']){await db.query('UPDATE memberships SET role=$1 WHERE workspace_id=$2 AND user_id=$3',[role,workspace,user]);assert.equal((await call(path+'/configuration','POST',{...body,expected_version:3})).r.status,403);assert.equal((await call(path+'/configurations')).r.status,role==='Viewer'?200:403);}await db.query("UPDATE memberships SET role='Owner'WHERE workspace_id=$1 AND user_id=$2",[workspace,user]);
 const reader=(await call('api-keys','POST',{name:'Owned campaign reader',scopes:['campaigns:read'],expires_in_days:1})).j.secret;assert.equal((await call(path,'GET',undefined,randomUUID(),workspace,reader)).r.status,200);assert.equal((await call(path+'/configuration','POST',{...body,expected_version:3},randomUUID(),workspace,reader)).r.status,403);
 const writer=(await call('api-keys','POST',{name:'Owned campaign writer',scopes:['campaigns:read','campaigns:write'],expires_in_days:1})).j.secret;const written=await call(path+'/configuration','POST',{...body,name:'Delegated draft',expected_version:3,planned_timing:null},randomUUID(),workspace,writer);assert.equal(written.j.campaign.version,4);assert.match((await call(path+'/configurations')).j.data[0].actor_id,/^api-key:/);assert.equal(written.j.campaign.intent.planned_timing,null);
 // Hold only the fixture campaign row; passive key expiry must be checked after the wait.
 const keyRow=(await db.query("SELECT id FROM api_keys WHERE workspace_id=$1 AND name='Owned campaign writer'",[workspace])).rows[0],lock=await db.connect();let expiryResult:Awaited<ReturnType<typeof call>>|undefined;
 try{await lock.query('BEGIN');await lock.query('SELECT id FROM campaigns WHERE id=$1 FOR UPDATE',[campaign.id]);await db.query("UPDATE api_keys SET expires_at=clock_timestamp()+interval '3 seconds' WHERE id=$1",[keyRow.id]);const pending=call(path+'/configuration','POST',{...body,name:'Expired while waiting',expected_version:4},randomUUID(),workspace,writer);const deadline=Date.now()+8000;let blocked=false;while(Date.now()<deadline){const waiting=(await db.query("SELECT EXISTS(SELECT FROM pg_stat_activity WHERE wait_event_type='Lock'AND query LIKE 'SELECT%FROM campaigns%FOR UPDATE%')AS blocked")).rows[0].blocked;if(waiting){blocked=true;break;}await new Promise(r=>setTimeout(r,40));}assert.equal(blocked,true);while((await db.query('SELECT expires_at>clock_timestamp()AS valid FROM api_keys WHERE id=$1',[keyRow.id])).rows[0].valid)await new Promise(r=>setTimeout(r,50));await lock.query('COMMIT');expiryResult=await pending;}finally{await lock.query('ROLLBACK');lock.release();}
 assert.equal(expiryResult.r.status,401);assert.equal((await call(path)).j.campaign.version,4);assert.equal((await call(path+'/configurations')).j.total_count,4);
 if(!process.argv.includes('--api')){
  const{chromium}=await import('playwright');browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844}});
  await context.addInitScript(w=>{if(!localStorage.getItem('mailcraft.workspace'))localStorage.setItem('mailcraft.workspace',w);},workspace);await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);const page=await context.newPage();
  const box=page.locator('[data-campaign-configuration="'+campaign.id+'"]'),field=box.getByLabel('Configuration name',{exact:true}),save=box.getByRole('button',{name:'Save draft configuration',exact:true}),retry=box.getByRole('button',{name:'Retry original configuration',exact:true}),reload=box.getByRole('button',{name:'Reload saved configuration',exact:true});
  let release!:()=>void,entered!:()=>void;const gate=new Promise<void>(r=>release=r),ready=new Promise<void>(r=>entered=r);
  await page.route('**/v1/'+path,async route=>{const response=await route.fetch();entered();await gate;await route.fulfill({response});});
  try{await page.goto(origin+'/app/campaigns');await ready;await field.waitFor();assert.equal(await field.isEnabled(),false);}finally{release();await page.unrouteAll({behavior:'wait'});}
  await page.waitForFunction(id=>{const input=document.querySelector<HTMLInputElement>('[data-campaign-configuration="'+id+'"] input');return !!input&&!input.disabled&&input.value==='Delegated draft';},campaign.id);assert.equal(await box.getByLabel('Configuration frozen revision',{exact:true}).inputValue(),second.id);
  let posts=0;const commandKeys:string[]=[];page.on('request',request=>{if(new URL(request.url()).pathname==='/v1/'+path+'/configuration'&&request.method()==='POST'){posts++;commandKeys.push(request.headers()['idempotency-key']);}});
  await box.getByLabel('Add planned timing',{exact:true}).check();await box.getByLabel('Planned local minute',{exact:true}).fill('2026-11-01T01:30');await box.getByLabel('Planned IANA time zone',{exact:true}).fill('America/New_York');await box.getByLabel('Planned UTC offset',{exact:true}).fill('-04:00');assert.match(await box.locator('[data-planned-candidate]').innerText(),/2026-11-01T05:30:00.000Z/);await box.getByLabel('Planned UTC offset',{exact:true}).fill('-05:00');assert.match(await box.locator('[data-planned-candidate]').innerText(),/2026-11-01T06:30:00.000Z/);await box.getByLabel('Planned local minute',{exact:true}).fill('2026-03-08T02:30');await box.getByLabel('Planned IANA time zone',{exact:true}).fill('America/New_York');await box.getByLabel('Planned UTC offset',{exact:true}).fill('-05:00');assert.equal(await save.isDisabled(),true);await save.evaluate((button:HTMLButtonElement)=>{button.click();});assert.equal(posts,0);
  await box.getByLabel('Planned local minute',{exact:true}).fill('2026-10-02T10:15');await box.getByLabel('Planned IANA time zone',{exact:true}).fill('Asia/Kathmandu');await box.getByLabel('Planned UTC offset',{exact:true}).fill('+05:45');assert.match(await box.locator('[data-planned-candidate]').innerText(),/2026-10-02T04:30:00.000Z/);await save.click();await box.getByRole('status').filter({hasText:'Draft configuration saved.'}).waitFor();assert.equal((await call(path)).j.campaign.version,5);
  await field.fill('Offline retained');await context.setOffline(true);await save.click();await box.getByRole('alert').filter({hasText:/Failed to fetch|fetch failed/i}).waitFor();assert.equal(await field.inputValue(),'Offline retained');assert.equal(await field.isEnabled(),false);await context.setOffline(false);await retry.click();await box.getByRole('status').filter({hasText:'Draft configuration saved.'}).waitFor();assert.equal((await call(path)).j.campaign.version,6);
  await box.getByLabel('Planned IANA time zone',{exact:true}).fill('UTC');await box.getByLabel('Planned UTC offset',{exact:true}).fill('+00:00');assert.match(await box.locator('[data-planned-candidate]').innerText(),/2026-10-02T10:15:00.000Z/);await field.fill('Lost acknowledgment');
  let accepted!:()=>void;const acceptedSave=new Promise<void>(r=>accepted=r);await page.route('**/v1/'+path+'/configuration',async route=>{const response=await route.fetch();assert.equal((await response.json()).campaign.version,7);accepted();await route.abort('failed');});const before=posts;await save.evaluate((button:HTMLButtonElement)=>{button.click();button.click();});await acceptedSave;await box.getByRole('alert').waitFor();assert.equal(posts,before+1);assert.equal(await field.inputValue(),'Lost acknowledgment');assert.equal(await field.isEnabled(),false);await page.unrouteAll({behavior:'wait'});await retry.click();await box.getByRole('status').filter({hasText:'Draft configuration saved.'}).waitFor();assert.equal(commandKeys.at(-1),commandKeys.at(-2));assert.equal((await call(path+'/configurations')).j.total_count,7);
  await page.reload();await page.waitForFunction(id=>document.querySelector<HTMLInputElement>('[data-campaign-configuration="'+id+'"] input')?.value==='Lost acknowledgment',campaign.id);await save.click();await box.getByRole('status').filter({hasText:'Configuration is unchanged.'}).waitFor();assert.equal((await call(path+'/configurations')).j.total_count,7);
  const secondPage=await context.newPage();await secondPage.goto(origin+'/app/campaigns');const secondBox=secondPage.locator('[data-campaign-configuration="'+campaign.id+'"]'),secondField=secondBox.getByLabel('Configuration name',{exact:true});await secondPage.waitForFunction(id=>document.querySelector<HTMLInputElement>('[data-campaign-configuration="'+id+'"] input')?.value==='Lost acknowledgment',campaign.id);await secondField.fill('Other tab unsaved');await field.fill('First tab accepted');await save.click();await box.getByRole('status').filter({hasText:'Draft configuration saved.'}).waitFor();await secondBox.getByRole('button',{name:'Save draft configuration',exact:true}).click();await secondBox.getByRole('alert').filter({hasText:'The campaign configuration changed.'}).waitFor();assert.equal(await secondField.inputValue(),'Other tab unsaved');assert.equal((await call(path)).j.campaign.version,8);await secondBox.getByRole('button',{name:'Reload saved configuration',exact:true}).click();await secondPage.waitForFunction(id=>document.querySelector<HTMLInputElement>('[data-campaign-configuration="'+id+'"] input')?.value==='First tab accepted',campaign.id);await secondPage.close();
  const history=box.getByRole('region',{name:'Configuration history',exact:true});await history.getByRole('heading',{name:'Observed configuration history (8)',exact:true}).waitFor();await history.locator('li').first().getByText('v8 · First tab accepted',{exact:true}).waitFor();assert.equal(await history.locator('li').count(),5);let pages=0;page.on('request',request=>{if(request.url().includes('/configurations?')&&request.url().includes('after='))pages++;});await history.getByRole('button',{name:'Load older configurations',exact:true}).evaluate((button:HTMLButtonElement)=>{button.click();button.click();});await page.waitForFunction(id=>document.querySelector('[data-campaign-configuration="'+id+'"] .campaign-configuration-history')?.querySelectorAll('li').length===8,campaign.id);assert.equal(pages,1);
  await page.route('**/v1/'+path+'/configurations?*',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'FIXTURE_HISTORY_ERROR',message:'Controlled history interruption'}})}));await history.getByRole('button',{name:'Refresh configuration history',exact:true}).click();await history.getByRole('alert').filter({hasText:'Controlled history interruption'}).waitFor();assert.equal(await history.locator('li').count(),8);await page.unrouteAll({behavior:'wait'});await history.getByRole('button',{name:'Refresh configuration history',exact:true}).click();await history.getByRole('alert').waitFor({state:'hidden'});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await field.scrollIntoViewIfNeeded();await page.screenshot({path:'output/playwright/lettercape-campaign-configuration-mobile.png'});
  await db.query("UPDATE memberships SET role='Viewer'WHERE workspace_id=$1 AND user_id=$2",[workspace,user]);await page.reload();await field.waitFor();await history.getByRole('heading',{name:'Observed configuration history (8)',exact:true}).waitFor();assert.equal(await save.isDisabled(),true);assert.equal(await field.isEnabled(),false);await db.query("UPDATE memberships SET role='Owner'WHERE workspace_id=$1 AND user_id=$2",[workspace,user]);
  await page.route('**/v1/'+path,route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'FIXTURE_INITIAL_ERROR',message:'Controlled configuration read failure'}})}));await page.reload();await box.getByRole('alert').filter({hasText:'Controlled configuration read failure'}).waitFor();assert.equal(await save.isDisabled(),true);await page.unrouteAll({behavior:'wait'});await reload.click();await page.waitForFunction(id=>document.querySelector<HTMLInputElement>('[data-campaign-configuration="'+id+'"] input')?.value==='First tab accepted',campaign.id);
  await page.setViewportSize({width:1280,height:900});let held!:()=>void,releaseRead!:()=>void;const heldRead=new Promise<void>(r=>held=r),readGate=new Promise<void>(r=>releaseRead=r);await page.route('**/v1/'+path,async route=>{const response=await route.fetch();held();await readGate;await route.fulfill({response});});
  try{await page.reload();await heldRead;await page.getByLabel('Active brand workspace').selectOption(other);await page.getByRole('heading',{name:'Make something worth opening.',exact:true}).waitFor();releaseRead();await page.unrouteAll({behavior:'wait'});assert.equal(await page.locator('[data-campaign-configuration]').count(),0);await page.getByRole('link',{name:'Campaigns',exact:true}).click();await page.getByRole('heading',{name:'No campaigns yet.',exact:true}).waitFor();assert.equal(await page.getByText('First tab accepted',{exact:true}).count(),0);}finally{releaseRead();await page.unrouteAll({behavior:'wait'});}
  console.log('Campaign actual Chromium PASS: initial read fence, invalid DST/no POST, Kathmandu/UTC candidate, offline retained command, repeated/lost acknowledgment original-key replay, reload no-op, independent tab CAS/explicit reload, redacted repeated history paging/error recovery, Viewer, initial read error,390px/no overflow and workspace interruption.');
 }
 await call(path+'/cancel','POST',{});assert.equal((await call(path+'/configuration','POST',{...body,expected_version:(await call(path)).j.campaign.version})).j.error.code,'STATE_CONFLICT');assert.equal((await call(path+'/schedule','POST',{})).r.status,409);
 console.log('Campaign configuration owned HTTP PASS: exact immutable pin, planned-only DST fold, strict authority, no-op/stale/replay, reset review, redacted signed history, role/key/tenant denial and passive expiry after row wait. No provider/send/model requests.');
}finally{await browser?.close();for(const table of['campaigns','preflights','revisions','emails','outbox','api_rate_events','api_keys','idempotency','audit_events','memberships','brands'])await db.query(`DELETE FROM ${table} WHERE workspace_id=ANY($1::uuid[])`,[[workspace,other]]);await db.query('DELETE FROM auth_sessions WHERE user_id=$1',[user]);await db.query('DELETE FROM workspaces WHERE id=ANY($1::uuid[])',[[workspace,other]]);await db.end();}
