import assert from'node:assert/strict';import{randomUUID,randomBytes}from'node:crypto';import{spawn,type ChildProcess}from'node:child_process';import{open,mkdir}from'node:fs/promises';import{chromium}from'playwright';import{sourceDatabase}from'./smoke-source-truth';import{blankSpec,type EmailSpec}from'../src/domain/email';import{createEmail,checkpoint}from'../src/server/emails';import{saveSourceDraft}from'../src/server/email-source';import{digest}from'../src/server/audit';import type{Brand}from'../src/domain/brand';
const origin='http://127.0.0.1:3049';
await sourceDatabase(async({db,p,brand,tx})=>{
 const old:Brand={name:'Old ordinary pin',website:'',description:'',voice:'',accent:'#0B625D',background:'#F7F6F2',font_stack:'Arial, sans-serif',address:'',forbidden_phrases:['OLDPIN_ONLY'],approved_claims:[],provenance:[],tone_rules:{}};
 await db.query('UPDATE brands SET data=$1 WHERE id=$2',[old,brand]);const newPin=randomUUID();await db.query('INSERT INTO brands(workspace_id,id,version,data)VALUES($1,$2,2,$3)',[p.workspace,newPin,{...old,name:'New ordinary pin',forbidden_phrases:['NEWPIN_ONLY']}]);
 const s:EmailSpec={...blankSpec(brand,'Fixture'),subject:'',preheader:'',sections:[{id:'nested',type:'columns',columns:[[{id:'alt:"字段',type:'image',src:'https://example.org/image.png',alt:''}],[{id:'decorative',type:'image',src:'https://example.org/deco.png',alt:'',decorative:true}]]},{id:'opaque',type:'custom_html',html:'<img src="https://example.org/opaque.png">'},{id:'body',type:'text',text:'Original body'}]},create=(title:string,spec:EmailSpec)=>tx(c=>createEmail(c,p,title,spec));
 const doc=await create('Live hygiene draft',s),raw=await create('Raw hygiene',{...s,editing_mode:'raw_html',raw_html:'\ufeff<p>Exact raw</p>\r\n<img src="https://example.org/raw.png">'}),rtl=await create('RTL hygiene',{...s,locale:'he-IL',direction:'rtl'}),many=await create('Many alt fields',{...s,subject:'Useful',preheader:'Context',sections:Array.from({length:55},(_,i)=>({id:'image:"'+i,type:'image',src:'https://example.org/image.png',alt:''}))});
 const pinSpec={...blankSpec(brand,'Fixture'),subject:'Old source OLDPIN_ONLY',preheader:'Context',sections:[]},pinDoc=await create('Ordinary restored pin',pinSpec);await tx(c=>checkpoint(c,p,pinDoc.id,1));await tx(c=>saveSourceDraft(c,p,pinDoc.id,1,{...pinSpec,brand_kit_version_id:newPin,subject:'New source NEWPIN_ONLY'},randomUUID()));
 const cookie=randomBytes(32).toString('hex');await db.query("INSERT INTO auth_sessions(token_hash,user_id,expires_at)VALUES($1,$2,clock_timestamp()+interval '1 hour')",[digest(cookie),p.user]);const runtime=new URL(process.env.DATABASE_URL!);runtime.pathname=new URL(db.options.connectionString!).pathname;assert.match(runtime.pathname,/^\/creation_fixture_[a-f0-9]{32}$/);
 const log=await open('/tmp/lettercape-live-hygiene-app.log','w');let app:ChildProcess|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
 try{
 app=spawn(process.execPath,['node_modules/next/dist/bin/next','dev','--hostname','127.0.0.1','--port','3049'],{env:{PATH:process.env.PATH,NODE_ENV:'development',LOCAL_DEVELOPMENT:'true',APP_ORIGIN:origin,DATABASE_URL:runtime.toString(),MIGRATION_DATABASE_URL:db.options.connectionString!,NEXT_TELEMETRY_DISABLED:'1',AI_GENERATION_ALLOWANCE:'0',PREFERENCE_SIGNING_SECRET:'owned-hygiene-fixture-only-32bytes'},stdio:['ignore',log.fd,log.fd]});for(let n=0;n<160;n++){if(app.exitCode!==null)throw Error('Owned hygiene app exited');try{if((await fetch(origin)).ok)break;}catch{}if(n===159)throw Error('Owned hygiene app unavailable');await new Promise(r=>setTimeout(r,250));}
 browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:320,height:1000}});context.setDefaultTimeout(10000);await context.addCookies([{name:'mailcraft_local_session',value:cookie,url:origin,sameSite:'Strict'}]);await context.addInitScript(workspace=>{if(window.top===window)localStorage.setItem('mailcraft.workspace',workspace);},p.workspace);let external=0,mutations=0,restores=0;const errors:string[]=[],warnings:string[]=[];
 await context.route(url=>url.origin!==origin&&url.protocol!=='blob:'&&url.protocol!=='data:',route=>{external++;return route.abort();});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(/same key|unique.*key/i.test(m.text()))warnings.push(m.text());});page.on('request',r=>{if(r.url().endsWith('/restore'))restores++;if(r.method()!=='GET'&&!r.url().includes('/draft')&&!r.url().includes('/preview')&&!r.url().endsWith('/restore'))mutations++;});await page.route('**/v1/emails/*/draft',route=>route.abort());
 const recovery=(email:string)=>page.evaluate(async scope=>new Promise<string|undefined>((resolve,reject)=>{const request=indexedDB.open('lettercape-source-recovery-1');request.onerror=()=>reject(request.error);request.onsuccess=()=>{const database=request.result,tx=database.transaction('slots','readonly'),get=tx.objectStore('slots').get(JSON.stringify([scope.workspace,scope.actor,scope.email]));tx.oncomplete=()=>{database.close();resolve(JSON.stringify(get.result));};tx.onerror=()=>reject(tx.error);};}),{workspace:p.workspace,actor:p.user,email});
 const records=async()=>(await db.query("SELECT json_build_object('emails',(SELECT md5(string_agg(md5(to_jsonb(t)::text),'' ORDER BY md5(to_jsonb(t)::text)))FROM emails t),'revisions',(SELECT md5(string_agg(md5(to_jsonb(t)::text),'' ORDER BY md5(to_jsonb(t)::text)))FROM revisions t),'provenance',(SELECT md5(string_agg(md5(to_jsonb(t)::text),'' ORDER BY md5(to_jsonb(t)::text)))FROM email_source_provenance t),'audits',(SELECT md5(string_agg(md5(to_jsonb(t)::text),'' ORDER BY md5(to_jsonb(t)::text)))FROM audit_events t),'commands',(SELECT md5(string_agg(md5(to_jsonb(t)::text),'' ORDER BY md5(to_jsonb(t)::text)))FROM idempotency t),'brands',(SELECT md5(string_agg(md5(to_jsonb(t)::text),'' ORDER BY md5(to_jsonb(t)::text)))FROM brands t))AS value")).rows[0].value;
 const until=async(check:()=>Promise<boolean>)=>{for(let n=0;n<100;n++){if(await check())return;await new Promise(r=>setTimeout(r,50));}throw Error('Owned hygiene condition unavailable');},settled=(email:string,text:string)=>until(async()=>{const slot=await recovery(email);if(!slot)return false;const value=JSON.parse(slot);return !!value.command&&JSON.stringify(value.draft.spec).includes(text);});
 const subject=()=>page.getByRole('textbox',{name:'Subject',exact:true}),preheader=()=>page.getByRole('textbox',{name:'Preheader',exact:true}),alt=()=>page.getByRole('textbox',{name:'Alternative text',exact:true}).first(),body=()=>page.getByRole('textbox',{name:'Body text',exact:true}).first(),panel=page.getByRole('region',{name:'Live authoring hygiene',exact:true}),code=(name:string)=>panel.locator('[data-hygiene-code="'+name+'"]'),openChecks=()=>page.getByRole('button',{name:'Show live authoring checks',exact:true}).click();
 await page.goto(origin+'/app/emails/'+doc.id);await body().waitFor();await body().fill('Current unacknowledged body');await settled(doc.id,'Current unacknowledged body');const original=await records(),before=await recovery(doc.id),command=JSON.parse(before!).command;
 await page.getByRole('alert').filter({hasText:'Failed to fetch'}).waitFor();assert.equal(await page.getByRole('button',{name:'Show live authoring checks',exact:true}).count(),1,'Unsaved editor must offer required-copy hygiene without a checkpoint');await openChecks();assert.equal(await code('SUBJECT_REQUIRED').count(),1);assert.equal(await code('PREHEADER_EMPTY').count(),1);assert.equal(await code('ALT_REQUIRED').count(),1);await panel.getByText('Column 1',{exact:false}).waitFor();await panel.getByText('Custom HTML: image alt was not checked.',{exact:false}).waitFor();assert.equal(await recovery(doc.id),before);assert.deepEqual(await records(),original);assert.equal(mutations,0);assert.equal(restores,0);await mkdir('output/live-authoring-hygiene',{recursive:true});await panel.screenshot({path:'output/live-authoring-hygiene/structured-mobile.png'});
 console.log('Actual unsaved empty subject/preheader/nested alt findings are located; decorative/opaque coverage and exact original-command recovery preserve documents PASS.');
 await subject().focus();await page.keyboard.type('S'.repeat(70));assert.equal(await code('SUBJECT_REQUIRED').count(),0);assert.equal(await code('SUBJECT_LENGTH').count(),0);await page.keyboard.type('S');await code('SUBJECT_LENGTH').waitFor();await preheader().fill('P'.repeat(150));assert.equal(await code('PREHEADER_EMPTY').count(),0);assert.equal(await code('PREHEADER_LENGTH').count(),0);await preheader().press('End');await page.keyboard.type('P');await code('PREHEADER_LENGTH').waitFor();for(const value of['😀'.repeat(35),'😀'.repeat(36),'Useful subject']){await subject().fill(value);assert.equal(await code('SUBJECT_LENGTH').count(),value.length>70?1:0);}await preheader().fill('Useful context');await alt().fill('Useful image description');await panel.getByText('No supported basic copy issues found.',{exact:true}).waitFor();assert.equal(await panel.locator('[data-hygiene-code]').count(),0);await settled(doc.id,'Useful image description');assert.equal(JSON.parse((await recovery(doc.id))!).command,command);assert.deepEqual(await records(),original);
 console.log('Keyboard at/one-over70/150 and repeated Unicode corrections update current feedback with no writes or original-command replacement PASS.');
 await alt().fill('');await code('ALT_REQUIRED').waitFor();const decorative=page.getByRole('checkbox',{name:'Decorative image',exact:true}).first();await decorative.focus();await page.keyboard.press('Space');assert.equal(await code('ALT_REQUIRED').count(),0);await page.keyboard.press('Space');await code('ALT_REQUIRED').waitFor();await page.getByRole('button',{name:'Undo',exact:true}).click();assert.equal(await decorative.isChecked(),true);assert.equal(await code('ALT_REQUIRED').count(),0);await panel.getByRole('button',{name:'Hide live authoring checks',exact:true}).evaluate(node=>{(node as HTMLButtonElement).click();(node as HTMLButtonElement).click();});assert.equal(await panel.count(),0);await openChecks();await panel.getByText('No supported basic copy issues found.',{exact:true}).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await context.setOffline(true);await subject().fill('Offline useful copy');await preheader().fill('');await code('PREHEADER_EMPTY').waitFor();await preheader().fill('Useful context');await subject().fill('Useful subject');await panel.getByText('No supported basic copy issues found.',{exact:true}).waitFor();await context.setOffline(false);await until(async()=>{const slot=JSON.parse((await recovery(doc.id))??'{}');return slot.command===command&&slot.draft?.spec.subject==='Useful subject'&&slot.draft?.spec.preheader==='Useful context'&&slot.draft?.spec.sections[0].columns[0][0].decorative===true&&slot.draft?.spec.sections[0].columns[0][0].alt==='';});const currentRecovery=await recovery(doc.id);assert.equal(JSON.parse(currentRecovery!).command,command);assert.deepEqual(await records(),original);
 console.log('Actual failed-save/offline edits, decorative keyboard toggles/Undo and repeated close/reopen preserve current copy and exact original-command recovery PASS.');
 await page.goto(origin+'/app/emails/'+many.id);await subject().waitFor();await openChecks();assert.equal(await panel.locator('[data-hygiene-code]').count(),20);await panel.getByRole('button',{name:'Next hygiene findings',exact:true}).focus();await page.keyboard.press('Enter');await panel.getByText('Page 2 of 3',{exact:true}).waitFor();await page.keyboard.press('Enter');await panel.getByText('Page 3 of 3',{exact:true}).waitFor();assert.equal(await panel.locator('[data-hygiene-code]').count(),15);await panel.getByText('Block 55 [image:"54] · Alternative text',{exact:true}).waitFor();await subject().fill('');await panel.getByText('Page 1 of 3',{exact:true}).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(await records(),original);
 console.log('All55missing alt fields remain keyboard reachable on20-row pages; repeated current edit resets pages and quote/Unicode IDs reflow at320px PASS.');
 await page.goto(origin+'/app/emails/'+raw.id);await subject().waitFor();await openChecks();assert.equal(await code('ALT_REQUIRED').count(),0);await panel.getByText('Raw HTML: image alt was not checked.',{exact:false}).waitFor();await panel.getByText('Inactive retained blocks',{exact:false}).waitFor();await page.getByRole('group',{name:'Editor view',exact:true}).getByRole('button',{name:'HTML',exact:true}).click();const rawInput=page.getByRole('textbox',{name:'Raw HTML source',exact:true});assert.equal(await rawInput.inputValue(),'\ufeff<p>Exact raw</p>\n<img src="https://example.org/raw.png">');await subject().fill('Raw useful');await preheader().fill('Raw context');await panel.getByText('No supported basic copy issues found.',{exact:true}).waitFor();await settled(raw.id,'Raw context');assert.equal(JSON.parse((await recovery(raw.id))!).draft.spec.raw_html,'\ufeff<p>Exact raw</p>\r\n<img src="https://example.org/raw.png">');await panel.screenshot({path:'output/live-authoring-hygiene/raw-mobile.png'});assert.deepEqual(await records(),original);
 await page.goto(origin+'/app/emails/'+rtl.id);await subject().waitFor();await subject().fill('שלום'.repeat(18));await openChecks();const rtlRow=code('SUBJECT_LENGTH');await rtlRow.waitFor();assert.equal(await rtlRow.locator('pre').getAttribute('dir'),'rtl');assert.equal(await rtlRow.locator('pre').getAttribute('lang'),'he-IL');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await panel.screenshot({path:'output/live-authoring-hygiene/rtl-mobile.png'});await page.goto(origin+'/app/emails/'+doc.id);await body().waitFor();assert.equal(await body().inputValue(),'Current unacknowledged body');assert.equal(await recovery(doc.id),currentRecovery);await openChecks();await panel.getByText('No supported basic copy issues found.',{exact:true}).waitFor();assert.deepEqual(await records(),original);
 console.log('Raw/inactive coverage, exact retained source, RTL/320px and navigation reentry use current copy without adoption or approval PASS.');
 await page.goto(origin+'/app/emails/'+pinDoc.id);await subject().waitFor();assert.equal(await subject().inputValue(),'New source NEWPIN_ONLY');await page.getByRole('button',{name:'History',exact:true}).click();const historyRow=page.locator('.history-row').filter({hasText:'Old source OLDPIN_ONLY'}).first();await historyRow.getByRole('button',{name:'Restore as new head',exact:true}).waitFor();let release!:()=>void,started!:()=>void,done!:()=>void;const gate=new Promise<void>(r=>release=r),seen=new Promise<void>(r=>started=r),finished=new Promise<void>(r=>done=r),url='**/v1/brands?*';await page.route(url,async route=>{const response=await route.fetch();started();await gate;try{await route.fulfill({response});}catch{}finally{done();}});await page.getByRole('button',{name:'Show live Voice Guard',exact:true}).click();await seen;await historyRow.getByRole('button',{name:'Restore as new head',exact:true}).click();await until(async()=>await subject().inputValue()==='Old source OLDPIN_ONLY');release();await finished;await page.unroute(url);const voice=page.getByRole('region',{name:'Live mechanical Voice Guard',exact:true});assert.equal(await voice.locator('[data-live-voice-location]').count(),0);assert.equal(await voice.getByText(newPin,{exact:true}).count(),0);await voice.getByText(brand,{exact:true}).waitFor();await voice.getByRole('button',{name:'Refresh pinned rules',exact:true}).click();await voice.getByText('Pinned kit · v1',{exact:true}).waitFor();await voice.getByText('Old source OLDPIN_ONLY',{exact:true}).waitFor();assert.equal(await voice.getByText('New source NEWPIN_ONLY',{exact:true}).count(),0);assert.equal(await voice.getByText('Pinned kit · v2',{exact:true}).count(),0);assert.equal(restores,1);assert.equal(mutations,0);assert.equal(await recovery(doc.id),currentRecovery);assert.equal((await db.query('SELECT doc_version FROM emails WHERE id=$1',[pinDoc.id])).rows[0].doc_version,3);const savedMain=(await db.query('SELECT spec,doc_version FROM emails WHERE id=$1',[doc.id])).rows[0];assert.equal(savedMain.doc_version,1);assert.deepEqual(savedMain.spec,s);
 console.log('Ordinary same-email history Restore changes the brand pin during a held rules read; old response is fenced and only explicitly refreshed current v1 findings appear PASS.');
 assert.deepEqual(errors,[]);assert.deepEqual(warnings,[]);assert.equal(external,0);
 console.log('Zero page/key/external errors; hygiene makes no source/checkpoint calls and no AI/client/accessibility/send approval claims PASS.');
 }finally{await browser?.close();if(app&&app.exitCode===null){app.kill('SIGTERM');await new Promise<void>(resolve=>app!.once('exit',()=>resolve()));}await log.close();}
});console.log('Owned live-hygiene app stopped and disposable database removed PASS.');
