import assert from'node:assert/strict';import{chromium}from'playwright';import{randomUUID}from'node:crypto';import type pg from'pg';import type{EmailSpec}from'../src/domain/email';
type Doc={id:string;doc_version:number;spec:EmailSpec};
export async function runUTMBrowser(f:{origin:string;workspace:string;other:string;cookie:string;user:string;email:string;db:pg.Pool}){
 const browser=await chromium.launch({headless:true});try{
 async function current():Promise<Doc>{const r=await fetch(f.origin+'/v1/emails/'+f.email,{headers:{Cookie:'mailcraft_local_session='+f.cookie,'X-Workspace-Id':f.workspace}});assert.equal(r.status,200);return(await r.json()).email;}
 async function external(spec:EmailSpec){const doc=await current();const r=await fetch(f.origin+'/v1/emails/'+f.email+'/draft',{method:'PATCH',headers:{Cookie:'mailcraft_local_session='+f.cookie,'X-Workspace-Id':f.workspace,Origin:f.origin,'Content-Type':'application/json','If-Match':String(doc.doc_version),'Idempotency-Key':randomUUID()},body:JSON.stringify({spec})});assert.equal(r.status,200);}
 const context=await browser.newContext({viewport:{width:1280,height:900}});await context.addInitScript(workspace=>localStorage.setItem('mailcraft.workspace',workspace),f.workspace);await context.addCookies([{name:'mailcraft_local_session',value:f.cookie,url:f.origin,sameSite:'Strict'}]);let page=await context.newPage();page.on('dialog',dialog=>void dialog.accept());
 const open=async()=>{await page.goto(f.origin+'/app/emails/'+f.email);await page.getByRole('heading',{name:'UTM frozen fixture',exact:true}).waitFor();await page.getByRole('region',{name:'UTM parameters',exact:true}).getByRole('heading',{name:'UTM parameters',exact:true}).waitFor({timeout:5000});};
 const panel=()=>page.getByRole('region',{name:'UTM parameters',exact:true});const saved=async()=>{await page.getByRole('status').filter({hasText:'Saved · v'}).waitFor();};
 const fill=async(campaign:string)=>{await panel().getByLabel('UTM source',{exact:true}).fill('newsletter');await panel().getByLabel('UTM medium',{exact:true}).fill('email');await panel().getByLabel('UTM campaign',{exact:true}).fill(campaign);};
 await open();assert.equal(await panel().getByLabel('Enable UTM parameters').isChecked(),false);
 await panel().getByLabel('Enable UTM parameters').check();await panel().getByRole('button',{name:'Apply UTM to draft',exact:true}).click();await panel().getByRole('alert').filter({hasText:'all three nonblank'}).waitFor();assert.equal((await current()).spec.tracking,undefined);
 await fill('first local');await page.getByLabel('Subject',{exact:true}).fill('Unrelated current subject');await panel().getByRole('button',{name:'Apply UTM to draft',exact:true}).evaluate(button=>{(button as HTMLButtonElement).click();(button as HTMLButtonElement).click();});await saved();assert.equal((await current()).spec.subject,'Unrelated current subject');assert.equal((await current()).spec.tracking?.utm_campaign,'first local');assert.equal((await current()).spec.sections.find(b=>b.type==='button')?.href,'https://example.com');
 await page.frameLocator('iframe[title="Email browser simulation"]').locator('a[href*="utm_source=newsletter"]').first().waitFor();
 await fill('invalid retained');await panel().getByLabel('UTM campaign',{exact:true}).fill('   ');await panel().getByRole('button',{name:'Apply UTM to draft',exact:true}).click();await panel().getByRole('alert').filter({hasText:'all three nonblank'}).waitFor();assert.equal(await panel().getByLabel('UTM campaign',{exact:true}).inputValue(),'   ');assert.equal((await current()).spec.tracking?.utm_campaign,'first local');
 await fill('unrelated fields retained');await page.getByLabel('Preheader',{exact:true}).fill('Updated after working settings');await panel().getByRole('button',{name:'Apply UTM to draft',exact:true}).click();await saved();assert.equal((await current()).spec.preheader,'Updated after working settings');assert.equal((await current()).spec.tracking?.utm_campaign,'unrelated fields retained');
 // A separately acknowledged changed policy must not hydrate or overwrite this working form.
 await fill('local working settings');let latest=await current();await external({...latest.spec,subject:'External current subject',tracking:{utm_source:'other',utm_medium:'email',utm_campaign:'external policy'}});await page.getByLabel('Subject',{exact:true}).fill('Conflict copy preserved');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('heading',{name:'A newer version is saved.',exact:true}).waitFor();assert.equal(await panel().getByRole('button',{name:'Apply UTM to draft',exact:true}).isDisabled(),true);assert.equal(await panel().getByLabel('UTM campaign',{exact:true}).inputValue(),'local working settings');await page.getByRole('button',{name:'Reload newer',exact:true}).click();await panel().getByRole('alert').filter({hasText:'UTM policy changed'}).waitFor();assert.equal(await panel().getByLabel('UTM campaign',{exact:true}).inputValue(),'local working settings');await panel().getByRole('button',{name:'Reload UTM settings',exact:true}).click();assert.equal(await panel().getByLabel('UTM campaign',{exact:true}).inputValue(),'external policy');assert.equal(await page.getByLabel('Subject',{exact:true}).inputValue(),'External current subject');
 // An external unrelated edit with the same policy preserves the working form.
 await fill('same policy retained form');latest=await current();await external({...latest.spec,subject:'Same-policy external subject'});await page.getByLabel('Subject',{exact:true}).fill('Local conflict subject');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('heading',{name:'A newer version is saved.',exact:true}).waitFor();await page.getByRole('button',{name:'Reload newer',exact:true}).click();await saved();assert.equal(await panel().getByLabel('UTM campaign',{exact:true}).inputValue(),'same policy retained form');assert.equal(await panel().getByRole('button',{name:'Reload UTM settings',exact:true}).count(),0);await panel().getByRole('button',{name:'Apply UTM to draft',exact:true}).click();await saved();assert.equal((await current()).spec.subject,'Same-policy external subject');assert.equal((await current()).spec.tracking?.utm_campaign,'same policy retained form');
 // Explicit remove leaves original source URLs and old immutable artifacts intact.
 await panel().getByRole('button',{name:'Remove UTM from draft',exact:true}).click();await saved();assert.equal((await current()).spec.tracking,undefined);await page.locator('.outline-select').filter({hasText:'button'}).click();await page.getByLabel('Destination URL',{exact:true}).fill('https://example.com/?utm_source=conflicting');await saved();await panel().getByLabel('Enable UTM parameters').check();await fill('refused conflict');await panel().getByRole('button',{name:'Apply UTM to draft',exact:true}).click();await panel().getByRole('alert').filter({hasText:'Existing UTM values conflict'}).waitFor();assert.equal((await current()).spec.tracking,undefined);await page.getByLabel('Destination URL',{exact:true}).fill('https://example.com');await saved();
 // Offline applied changes are local until acknowledgment, and survive closing the view.
 await context.setOffline(true);await fill('offline retained policy');await panel().getByRole('button',{name:'Apply UTM to draft',exact:true}).click();await page.getByRole('status').filter({hasText:/local only/}).waitFor();assert.equal((await current()).spec.tracking,undefined);await page.close();await context.setOffline(false);page=await context.newPage();page.on('dialog',dialog=>void dialog.accept());await open();assert.equal(await panel().getByLabel('UTM campaign',{exact:true}).inputValue(),'offline retained policy');await saved();assert.equal((await current()).spec.tracking?.utm_campaign,'offline retained policy');
 await page.getByRole('button',{name:'History',exact:true}).click();
 let checkpointEntered!:()=>void,checkpointRelease!:()=>void;const checkpointReady=new Promise<void>(r=>checkpointEntered=r),checkpointGate=new Promise<void>(r=>checkpointRelease=r);await page.route('**/v1/emails/'+f.email+'/revisions',async route=>{const response=await route.fetch();checkpointEntered();await checkpointGate;await route.fulfill({response});});await page.getByRole('button',{name:'Create checkpoint',exact:true}).click();await checkpointReady;assert.equal(await panel().getByRole('button',{name:'Apply UTM to draft',exact:true}).isDisabled(),true);assert.equal(await panel().getByLabel('UTM campaign',{exact:true}).isDisabled(),true);checkpointRelease();await page.locator('.history-row').filter({hasText:'Same-policy external subject'}).first().waitFor();await page.unroute('**/v1/emails/'+f.email+'/revisions');assert.ok((await f.db.query('SELECT html FROM revisions WHERE email_id=$1 ORDER BY revision_no DESC LIMIT 1',[f.email])).rows[0].html.includes('utm_campaign=offline%20retained%20policy'));
 await page.setViewportSize({width:390,height:844});await panel().scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('iframe[title="Email browser simulation"]').scrollIntoViewIfNeeded();await page.frameLocator('iframe[title="Email browser simulation"]').getByText('Your next story starts here',{exact:true}).waitFor();await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve(true)))));await page.screenshot({path:'/tmp/lettercape-utm-mobile.png',fullPage:true});await panel().screenshot({path:'/tmp/lettercape-utm-mobile-panel.png'});
 // Current-role changes reach the actual settings controls.
 await f.db.query("UPDATE memberships SET role='Viewer' WHERE workspace_id=$1 AND user_id=$2",[f.workspace,f.user]);await page.reload();await panel().getByText('Your role can view these settings.',{exact:true}).waitFor();for(const label of['Enable UTM parameters','UTM source','UTM medium','UTM campaign'])assert.equal(await panel().getByLabel(label,{exact:true}).isDisabled(),true);assert.equal(await panel().getByRole('button',{name:'Apply UTM to draft',exact:true}).isDisabled(),true);await f.db.query("UPDATE memberships SET role='Owner' WHERE workspace_id=$1 AND user_id=$2",[f.workspace,f.user]);
 // Delayed initial read exposes no writable settings and cannot repopulate another workspace.
 let entered!:()=>void,release!:()=>void,finished!:()=>void;const ready=new Promise<void>(r=>entered=r),gate=new Promise<void>(r=>release=r),done=new Promise<void>(r=>finished=r);await page.route('**/v1/emails/'+f.email,async route=>{if(route.request().method()!=='GET')return route.continue();const response=await route.fetch();entered();await gate;try{await route.fulfill({response});}finally{finished();}});await page.reload();await ready;assert.equal(await panel().count(),0);await page.getByRole('button',{name:'Open navigation'}).click();await page.getByLabel('Active brand workspace').selectOption(f.other);await page.getByRole('heading',{name:'Make something worth opening.',exact:true}).waitFor();release();await done;assert.equal(await panel().count(),0);assert.equal(await page.getByLabel('Active brand workspace').inputValue(),f.other);
 const failedPage=await context.newPage();await failedPage.route('**/v1/emails/'+f.email,route=>route.abort('failed'));await failedPage.goto(f.origin+'/app/emails/'+f.email);await failedPage.getByRole('status').filter({hasText:/fetch|network|Failed|offline|acknowledge/i}).waitFor();assert.equal(await failedPage.getByRole('region',{name:'UTM parameters',exact:true}).count(),0);await failedPage.goto(f.origin+'/app');await failedPage.getByRole('heading',{name:'Make something worth opening.',exact:true}).waitFor();await failedPage.close();
 console.log('Owned UTM Chromium PASS: defaultoff/invalid retention, repeated Apply, latest unrelated edits, changed/same policy conflict reload, local semantic refusal, remove, offline close/recovery/autosave, in-flight checkpoint gate, initial error/navigation, frozen checkpoint, Viewer,390px/nooverflow and delayed read/workspace fence; no providers/collectors/sends.');
 }finally{await browser.close();}
}
