import assert from'node:assert/strict';import{chromium}from'playwright';import{randomUUID}from'node:crypto';import type pg from'pg';import type{EmailSpec}from'../src/domain/email';
export async function runUTMReviewBrowser(f:{origin:string;workspace:string;other:string;cookie:string;user:string;email:string;db:pg.Pool;mode:'proposal'|'working'|'links'}){
 const browser=await chromium.launch({headless:true});try{
 async function current(){const r=await fetch(f.origin+'/v1/emails/'+f.email,{headers:{Cookie:'mailcraft_local_session='+f.cookie,'X-Workspace-Id':f.workspace}});assert.equal(r.status,200);return(await r.json()).email as{spec:EmailSpec;doc_version:number};}
 async function external(spec:EmailSpec){const doc=await current(),r=await fetch(f.origin+'/v1/emails/'+f.email+'/draft',{method:'PATCH',headers:{Cookie:'mailcraft_local_session='+f.cookie,'X-Workspace-Id':f.workspace,Origin:f.origin,'Content-Type':'application/json','If-Match':String(doc.doc_version)},body:JSON.stringify({spec})});assert.equal(r.status,200);}
 const policy={utm_source:'newsletter',utm_medium:'email',utm_campaign:'retained explicit policy'};
 if(f.mode==='proposal'){const doc=await current();await external({...doc.spec,tracking:policy});}
 const context=await browser.newContext({viewport:{width:390,height:844}});await context.addInitScript(workspace=>localStorage.setItem('mailcraft.workspace',workspace),f.workspace);await context.addCookies([{name:'mailcraft_local_session',value:f.cookie,url:f.origin,sameSite:'Strict'}]);const page=await context.newPage();let dialogs=0;page.on('dialog',async dialog=>{if(dialog.type()==='beforeunload')dialogs++;await dialog.accept();});const panel=()=>page.getByRole('region',{name:'UTM parameters',exact:true});
 await page.goto(f.origin+'/app/emails/'+f.email);await panel().waitFor();
 if(f.mode==='proposal'){
  // Deliberately synthetic mocked generation receipts; actual draft persistence
  // remains real HTTP. This does not exercise or claim a configured AI provider.
  const operation=randomUUID();const base=(await current()).spec;let spec={...base,subject:'Synthetic reviewed copy proposal'};delete spec.tracking;
  await page.route('**/v1/emails/generate',route=>route.fulfill({status:202,contentType:'application/json',body:JSON.stringify({operation:{id:operation}})}));
  await page.route('**/v1/operations/'+operation,route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({operation:{state:'succeeded',result:{proposals:[{spec,review_notes:['Synthetic mocked proposal: no AI provider call.']}]}}})}));
  await page.getByLabel('Propose changes',{exact:true}).fill('Synthetic owned copy-change fixture');await page.getByRole('button',{name:'Generate proposal',exact:true}).click();await page.getByRole('button',{name:'Apply proposal',exact:true}).waitFor();const ack=page.waitForResponse(r=>new URL(r.url()).pathname==='/v1/emails/'+f.email+'/draft'&&r.request().method()==='PATCH');await page.getByRole('button',{name:'Apply proposal',exact:true}).click();assert.equal((await ack).status(),200);await page.getByRole('status').filter({hasText:'Saved · v'}).waitFor();assert.deepEqual((await current()).spec.tracking,policy);assert.equal((await current()).spec.subject,spec.subject);
  console.log('Owned synthetic copy-proposal actual persisted UTM preservation PASS; mocked generation only, zero provider calls.');
  const saved=await current();await page.reload();await panel().waitFor();spec={...saved.spec,subject:'Synthetic conflicting proposal',sections:[{id:'conflict',type:'button',label:'Conflict',href:'https://example.org/?utm_source=other'}]};delete spec.tracking;
  await page.getByLabel('Propose changes',{exact:true}).fill('Synthetic conflicting owned fixture');await page.getByRole('button',{name:'Generate proposal',exact:true}).click();await page.getByRole('button',{name:'Apply proposal',exact:true}).waitFor();await page.getByRole('button',{name:'Apply proposal',exact:true}).click();await page.getByRole('alert').filter({hasText:'Existing UTM values conflict'}).waitFor();assert.deepEqual(await current(),saved);assert.equal(await page.getByRole('button',{name:'Apply proposal',exact:true}).count(),1);console.log('Owned synthetic conflicting proposal refusal retains actual policy/document/version and proposal PASS.');
 }else if(f.mode==='links'){
  await page.locator('.outline-select').filter({hasText:'button'}).click();await panel().getByLabel('Enable UTM parameters').check();for(const [label,value]of[['UTM source','newsletter'],['UTM medium','email'],['UTM campaign','editor link recovery']])await panel().getByLabel(label,{exact:true}).fill(value);
  for(const href of['https:example.com/offer','https:/example.com/offer','https:'+String.fromCharCode(92)+'example.com/offer']){
   await page.getByLabel('Destination URL',{exact:true}).fill(href);await page.getByRole('status').filter({hasText:'Saved · v'}).waitFor();const saved=await current();await panel().getByRole('button',{name:'Apply UTM to draft',exact:true}).click();await panel().getByRole('alert').filter({hasText:'literal absolute HTTPS'}).waitFor();assert.deepEqual(await current(),saved);assert.equal(await panel().getByLabel('UTM campaign',{exact:true}).inputValue(),'editor link recovery');
  }
  await page.getByLabel('Destination URL',{exact:true}).fill('https://example.org/offer?x=a%20b#part');await page.getByRole('status').filter({hasText:'Saved · v'}).waitFor();await panel().getByRole('button',{name:'Apply UTM to draft',exact:true}).evaluate(button=>{(button as HTMLButtonElement).click();(button as HTMLButtonElement).click();});await page.getByRole('status').filter({hasText:'Saved · v'}).waitFor();assert.equal((await current()).spec.tracking?.utm_campaign,'editor link recovery');await page.reload();await panel().waitFor();assert.equal(await panel().getByLabel('UTM campaign',{exact:true}).inputValue(),'editor link recovery');await page.frameLocator('iframe[title="Email browser simulation"]').locator('a[href*="utm_campaign=editor%20link%20recovery"]').first().waitFor();
  const doc=await current(),checkpoint=await fetch(f.origin+'/v1/emails/'+f.email+'/revisions',{method:'POST',headers:{Cookie:'mailcraft_local_session='+f.cookie,'X-Workspace-Id':f.workspace,Origin:f.origin,'Content-Type':'application/json','If-Match':String(doc.doc_version),'Idempotency-Key':randomUUID()},body:'{}'});assert.equal(checkpoint.status,200);const revision=(await checkpoint.json()).revision;for(const format of['html','txt']){const downloaded=await fetch(f.origin+'/v1/email-revisions/'+revision.id+'/download?format='+format,{headers:{Cookie:'mailcraft_local_session='+f.cookie,'X-Workspace-Id':f.workspace}});assert.equal(downloaded.status,200);assert.equal(downloaded.headers.get('x-artifact-hash'),revision.artifact_hash);const bytes=await downloaded.text();assert.equal(bytes,format==='html'?revision.html:revision.plaintext);assert.ok(bytes.includes('utm_campaign=editor%20link%20recovery'));assert.ok(bytes.includes('x=a%20b'));assert.ok(bytes.includes('#part'));}
  console.log('Owned actual editor abbreviated-link refusal/correction/repeated Apply/persistence/reload/preview/frozen HTML+TXT export PASS; no provider calls.');
 }else{
  const version=(await current()).doc_version;await panel().getByLabel('Enable UTM parameters').check();await panel().getByLabel('UTM source',{exact:true}).fill('invalid working source');await panel().getByLabel('UTM medium',{exact:true}).fill('email');await panel().getByLabel('UTM campaign',{exact:true}).fill('   ');
  await page.reload();await panel().waitFor();assert.equal(await panel().getByLabel('UTM source',{exact:true}).inputValue(),'invalid working source');assert.equal(await panel().getByLabel('UTM campaign',{exact:true}).inputValue(),'   ');assert.equal(await panel().getByLabel('Enable UTM parameters').isChecked(),true);assert.equal((await current()).doc_version,version);assert.equal((await current()).spec.tracking,undefined);
  await panel().getByRole('status').filter({hasText:/unapplied/i}).waitFor();await page.getByRole('button',{name:'Open navigation'}).click();await page.getByLabel('Active brand workspace').selectOption(f.other);await page.getByRole('heading',{name:'Make something worth opening.',exact:true}).waitFor();assert.equal(await panel().count(),0);await page.getByRole('button',{name:'Open navigation'}).click();await page.getByLabel('Active brand workspace').selectOption(f.workspace);await page.getByRole('heading',{name:'Make something worth opening.',exact:true}).waitFor();await page.goto(f.origin+'/app/emails/'+f.email);await panel().waitFor();assert.equal(await panel().getByLabel('UTM source',{exact:true}).inputValue(),'invalid working source');assert.equal(await panel().getByLabel('UTM campaign',{exact:true}).inputValue(),'   ');
  const sibling=await fetch(f.origin+'/v1/emails',{method:'POST',headers:{Cookie:'mailcraft_local_session='+f.cookie,'X-Workspace-Id':f.workspace,Origin:f.origin,'Content-Type':'application/json','Idempotency-Key':randomUUID()},body:JSON.stringify({title:'Owned recovery isolation'})});assert.equal(sibling.status,200);const siblingID=(await sibling.json()).email.id;await page.goto(f.origin+'/app/emails/'+siblingID);await panel().waitFor();assert.equal(await panel().getByLabel('Enable UTM parameters').isChecked(),false);assert.equal(await panel().getByLabel('UTM campaign',{exact:true}).inputValue(),'');await page.goto(f.origin+'/app/emails/'+f.email);await panel().waitFor();assert.equal(await panel().getByLabel('UTM campaign',{exact:true}).inputValue(),'   ');
  const doc=await current();await external({...doc.spec,tracking:policy});await page.reload();await panel().getByRole('alert').filter({hasText:'UTM policy changed'}).waitFor();assert.equal(await panel().getByLabel('UTM source',{exact:true}).inputValue(),'invalid working source');assert.equal(await panel().getByRole('button',{name:'Apply UTM to draft',exact:true}).isDisabled(),true);await panel().getByRole('button',{name:'Reload UTM settings',exact:true}).click();assert.equal(await panel().getByLabel('UTM campaign',{exact:true}).inputValue(),policy.utm_campaign);
  console.log('Owned unapplied/invalid UTM reload/workspace recovery and original-fingerprint stale fence PASS; document version/content unchanged until explicit commands, dialogs='+dialogs+'.');
  // Fail only this new working-form storage boundary, leaving unrelated app
  // storage functional. SPA recovery must stay scoped; full reload must warn.
  await page.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(name,value){if(name.startsWith('lettercape.utm-form.'))throw new DOMException('Owned storage fault','QuotaExceededError');return original.call(this,name,value);};});
  await panel().getByLabel('UTM campaign',{exact:true}).fill('unpersisted working text');await panel().getByRole('alert').filter({hasText:'recovery storage is unavailable'}).waitFor();await page.locator('.back-link').click();await page.locator('.email-rows a[href="/app/emails/'+f.email+'"]').waitFor();await page.locator('.email-rows a[href="/app/emails/'+f.email+'"]').click();await panel().waitFor();assert.equal(await panel().getByLabel('UTM campaign',{exact:true}).inputValue(),'unpersisted working text');await panel().getByRole('alert').filter({hasText:'recovery storage is unavailable'}).waitFor();const before=dialogs;await page.reload();await panel().waitFor();assert.equal(dialogs,before+1,'unpersisted working text must require an explicit unload discard');assert.equal(await panel().getByLabel('UTM campaign',{exact:true}).inputValue(),policy.utm_campaign);assert.deepEqual((await current()).spec.tracking,policy);console.log('Owned targeted unavailable-storage SPA recovery and explicit reload discard protection PASS.');
 }
 }finally{await browser.close();}
}
