// Generated by npm run api:generate. Do not edit.
export const operationRegistry = {
  "listWebhookDeliveries": {
    "method": "GET",
    "path": "/v1/webhook-deliveries",
    "keyed": false,
    "paged": true,
    "binary": false,
    "blocked": false
  },
  "getWebhookDelivery": {
    "method": "GET",
    "path": "/v1/webhook-deliveries/{id}",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "listWebhookAttempts": {
    "method": "GET",
    "path": "/v1/webhook-deliveries/{id}/attempts",
    "keyed": false,
    "paged": true,
    "binary": false,
    "blocked": false
  },
  "replayWebhookDelivery": {
    "method": "POST",
    "path": "/v1/webhook-deliveries/{id}/replay",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "listWebhookEndpoints": {
    "method": "GET",
    "path": "/v1/webhook-endpoints",
    "keyed": false,
    "paged": true,
    "binary": false,
    "blocked": false
  },
  "getWebhookEndpoint": {
    "method": "GET",
    "path": "/v1/webhook-endpoints/{id}",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "createWebhookEndpoint": {
    "method": "POST",
    "path": "/v1/webhook-endpoints",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "rotateWebhookEndpoint": {
    "method": "POST",
    "path": "/v1/webhook-endpoints/{id}/rotate",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "pauseWebhookEndpoint": {
    "method": "POST",
    "path": "/v1/webhook-endpoints/{id}/pause",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "listEvents": {
    "method": "GET",
    "path": "/v1/events",
    "keyed": false,
    "paged": true,
    "binary": false,
    "blocked": false
  },
  "getEvent": {
    "method": "GET",
    "path": "/v1/events/{id}",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "getDispatchControls": {
    "method": "GET",
    "path": "/v1/dispatch-controls",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "setWorkspaceDispatchPolicy": {
    "method": "POST",
    "path": "/v1/dispatch-controls/workspace",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "health": {
    "method": "GET",
    "path": "/v1/health",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "listWorkspaces": {
    "method": "GET",
    "path": "/v1/workspaces",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "createWorkspace": {
    "method": "POST",
    "path": "/v1/workspaces",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "signOutLocalSession": {
    "method": "DELETE",
    "path": "/v1/session",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "localSession": {
    "method": "POST",
    "path": "/v1/local-session",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "listIntegrations": {
    "method": "GET",
    "path": "/v1/integrations",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "listBrands": {
    "method": "GET",
    "path": "/v1/brands",
    "keyed": false,
    "paged": true,
    "binary": false,
    "blocked": false
  },
  "listEmails": {
    "method": "GET",
    "path": "/v1/emails",
    "keyed": false,
    "paged": true,
    "binary": false,
    "blocked": false
  },
  "listContacts": {
    "method": "GET",
    "path": "/v1/contacts",
    "keyed": false,
    "paged": true,
    "binary": false,
    "blocked": false
  },
  "listCampaigns": {
    "method": "GET",
    "path": "/v1/campaigns",
    "keyed": false,
    "paged": true,
    "binary": false,
    "blocked": false
  },
  "listSegments": {
    "method": "GET",
    "path": "/v1/segments",
    "keyed": false,
    "paged": true,
    "binary": false,
    "blocked": false
  },
  "listApiKeys": {
    "method": "GET",
    "path": "/v1/api-keys",
    "keyed": false,
    "paged": true,
    "binary": false,
    "blocked": false
  },
  "listAudit": {
    "method": "GET",
    "path": "/v1/audit",
    "keyed": false,
    "paged": true,
    "binary": false,
    "blocked": false
  },
  "listRevisions": {
    "method": "GET",
    "path": "/v1/email-revisions",
    "keyed": false,
    "paged": true,
    "binary": false,
    "blocked": false
  },
  "getCurrentBrand": {
    "method": "GET",
    "path": "/v1/brands/current",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "confirmBrand": {
    "method": "POST",
    "path": "/v1/brands",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "extractBrand": {
    "method": "POST",
    "path": "/v1/brands/from-url",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "createEmail": {
    "method": "POST",
    "path": "/v1/emails",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "getEmail": {
    "method": "GET",
    "path": "/v1/emails/{id}",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "generateEmail": {
    "method": "POST",
    "path": "/v1/emails/generate",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "listEmailDerivatives": {
    "method": "GET",
    "path": "/v1/emails/{id}/derivatives",
    "keyed": false,
    "paged": true,
    "binary": false,
    "blocked": false
  },
  "remixRevision": {
    "method": "POST",
    "path": "/v1/email-revisions/{id}/remix",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "createLocaleDraft": {
    "method": "POST",
    "path": "/v1/email-revisions/{id}/localize",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "saveDraft": {
    "method": "PATCH",
    "path": "/v1/emails/{id}/draft",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "checkpointEmail": {
    "method": "POST",
    "path": "/v1/emails/{id}/revisions",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "restoreEmail": {
    "method": "POST",
    "path": "/v1/emails/{id}/restore",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "previewEmail": {
    "method": "POST",
    "path": "/v1/emails/{id}/preview",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "importHtml": {
    "method": "POST",
    "path": "/v1/emails/{id}/import-html",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "downloadRevision": {
    "method": "GET",
    "path": "/v1/email-revisions/{id}/download",
    "keyed": false,
    "paged": false,
    "binary": true,
    "blocked": false
  },
  "preflightRevision": {
    "method": "POST",
    "path": "/v1/email-revisions/{id}/preflight",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "exportRevision": {
    "method": "POST",
    "path": "/v1/email-revisions/{id}/export",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": true
  },
  "getOperation": {
    "method": "GET",
    "path": "/v1/operations/{id}",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "cancelOperation": {
    "method": "POST",
    "path": "/v1/operations/{id}/cancel",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "getAudienceSchema": {
    "method": "GET",
    "path": "/v1/audience-schema",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "createList": {
    "method": "POST",
    "path": "/v1/lists",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "createTag": {
    "method": "POST",
    "path": "/v1/tags",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "createContactField": {
    "method": "POST",
    "path": "/v1/contact-fields",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "updateContactProfile": {
    "method": "PATCH",
    "path": "/v1/contacts/{id}/profile",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "suppressContact": {
    "method": "POST",
    "path": "/v1/contacts/{id}/suppress",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "createSegment": {
    "method": "POST",
    "path": "/v1/segments",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "getSegment": {
    "method": "GET",
    "path": "/v1/segments/{id}",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "createSegmentVersion": {
    "method": "POST",
    "path": "/v1/segments/{id}/versions",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "previewSegment": {
    "method": "POST",
    "path": "/v1/segments/{id}/preview",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "freezeAudience": {
    "method": "POST",
    "path": "/v1/segments/{id}/snapshots",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "getAudienceSnapshot": {
    "method": "GET",
    "path": "/v1/audience-snapshots/{id}",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "inspectImport": {
    "method": "POST",
    "path": "/v1/contact-imports/inspect",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "dryRunImport": {
    "method": "POST",
    "path": "/v1/contact-imports",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "confirmImport": {
    "method": "POST",
    "path": "/v1/contact-imports/{id}/confirm",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "importErrors": {
    "method": "GET",
    "path": "/v1/contact-imports/{id}/errors",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "createCampaign": {
    "method": "POST",
    "path": "/v1/campaigns",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "submitCampaignReview": {
    "method": "POST",
    "path": "/v1/campaigns/{id}/submit-review",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "approveCampaign": {
    "method": "POST",
    "path": "/v1/campaigns/{id}/approve",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": true
  },
  "sendCampaign": {
    "method": "POST",
    "path": "/v1/campaigns/{id}/send",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": true
  },
  "scheduleCampaign": {
    "method": "POST",
    "path": "/v1/campaigns/{id}/schedule",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": true
  },
  "pauseCampaign": {
    "method": "POST",
    "path": "/v1/campaigns/{id}/pause",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "resumeCampaign": {
    "method": "POST",
    "path": "/v1/campaigns/{id}/resume",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": true
  },
  "cancelCampaign": {
    "method": "POST",
    "path": "/v1/campaigns/{id}/cancel",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "createApiKey": {
    "method": "POST",
    "path": "/v1/api-keys",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "rotateApiKey": {
    "method": "POST",
    "path": "/v1/api-keys/{id}/rotate",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "revokeApiKey": {
    "method": "POST",
    "path": "/v1/api-keys/{id}/revoke",
    "keyed": true,
    "paged": false,
    "binary": false,
    "blocked": false
  },
  "getUsage": {
    "method": "GET",
    "path": "/v1/usage",
    "keyed": false,
    "paged": false,
    "binary": false,
    "blocked": false
  }
} as const;
